use super::helpers::run_vb;

#[test] fn opt_arg_basic() { assert_eq!(run_vb("Module M\nFunction GetV(Optional v As Integer = 5) As Integer\nReturn v\nEnd Function\nSub Main()\nConsole.WriteLine(GetV())\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn opt_arg_provided() { assert_eq!(run_vb("Module M\nFunction GetV(Optional v As Integer = 5) As Integer\nReturn v\nEnd Function\nSub Main()\nConsole.WriteLine(GetV(10))\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn opt_arg_multiple() { assert_eq!(run_vb("Module M\nFunction GetV(Optional a As Integer = 1, Optional b As Integer = 2) As Integer\nReturn a + b\nEnd Function\nSub Main()\nConsole.WriteLine(GetV())\nEnd Sub\nEnd Module"), vec!["3"]); }
#[test] fn opt_arg_multiple_provided() { assert_eq!(run_vb("Module M\nFunction GetV(Optional a As Integer = 1, Optional b As Integer = 2) As Integer\nReturn a + b\nEnd Function\nSub Main()\nConsole.WriteLine(GetV(5, 5))\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn opt_arg_mix_normal() { assert_eq!(run_vb("Module M\nFunction GetV(a As Integer, Optional b As Integer = 2) As Integer\nReturn a + b\nEnd Function\nSub Main()\nConsole.WriteLine(GetV(5))\nEnd Sub\nEnd Module"), vec!["7"]); }

#[test] fn opt_arg_missing_comma() { assert_eq!(run_vb("Module M\nFunction GetV(Optional a As Integer = 1, Optional b As Integer = 2) As Integer\nReturn a + b\nEnd Function\nSub Main()\nConsole.WriteLine(GetV(, 5))\nEnd Sub\nEnd Module"), vec!["6"]); } // First arg gets default 1, second gets 5
#[test] fn opt_arg_missing_comma_three() { assert_eq!(run_vb("Module M\nFunction GetV(Optional a = 1, Optional b = 2, Optional c = 3) As Integer\nReturn a + b + c\nEnd Function\nSub Main()\nConsole.WriteLine(GetV(,,5))\nEnd Sub\nEnd Module"), vec!["8"]); }
#[test] fn opt_arg_no_default_value() { assert_eq!(run_vb("Module M\nFunction GetV(Optional v As Integer) As Integer\nReturn v\nEnd Function\nSub Main()\nConsole.WriteLine(GetV())\nEnd Sub\nEnd Module"), vec!["0"]); } // Default is Nothing (0 for Integer)
#[test] fn opt_arg_default_constant_expression() { assert_eq!(run_vb("Module M\nConst def = 10\nFunction GetV(Optional v As Integer = def + 5) As Integer\nReturn v\nEnd Function\nSub Main()\nConsole.WriteLine(GetV())\nEnd Sub\nEnd Module"), vec!["15"]); }
#[test] fn opt_arg_invalid_default() { assert_eq!(run_vb("Module M\n' Function GetV(Optional v As Integer = Environment.TickCount) As Integer\n' Default value must be a constant expression\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }

#[test] fn opt_arg_byref() { assert_eq!(run_vb("Module M\nFunction GetV(Optional ByRef v As Integer = 5) As Integer\nv += 1\nReturn v\nEnd Function\nSub Main()\nConsole.WriteLine(GetV())\nEnd Sub\nEnd Module"), vec!["6"]); }
#[test] fn paramarray_basic() { assert_eq!(run_vb("Module M\nFunction Sum(ParamArray args() As Integer) As Integer\nDim s = 0\nFor Each v In args\ns += v\nNext\nReturn s\nEnd Function\nSub Main()\nConsole.WriteLine(Sum(1, 2, 3))\nEnd Sub\nEnd Module"), vec!["6"]); }
#[test] fn paramarray_empty() { assert_eq!(run_vb("Module M\nFunction Sum(ParamArray args() As Integer) As Integer\nReturn args.Length\nEnd Function\nSub Main()\nConsole.WriteLine(Sum())\nEnd Sub\nEnd Module"), vec!["0"]); }
#[test] fn paramarray_passing_array() { assert_eq!(run_vb("Module M\nFunction Sum(ParamArray args() As Integer) As Integer\nDim s = 0\nFor Each v In args\ns += v\nNext\nReturn s\nEnd Function\nSub Main()\nDim arr() As Integer = {1, 2, 3}\nConsole.WriteLine(Sum(arr))\nEnd Sub\nEnd Module"), vec!["6"]); } // Can pass array directly
#[test] fn paramarray_with_normal_args() { assert_eq!(run_vb("Module M\nFunction PrintArgs(a As String, ParamArray args() As Integer) As String\nReturn a & args(0)\nEnd Function\nSub Main()\nConsole.WriteLine(PrintArgs(\"A\", 1, 2))\nEnd Sub\nEnd Module"), vec!["A1"]); }

#[test] fn paramarray_object_array() { assert_eq!(run_vb("Option Strict Off\nModule M\nFunction PrintArgs(ParamArray args() As Object) As String\nReturn args(0) & args(1)\nEnd Function\nSub Main()\nConsole.WriteLine(PrintArgs(\"A\", 1))\nEnd Sub\nEnd Module"), vec!["A1"]); }
#[test] fn paramarray_coercion() { assert_eq!(run_vb("Option Strict Off\nModule M\nFunction Sum(ParamArray args() As Double) As Double\nReturn args(0) + args(1)\nEnd Function\nSub Main()\nConsole.WriteLine(Sum(1, 2))\nEnd Sub\nEnd Module"), vec!["3"]); } // Integers coerced to Double array implicitly
#[test] fn paramarray_must_be_last() { assert_eq!(run_vb("Module M\n' Function F(ParamArray args() As Integer, a As Integer) ' ParamArray must be last parameter\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn opt_arg_must_be_at_end() { assert_eq!(run_vb("Module M\n' Function F(Optional a As Integer = 1, b As Integer) ' Optional args must be at end\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn paramarray_and_optional_together() { assert_eq!(run_vb("Module M\n' Function F(Optional a As Integer = 1, ParamArray args() As Integer) ' Cannot combine Optional and ParamArray\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }

#[test] fn paramarray_byval_by_default() { assert_eq!(run_vb("Module M\nSub Mutate(ParamArray args() As Integer)\nargs(0) = 2\nEnd Sub\nSub Main()\nDim arr() As Integer = {1}\nMutate(arr)\nConsole.WriteLine(arr(0))\nEnd Sub\nEnd Module"), vec!["2"]); } // Array is reference type, element changes persist
#[test] fn paramarray_byref_fails() { assert_eq!(run_vb("Module M\n' Sub F(ByRef ParamArray args() As Integer) ' ParamArray cannot be ByRef\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn opt_arg_date_literal_default() { assert_eq!(run_vb("Module M\nFunction F(Optional d As Date = #1/1/2000#) As String\nReturn d.Year.ToString()\nEnd Function\nSub Main()\nConsole.WriteLine(F())\nEnd Sub\nEnd Module"), vec!["2000"]); }
#[test] fn opt_arg_nothing_default() { assert_eq!(run_vb("Module M\nFunction F(Optional obj As Object = Nothing) As Boolean\nReturn obj Is Nothing\nEnd Function\nSub Main()\nConsole.WriteLine(F())\nEnd Sub\nEnd Module"), vec!["True"]); }
#[test] fn opt_arg_enum_default() { assert_eq!(run_vb("Enum E\nA\nB\nEnd Enum\nModule M\nFunction F(Optional e1 As E = E.B) As String\nReturn e1.ToString()\nEnd Function\nSub Main()\nConsole.WriteLine(F())\nEnd Sub\nEnd Module"), vec!["B"]); }
