use super::helpers::run_vb;

#[test] fn prop_auto_property_basic() { assert_eq!(run_vb("Class C\nPublic Property V As Integer\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.V = 10\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn prop_auto_property_initializer() { assert_eq!(run_vb("Class C\nPublic Property V As Integer = 5\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn prop_explicit_get_set() { assert_eq!(run_vb("Class C\nPrivate _v As Integer\nPublic Property V As Integer\nGet\nReturn _v\nEnd Get\nSet(value As Integer)\n_v = value\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.V = 10\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn prop_readonly_auto_fails() { assert_eq!(run_vb("Class C\n' ReadOnly Property V As Integer ' Auto-properties cannot be ReadOnly without initializer or constructor init\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn prop_readonly_with_get() { assert_eq!(run_vb("Class C\nPublic ReadOnly Property V As Integer\nGet\nReturn 42\nEnd Get\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["42"]); }

#[test] fn prop_readonly_set_fails() { assert_eq!(run_vb("Class C\nPublic ReadOnly Property V As Integer\nGet\nReturn 42\nEnd Get\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\n' c1.V = 10 ' Cannot assign to ReadOnly property\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn prop_writeonly_with_set() { assert_eq!(run_vb("Class C\nPrivate _v As Integer\nPublic WriteOnly Property V As Integer\nSet(value As Integer)\n_v = value\nEnd Set\nEnd Property\nPublic Function GetV() As Integer\nReturn _v\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.V = 5\nConsole.WriteLine(c1.GetV())\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn prop_writeonly_get_fails() { assert_eq!(run_vb("Class C\nPublic WriteOnly Property V As Integer\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\n' Dim x = c1.V ' Cannot read WriteOnly property\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn prop_set_implicit_value() { assert_eq!(run_vb("Class C\nPrivate _v As Integer\nPublic Property V As Integer\nGet\nReturn _v\nEnd Get\nSet ' Implicit value parameter\n_v = value\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.V = 7\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["7"]); }
#[test] fn prop_set_different_access_modifier() { assert_eq!(run_vb("Class C\nPrivate _v As Integer\nPublic Property V As Integer\nGet\nReturn _v\nEnd Get\nPrivate Set(value As Integer) ' Mixed access\n_v = value\nEnd Set\nEnd Property\nPublic Sub SetV(val As Integer)\nV = val\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.SetV(8)\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["8"]); }

#[test] fn prop_indexed_default() { assert_eq!(run_vb("Class C\nDefault Public Property Item(i As Integer) As String\nGet\nReturn \"A\" & i\nEnd Get\nSet(value As String)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1(5))\nEnd Sub\nEnd Module"), vec!["A5"]); }
#[test] fn prop_indexed_non_default() { assert_eq!(run_vb("Class C\nPublic Property Elem(i As Integer) As String\nGet\nReturn \"E\" & i\nEnd Get\nSet(value As String)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.Elem(3))\nEnd Sub\nEnd Module"), vec!["E3"]); }
#[test] fn prop_indexed_multiple_args() { assert_eq!(run_vb("Class C\nPublic Property Grid(x As Integer, y As Integer) As Integer\nGet\nReturn x + y\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.Grid(2, 3))\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn prop_get_implicit_return() { assert_eq!(run_vb("Class C\nPublic Property V As Integer\nGet\nV = 42\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["42"]); } // Can return via property name
#[test] fn prop_get_recursive_throws() { assert_eq!(run_vb("Class C\nPublic Property V As Integer\nGet\nReturn V ' Accessing itself without _v causes infinite recursion (StackOverflow)\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }

#[test] fn prop_byref_param_in_setter_fails() { assert_eq!(run_vb("Class C\n' Public Property V As Integer\n' Set(ByRef value As Integer) ' Setter param must be ByVal\n' End Set\n' End Property\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn prop_shared_property() { assert_eq!(run_vb("Class C\nPrivate Shared _v As Integer\nPublic Shared Property V As Integer\nGet\nReturn _v\nEnd Get\nSet(value As Integer)\n_v = value\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nC.V = 11\nConsole.WriteLine(C.V)\nEnd Sub\nEnd Module"), vec!["11"]); }
#[test] fn prop_overloads_same_name_different_args() { assert_eq!(run_vb("Class C\nPublic Property V(s As String) As Integer\nGet\nReturn 1\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nPublic Property V(i As Integer) As Integer\nGet\nReturn 2\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.V(\"A\") + c1.V(1))\nEnd Sub\nEnd Module"), vec!["3"]); }
#[test] fn prop_with_block_mutation() { assert_eq!(run_vb("Class C\nPublic Property V As Integer\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nWith c1\n.V = 10\n.V += 5\nConsole.WriteLine(.V)\nEnd With\nEnd Sub\nEnd Module"), vec!["15"]); }
#[test] fn prop_passing_to_byref() { assert_eq!(run_vb("Class C\nPublic Property V As Integer = 5\nEnd Class\nModule M\nSub Mutate(ByRef x As Integer)\nx = 10\nEnd Sub\nSub Main()\nDim c1 As New C()\nMutate(c1.V)\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["10"]); } // Copied back

#[test] fn prop_interface_implementation() { assert_eq!(run_vb("Interface I\nProperty V As Integer\nEnd Interface\nClass C\nImplements I\nPublic Property V As Integer Implements I.V\nEnd Class\nModule M\nSub Main()\nDim c1 As I = New C()\nc1.V = 3\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["3"]); }
#[test] fn prop_abstract_mustoverride() { assert_eq!(run_vb("MustInherit Class B\nPublic MustOverride Property V As Integer\nEnd Class\nClass C\nInherits B\nPublic Overrides Property V As Integer\nEnd Class\nModule M\nSub Main()\nDim c1 As B = New C()\nc1.V = 9\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["9"]); }
#[test] fn prop_virtual_overridable() { assert_eq!(run_vb("Class B\nPublic Overridable Property V As Integer\nGet\nReturn 1\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nClass C\nInherits B\nPublic Overrides Property V As Integer\nGet\nReturn 2\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As B = New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["2"]); }
#[test] fn prop_hiding_shadows() { assert_eq!(run_vb("Class B\nPublic Property V As Integer\nGet\nReturn 1\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nClass C\nInherits B\nPublic Shadows Property V As Integer\nGet\nReturn 2\nEnd Get\nSet(value As Integer)\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As B = New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["1"]); } // Early bound resolves to B.V
#[test] fn prop_late_bound_access() { assert_eq!(run_vb("Option Strict Off\nClass C\nPublic Property V As Integer = 8\nEnd Class\nModule M\nSub Main()\nDim obj As Object = New C()\nConsole.WriteLine(obj.V)\nEnd Sub\nEnd Module"), vec!["8"]); }
