use super::helpers::run_vb;

#[test] fn override_basic_method() { assert_eq!(run_vb("Class B\nPublic Overridable Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Overrides Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim b1 As B = New C()\nConsole.WriteLine(b1.M())\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn override_missing_overridable_fails() { assert_eq!(run_vb("Class B\nPublic Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\n' Public Overrides Function M() As String ' Cannot override non-overridable\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn override_missing_overrides_fails() { assert_eq!(run_vb("Class B\nPublic Overridable Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\n' Public Function M() As String ' Must specify Shadows or Overrides\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn shadow_basic_method() { assert_eq!(run_vb("Class B\nPublic Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Shadows Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.M())\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn shadow_method_base_reference() { assert_eq!(run_vb("Class B\nPublic Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Shadows Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim b1 As B = New C()\nConsole.WriteLine(b1.M())\nEnd Sub\nEnd Module"), vec!["B"]); }

#[test] fn shadow_implicit_warning_only() { assert_eq!(run_vb("Class B\nPublic Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\n' In VB, creating M without Shadows or Overrides is a warning, defaults to Shadows implicitly\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn override_mustoverride_basic() { assert_eq!(run_vb("MustInherit Class B\nPublic MustOverride Function M() As String\nEnd Class\nClass C\nInherits B\nPublic Overrides Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim b1 As B = New C()\nConsole.WriteLine(b1.M())\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn override_mustoverride_fails_if_not_implemented() { assert_eq!(run_vb("MustInherit Class B\nPublic MustOverride Function M() As String\nEnd Class\n' Class C: Inherits B ' Class must be MustInherit or override M\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn override_notoverridable() { assert_eq!(run_vb("Class B\nPublic Overridable Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic NotOverridable Overrides Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nClass D\nInherits C\n' Cannot override M again\nEnd Class\nModule M\nSub Main()\nDim d1 As New D()\nConsole.WriteLine(d1.M())\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn override_property_get() { assert_eq!(run_vb("Class B\nPublic Overridable Property V As Integer\nGet\nReturn 1\nEnd Get\nSet\nEnd Set\nEnd Property\nEnd Class\nClass C\nInherits B\nPublic Overrides Property V As Integer\nGet\nReturn 2\nEnd Get\nSet\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim b1 As B = New C()\nConsole.WriteLine(b1.V)\nEnd Sub\nEnd Module"), vec!["2"]); }

#[test] fn shadow_property_with_field() { assert_eq!(run_vb("Class B\nPublic Property V As Integer\nEnd Class\nClass C\nInherits B\nPublic Shadows V As Integer = 10\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn shadow_field_with_property() { assert_eq!(run_vb("Class B\nPublic V As Integer = 5\nEnd Class\nClass C\nInherits B\nPublic Shadows Property V As Integer\nGet\nReturn 10\nEnd Get\nSet\nEnd Set\nEnd Property\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.V)\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn override_changes_access_fails() { assert_eq!(run_vb("Class B\nProtected Overridable Sub M()\nEnd Sub\nEnd Class\nClass C\nInherits B\n' Public Overrides Sub M() ' Cannot change access modifier\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn shadow_changes_access_succeeds() { assert_eq!(run_vb("Class B\nProtected Sub M()\nEnd Sub\nEnd Class\nClass C\nInherits B\nPublic Shadows Sub M()\nConsole.WriteLine(\"C\")\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.M()\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn shadow_by_signature_or_name() { assert_eq!(run_vb("Class B\nPublic Sub M(v As Integer)\nEnd Sub\nEnd Class\nClass C\nInherits B\nPublic Shadows Sub M(s As String)\nConsole.WriteLine(\"C\")\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.M(\"A\")\nEnd Sub\nEnd Module"), vec!["C"]); } // Shadows hides all overloads of M by default

#[test] fn shadow_overloads() { assert_eq!(run_vb("Class B\nPublic Sub M(v As Integer)\nConsole.WriteLine(\"B\")\nEnd Sub\nEnd Class\nClass C\nInherits B\nPublic Overloads Sub M(s As String)\nConsole.WriteLine(\"C\")\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nc1.M(1)\nc1.M(\"A\")\nEnd Sub\nEnd Module"), vec!["B", "C"]); } // Overloads merges with base methods instead of hiding
#[test] fn override_covariant_return_fails() { assert_eq!(run_vb("Class B\nPublic Overridable Function M() As Object\nReturn Nothing\nEnd Function\nEnd Class\nClass C\nInherits B\n' Public Overrides Function M() As String ' VB doesn't support covariant return types\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn shadow_different_return_type() { assert_eq!(run_vb("Class B\nPublic Function M() As Object\nReturn Nothing\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Shadows Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.M())\nEnd Sub\nEnd Module"), vec!["C"]); } // Shadows allows changing signature entirely
#[test] fn override_requires_exact_signature() { assert_eq!(run_vb("Class B\nPublic Overridable Sub M(v As Integer)\nEnd Sub\nEnd Class\nClass C\nInherits B\n' Public Overrides Sub M(ByRef v As Integer) ' ByRef/ByVal must match exactly\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn override_mybase_access_in_overridden() { assert_eq!(run_vb("Class B\nPublic Overridable Function M() As Integer\nReturn 10\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Overrides Function M() As Integer\nReturn MyBase.M() + 5\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.M())\nEnd Sub\nEnd Module"), vec!["15"]); }

#[test] fn override_myclass_access_in_base() { assert_eq!(run_vb("Class B\nPublic Overridable Function M() As Integer\nReturn 10\nEnd Function\nPublic Function CallM() As Integer\nReturn MyClass.M()\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Overrides Function M() As Integer\nReturn 20\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.CallM())\nEnd Sub\nEnd Module"), vec!["10"]); } // MyClass M() resolves to B's M, ignoring C's override
#[test] fn shadow_myclass_access_in_base() { assert_eq!(run_vb("Class B\nPublic Function M() As Integer\nReturn 10\nEnd Function\nPublic Function CallM() As Integer\nReturn MyClass.M()\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Shadows Function M() As Integer\nReturn 20\nEnd Function\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nConsole.WriteLine(c1.CallM())\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn override_shared_fails() { assert_eq!(run_vb("Class B\n' Public Shared Overridable Sub M() ' Shared methods cannot be Overridable\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn shadow_shared_method() { assert_eq!(run_vb("Class B\nPublic Shared Function M() As String\nReturn \"B\"\nEnd Function\nEnd Class\nClass C\nInherits B\nPublic Shadows Shared Function M() As String\nReturn \"C\"\nEnd Function\nEnd Class\nModule M\nSub Main()\nConsole.WriteLine(C.M())\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn shadow_nested_type() { assert_eq!(run_vb("Class B\nClass N\nPublic V As Integer = 1\nEnd Class\nEnd Class\nClass C\nInherits B\nShadows Class N\nPublic V As Integer = 2\nEnd Class\nEnd Class\nModule M\nSub Main()\nDim n1 As New C.N()\nConsole.WriteLine(n1.V)\nEnd Sub\nEnd Module"), vec!["2"]); }
