use super::helpers::run_vb;

#[test] fn delegate_basic_declaration() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub Print()\nConsole.WriteLine(\"D\")\nEnd Sub\nSub Main()\nDim del As D = AddressOf Print\ndel()\nEnd Sub\nEnd Module"), vec!["D"]); }
#[test] fn delegate_invoke_method() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub Print()\nConsole.WriteLine(\"D\")\nEnd Sub\nSub Main()\nDim del As D = AddressOf Print\ndel.Invoke()\nEnd Sub\nEnd Module"), vec!["D"]); }
#[test] fn delegate_function() { assert_eq!(run_vb("Delegate Function D() As Integer\nModule M\nFunction GetV() As Integer\nReturn 42\nEnd Function\nSub Main()\nDim del As D = AddressOf GetV\nConsole.WriteLine(del())\nEnd Sub\nEnd Module"), vec!["42"]); }
#[test] fn delegate_with_args() { assert_eq!(run_vb("Delegate Sub D(v As Integer)\nModule M\nSub Print(v As Integer)\nConsole.WriteLine(v)\nEnd Sub\nSub Main()\nDim del As D = AddressOf Print\ndel(10)\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn delegate_multicast() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub P1()\nConsole.WriteLine(\"1\")\nEnd Sub\nSub P2()\nConsole.WriteLine(\"2\")\nEnd Sub\nSub Main()\nDim d1 As D = AddressOf P1\nDim d2 As D = AddressOf P2\nDim d3 As D = CType([Delegate].Combine(d1, d2), D)\nd3()\nEnd Sub\nEnd Module"), vec!["1", "2"]); }

#[test] fn delegate_implicit_instantiation() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub Print()\nConsole.WriteLine(\"D\")\nEnd Sub\nSub Main()\nDim del As D = AddressOf Print ' Implicitly New D(AddressOf Print)\ndel()\nEnd Sub\nEnd Module"), vec!["D"]); }
#[test] fn delegate_explicit_instantiation() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub Print()\nConsole.WriteLine(\"D\")\nEnd Sub\nSub Main()\nDim del As New D(AddressOf Print)\ndel()\nEnd Sub\nEnd Module"), vec!["D"]); }
#[test] fn delegate_address_of_instance_method() { assert_eq!(run_vb("Delegate Sub D()\nClass C\nPublic Sub Print()\nConsole.WriteLine(\"C\")\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim c1 As New C()\nDim del As D = AddressOf c1.Print\ndel()\nEnd Sub\nEnd Module"), vec!["C"]); }
#[test] fn delegate_address_of_shared_method() { assert_eq!(run_vb("Delegate Sub D()\nClass C\nPublic Shared Sub Print()\nConsole.WriteLine(\"S\")\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim del As D = AddressOf C.Print\ndel()\nEnd Sub\nEnd Module"), vec!["S"]); }
#[test] fn delegate_relaxation_drop_args() { assert_eq!(run_vb("Delegate Sub D(v As Integer)\nModule M\nSub Print() ' Takes 0 args, matches delegate taking 1 arg (relaxed)\nConsole.WriteLine(\"Relaxed\")\nEnd Sub\nSub Main()\nDim del As D = AddressOf Print\ndel(5)\nEnd Sub\nEnd Module"), vec!["Relaxed"]); }

#[test] fn delegate_relaxation_return_type_coercion() { assert_eq!(run_vb("Option Strict Off\nDelegate Function D() As String\nModule M\nFunction GetV() As Integer\nReturn 42\nEnd Function\nSub Main()\nDim del As D = AddressOf GetV ' Integer coerces to String\nConsole.WriteLine(del())\nEnd Sub\nEnd Module"), vec!["42"]); }
#[test] fn delegate_relaxation_arg_type_coercion() { assert_eq!(run_vb("Option Strict Off\nDelegate Sub D(v As Double)\nModule M\nSub Print(v As Integer)\nConsole.WriteLine(v)\nEnd Sub\nSub Main()\nDim del As D = AddressOf Print ' Double coerces to Integer (narrowing allowed with Strict Off)\ndel(5.5)\nEnd Sub\nEnd Module"), vec!["6"]); } // Bankers rounding 5.5 to 6
#[test] fn delegate_lambda_sub() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub Main()\nDim del As D = Sub() Console.WriteLine(\"Lambda\")\ndel()\nEnd Sub\nEnd Module"), vec!["Lambda"]); }
#[test] fn delegate_lambda_function() { assert_eq!(run_vb("Delegate Function D() As Integer\nModule M\nSub Main()\nDim del As D = Function() 42\nConsole.WriteLine(del())\nEnd Sub\nEnd Module"), vec!["42"]); }
#[test] fn delegate_lambda_with_args() { assert_eq!(run_vb("Delegate Function D(x As Integer, y As Integer) As Integer\nModule M\nSub Main()\nDim del As D = Function(a, b) a + b\nConsole.WriteLine(del(2, 3))\nEnd Sub\nEnd Module"), vec!["5"]); }

#[test] fn delegate_multiline_lambda_sub() { assert_eq!(run_vb("Delegate Sub D()\nModule M\nSub Main()\nDim del As D = Sub()\nConsole.WriteLine(\"L1\")\nConsole.WriteLine(\"L2\")\nEnd Sub\ndel()\nEnd Sub\nEnd Module"), vec!["L1", "L2"]); }
#[test] fn delegate_multiline_lambda_function() { assert_eq!(run_vb("Delegate Function D() As Integer\nModule M\nSub Main()\nDim del As D = Function()\nReturn 99\nEnd Function\nConsole.WriteLine(del())\nEnd Sub\nEnd Module"), vec!["99"]); }
#[test] fn delegate_closure_capture() { assert_eq!(run_vb("Delegate Function D() As Integer\nModule M\nSub Main()\nDim x = 5\nDim del As D = Function() x + 5\nx = 10\nConsole.WriteLine(del())\nEnd Sub\nEnd Module"), vec!["15"]); } // Captures by reference
#[test] fn delegate_action_implicit() { assert_eq!(run_vb("Module M\nSub Main()\nDim del As System.Action = Sub() Console.WriteLine(\"Action\")\ndel()\nEnd Sub\nEnd Module"), vec!["Action"]); }
#[test] fn delegate_func_implicit() { assert_eq!(run_vb("Module M\nSub Main()\nDim del As System.Func(Of Integer) = Function() 42\nConsole.WriteLine(del())\nEnd Sub\nEnd Module"), vec!["42"]); }

#[test] fn event_basic() { assert_eq!(run_vb("Class C\nPublic Event E()\nPublic Sub Raise()\nRaiseEvent E()\nEnd Sub\nEnd Class\nModule M\nSub Handler()\nConsole.WriteLine(\"Handled\")\nEnd Sub\nSub Main()\nDim c1 As New C()\nAddHandler c1.E, AddressOf Handler\nc1.Raise()\nEnd Sub\nEnd Module"), vec!["Handled"]); }
#[test] fn event_remove_handler() { assert_eq!(run_vb("Class C\nPublic Event E()\nPublic Sub Raise()\nRaiseEvent E()\nEnd Sub\nEnd Class\nModule M\nSub Handler()\nConsole.WriteLine(\"Handled\")\nEnd Sub\nSub Main()\nDim c1 As New C()\nAddHandler c1.E, AddressOf Handler\nRemoveHandler c1.E, AddressOf Handler\nc1.Raise()\nConsole.WriteLine(\"OK\")\nEnd Sub\nEnd Module"), vec!["OK"]); }
#[test] fn event_withevents_handles() { assert_eq!(run_vb("Class C\nPublic Event E()\nPublic Sub Raise()\nRaiseEvent E()\nEnd Sub\nEnd Class\nClass Wrapper\nPrivate WithEvents _c As New C()\nPrivate Sub Handler() Handles _c.E\nConsole.WriteLine(\"Handled\")\nEnd Sub\nPublic Sub Test()\n_c.Raise()\nEnd Sub\nEnd Class\nModule M\nSub Main()\nDim w As New Wrapper()\nw.Test()\nEnd Sub\nEnd Module"), vec!["Handled"]); }
#[test] fn event_custom_event() { assert_eq!(run_vb("Class C\nPublic Custom Event E As System.Action\nAddHandler(value As System.Action)\nConsole.WriteLine(\"Added\")\nEnd AddHandler\nRemoveHandler(value As System.Action)\nEnd RemoveHandler\nRaiseEvent()\nEnd RaiseEvent\nEnd Event\nEnd Class\nModule M\nSub Handler()\nEnd Sub\nSub Main()\nDim c1 As New C()\nAddHandler c1.E, AddressOf Handler\nEnd Sub\nEnd Module"), vec!["Added"]); }
#[test] fn event_delegate_type() { assert_eq!(run_vb("Delegate Sub D(v As Integer)\nClass C\nPublic Event E As D\nPublic Sub Raise()\nRaiseEvent E(5)\nEnd Sub\nEnd Class\nModule M\nSub Handler(v As Integer)\nConsole.WriteLine(v)\nEnd Sub\nSub Main()\nDim c1 As New C()\nAddHandler c1.E, AddressOf Handler\nc1.Raise()\nEnd Sub\nEnd Module"), vec!["5"]); }
