use super::helpers::run_vb;

#[test] fn struct_basic_instantiation() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 10\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["10"]); }
#[test] fn struct_new_instantiation() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As New S()\ns1.V = 5\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn struct_value_type_copy() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As New S()\ns1.V = 1\nDim s2 = s1\ns2.V = 2\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["1"]); } // Value type semantics
#[test] fn struct_parameterized_constructor() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nPublic Sub New(val As Integer)\nV = val\nEnd Sub\nEnd Structure\nModule M\nSub Main()\nDim s1 As New S(42)\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["42"]); }
#[test] fn struct_parameterless_constructor_fails() { assert_eq!(run_vb("Structure S\nPublic V As Integer\n' Public Sub New() ' Structures cannot have parameterless constructors in VB unless fields are initialized inline (and even then it's implicitly created)\n' End Sub\nEnd Structure\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }

#[test] fn struct_field_initializer_requires_constructor_in_old_vb() { assert_eq!(run_vb("Structure S\nPublic V As Integer = 5 ' This works in newer VB but traditionally required a constructor or Dim s As New S\nEnd Structure\nModule M\nSub Main()\nDim s1 As New S()\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn struct_method() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nPublic Function GetV() As Integer\nReturn V\nEnd Function\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 7\nConsole.WriteLine(s1.GetV())\nEnd Sub\nEnd Module"), vec!["7"]); }
#[test] fn struct_property() { assert_eq!(run_vb("Structure S\nPublic Property V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 8\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["8"]); }
#[test] fn struct_implements_interface() { assert_eq!(run_vb("Interface I\nFunction GetV() As Integer\nEnd Interface\nStructure S\nImplements I\nPublic Function GetV() As Integer Implements I.GetV\nReturn 42\nEnd Function\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\nConsole.WriteLine(s1.GetV())\nEnd Sub\nEnd Module"), vec!["42"]); }
#[test] fn struct_boxing() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 1\nDim obj As Object = s1\nDim s2 As S = DirectCast(obj, S)\nConsole.WriteLine(s2.V)\nEnd Sub\nEnd Module"), vec!["1"]); }

#[test] fn struct_boxing_mutation() { assert_eq!(run_vb("Option Strict Off\nStructure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 1\nDim obj As Object = s1\nobj.V = 2\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["1"]); } // Boxed copy is mutated, original is unaffected
#[test] fn struct_inheritance_fails() { assert_eq!(run_vb("Structure S1\nEnd Structure\n' Structure S2: Inherits S1 ' Structures cannot inherit\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn struct_inherit_class_fails() { assert_eq!(run_vb("Class C\nEnd Class\n' Structure S: Inherits C ' Structures cannot inherit\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn struct_inherited_by_class_fails() { assert_eq!(run_vb("Structure S\nEnd Structure\n' Class C: Inherits S ' Classes cannot inherit from structures\nModule M\nSub Main()\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn struct_nested_type() { assert_eq!(run_vb("Structure Outer\nStructure Inner\nPublic V As Integer\nEnd Structure\nPublic I As Inner\nEnd Structure\nModule M\nSub Main()\nDim o As Outer\no.I.V = 10\nConsole.WriteLine(o.I.V)\nEnd Sub\nEnd Module"), vec!["10"]); }

#[test] fn struct_shared_member() { assert_eq!(run_vb("Structure S\nPublic Shared V As Integer = 5\nEnd Structure\nModule M\nSub Main()\nConsole.WriteLine(S.V)\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn struct_shared_constructor() { assert_eq!(run_vb("Structure S\nPublic Shared V As Integer\nShared Sub New()\nV = 42\nEnd Sub\nEnd Structure\nModule M\nSub Main()\nConsole.WriteLine(S.V)\nEnd Sub\nEnd Module"), vec!["42"]); }
#[test] fn struct_equality_operator_fails_without_overload() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S, s2 As S\n' Dim eq = (s1 = s2) ' Operator = not defined for structure S\nConsole.WriteLine(\"Parsed\")\nEnd Sub\nEnd Module"), vec!["Parsed"]); }
#[test] fn struct_equals_method() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 1\nDim s2 As S\ns2.V = 1\nConsole.WriteLine(s1.Equals(s2))\nEnd Sub\nEnd Module"), vec!["True"]); } // Value type Equals compares fields via reflection
#[test] fn struct_not_nothing() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\nConsole.WriteLine(s1 IsNot Nothing)\nEnd Sub\nEnd Module"), vec!["True"]); } // Value types are never Nothing as a reference

#[test] fn struct_assigned_nothing() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\ns1.V = 5\ns1 = Nothing\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["0"]); } // Assigning Nothing zeroes out the struct
#[test] fn struct_array() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim arr(1) As S\narr(0).V = 5\nConsole.WriteLine(arr(0).V)\nEnd Sub\nEnd Module"), vec!["5"]); }
#[test] fn struct_array_copy() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Main()\nDim arr(1) As S\narr(0).V = 5\nDim s1 = arr(0)\ns1.V = 10\nConsole.WriteLine(arr(0).V)\nEnd Sub\nEnd Module"), vec!["5"]); } // s1 is a copy
#[test] fn struct_passing_byref() { assert_eq!(run_vb("Structure S\nPublic V As Integer\nEnd Structure\nModule M\nSub Mutate(ByRef s1 As S)\ns1.V = 2\nEnd Sub\nSub Main()\nDim s1 As S\ns1.V = 1\nMutate(s1)\nConsole.WriteLine(s1.V)\nEnd Sub\nEnd Module"), vec!["2"]); } // ByRef mutates original
#[test] fn struct_custom_event() { assert_eq!(run_vb("Structure S\nPublic Event E()\nPublic Sub Raise()\nRaiseEvent E()\nEnd Sub\nEnd Structure\nModule M\nSub Main()\nDim s1 As S\nConsole.WriteLine(s1 IsNot Nothing)\nEnd Sub\nEnd Module"), vec!["True"]); }
