//! Force-link every plugin crate this crate depends on.

use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");
    let manifest = std::fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let mut out = String::from("// @generated by build.rs — see its docs.\n");
    let mut in_deps = false;
    for line in manifest.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_deps = trimmed == "[dependencies]";
            continue;
        }
        if !in_deps {
            continue;
        }
        let Some(name) = trimmed.split(['=', ' ']).next() else {
            continue;
        };
        if name.starts_with("vybe_platform_") || name.starts_with("vybe_language_") {
            out.push_str(&format!("extern crate {name};\n"));
        }
    }
    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("linked_plugins.rs");
    let mut f = std::fs::File::create(dest).expect("create linked_plugins.rs");
    f.write_all(out.as_bytes())
        .expect("write linked_plugins.rs");
}
