//! `DataGridView` — the WinForms data grid.
//!
//! Inherits from `Control` directly. Property surface is large; we list
//! the user-facing ones (cells, columns, rows, behaviour, appearance).

use super::DotnetClass;

pub fn classes() -> &'static [DotnetClass] {
    &[DotnetClass {
        name: "DataGridView",
        parent: Some("Control"),
        properties: &[
            "AllowUserToAddRows",
            "AllowUserToDeleteRows",
            "AllowUserToOrderColumns",
            "AllowUserToResizeColumns",
            "AllowUserToResizeRows",
            "AlternatingRowsDefaultCellStyle",
            "AutoGenerateColumns",
            "AutoSizeColumnsMode",
            "AutoSizeRowsMode",
            "BackgroundColor",
            "BorderStyle",
            "CellBorderStyle",
            "ClipboardCopyMode",
            "ColumnCount",
            "ColumnHeadersBorderStyle",
            "ColumnHeadersDefaultCellStyle",
            "ColumnHeadersHeight",
            "ColumnHeadersHeightSizeMode",
            "ColumnHeadersVisible",
            "Columns",
            "CurrentCell",
            "CurrentCellAddress",
            "CurrentRow",
            "DataMember",
            "DataSource",
            "DefaultCellStyle",
            "EditMode",
            "EnableHeadersVisualStyles",
            "FirstDisplayedCell",
            "FirstDisplayedScrollingColumnIndex",
            "FirstDisplayedScrollingRowIndex",
            "GridColor",
            "MultiSelect",
            "NewRowIndex",
            "ReadOnly",
            "RowCount",
            "RowHeadersBorderStyle",
            "RowHeadersDefaultCellStyle",
            "RowHeadersVisible",
            "RowHeadersWidth",
            "RowHeadersWidthSizeMode",
            "Rows",
            "RowsDefaultCellStyle",
            "RowTemplate",
            "ScrollBars",
            "SelectedCells",
            "SelectedColumns",
            "SelectedRows",
            "SelectionMode",
            "ShowCellErrors",
            "ShowCellToolTips",
            "ShowEditingIcon",
            "ShowRowErrors",
            "Sort",
            "SortedColumn",
            "SortOrder",
            "StandardTab",
            "TopLeftHeaderCell",
            "VirtualMode",
        ],
        methods: &[],
        ctor_arity: 0,
        widget_host_fn: Some("new_DataGridView"),
        widget_host_module: "vybe:gui",
    }]
}
