[package]
name = "vybe_parser_generated_tests"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
publish = false

[workspace]

[features]
all-grammars = []

[dependencies]
vybe_parser = { path = ".." }

[build-dependencies]
vybe_parser_codegen = { path = "../codegen" }
vybe_parser = { path = ".." }

[dev-dependencies]
vybe_ast = { path = "../../vybe_ast" }
