[package]
name = "vybe_host"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
gui = ["vybe_widgets"]
gui_forms = ["gui"]

[dependencies]
vybe_bytecode = { workspace = true }
vybe_widgets = { workspace = true, optional = true }
regex = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
indexmap = { workspace = true }
