//! html, html/template, mime/quotedprintable, log/slog, log/syslog
//! - one distinct API per compile smoke (breadth over depth).


go_compile_cases! {
    // html
    html_escape_string => "package main; import \"html\"; func main() { _ = html.EscapeString(\"<b>bold</b>\") }",
    html_unescape_string => "package main; import \"html\"; func main() { _ = html.UnescapeString(\"&lt;b&gt;\") }",
    html_escape_writer => "package main; import \"html\"; import \"bytes\"; func main() { _ = html.Escape(bytes.NewBuffer(nil), []byte(\"<a>\")) }",

    // html/template
    html_template_new => "package main; import \"html/template\"; func main() { _ = html/template.New(\"page\") }",
    html_template_parse => "package main; import \"html/template\"; func main() { _, _ = html/template.New(\"p\").Parse(\"{{.Name}}\") }",
    html_template_escape_string => "package main; import \"html/template\"; func main() { _ = html/template.HTMLEscapeString(\"<div>\") }",
    html_template_escape_writer => "package main; import \"html/template\"; import \"bytes\"; func main() { html/template.HTMLEscape(bytes.NewBuffer(nil), []byte(\"<p>\")) }",
    html_template_js => "package main; import \"html/template\"; func main() { _ = html/template.JSEscapeString(\"alert(1)\") }",
    html_template_js_escape => "package main; import \"html/template\"; import \"bytes\"; func main() { html/template.JSEscape(bytes.NewBuffer(nil), []byte(\"fn()\")) }",
    html_template_css => "package main; import \"html/template\"; func main() { _ = html/template.CSSEscapeString(\"color:red\") }",
    html_template_css_escape => "package main; import \"html/template\"; import \"bytes\"; func main() { html/template.CSSEscape(bytes.NewBuffer(nil), []byte(\"body{}\")) }",
    html_template_url_escape => "package main; import \"html/template\"; func main() { _ = html/template.URLEscapeString(\"a=b c\") }",
    html_template_url_query => "package main; import \"html/template\"; func main() { _ = html/template.URLQueryEscaper([]byte(\"q=go\")) }",
    html_template_must => "package main; import \"html/template\"; func main() { _ = html/template.Must(html/template.New(\"m\").Parse(\"{{.}}\")) }",
    html_template_execute => "package main; import \"html/template\"; import \"bytes\"; func main() { t := html/template.Must(html/template.New(\"e\").Parse(\"{{.}}\")); _ = t.Execute(bytes.NewBuffer(nil), \"hi\") }",
    html_template_execute_template => "package main; import \"html/template\"; import \"bytes\"; func main() { t := html/template.Must(html/template.New(\"base\").Parse(\"{{.}}\")); _ = t.ExecuteTemplate(bytes.NewBuffer(nil), \"base\", \"x\") }",
    html_template_lookup => "package main; import \"html/template\"; func main() { t := html/template.Must(html/template.New(\"root\").Parse(\"{{.}}\")); _ = t.Lookup(\"root\") }",
    html_template_defined_templates => "package main; import \"html/template\"; func main() { t := html/template.Must(html/template.New(\"d\").Parse(\"{{.}}\")); _ = t.DefinedTemplates() }",
    html_template_parse_files => "package main; import \"html/template\"; func main() { _, _ = html/template.ParseFiles(\"tmpl.html\") }",
    html_template_parse_glob => "package main; import \"html/template\"; func main() { _, _ = html/template.ParseGlob(\"*.html\") }",
    html_template_clone => "package main; import \"html/template\"; func main() { t := html/template.Must(html/template.New(\"c\").Parse(\"{{.}}\")); _, _ = t.Clone() }",
    html_template_add_parse_tree => "package main; import \"html/template\"; import \"text/template/parse\"; func main() { t := html/template.New(\"a\"); tree, _ := parse.Parse(\"a\", \"{{.}}\", \"\", \"\"); _ = t.AddParseTree(\"a\", tree) }",
    html_template_option => "package main; import \"html/template\"; func main() { _ = html/template.New(\"o\").Option(\"missingkey=zero\") }",

    // mime/quotedprintable
    quotedprintable_new_reader => "package main; import \"mime/quotedprintable\"; import \"strings\"; func main() { _ = quotedprintable.NewReader(strings.NewReader(\"=41\")) }",
    quotedprintable_new_writer => "package main; import \"mime/quotedprintable\"; import \"bytes\"; func main() { _ = quotedprintable.NewWriter(bytes.NewBuffer(nil)) }",
    quotedprintable_reader_read => "package main; import \"mime/quotedprintable\"; import \"strings\"; func main() { r := quotedprintable.NewReader(strings.NewReader(\"=41\")); buf := make([]byte, 4); _, _ = r.Read(buf) }",
    quotedprintable_writer_write => "package main; import \"mime/quotedprintable\"; import \"bytes\"; func main() { w := quotedprintable.NewWriter(bytes.NewBuffer(nil)); _, _ = w.Write([]byte(\"A\")) }",
    quotedprintable_writer_close => "package main; import \"mime/quotedprintable\"; import \"bytes\"; func main() { w := quotedprintable.NewWriter(bytes.NewBuffer(nil)); _ = w.Close() }",

    // log/slog
    slog_new => "package main; import \"log/slog\"; import \"os\"; func main() { _ = slog.New(slog.NewTextHandler(os.Stdout, nil)) }",
    slog_default => "package main; import \"log/slog\"; func main() { _ = slog.Default() }",
    slog_set_default => "package main; import \"log/slog\"; func main() { slog.SetDefault(slog.Default()) }",
    slog_info => "package main; import \"log/slog\"; func main() { slog.Info(\"ready\") }",
    slog_debug => "package main; import \"log/slog\"; func main() { slog.Debug(\"trace\") }",
    slog_warn => "package main; import \"log/slog\"; func main() { slog.Warn(\"slow\") }",
    slog_error => "package main; import \"log/slog\"; func main() { slog.Error(\"fail\") }",
    slog_log => "package main; import \"log/slog\"; import \"context\"; func main() { slog.Log(context.Background(), slog.LevelInfo, \"msg\") }",
    slog_log_attrs => "package main; import \"log/slog\"; import \"context\"; func main() { slog.LogAttrs(context.Background(), slog.LevelInfo, \"msg\", slog.Int(\"n\", 1)) }",
    slog_with => "package main; import \"log/slog\"; func main() { _ = slog.With(\"k\", \"v\") }",
    slog_with_group => "package main; import \"log/slog\"; func main() { _ = slog.WithGroup(\"g\") }",
    slog_new_record => "package main; import \"log/slog\"; import \"time\"; func main() { _ = slog.NewRecord(time.Now(), slog.LevelInfo, \"msg\", 0) }",
    slog_level_info => "package main; import \"log/slog\"; func main() { _ = slog.LevelInfo }",
    slog_level_debug => "package main; import \"log/slog\"; func main() { _ = slog.LevelDebug }",
    slog_level_warn => "package main; import \"log/slog\"; func main() { _ = slog.LevelWarn }",
    slog_level_error => "package main; import \"log/slog\"; func main() { _ = slog.LevelError }",
    slog_int_attr => "package main; import \"log/slog\"; func main() { _ = slog.Int(\"n\", 42) }",
    slog_string_attr => "package main; import \"log/slog\"; func main() { _ = slog.String(\"s\", \"go\") }",
    slog_bool_attr => "package main; import \"log/slog\"; func main() { _ = slog.Bool(\"ok\", true) }",
    slog_any_attr => "package main; import \"log/slog\"; func main() { _ = slog.Any(\"v\", 1) }",
    slog_group => "package main; import \"log/slog\"; func main() { _ = slog.Group(\"g\", slog.Int(\"n\", 1)) }",
    slog_new_text_handler => "package main; import \"log/slog\"; import \"os\"; func main() { _ = slog.NewTextHandler(os.Stdout, nil) }",
    slog_new_json_handler => "package main; import \"log/slog\"; import \"os\"; func main() { _ = slog.NewJSONHandler(os.Stdout, nil) }",
    slog_set_log_logger_level => "package main; import \"log/slog\"; func main() { _ = slog.SetLogLoggerLevel(slog.LevelInfo) }",
    slog_level_string => "package main; import \"log/slog\"; func main() { _ = slog.LevelInfo.String() }",
    slog_level_enabled => "package main; import \"log/slog\"; import \"context\"; func main() { _ = slog.Default().Enabled(context.Background(), slog.LevelInfo) }",
    slog_handler_with_attrs => "package main; import \"log/slog\"; import \"os\"; func main() { h := slog.NewTextHandler(os.Stdout, nil); _ = h.WithAttrs(nil) }",
    slog_handler_with_group => "package main; import \"log/slog\"; import \"os\"; func main() { h := slog.NewTextHandler(os.Stdout, nil); _ = h.WithGroup(\"g\") }",

    // log/syslog
    syslog_new => "package main; import \"log/syslog\"; func main() { _, _ = syslog.New(syslog.LOG_INFO, \"app\") }",
    syslog_new_logger => "package main; import \"log/syslog\"; func main() { _, _ = syslog.NewLogger(syslog.LOG_INFO, \"app\") }",
    syslog_dial => "package main; import \"log/syslog\"; func main() { _, _ = syslog.Dial(\"\", \"\", syslog.LOG_INFO, \"app\") }",
    syslog_writer => "package main; import \"log/syslog\"; func main() { _, _ = syslog.Writer() }",
    syslog_priority_info => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_INFO }",
    syslog_priority_err => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_ERR }",
    syslog_priority_debug => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_DEBUG }",
    syslog_priority_warning => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_WARNING }",
    syslog_priority_crit => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_CRIT }",
    syslog_priority_alert => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_ALERT }",
    syslog_priority_emerg => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_EMERG }",
    syslog_priority_notice => "package main; import \"log/syslog\"; func main() { _ = syslog.LOG_NOTICE }",
}
