//! Defer LIFO stack — print order, named returns, loop capture, return/panic interaction.

go_run_cases! {
    defer_two_prints_reverse_order => ("package main; import \"fmt\"; func main() { defer fmt.Println(\"first\"); defer fmt.Println(\"second\"); }", vec!["second", "first"]),
    defer_three_prints_lifo => ("package main; import \"fmt\"; func main() { defer fmt.Println(1); defer fmt.Println(2); defer fmt.Println(3); }", vec!["3", "2", "1"]),
    defer_five_level_stack => ("package main; import \"fmt\"; func main() { defer fmt.Println(\"a\"); defer fmt.Println(\"b\"); defer fmt.Println(\"c\"); defer fmt.Println(\"d\"); defer fmt.Println(\"e\"); }", vec!["e", "d", "c", "b", "a"]),
    defer_mixed_func_and_literal_order => ("package main; import \"fmt\"; func tag(s string) { fmt.Println(s) }; func main() { defer tag(\"one\"); defer func() { fmt.Println(\"two\") }(); defer tag(\"three\"); }", vec!["three", "two", "one"]),
    defer_registered_in_inner_call_runs_before_outer => ("package main; import \"fmt\"; func inner() { defer fmt.Println(\"inner\"); }; func main() { defer fmt.Println(\"outer\"); inner(); }", vec!["inner", "outer"]),
    defer_before_explicit_return => ("package main; import \"fmt\"; func work() int { defer fmt.Println(\"defer\"); fmt.Println(\"body\"); return 1 }; func main() { fmt.Println(work()) }", vec!["body", "defer", "1"]),
    defer_runs_after_return_value_evaluated => ("package main; import \"fmt\"; func work() int { defer fmt.Println(\"defer\"); return func() int { fmt.Println(\"ret\"); return 2 }() }; func main() { fmt.Println(work()) }", vec!["ret", "defer", "2"]),
    defer_named_return_int_overwritten => ("package main; import \"fmt\"; func work() (n int) { defer func() { n = 20 }(); return 5 }; func main() { fmt.Println(work()) }", vec!["20"]),
    defer_named_return_string_overwritten => ("package main; import \"fmt\"; func work() (s string) { defer func() { s = \"bye\" }(); return \"hi\" }; func main() { fmt.Println(work()) }", vec!["bye"]),
    defer_named_return_two_values_both_set => ("package main; import \"fmt\"; func work() (a int, b int) { defer func() { a = 1; b = 2 }(); return 9, 8 }; func main() { x, y := work(); fmt.Println(x); fmt.Println(y) }", vec!["1", "2"]),
    defer_named_return_bare_return_uses_updated => ("package main; import \"fmt\"; func work() (n int) { defer func() { n = n + 1 }(); n = 4; return }; func main() { fmt.Println(work()) }", vec!["5"]),
    defer_named_return_increment_twice => ("package main; import \"fmt\"; func work() (n int) { defer func() { n++ }(); defer func() { n++ }(); return 0 }; func main() { fmt.Println(work()) }", vec!["2"]),
    defer_named_return_bool_set_true => ("package main; import \"fmt\"; func work() (ok bool) { defer func() { ok = true }(); return false }; func main() { fmt.Println(work()) }", vec!["true"]),
    defer_named_return_float64_scaled => ("package main; import \"fmt\"; func work() (f float64) { defer func() { f = f * 2 }(); return 3.5 }; func main() { fmt.Println(f == 7.0) }", vec!["true"]),
    defer_closure_captures_loop_var_classic => ("package main; import \"fmt\"; func main() { for i := 0; i < 3; i++ { defer func() { fmt.Println(i) }() }; }", vec!["3", "3", "3"]),
    defer_closure_captures_loop_var_fixed_by_param => ("package main; import \"fmt\"; func main() { for i := 0; i < 3; i++ { defer func(n int) { fmt.Println(n) }(i) }; }", vec!["2", "1", "0"]),
    defer_range_loop_registers_lifo => ("package main; import \"fmt\"; func main() { for _, v := range []int{10, 20} { defer fmt.Println(v) } }", vec!["20", "10"]),
    defer_for_loop_break_registers_partial => ("package main; import \"fmt\"; func main() { for i := 0; i < 5; i++ { defer fmt.Println(i); if i == 1 { break } } }", vec!["1", "0"]),
    defer_in_nested_loops_six_entries => ("package main; import \"fmt\"; func main() { for i := 0; i < 2; i++ { for j := 0; j < 3; j++ { defer fmt.Println(i*10+j) } } }", vec!["12", "11", "10", "2", "1", "0"]),
    defer_arg_evaluated_at_register_time => ("package main; import \"fmt\"; func main() { n := 1; defer fmt.Println(n); n = 9; }", vec!["1"]),
    defer_method_receiver_evaluated_early => ("package main; import \"fmt\"; type T struct { v int }; func (t T) show() { fmt.Println(t.v) }; func main() { t := T{v: 1}; defer t.show(); t.v = 2; }", vec!["1"]),
    defer_pointer_receiver_sees_mutation => ("package main; import \"fmt\"; type T struct { v int }; func (t *T) show() { fmt.Println(t.v) }; func main() { t := &T{v: 1}; defer t.show(); t.v = 2; }", vec!["2"]),
    defer_after_panic_still_runs_with_recover => ("package main; import \"fmt\"; func run() { defer fmt.Println(\"cleanup\"); defer func() { recover() }(); panic(\"stop\"); fmt.Println(\"skip\") }; func main() { run(); fmt.Println(\"done\") }", vec!["cleanup", "done"]),
    defer_lifo_with_panic_middle_frame => ("package main; import \"fmt\"; func run() { defer fmt.Println(\"c\"); defer fmt.Println(\"b\"); defer func() { recover() }(); fmt.Println(\"a\"); panic(\"x\") }; func main() { run() }", vec!["a", "c", "b"]),
    defer_inside_deferred_func_runs_first_on_exit => ("package main; import \"fmt\"; func main() { defer func() { defer fmt.Println(\"inner\"); fmt.Println(\"outer\") }(); }", vec!["outer", "inner"]),
    defer_chain_three_closures => ("package main; import \"fmt\"; func main() { defer func() { fmt.Println(3) }(); defer func() { fmt.Println(2) }(); defer func() { fmt.Println(1) }(); }", vec!["1", "2", "3"]),
    defer_with_if_else_register => ("package main; import \"fmt\"; func main() { ok := true; if ok { defer fmt.Println(\"yes\") } else { defer fmt.Println(\"no\") } }", vec!["yes"]),
    defer_in_switch_case => ("package main; import \"fmt\"; func main() { switch 2 { case 2: defer fmt.Println(\"case\"); default: defer fmt.Println(\"def\") } }", vec!["case"]),
    defer_in_select_case => ("package main; import \"fmt\"; func main() { ch := make(chan int, 1); ch <- 1; select { case <-ch: defer fmt.Println(\"sel\"); default: defer fmt.Println(\"def\") } }", vec!["sel"]),
    defer_before_return_in_nested_func => ("package main; import \"fmt\"; func inner() int { defer fmt.Println(\"in\"); return 1 }; func main() { defer fmt.Println(\"out\"); fmt.Println(inner()) }", vec!["in", "1", "out"]),
    defer_modifies_outer_named_via_closure => ("package main; import \"fmt\"; func main() { result := 0; defer func() { result = 5 }(); fmt.Println(result) }", vec!["0"]),
    defer_runs_at_function_exit_not_block => ("package main; import \"fmt\"; func main() { if true { defer fmt.Println(\"defer\"); fmt.Println(\"block\"); }; fmt.Println(\"main\") }", vec!["block", "main", "defer"]),
    defer_multiple_modify_same_named_return => ("package main; import \"fmt\"; func work() (n int) { defer func() { n += 1 }(); defer func() { n += 10 }(); return 0 }; func main() { fmt.Println(work()) }", vec!["11"]),
    defer_with_recover_then_next_defer => ("package main; import \"fmt\"; func run() { defer fmt.Println(\"last\"); defer func() { recover() }(); defer fmt.Println(\"mid\"); panic(\"p\") }; func main() { run() }", vec!["last", "mid"]),
    defer_prints_after_return_in_main => ("package main; import \"fmt\"; func main() { defer fmt.Println(\"end\"); fmt.Println(\"start\"); return; fmt.Println(\"skip\") }", vec!["start", "end"]),
    defer_in_anonymous_func_separate_stack => ("package main; import \"fmt\"; func main() { defer fmt.Println(\"main\"); func() { defer fmt.Println(\"anon\"); }(); }", vec!["anon", "main"]),
    defer_lifo_preserves_registration_order_on_panic => ("package main; import \"fmt\"; func run() { defer fmt.Println(1); defer fmt.Println(2); defer func() { recover() }(); panic(\"x\") }; func main() { run() }", vec!["2", "1"]),
    defer_on_label_statement_in_loop => ("package main; import \"fmt\"; func main() { for i := 0; i < 2; i++ { defer fmt.Println(i); if i == 1 { break } } }", vec!["1", "0"]),
    defer_captures_outer_var_by_reference => ("package main; import \"fmt\"; func main() { n := 0; defer func() { fmt.Println(n) }(); n = 7; }", vec!["7"]),
    defer_with_variadic_helper => ("package main; import \"fmt\"; func show(parts ...string) { fmt.Println(len(parts)) }; func main() { defer show(\"a\", \"b\"); }", vec!["2"]),
    defer_string_concat_in_defer_arg => ("package main; import \"fmt\"; func main() { s := \"go\"; defer fmt.Println(s + \"lang\"); s = \"rust\"; }", vec!["golang"]),
    defer_in_type_switch_case => ("package main; import \"fmt\"; func tag(v interface{}) { switch v.(type) { case int: defer fmt.Println(\"int\"); default: defer fmt.Println(\"def\") } }; func main() { tag(1) }", vec!["int"]),
    defer_two_funcs_same_name_different_order => ("package main; import \"fmt\"; func a() { fmt.Println(\"a\") }; func b() { fmt.Println(\"b\") }; func main() { defer a(); defer b(); }", vec!["b", "a"]),
    defer_after_short_var_in_if => ("package main; import \"fmt\"; func main() { if x := 1; x > 0 { defer fmt.Println(x); }; }", vec!["1"]),
    defer_runs_on_os_exit_path_not_called => ("package main; import \"fmt\"; func main() { defer fmt.Println(\"defer\"); fmt.Println(\"run\"); }", vec!["run", "defer"]),
    defer_named_return_struct_field => ("package main; import \"fmt\"; type pair struct { a int; b int }; func work() (p pair) { defer func() { p.b = 3 }(); p.a = 1; return }; func main() { r := work(); fmt.Println(r.a); fmt.Println(r.b) }", vec!["1", "3"]),
    defer_lifo_with_empty_func_body => ("package main; import \"fmt\"; func noop() {}; func main() { defer noop(); defer fmt.Println(\"x\"); }", vec!["x"]),
    defer_in_init_not_in_main => ("package main; import \"fmt\"; var x = func() int { defer fmt.Println(\"init\"); return 1 }(); func main() { fmt.Println(x) }", vec!["init", "1"]),
    defer_accumulates_in_loop_with_continue => ("package main; import \"fmt\"; func main() { for i := 0; i < 3; i++ { defer fmt.Println(i); if i == 0 { continue } } }", vec!["2", "1", "0"]),
    defer_with_map_literal_arg => ("package main; import \"fmt\"; func main() { m := map[string]int{\"a\": 1}; defer fmt.Println(m[\"a\"]); m[\"a\"] = 9; }", vec!["1"]),
    defer_before_goto_not_supported_use_break => ("package main; import \"fmt\"; func main() { loop: for i := 0; i < 2; i++ { defer fmt.Println(i); if i == 1 { break loop } } }", vec!["1", "0"]),
    defer_on_method_value => ("package main; import \"fmt\"; type counter struct { n int }; func (c counter) val() { fmt.Println(c.n) }; func main() { c := counter{n: 5}; defer c.val(); c.n = 9; }", vec!["5"]),
    defer_on_method_expr_with_pointer => ("package main; import \"fmt\"; type counter struct { n int }; func (c *counter) val() { fmt.Println(c.n) }; func main() { c := &counter{n: 5}; defer c.val(); c.n = 9; }", vec!["9"]),
    defer_runs_after_panic_in_same_func_with_recover_outer => ("package main; import \"fmt\"; func run() { defer fmt.Println(\"a\"); panic(\"p\") }; func main() { defer func() { recover() }(); run() }", vec!["a"]),
    defer_order_with_three_named_funcs => ("package main; import \"fmt\"; func p1() { fmt.Println(1) }; func p2() { fmt.Println(2) }; func p3() { fmt.Println(3) }; func main() { defer p1(); defer p2(); defer p3(); }", vec!["3", "2", "1"]),
    defer_in_defer_registers_inner_first_on_pop => ("package main; import \"fmt\"; func main() { defer func() { defer fmt.Println(2); fmt.Println(1) }(); }", vec!["1", "2"]),
    defer_before_return_zero_value => ("package main; import \"fmt\"; func work() int { defer fmt.Println(\"d\"); return 0 }; func main() { fmt.Println(work()) }", vec!["d", "0"]),
    defer_with_slice_arg_copy => ("package main; import \"fmt\"; func main() { s := []int{1, 2}; defer fmt.Println(len(s)); s = append(s, 3); }", vec!["2"]),
    defer_closure_modifies_slice_header => ("package main; import \"fmt\"; func main() { s := []int{1}; defer func() { fmt.Println(len(s)) }(); s = append(s, 2); }", vec!["2"]),
}

go_compile_cases! {
    defer_after_panic_without_recover_compile => "package main; func run() { defer func() {}(); panic(\"x\"); defer func() { _ = 1 }() }; func main() { run() }",
    defer_in_defer_panic_uncaught_compile => "package main; func run() { defer func() { panic(\"inner\") }(); panic(\"outer\") }; func main() { run() }",
    defer_on_non_call_expression_compile => "package main; func main() { defer 1 + 2 }",
    defer_with_return_values_compile => "package main; func main() { defer func() int { return 1 }() }",
    defer_in_function_literal_label_compile => "package main; func main() { f := func() { defer func() {}() }; f() }",
    defer_named_return_and_naked_return_compile => "package main; func work() (n int) { defer func() { n = 1 }(); return n }; func main() { _ = work() }",
    defer_in_select_with_fallthrough_compile => "package main; func main() { ch := make(chan int); select { case <-ch: defer func() {}(); default: } }",
    defer_register_in_init_with_panic_compile => "package main; func init() { defer func() { recover() }(); panic(\"init\") }; func main() {}",
    defer_method_on_nil_pointer_compile => "package main; type T struct{}; func (t *T) f() {}; func main() { var t *T; defer t.f() }",
    defer_in_go_statement_compile => "package main; func main() { defer func() { go func() {}() }() }",
}
