//! go/build, go/constant, go/doc, go/format, go/importer, go/printer, go/types, go/version — breadth-only, one API per test.


go_compile_cases! {
    build_default => "package main; import \"go/build\"; func main() { _ = build.Default }",
    build_import => "package main; import \"go/build\"; func main() { _, _ = build.Import(\"fmt\", \".\", 0) }",
    build_import_dir => "package main; import \"go/build\"; func main() { _, _ = build.ImportDir(\".\", 0) }",
    build_context_import => "package main; import \"go/build\"; func main() { _, _ = build.Default.Import(\"fmt\", \".\", 0) }",
    build_context_import_dir => "package main; import \"go/build\"; func main() { _, _ = build.Default.ImportDir(\".\", 0) }",
    build_context_is_abs_path => "package main; import \"go/build\"; func main() { _ = build.Default.IsAbsPath(\"/x\") }",
    build_context_is_dir => "package main; import \"go/build\"; func main() { _, _ = build.Default.IsDir(\".\") }",
    build_context_is_local_import => "package main; import \"go/build\"; func main() { _ = build.Default.IsLocalImport(\"./x\") }",
    build_context_join_path => "package main; import \"go/build\"; func main() { _, _ = build.Default.JoinPath(\"a\", \"b\") }",
    build_context_split_path_list => "package main; import \"go/build\"; func main() { _ = build.Default.SplitPathList(\"a:b\") }",
    build_context_validated_go_version => "package main; import \"go/build\"; func main() { _, _ = build.Default.ValidatedGoVersion(\"go1.21\") }",
    build_context_match => "package main; import \"go/build\"; func main() { _, _ = build.Default.Match([]string{\"*.go\"}, \".\") }",
    build_context_src_dirs => "package main; import \"go/build\"; func main() { _ = build.Default.SrcDirs() }",
    build_find_only => "package main; import \"go/build\"; func main() { _ = build.FindOnly }",
    build_ignore_vendor => "package main; import \"go/build\"; func main() { _ = build.IgnoreVendor }",
    build_import_comment => "package main; import \"go/build\"; func main() { _ = build.ImportComment }",
    build_allow_binary => "package main; import \"go/build\"; func main() { _ = build.AllowBinary }",
    build_tool_tags => "package main; import \"go/build\"; func main() { _ = build.ToolTags }",
    build_release_tags => "package main; import \"go/build\"; func main() { _ = build.ReleaseTags }",
    constant_make => "package main; import \"go/constant\"; func main() { _ = constant.Make(1) }",
    constant_make_from_bytes => "package main; import \"go/constant\"; func main() { _ = constant.MakeFromBytes([]byte{1}) }",
    constant_make_from_literal => "package main; import \"go/constant\"; func main() { _, _ = constant.MakeFromLiteral(\"1\", constant.Int, 0) }",
    constant_make_bool => "package main; import \"go/constant\"; func main() { _ = constant.MakeBool(true) }",
    constant_make_int64 => "package main; import \"go/constant\"; func main() { _ = constant.MakeInt64(1) }",
    constant_make_uint64 => "package main; import \"go/constant\"; func main() { _ = constant.MakeUint64(1) }",
    constant_make_float64 => "package main; import \"go/constant\"; func main() { _ = constant.MakeFloat64(1.0) }",
    constant_make_string => "package main; import \"go/constant\"; func main() { _ = constant.MakeString(\"x\") }",
    constant_make_char => "package main; import \"go/constant\"; func main() { _ = constant.MakeChar(65) }",
    constant_make_unknown => "package main; import \"go/constant\"; func main() { _ = constant.MakeUnknown() }",
    constant_kind => "package main; import \"go/constant\"; func main() { _ = constant.Kind(constant.Make(1)) }",
    constant_string_val => "package main; import \"go/constant\"; func main() { _ = constant.String(constant.Make(1)) }",
    constant_bool_val => "package main; import \"go/constant\"; func main() { _, _ = constant.Bool(constant.MakeBool(true)) }",
    constant_int64_val => "package main; import \"go/constant\"; func main() { _, _ = constant.Int64Val(constant.MakeInt64(1)) }",
    constant_uint64_val => "package main; import \"go/constant\"; func main() { _, _ = constant.Uint64Val(constant.MakeUint64(1)) }",
    constant_float32_val => "package main; import \"go/constant\"; func main() { _, _ = constant.Float32Val(constant.MakeFloat64(1.0)) }",
    doc_new => "package main; import \"go/doc\"; import \"go/parser\"; import \"go/token\"; func main() { fs := token.NewFileSet(); f, _ := parser.ParseFile(fs, \"\", \"package main\\nfunc F() {}\", 0); _, _ = doc.New(f, \"./\", 0) }",
    doc_new_from_files => "package main; import \"go/doc\"; import \"go/ast\"; import \"go/parser\"; import \"go/token\"; func main() { fs := token.NewFileSet(); f, _ := parser.ParseFile(fs, \"\", \"package main\", 0); _, _ = doc.NewFromFiles(fs, []*ast.File{f}, \"./\", 0) }",
    doc_to_html => "package main; import \"go/doc\"; import \"bytes\"; func main() { var b bytes.Buffer; doc.ToHTML(&b, \"Title\", []byte(\"body\")) }",
    doc_to_text => "package main; import \"go/doc\"; import \"bytes\"; func main() { var b bytes.Buffer; doc.ToText(&b, \"Title\", []byte(\"body\"), \"\", 0) }",
    doc_is_predeclared => "package main; import \"go/doc\"; func main() { _ = doc.IsPredeclared(\"int\") }",
    doc_is_principal => "package main; import \"go/doc\"; func main() { _ = doc.IsPrincipal(\"main\") }",
    doc_example_suffix => "package main; import \"go/doc\"; func main() { _ = doc.ExampleSuffix(\"Example\") }",
    doc_filter => "package main; import \"go/doc\"; func main() { _ = doc.Filter(nil, nil) }",
    doc_note => "package main; import \"go/doc\"; func main() { _ = doc.Note{Key: \"BUG\", Body: \"x\"} }",
    format_node => "package main; import \"go/format\"; import \"go/parser\"; func main() { f, _ := parser.ParseFile(nil, \"\", \"package main\", 0); _ = format.Node(nil, f) }",
    format_source => "package main; import \"go/format\"; func main() { _, _ = format.Source([]byte(\"package main\")) }",
    importer_default => "package main; import \"go/importer\"; func main() { _ = importer.Default() }",
    importer_for => "package main; import \"go/importer\"; import \"go/token\"; func main() { _ = importer.For(token.NewFileSet(), nil) }",
    importer_from => "package main; import \"go/importer\"; import \"go/token\"; func main() { _ = importer.From(\"gc\", \"./\", nil) }",
    printer_fprint => "package main; import \"go/printer\"; import \"go/ast\"; func main() { _ = printer.Fprint(nil, nil, &ast.Ident{Name: \"x\"}) }",
    printer_config_fprint => "package main; import \"go/printer\"; import \"go/ast\"; func main() { var c printer.Config; _ = c.Fprint(nil, nil, &ast.Ident{Name: \"x\"}) }",
    printer_commented_node => "package main; import \"go/printer\"; import \"go/ast\"; func main() { _ = printer.CommentedNode{Node: &ast.Ident{Name: \"x\"}, Comments: nil} }",
    printer_raw_format => "package main; import \"go/printer\"; func main() { _ = printer.RawFormat }",
    printer_tab_indent => "package main; import \"go/printer\"; func main() { _ = printer.TabIndent }",
    printer_use_spaces => "package main; import \"go/printer\"; func main() { _ = printer.UseSpaces }",
    version_lang => "package main; import \"go/version\"; func main() { _ = version.Lang }",
    version_compare => "package main; import \"go/version\"; func main() { _ = version.Compare(\"go1.21\", \"go1.22\") }",
    version_is_valid => "package main; import \"go/version\"; func main() { _ = version.IsValid(\"go1.21\") }",
    types_new_package => "package main; import \"go/types\"; func main() { _ = types.NewPackage(\"p\", \"p\") }",
    types_new_scope => "package main; import \"go/types\"; func main() { _ = types.NewScope(nil) }",
    types_new_named => "package main; import \"go/types\"; func main() { _ = types.NewNamed(types.NewTypeName(0, nil, \"T\", nil), types.Typ[types.Int], nil) }",
    types_new_interface => "package main; import \"go/types\"; func main() { _ = types.NewInterfaceType(nil, nil) }",
    types_new_struct => "package main; import \"go/types\"; func main() { _ = types.NewStruct(nil, nil) }",
    types_type_string => "package main; import \"go/types\"; func main() { _ = types.TypeString(types.Typ[types.Int], nil) }",
    types_identical => "package main; import \"go/types\"; func main() { _ = types.Identical(types.Typ[types.Int], types.Typ[types.Int]) }",
    types_assignable_to => "package main; import \"go/types\"; func main() { _ = types.AssignableTo(types.Typ[types.Int], types.Typ[types.Int]) }",
    types_convertible_to => "package main; import \"go/types\"; func main() { _ = types.ConvertibleTo(types.Typ[types.Int], types.Typ[types.Int64]) }",
    types_implements => "package main; import \"go/types\"; func main() { _ = types.Implements(types.Typ[types.Int], types.NewInterfaceType(nil, nil)) }",
}
