//! Switch fallthrough and expression forms — init, tagless, bool, string, default, empty compile.

go_run_cases! {
    fallthrough_to_next_case => ("package main; import \"fmt\"; func main() { x := 1; switch x { case 1: fmt.Println(\"a\"); fallthrough; case 2: fmt.Println(\"b\") } }", vec!["a", "b"]),
    fallthrough_skips_case_check => ("package main; import \"fmt\"; func main() { x := 1; switch x { case 1: fmt.Println(1); fallthrough; case 3: fmt.Println(3) } }", vec!["1", "3"]),
    fallthrough_into_default => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(\"one\"); fallthrough; default: fmt.Println(\"def\") } }", vec!["one", "def"]),
    fallthrough_chain_three_cases => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(1); fallthrough; case 2: fmt.Println(2); fallthrough; case 3: fmt.Println(3) } }", vec!["1", "2", "3"]),
    fallthrough_stops_at_case_without => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(1); fallthrough; case 2: fmt.Println(2); case 3: fmt.Println(3) } }", vec!["1", "2"]),
    expression_switch_with_init => ("package main; import \"fmt\"; func main() { switch n := 4; n { case 4: fmt.Println(\"four\"); default: fmt.Println(\"other\") } }", vec!["four"]),
    expression_switch_init_shadows_outer => ("package main; import \"fmt\"; func main() { n := 1; switch n := 2; n { case 2: fmt.Println(n); default: fmt.Println(0) }; fmt.Println(n) }", vec!["2", "1"]),
    expression_switch_init_with_side_effect => ("package main; import \"fmt\"; func main() { count := 0; switch count++; count { case 1: fmt.Println(count); default: fmt.Println(0) } }", vec!["1"]),
    tagless_switch_first_true_case => ("package main; import \"fmt\"; func main() { x := 7; switch { case x < 5: fmt.Println(\"low\"); case x < 10: fmt.Println(\"mid\"); default: fmt.Println(\"high\") } }", vec!["mid"]),
    tagless_switch_multiple_false_then_true => ("package main; import \"fmt\"; func main() { n := 12; switch { case n%2 == 1: fmt.Println(\"odd\"); case n%3 == 0: fmt.Println(\"three\"); case n%4 == 0: fmt.Println(\"four\"); default: fmt.Println(\"none\") } }", vec!["three"]),
    tagless_switch_default_only => ("package main; import \"fmt\"; func main() { switch { default: fmt.Println(\"def\") } }", vec!["def"]),
    tagless_switch_no_match_no_default => ("package main; import \"fmt\"; func main() { switch { case false: fmt.Println(\"no\") }; fmt.Println(\"done\") }", vec!["done"]),
    switch_on_bool_true => ("package main; import \"fmt\"; func main() { switch true { case true: fmt.Println(\"yes\"); case false: fmt.Println(\"no\") } }", vec!["yes"]),
    switch_on_bool_false => ("package main; import \"fmt\"; func main() { switch false { case true: fmt.Println(\"yes\"); case false: fmt.Println(\"no\") } }", vec!["no"]),
    switch_on_string_match => ("package main; import \"fmt\"; func main() { switch \"go\" { case \"go\": fmt.Println(\"match\"); default: fmt.Println(\"miss\") } }", vec!["match"]),
    switch_on_string_default => ("package main; import \"fmt\"; func main() { switch \"rust\" { case \"go\": fmt.Println(\"go\"); default: fmt.Println(\"other\") } }", vec!["other"]),
    switch_on_string_multi_case => ("package main; import \"fmt\"; func main() { switch \"a\" { case \"a\", \"b\": fmt.Println(\"ab\"); default: fmt.Println(\"x\") } }", vec!["ab"]),
    default_case_last_position => ("package main; import \"fmt\"; func main() { switch 99 { case 1: fmt.Println(1); case 2: fmt.Println(2); default: fmt.Println(\"def\") } }", vec!["def"]),
    default_case_first_still_works => ("package main; import \"fmt\"; func main() { switch 5 { default: fmt.Println(\"def\"); case 1: fmt.Println(1) } }", vec!["def"]),
    default_case_middle => ("package main; import \"fmt\"; func main() { switch 3 { case 1: fmt.Println(1); default: fmt.Println(\"mid\"); case 3: fmt.Println(3) } }", vec!["3"]),
    expression_switch_comma_list => ("package main; import \"fmt\"; func main() { switch 2 { case 1, 2, 3: fmt.Println(\"hit\"); default: fmt.Println(\"miss\") } }", vec!["hit"]),
    expression_switch_no_match => ("package main; import \"fmt\"; func main() { switch 5 { case 1, 2: fmt.Println(\"hit\"); default: fmt.Println(\"miss\") } }", vec!["miss"]),
    switch_on_rune => ("package main; import \"fmt\"; func main() { switch rune('A') { case 'A': fmt.Println(\"A\"); default: fmt.Println(\"other\") } }", vec!["A"]),
    switch_on_byte => ("package main; import \"fmt\"; func main() { switch byte(10) { case 10: fmt.Println(\"ten\"); default: fmt.Println(\"other\") } }", vec!["ten"]),
    switch_on_float_not_equal_use_tagless => ("package main; import \"fmt\"; func main() { f := 1.5; switch { case f == 1.5: fmt.Println(\"eq\"); default: fmt.Println(\"ne\") } }", vec!["eq"]),
    switch_on_int_negative => ("package main; import \"fmt\"; func main() { switch -3 { case -3: fmt.Println(\"neg\"); default: fmt.Println(\"other\") } }", vec!["neg"]),
    switch_on_uint => ("package main; import \"fmt\"; func main() { switch uint(7) { case 7: fmt.Println(\"u\"); default: fmt.Println(\"other\") } }", vec!["u"]),
    fallthrough_with_bool_switch => ("package main; import \"fmt\"; func main() { switch true { case true: fmt.Println(1); fallthrough; case false: fmt.Println(0) } }", vec!["1", "0"]),
    fallthrough_with_string_switch => ("package main; import \"fmt\"; func main() { switch \"x\" { case \"x\": fmt.Println(\"a\"); fallthrough; case \"y\": fmt.Println(\"b\"); default: fmt.Println(\"c\") } }", vec!["a", "b"]),
    switch_init_with_call => ("package main; import \"fmt\"; func val() int { return 3 }; func main() { switch v := val(); v { case 3: fmt.Println(v); default: fmt.Println(0) } }", vec!["3"]),
    tagless_switch_with_and_condition => ("package main; import \"fmt\"; func main() { a, b := 2, 3; switch { case a < 5 && b > 2: fmt.Println(\"ok\"); default: fmt.Println(\"no\") } }", vec!["ok"]),
    tagless_switch_with_or_condition => ("package main; import \"fmt\"; func main() { x := 0; switch { case x == 1 || x == 0: fmt.Println(\"zero\"); default: fmt.Println(\"other\") } }", vec!["zero"]),
    switch_case_with_single_statement => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(\"one\") } }", vec!["one"]),
    switch_multiple_cases_same_body => ("package main; import \"fmt\"; func main() { switch 2 { case 1: fmt.Println(\"a\"); case 2: fmt.Println(\"b\"); case 3: fmt.Println(\"b\") } }", vec!["b"]),
    switch_on_named_type => ("package main; import \"fmt\"; type code int; func main() { switch code(2) { case code(2): fmt.Println(\"c\"); default: fmt.Println(\"d\") } }", vec!["c"]),
    switch_on_interface_holding_int => ("package main; import \"fmt\"; func main() { var v interface{} = 8; switch v.(type) { case int: fmt.Println(\"int\"); default: fmt.Println(\"other\") } }", vec!["int"]),
    fallthrough_does_not_recheck_prior => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(1); fallthrough; case 1: fmt.Println(2) } }", vec!["1", "2"]),
    switch_in_for_loop => ("package main; import \"fmt\"; func main() { for i := 0; i < 2; i++ { switch i { case 0: fmt.Println(\"z\"); case 1: fmt.Println(\"o\"); } } }", vec!["z", "o"]),
    switch_in_func_returns_via_case => ("package main; import \"fmt\"; func label(n int) string { switch n { case 1: return \"one\"; default: return \"many\" } }; func main() { fmt.Println(label(1)); fmt.Println(label(9)) }", vec!["one", "many"]),
    switch_with_break_in_case => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(\"a\"); break; case 2: fmt.Println(\"b\") }; fmt.Println(\"done\") }", vec!["a", "done"]),
    tagless_switch_nested_comparison => ("package main; import \"fmt\"; func main() { score := 85; switch { case score >= 90: fmt.Println(\"A\"); case score >= 80: fmt.Println(\"B\"); default: fmt.Println(\"C\") } }", vec!["B"]),
    expression_switch_zero_value => ("package main; import \"fmt\"; func main() { switch 0 { case 0: fmt.Println(\"zero\"); default: fmt.Println(\"other\") } }", vec!["zero"]),
    switch_on_empty_string => ("package main; import \"fmt\"; func main() { switch \"\" { case \"\": fmt.Println(\"empty\"); default: fmt.Println(\"other\") } }", vec!["empty"]),
    switch_string_case_sensitive => ("package main; import \"fmt\"; func main() { switch \"Go\" { case \"go\": fmt.Println(\"lower\"); case \"Go\": fmt.Println(\"exact\"); default: fmt.Println(\"other\") } }", vec!["exact"]),
    fallthrough_into_case_with_multiple_stmts => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(1); fallthrough; case 2: fmt.Println(2); fmt.Println(3) } }", vec!["1", "2", "3"]),
    switch_init_declares_new_var => ("package main; import \"fmt\"; func main() { x := 10; switch y := 5; y { case 5: fmt.Println(y); default: fmt.Println(0) }; fmt.Println(x) }", vec!["5", "10"]),
    tagless_switch_with_not => ("package main; import \"fmt\"; func main() { ready := false; switch { case !ready: fmt.Println(\"wait\"); default: fmt.Println(\"go\") } }", vec!["wait"]),
    switch_on_comma_ok_true => ("package main; import \"fmt\"; func main() { m := map[string]int{\"a\": 1}; switch v, ok := m[\"a\"]; ok { case true: fmt.Println(v); default: fmt.Println(0) } }", vec!["1"]),
    switch_on_comma_ok_false => ("package main; import \"fmt\"; func main() { m := map[string]int{}; switch _, ok := m[\"z\"]; ok { case true: fmt.Println(1); default: fmt.Println(0) } }", vec!["0"]),
    fallthrough_from_default => ("package main; import \"fmt\"; func main() { switch 9 { default: fmt.Println(\"d\"); fallthrough; case 9: fmt.Println(\"nine\") } }", vec!["d", "nine"]),
    switch_bool_with_default => ("package main; import \"fmt\"; func main() { switch bool(0 == 1) { default: fmt.Println(\"def\"); case true: fmt.Println(\"t\") } }", vec!["def"]),
    switch_string_with_fallthrough_to_default => ("package main; import \"fmt\"; func main() { switch \"a\" { case \"a\": fmt.Println(\"a\"); fallthrough; default: fmt.Println(\"d\") } }", vec!["a", "d"]),
    tagless_switch_short_circuit => ("package main; import \"fmt\"; func main() { called := false; switch { case false: called = true; fmt.Println(1); case true: fmt.Println(2) }; fmt.Println(called) }", vec!["2", "false"]),
    expression_switch_type_convert => ("package main; import \"fmt\"; type myint int; func main() { switch myint(3) { case 3: fmt.Println(\"n\"); default: fmt.Println(\"o\") } }", vec!["n"]),
    switch_case_list_with_fallthrough => ("package main; import \"fmt\"; func main() { switch 2 { case 1, 2: fmt.Println(\"hit\"); fallthrough; case 3: fmt.Println(\"next\") } }", vec!["hit", "next"]),
    switch_on_iota_const => ("package main; import \"fmt\"; const ( a = iota; b; c ); func main() { switch b { case 1: fmt.Println(\"b\"); default: fmt.Println(\"x\") } }", vec!["b"]),
    switch_in_defer => ("package main; import \"fmt\"; func main() { defer func() { switch 1 { case 1: fmt.Println(\"defer-sw\") } }() }", vec!["defer-sw"]),
    tagless_switch_with_equality => ("package main; import \"fmt\"; func main() { a, b := 3, 3; switch { case a == b: fmt.Println(\"eq\"); default: fmt.Println(\"ne\") } }", vec!["eq"]),
    switch_no_fallthrough_stops => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(1); case 2: fmt.Println(2) } }", vec!["1"]),
    switch_on_interface_nil => ("package main; import \"fmt\"; func main() { var v interface{}; switch v.(type) { case nil: fmt.Println(\"nil\"); default: fmt.Println(\"other\") } }", vec!["other"]),
}

go_compile_cases! {
    empty_switch_no_cases_compile => "package main; func main() { switch 1 {} }",
    fallthrough_in_type_switch_compile => "package main; func tag(v interface{}) { switch v.(type) { case int: fallthrough; case string: _ = v } }; func main() { tag(1) }",
    fallthrough_as_first_statement_compile => "package main; func main() { switch 1 { case 1: fallthrough } }",
    fallthrough_outside_switch_compile => "package main; func main() { fallthrough }",
    switch_duplicate_case_value_compile => "package main; func main() { switch 1 { case 1, 1: _ = 1 } }",
    switch_case_outside_switch_compile => "package main; func main() { case 1: _ = 1 }",
    switch_init_without_expression_compile => "package main; func main() { switch x := 1; { case true: _ = x } }",
    switch_on_struct_compile => "package main; type p struct { x int }; func main() { switch p{x: 1} { case p{x: 1}: _ = 1 } }",
    switch_on_slice_compile => "package main; func main() { switch []int{1} { case []int{1}: _ = 1 } }",
    switch_on_map_compile => "package main; func main() { switch map[int]int{1: 2} { case map[int]int{1: 2}: _ = 1 } }",
    switch_fallthrough_in_default_only_compile => "package main; func main() { switch 1 { default: fallthrough } }",
    switch_case_with_fallthrough_to_same_case_compile => "package main; func main() { switch 1 { case 1: fallthrough; fallthrough; case 2: _ = 1 } }",
    tagless_switch_with_expression_compile => "package main; func main() { switch 1 { case 1: _ = 1 } }",
    switch_init_undeclared_var_compile => "package main; func main() { switch y; y { case 1: _ = y } }",
    switch_bool_non_constant_compile => "package main; func main() { b := true; switch b { case 1: _ = b } }",
}
