//! regexp/syntax package APIs — breadth-only, one API per test.


go_compile_cases! {
    syntax_parse => "package main; import \"regexp/syntax\"; func main() { _, _ = syntax.Parse(\"a\", syntax.Perl) }",
    syntax_compile => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"a\", 0); _, _ = syntax.Compile(re) }",
    syntax_is_word_char => "package main; import \"regexp/syntax\"; func main() { _ = syntax.IsWordChar(97) }",
    syntax_empty_op_context => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyOpContext(97, 98) }",
    syntax_regexp_cap_names => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"(a)\", syntax.Perl); _ = re.CapNames() }",
    syntax_regexp_equal => "package main; import \"regexp/syntax\"; func main() { a, _ := syntax.Parse(\"a\", 0); b, _ := syntax.Parse(\"a\", 0); _ = a.Equal(b) }",
    syntax_regexp_max_cap => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"(a)\", 0); _ = re.MaxCap() }",
    syntax_regexp_simplify => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"a+\", 0); _ = re.Simplify() }",
    syntax_regexp_string => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"a\", 0); _ = re.String() }",
    syntax_prog_prefix => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"abc\", 0); p, _ := syntax.Compile(re); _, _ = p.Prefix() }",
    syntax_prog_start_cond => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"^a\", 0); p, _ := syntax.Compile(re); _ = p.StartCond() }",
    syntax_prog_string => "package main; import \"regexp/syntax\"; func main() { re, _ := syntax.Parse(\"a\", 0); p, _ := syntax.Compile(re); _ = p.String() }",
    syntax_inst_match_empty_width => "package main; import \"regexp/syntax\"; func main() { var i syntax.Inst; _ = i.MatchEmptyWidth(0, 0) }",
    syntax_inst_match_rune => "package main; import \"regexp/syntax\"; func main() { var i syntax.Inst; _ = i.MatchRune(97) }",
    syntax_inst_match_rune_pos => "package main; import \"regexp/syntax\"; func main() { var i syntax.Inst; _ = i.MatchRunePos(97) }",
    syntax_inst_string => "package main; import \"regexp/syntax\"; func main() { var i syntax.Inst; _ = i.String() }",
    syntax_inst_op_string => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstAlt.String() }",
    syntax_op_string => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpLiteral.String() }",
    syntax_error_string => "package main; import \"regexp/syntax\"; func main() { var e syntax.Error; _ = e.Error() }",
    syntax_error_code_string => "package main; import \"regexp/syntax\"; func main() { _ = syntax.ErrInvalidRepeatSize.String() }",
    syntax_flag_fold_case => "package main; import \"regexp/syntax\"; func main() { _ = syntax.FoldCase }",
    syntax_flag_literal => "package main; import \"regexp/syntax\"; func main() { _ = syntax.Literal }",
    syntax_flag_class_nl => "package main; import \"regexp/syntax\"; func main() { _ = syntax.ClassNL }",
    syntax_flag_one_line => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OneLine }",
    syntax_flag_dot_nl => "package main; import \"regexp/syntax\"; func main() { _ = syntax.DotNL }",
    syntax_flag_perl_x => "package main; import \"regexp/syntax\"; func main() { _ = syntax.PerlX }",
    syntax_flag_unicode_groups => "package main; import \"regexp/syntax\"; func main() { _ = syntax.UnicodeGroups }",
    syntax_flag_was_dollar => "package main; import \"regexp/syntax\"; func main() { _ = syntax.WasDollar }",
    syntax_flag_simple => "package main; import \"regexp/syntax\"; func main() { _ = syntax.Simple }",
    syntax_flag_match_nl => "package main; import \"regexp/syntax\"; func main() { _ = syntax.MatchNL }",
    syntax_flag_posix => "package main; import \"regexp/syntax\"; func main() { _ = syntax.POSIX }",
    syntax_flag_perl => "package main; import \"regexp/syntax\"; func main() { _ = syntax.Perl }",
    syntax_op_no_match => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpNoMatch }",
    syntax_op_empty_match => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpEmptyMatch }",
    syntax_op_literal => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpLiteral }",
    syntax_op_char_class => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpCharClass }",
    syntax_op_any_char_not_nl => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpAnyCharNotNL }",
    syntax_op_any_char => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpAnyChar }",
    syntax_op_begin_line => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpBeginLine }",
    syntax_op_end_line => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpEndLine }",
    syntax_op_begin_text => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpBeginText }",
    syntax_op_end_text => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpEndText }",
    syntax_op_word_boundary => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpWordBoundary }",
    syntax_op_no_word_boundary => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpNoWordBoundary }",
    syntax_op_capture => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpCapture }",
    syntax_op_star => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpStar }",
    syntax_op_plus => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpPlus }",
    syntax_op_quest => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpQuest }",
    syntax_op_repeat => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpRepeat }",
    syntax_op_concat => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpConcat }",
    syntax_op_alternate => "package main; import \"regexp/syntax\"; func main() { _ = syntax.OpAlternate }",
    syntax_empty_begin_line => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyBeginLine }",
    syntax_empty_end_line => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyEndLine }",
    syntax_empty_begin_text => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyBeginText }",
    syntax_empty_end_text => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyEndText }",
    syntax_empty_word_boundary => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyWordBoundary }",
    syntax_empty_no_word_boundary => "package main; import \"regexp/syntax\"; func main() { _ = syntax.EmptyNoWordBoundary }",
    syntax_inst_alt => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstAlt }",
    syntax_inst_alt_match => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstAltMatch }",
    syntax_inst_capture => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstCapture }",
    syntax_inst_empty_width => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstEmptyWidth }",
    syntax_inst_match => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstMatch }",
    syntax_inst_fail => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstFail }",
    syntax_inst_nop => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstNop }",
    syntax_inst_rune => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstRune }",
    syntax_inst_rune1 => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstRune1 }",
    syntax_inst_rune_any => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstRuneAny }",
    syntax_inst_rune_any_not_nl => "package main; import \"regexp/syntax\"; func main() { _ = syntax.InstRuneAnyNotNL }",
}

