//! debug/buildinfo, debug/dwarf, debug/elf, debug/macho, debug/pe, debug/plan9obj, debug/gosym — breadth-only, one API per test.

go_compile_cases! {
    buildinfo_read => "package main; import \"debug/buildinfo\"; import \"bytes\"; func main() { _, _ = buildinfo.Read(bytes.NewReader(nil)) }",
    buildinfo_read_file => "package main; import \"debug/buildinfo\"; func main() { _, _ = buildinfo.ReadFile(\"/dev/null\") }",
    dwarf_err_unknown_pc => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.ErrUnknownPC }",
    dwarf_attr_sibling => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.AttrSibling }",
    dwarf_attr_name => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.AttrName }",
    dwarf_attr_lowpc => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.AttrLowpc }",
    dwarf_attr_byte_size => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.AttrByteSize }",
    dwarf_attr_language => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.AttrLanguage }",
    dwarf_tag_compile_unit => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.TagCompileUnit }",
    dwarf_tag_subprogram => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.TagSubprogram }",
    dwarf_tag_variable => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.TagVariable }",
    dwarf_tag_typedef => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.TagTypedef }",
    dwarf_tag_structure_type => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.TagStructureType }",
    dwarf_class_address => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.ClassAddress }",
    dwarf_class_constant => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.ClassConstant }",
    dwarf_format_dwarf64 => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.Dwarf64 }",
    dwarf_format_dwarf32 => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.Dwarf32 }",
    elf_open => "package main; import \"debug/elf\"; func main() { _, _ = elf.Open(\"/dev/null\") }",
    elf_elfmag => "package main; import \"debug/elf\"; func main() { _ = elf.ELFMAG }",
    elf_err_no_symbols => "package main; import \"debug/elf\"; func main() { _ = elf.ErrNoSymbols }",
    elf_r_info => "package main; import \"debug/elf\"; func main() { _ = elf.R_INFO(1, 2) }",
    elf_r_info32 => "package main; import \"debug/elf\"; func main() { _ = elf.R_INFO32(1, 2) }",
    elf_r_sym32 => "package main; import \"debug/elf\"; func main() { _ = elf.R_SYM32(1) }",
    elf_r_sym64 => "package main; import \"debug/elf\"; func main() { _ = elf.R_SYM64(1) }",
    elf_r_type32 => "package main; import \"debug/elf\"; func main() { _ = elf.R_TYPE32(1) }",
    elf_r_type64 => "package main; import \"debug/elf\"; func main() { _ = elf.R_TYPE64(1) }",
    elf_st_info => "package main; import \"debug/elf\"; func main() { _ = elf.ST_INFO(elf.STB_LOCAL, elf.STT_OBJECT) }",
    elf_class_elf64 => "package main; import \"debug/elf\"; func main() { _ = elf.ELFCLASS64 }",
    elf_data_lsb => "package main; import \"debug/elf\"; func main() { _ = elf.ELFDATA2LSB }",
    elf_type_exec => "package main; import \"debug/elf\"; func main() { _ = elf.ET_EXEC }",
    elf_machine_amd64 => "package main; import \"debug/elf\"; func main() { _ = elf.EM_X86_64 }",
    elf_sym32_size => "package main; import \"debug/elf\"; func main() { _ = elf.Sym32Size }",
    elf_sym64_size => "package main; import \"debug/elf\"; func main() { _ = elf.Sym64Size }",
    macho_open => "package main; import \"debug/macho\"; func main() { _, _ = macho.Open(\"/dev/null\") }",
    macho_magic64 => "package main; import \"debug/macho\"; func main() { _ = macho.Magic64 }",
    macho_magic32 => "package main; import \"debug/macho\"; func main() { _ = macho.Magic32 }",
    macho_err_not_fat => "package main; import \"debug/macho\"; func main() { _ = macho.ErrNotFat }",
    macho_cpu_amd64 => "package main; import \"debug/macho\"; func main() { _ = macho.CpuAmd64 }",
    macho_cpu_arm64 => "package main; import \"debug/macho\"; func main() { _ = macho.CpuArm64 }",
    macho_flag_pie => "package main; import \"debug/macho\"; func main() { _ = macho.FlagPIE }",
    macho_open_fat => "package main; import \"debug/macho\"; func main() { _, _ = macho.OpenFat(\"/dev/null\") }",
    macho_new_fat_file => "package main; import \"debug/macho\"; import \"bytes\"; func main() { _, _ = macho.NewFatFile(bytes.NewReader(nil)) }",
    pe_open => "package main; import \"debug/pe\"; func main() { _, _ = pe.Open(\"/dev/null\") }",
    pe_machine_amd64 => "package main; import \"debug/pe\"; func main() { _ = pe.IMAGE_FILE_MACHINE_AMD64 }",
    pe_machine_i386 => "package main; import \"debug/pe\"; func main() { _ = pe.IMAGE_FILE_MACHINE_I386 }",
    pe_directory_entry_export => "package main; import \"debug/pe\"; func main() { _ = pe.IMAGE_DIRECTORY_ENTRY_EXPORT }",
    pe_directory_entry_import => "package main; import \"debug/pe\"; func main() { _ = pe.IMAGE_DIRECTORY_ENTRY_IMPORT }",
    pe_err_no_symbols => "package main; import \"debug/pe\"; func main() { _ = pe.ErrNoSymbols }",
    plan9obj_open => "package main; import \"debug/plan9obj\"; func main() { _, _ = plan9obj.Open(\"/dev/null\") }",
    plan9obj_magic_amd64 => "package main; import \"debug/plan9obj\"; func main() { _ = plan9obj.MagicAMD64 }",
    plan9obj_magic_arm => "package main; import \"debug/plan9obj\"; func main() { _ = plan9obj.MagicARM }",
    plan9obj_magic386 => "package main; import \"debug/plan9obj\"; func main() { _ = plan9obj.Magic386 }",
    plan9obj_err_no_symbols => "package main; import \"debug/plan9obj\"; func main() { _ = plan9obj.ErrNoSymbols }",
    gosym_new_line_table => "package main; import \"debug/gosym\"; func main() { _ = gosym.NewLineTable(nil, 0) }",
    gosym_line_table_line_to_pc => "package main; import \"debug/gosym\"; func main() { t := gosym.NewLineTable(nil, 0); _ = t.LineToPC(1, 0) }",
    gosym_decoding_error => "package main; import \"debug/gosym\"; func main() { var e gosym.DecodingError; _ = e.Error() }",
    gosym_table_lookup_func => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _ = t.LookupFunc(\"main.main\") } }",
    gosym_table_pct_to_line => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _, _, _ = t.PCToLine(0) } }",
    gosym_table_line_to_pc => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _, _, _ = t.LineToPC(\"main.go\", 1) } }",
    gosym_table_funcs => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _ = t.Funcs } }",
    gosym_table_lookup_sym => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _ = t.LookupSym(\"main.main\") } }",
    gosym_table_pct_to_func => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _ = t.PCToFunc(0) } }",
    gosym_table_sym_by_addr => "package main; import \"debug/gosym\"; func main() { t, _ := gosym.NewTable(nil, nil); if t != nil { _ = t.SymByAddr(0) } }",
    gosym_func_entry => "package main; import \"debug/gosym\"; func main() { var f gosym.Func; _ = f.Entry }",
    gosym_sym_value => "package main; import \"debug/gosym\"; func main() { var s gosym.Sym; _ = s.Value }",
    gosym_obj_size => "package main; import \"debug/gosym\"; func main() { var o gosym.Obj; _ = o.Size }",
    dwarf_attr_highpc => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.AttrHighpc }",
    dwarf_tag_base_type => "package main; import \"debug/dwarf\"; func main() { _ = dwarf.TagBaseType }",
}
