//! Core builtins min/max/clear and distinct language semantics (one behavior per test).


go_run_cases! {
    builtin_min_int => ("package main; import \"fmt\"; func main() { fmt.Println(min(9, 4)) }", vec!["4"]),
    builtin_max_int => ("package main; import \"fmt\"; func main() { fmt.Println(max(9, 4)) }", vec!["9"]),
    builtin_min_string => ("package main; import \"fmt\"; func main() { fmt.Println(min(\"b\", \"a\")) }", vec!["a"]),
    builtin_max_float => ("package main; import \"fmt\"; func main() { fmt.Println(max(1.5, 2.5)) }", vec!["2.5"]),
    clear_slice_zeroes_elements => ("package main; import \"fmt\"; func main() { s := []int{1,2,3}; clear(s); fmt.Println(s[0], s[2]) }", vec!["0 0"]),
    clear_slice_len_unchanged => ("package main; import \"fmt\"; func main() { s := []int{1,2}; clear(s); fmt.Println(len(s)) }", vec!["2"]),
    copy_builtin_overlap => ("package main; import \"fmt\"; func main() { s := []int{1,2,3,4}; copy(s[1:], s); fmt.Println(s) }", vec!["[1 1 2 3]"]),
    append_nil_slice => ("package main; import \"fmt\"; func main() { var s []int; s = append(s, 1); fmt.Println(len(s)) }", vec!["1"]),
    len_nil_slice => ("package main; import \"fmt\"; func main() { var s []int; fmt.Println(len(s)) }", vec!["0"]),
    cap_nil_slice => ("package main; import \"fmt\"; func main() { var s []int; fmt.Println(cap(s)) }", vec!["0"]),
    nil_map_read_zero => ("package main; import \"fmt\"; func main() { var m map[string]int; fmt.Println(m[\"x\"]) }", vec!["0"]),
    delete_missing_key => ("package main; import \"fmt\"; func main() { m := map[string]int{\"a\":1}; delete(m, \"z\"); fmt.Println(len(m)) }", vec!["1"]),
    struct_literal_field_order => ("package main; import \"fmt\"; type P struct { A int; B int }; func main() { fmt.Println(P{B:2, A:1}.A) }", vec!["1"]),
    array_value_identity_len => ("package main; import \"fmt\"; func main() { var a [3]int; fmt.Println(len(a)) }", vec!["3"]),
    slice_from_array_full => ("package main; import \"fmt\"; func main() { a := [3]int{1,2,3}; s := a[:]; fmt.Println(s[1]) }", vec!["2"]),
    slice_from_array_slice_expr => ("package main; import \"fmt\"; func main() { a := [4]int{1,2,3,4}; s := a[1:3]; fmt.Println(len(s), s[0]) }", vec!["2 2"]),
    string_index_byte => ("package main; import \"fmt\"; func main() { fmt.Println(\"abc\"[1]) }", vec!["98"]),
    rune_constant_arithmetic => ("package main; import \"fmt\"; func main() { const c = 'A' + 1; fmt.Println(c) }", vec!["66"]),
    untyped_const_shift => ("package main; import \"fmt\"; func main() { const x = 1 << 3; fmt.Println(x) }", vec!["8"]),
    iota_in_const_block => ("package main; import \"fmt\"; const ( A = iota; B; C ); func main() { fmt.Println(C) }", vec!["2"]),
    blank_identifier_discard => ("package main; import \"fmt\"; func main() { _, y := 1, 2; fmt.Println(y) }", vec!["2"]),
    multiple_assignment_swap => ("package main; import \"fmt\"; func main() { a, b := 1, 2; a, b = b, a; fmt.Println(a, b) }", vec!["2 1"]),
    short_decl_shadow_outer => ("package main; import \"fmt\"; func main() { a := 1; { a := 2; fmt.Println(a) } }", vec!["2"]),
    for_range_string_index => ("package main; import \"fmt\"; func main() { for i := range \"ab\" { if i == 1 { fmt.Println(i); break } } }", vec!["1"]),
    for_range_map_single_var => ("package main; import \"fmt\"; func main() { m := map[string]int{\"k\":5}; for k := range m { fmt.Println(k); break } }", vec!["k"]),
    break_in_switch => ("package main; import \"fmt\"; func main() { switch 1 { case 1: fmt.Println(\"hit\"); break }; fmt.Println(\"after\") }", vec!["hit", "after"]),
    continue_in_for => ("package main; import \"fmt\"; func main() { for i := 0; i < 3; i++ { if i == 1 { continue }; fmt.Println(i) } }", vec!["0", "2"]),
    if_init_statement => ("package main; import \"fmt\"; func main() { if x := 3; x > 1 { fmt.Println(x) } }", vec!["3"]),
    switch_init_statement => ("package main; import \"fmt\"; func main() { switch x := 2; x { case 2: fmt.Println(\"ok\") } }", vec!["ok"]),
    select_default_immediate => ("package main; import \"fmt\"; func main() { select { default: fmt.Println(\"d\") } }", vec!["d"]),
    func_literal_closure => ("package main; import \"fmt\"; func main() { f := func(x int) int { return x + 1 }; fmt.Println(f(4)) }", vec!["5"]),
    variadic_forward => ("package main; import \"fmt\"; func sum(xs ...int) int { t := 0; for _, v := range xs { t += v }; return t }; func main() { fmt.Println(sum(1,2,3)) }", vec!["6"]),
    method_value_call => ("package main; import \"fmt\"; type N int; func (n N) Twice() int { return int(n)*2 }; func main() { var n N = 3; f := n.Twice; fmt.Println(f()) }", vec!["6"]),
    interface_nil_dynamic_type => ("package main; import \"fmt\"; func main() { var i interface{} = (*int)(nil); fmt.Println(i == nil) }", vec!["false"]),
    type_assertion_ok_false => ("package main; import \"fmt\"; func main() { var i interface{} = 1; _, ok := i.(string); fmt.Println(ok) }", vec!["false"]),
    comma_ok_map_lookup => ("package main; import \"fmt\"; func main() { m := map[string]int{\"a\":1}; _, ok := m[\"b\"]; fmt.Println(ok) }", vec!["false"]),
    comma_ok_channel_receive => ("package main; import \"fmt\"; func main() { ch := make(chan int, 1); close(ch); _, ok := <-ch; fmt.Println(ok) }", vec!["false"]),
    defer_lifo_order => ("package main; import \"fmt\"; func main() { defer fmt.Println(1); defer fmt.Println(2); fmt.Println(0) }", vec!["0", "2", "1"]),
    panic_recover_value => ("package main; import \"fmt\"; func main() { defer func() { if r := recover(); r != nil { fmt.Println(r) } }(); panic(\"boom\") }", vec!["boom"]),
}

go_compile_cases! {
    goto_forward_compile => "package main; func main() { goto L; L: return }",
    switch_fallthrough_compile => "package main; func main() { switch 1 { case 1: fallthrough; case 2: } }",
    named_result_bare_return => "package main; func f() (n int) { n = 3; return }; func main() { _ = f() }",
    channel_send_only_type => "package main; func main() { var ch chan<- int; _ = ch }",
    channel_recv_only_type => "package main; func main() { var ch <-chan int; _ = ch }",
    map_struct_key => "package main; type K struct { X int }; func main() { _ = map[K]string{} }",
    map_array_key => "package main; func main() { _ = map[[2]int]string{} }",
    unsafe_slice_compile => "package main; import \"unsafe\"; func main() { _ = unsafe.Slice((*int)(nil), 0) }",
    unsafe_string_compile => "package main; import \"unsafe\"; func main() { _ = unsafe.String((*byte)(nil), 0) }",
    unsafe_add_compile => "package main; import \"unsafe\"; func main() { var p *int; _ = unsafe.Add(p, 1) }",
    slice_to_array_ptr => "package main; func main() { s := []int{1,2}; _ = (*[2]int)(s) }",
}
