//! image/* packages — one API per test.

go_compile_cases! {
    image_new_rgba => "package main; import \"image\"; func main() { _ = image.NewRGBA(image.Rect(0, 0, 2, 2)) }",
    image_new_nrgba => "package main; import \"image\"; func main() { _ = image.NewNRGBA(image.Rect(0, 0, 2, 2)) }",
    image_new_alpha => "package main; import \"image\"; func main() { _ = image.NewAlpha(image.Rect(0, 0, 2, 2)) }",
    image_new_gray => "package main; import \"image\"; func main() { _ = image.NewGray(image.Rect(0, 0, 2, 2)) }",
    image_rect_union => "package main; import \"image\"; func main() { _ = image.Rect(0, 0, 1, 1).Union(image.Rect(1, 1, 2, 2)) }",
    image_rect_intersect => "package main; import \"image\"; func main() { _ = image.Rect(0, 0, 2, 2).Intersect(image.Rect(1, 1, 3, 3)) }",
    color_rgba_model => "package main; import \"image/color\"; func main() { _ = color.RGBAModel }",
    color_nrgba_model => "package main; import \"image/color\"; func main() { _ = color.NRGBAModel }",
    color_gray_model => "package main; import \"image/color\"; func main() { _ = color.GrayModel }",
    color_rgb_to_rgba => "package main; import \"image/color\"; func main() { _ = color.RGBA{R: 1, G: 2, B: 3, A: 255} }",
    draw_draw => "package main; import \"image/draw\"; import \"image\"; func main() { dst := image.NewRGBA(image.Rect(0, 0, 1, 1)); draw.Draw(dst, dst.Bounds(), dst, image.Point{}, draw.Src) }",
    draw_floyd_steinberg => "package main; import \"image/draw\"; func main() { _ = draw.FloydSteinberg }",
    gif_decode => "package main; import \"image/gif\"; import \"bytes\"; func main() { _, _ = gif.Decode(bytes.NewReader(nil)) }",
    gif_decode_config => "package main; import \"image/gif\"; import \"bytes\"; func main() { _, _ = gif.DecodeConfig(bytes.NewReader(nil)) }",
    gif_encode => "package main; import \"image/gif\"; import \"image\"; import \"bytes\"; func main() { _ = gif.Encode(bytes.NewBuffer(nil), image.NewRGBA(image.Rect(0, 0, 1, 1)), nil) }",
    jpeg_decode => "package main; import \"image/jpeg\"; import \"bytes\"; func main() { _, _ = jpeg.Decode(bytes.NewReader(nil)) }",
    jpeg_decode_config => "package main; import \"image/jpeg\"; import \"bytes\"; func main() { _, _ = jpeg.DecodeConfig(bytes.NewReader(nil)) }",
    jpeg_encode => "package main; import \"image/jpeg\"; import \"image\"; import \"bytes\"; func main() { _ = jpeg.Encode(bytes.NewBuffer(nil), image.NewRGBA(image.Rect(0, 0, 1, 1)), nil) }",
    png_decode => "package main; import \"image/png\"; import \"bytes\"; func main() { _, _ = png.Decode(bytes.NewReader(nil)) }",
    png_decode_config => "package main; import \"image/png\"; import \"bytes\"; func main() { _, _ = png.DecodeConfig(bytes.NewReader(nil)) }",
    png_encode => "package main; import \"image/png\"; import \"image\"; import \"bytes\"; func main() { _ = png.Encode(bytes.NewBuffer(nil), image.NewRGBA(image.Rect(0, 0, 1, 1))) }",
}
