use super::helpers::run_python;

// ═══════════════════════════════════════════════════════════
// Python: dataclasses — @dataclass, field(), __post_init__, frozen, kw_only, slots
// ═══════════════════════════════════════════════════════════

#[test]
fn test_py_dataclass_basic_fields_init_repr() {
    let src = r#"
from dataclasses import dataclass

@dataclass
class Point:
    x: float
    y: float

p = Point(1.0, 2.5)
print(p.x, p.y)
print(repr(p))
"#;
    assert_eq!(run_python(src), vec!["1.0 2.5", "Point(x=1.0, y=2.5)"]);
}

#[test]
fn test_py_dataclass_default_values() {
    let src = r#"
from dataclasses import dataclass, field

@dataclass
class Config:
    host: str = "localhost"
    port: int = 8080
    tags: list = field(default_factory=list)

c = Config()
print(c.host, c.port, c.tags)
c.tags.append("web")
c2 = Config()
print(c2.tags)  # independent copy, not shared!
"#;
    assert_eq!(run_python(src), vec!["localhost 8080 []", "[]"]);
}

#[test]
fn test_py_dataclass_post_init() {
    let src = r#"
from dataclasses import dataclass

@dataclass
class Circle:
    radius: float

    def __post_init__(self):
        if self.radius <= 0:
            raise ValueError("Radius must be positive")
        self.area = 3.14159 * self.radius ** 2

c = Circle(5.0)
print(round(c.area, 2))
try:
    Circle(-1)
except ValueError as e:
    print(e)
"#;
    assert_eq!(run_python(src), vec!["78.54", "Radius must be positive"]);
}

#[test]
fn test_py_dataclass_frozen_immutability() {
    let src = r#"
from dataclasses import dataclass

@dataclass(frozen=True)
class ImmutablePoint:
    x: int
    y: int

p = ImmutablePoint(3, 4)
print(p.x, p.y)
try:
    p.x = 99
except Exception as e:
    print(type(e).__name__)
"#;
    assert_eq!(run_python(src), vec!["3 4", "FrozenInstanceError"]);
}

#[test]
fn test_py_dataclass_eq_and_hash_behavior() {
    let src = r#"
from dataclasses import dataclass

@dataclass
class Regular:
    x: int

@dataclass(frozen=True)
class Hashable:
    x: int

r1, r2 = Regular(5), Regular(5)
print(r1 == r2)    # eq generated by default
print(hash(Hashable(5)) == hash(Hashable(5)))
s = {Hashable(1), Hashable(2), Hashable(1)}
print(len(s))
"#;
    assert_eq!(run_python(src), vec!["True", "True", "2"]);
}

#[test]
fn test_py_dataclass_field_repr_false_compare_false() {
    let src = r#"
from dataclasses import dataclass, field

@dataclass
class Secret:
    username: str
    password: str = field(repr=False, compare=False)

s = Secret("admin", "secret123")
print(repr(s))
s2 = Secret("admin", "different")
print(s == s2)  # compare=False excludes password from eq
"#;
    assert_eq!(run_python(src), vec!["Secret(username='admin')", "True"]);
}

#[test]
fn test_py_dataclass_init_false_field() {
    let src = r#"
from dataclasses import dataclass, field

@dataclass
class Tracked:
    name: str
    _instance_count: int = field(default=0, init=False, repr=False)

    def __post_init__(self):
        Tracked._instance_count = getattr(Tracked, '_total', 0) + 1
        Tracked._total = Tracked._instance_count

t1 = Tracked("A")
t2 = Tracked("B")
print(Tracked._total)
"#;
    assert_eq!(run_python(src), vec!["2"]);
}

#[test]
fn test_py_dataclass_ordering() {
    let src = r#"
from dataclasses import dataclass

@dataclass(order=True)
class Version:
    major: int
    minor: int
    patch: int

v1 = Version(1, 2, 3)
v2 = Version(1, 3, 0)
v3 = Version(1, 2, 3)
print(v1 < v2)
print(v1 == v3)
versions = [v2, v1, v3]
print(sorted(versions)[0])
"#;
    assert_eq!(
        run_python(src),
        vec!["True", "True", "Version(major=1, minor=2, patch=3)"]
    );
}

#[test]
fn test_py_dataclass_inheritance() {
    let src = r#"
from dataclasses import dataclass

@dataclass
class Base:
    x: int
    y: int

@dataclass
class Extended(Base):
    z: int = 0

e = Extended(1, 2, 3)
print(e.x, e.y, e.z)
print(repr(e))
"#;
    assert_eq!(run_python(src), vec!["1 2 3", "Extended(x=1, y=2, z=3)"]);
}

#[test]
fn test_py_dataclass_kw_only_fields() {
    let src = r#"
from dataclasses import dataclass

@dataclass(kw_only=True)
class Settings:
    debug: bool = False
    timeout: int = 30

s = Settings(debug=True, timeout=60)
print(s.debug, s.timeout)
try:
    Settings(True, 60)  # positional not allowed!
except TypeError:
    print("TypeError: no positional args allowed")
"#;
    assert_eq!(
        run_python(src),
        vec!["True 60", "TypeError: no positional args allowed"]
    );
}

#[test]
fn test_py_dataclass_slots_py310() {
    let src = r#"
from dataclasses import dataclass
import sys

if sys.version_info >= (3, 10):
    @dataclass(slots=True)
    class Slotted:
        x: int
        y: int
    s = Slotted(1, 2)
    print(s.x + s.y)
    print(hasattr(s, '__dict__'))
else:
    print("3")
    print("False")
"#;
    assert_eq!(run_python(src), vec!["3", "False"]);
}

#[test]
fn test_py_dataclass_asdict_astuple() {
    let src = r#"
from dataclasses import dataclass, asdict, astuple

@dataclass
class Coord:
    lat: float
    lon: float

c = Coord(51.5, -0.1)
d = asdict(c)
print(d)
t = astuple(c)
print(t)
"#;
    assert_eq!(
        run_python(src),
        vec!["{'lat': 51.5, 'lon': -0.1}", "(51.5, -0.1)"]
    );
}

#[test]
fn test_py_dataclass_replace() {
    let src = r#"
from dataclasses import dataclass, replace

@dataclass(frozen=True)
class Config:
    host: str = "localhost"
    port: int = 8080

original = Config()
modified = replace(original, port=9090)
print(original)
print(modified)
"#;
    assert_eq!(
        run_python(src),
        vec![
            "Config(host='localhost', port=8080)",
            "Config(host='localhost', port=9090)"
        ]
    );
}

#[test]
fn test_py_dataclass_fields_introspection() {
    let src = r#"
from dataclasses import dataclass, fields

@dataclass
class Model:
    name: str
    score: float = 0.0

for f in fields(Model):
    print(f.name, f.type, f.default)
"#;
    assert_eq!(
        run_python(src),
        vec!["name <class 'str'> MISSING", "score <class 'float'> 0.0"]
    );
}

#[test]
fn test_py_dataclass_mutable_default_raises_valueerror() {
    let src = r#"
from dataclasses import dataclass

try:
    @dataclass
    class Bad:
        items: list = []  # mutable default not allowed!
except ValueError as e:
    print("ValueError: mutable default")
"#;
    assert_eq!(run_python(src), vec!["ValueError: mutable default"]);
}

#[test]
fn test_py_dataclass_classvar_excluded_from_init() {
    let src = r#"
from dataclasses import dataclass
from typing import ClassVar

@dataclass
class Counter:
    total: ClassVar[int] = 0
    name: str

    def __post_init__(self):
        Counter.total += 1

Counter("a")
Counter("b")
print(Counter.total)
# ClassVar not an __init__ param:
c = Counter("c")
print(c.__dataclass_fields__.keys())
"#;
    assert_eq!(run_python(src), vec!["3", "dict_keys(['name'])"]);
}

#[test]
fn test_py_dataclass_is_dataclass_check() {
    let src = r#"
from dataclasses import dataclass, is_dataclass

@dataclass
class MyDC:
    x: int

class Regular:
    x: int = 0

print(is_dataclass(MyDC))
print(is_dataclass(Regular))
print(is_dataclass(MyDC(1)))  # instances also return True
"#;
    assert_eq!(run_python(src), vec!["True", "False", "True"]);
}

#[test]
fn test_py_dataclass_nested_asdict_recursion() {
    let src = r#"
from dataclasses import dataclass, asdict

@dataclass
class Address:
    city: str
    country: str

@dataclass
class Person:
    name: str
    address: Address

p = Person("Alice", Address("London", "UK"))
d = asdict(p)
print(d['name'])
print(d['address']['city'])
"#;
    assert_eq!(run_python(src), vec!["Alice", "London"]);
}

#[test]
fn test_py_dataclass_field_metadata() {
    let src = r#"
from dataclasses import dataclass, field, fields

@dataclass
class Schema:
    email: str = field(metadata={"validator": "email_format", "required": True})

f = fields(Schema)[0]
print(f.metadata["validator"])
print(f.metadata["required"])
"#;
    assert_eq!(run_python(src), vec!["email_format", "True"]);
}

#[test]
fn test_py_dataclass_unsafe_hash() {
    let src = r#"
from dataclasses import dataclass

@dataclass(unsafe_hash=True)
class Key:
    val: int

k1 = Key(10)
k2 = Key(10)
d = {k1: "first"}
print(d[k2])  # hashable since unsafe_hash=True forces __hash__
"#;
    assert_eq!(run_python(src), vec!["first"]);
}
