[package]
name = "vybe_ide"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "vybe_ide"
path = "src/main.rs"

[dependencies]
vybe_parser_basic = { workspace = true }
vybe_forms = { workspace = true }
vybe_project = { workspace = true }
vybe_host = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_compiler_vb = { workspace = true }
vybe_cli = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
rfd = "0.14"
eframe = { version = "0.31", features = ["default"] }
egui = "0.31"
egui_extras = "0.31"
