[package]
name = "vybe_ide"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "vybe_ide"
path = "src/main.rs"

[dependencies]
vybe_forms = { workspace = true }
vybe_project = { workspace = true }
vybe_widgets = { path = "../vybe_widgets" }
serde = { workspace = true }
uuid = { workspace = true }
rfd = "0.14"
tiny-skia = "0.12"
softbuffer = "0.4"
winit = "0.30"
cosmic-text = "0.18"
