use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

cobol_test!(test_round_add_up, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. ADD 5.5 6.6 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["12"]);
cobol_test!(test_round_add_down, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. ADD 5.2 6.2 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["11"]);
cobol_test!(test_round_sub_up, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. SUBTRACT 5.5 FROM 20.0 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["15"]);
cobol_test!(test_round_sub_down, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. SUBTRACT 5.2 FROM 20.0 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["15"]);
cobol_test!(test_round_mul_up, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. MULTIPLY 2.5 BY 3.0 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["08"]);
cobol_test!(test_round_mul_down, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. MULTIPLY 2.1 BY 3.0 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["06"]);
cobol_test!(test_round_div_up, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. DIVIDE 3 INTO 20 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["07"]);
cobol_test!(test_round_div_down, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. DIVIDE 4 INTO 17 GIVING R ROUNDED. DISPLAY R. STOP RUN.", vec!["04"]);
cobol_test!(test_round_comp_up, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. COMPUTE R ROUNDED = 12.5. DISPLAY R. STOP RUN.", vec!["13"]);
cobol_test!(test_round_comp_down, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R PIC 99. PROCEDURE DIVISION. COMPUTE R ROUNDED = 12.4. DISPLAY R. STOP RUN.", vec!["12"]);
