use super::helpers::compile_ok;

#[test]
fn file_control_select_assign_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn file_control_with_access_mode_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\"\n        ORGANIZATION IS INDEXED\n        ACCESS MODE IS DYNAMIC\n        RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn file_control_optional_file_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT OPTIONAL F ASSIGN TO \"f.dat\" ORGANIZATION IS SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_alternate_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K ALTERNATE RECORD KEY IS K2 WITH DUPLICATES.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\n   05 K2 PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_relative_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_file_status_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" FILE STATUS IS FS.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nWORKING-STORAGE SECTION.\n01 FS PIC XX.\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_line_sequential_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_reserve_areas_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" RESERVE 2 AREAS.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_padding_character_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" PADDING CHARACTER IS \"0\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn file_control_record_delimiter_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" RECORD DELIMITER IS STANDARD-1.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    STOP RUN.");
}