use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 distinct tests for String Functions
cobol_test!(test_str_fn_upper_case, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(3) VALUE 'abc'. PROCEDURE DIVISION. DISPLAY FUNCTION UPPER-CASE(V). STOP RUN.", vec!["ABC"]);
cobol_test!(test_str_fn_lower_case, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(3) VALUE 'ABC'. PROCEDURE DIVISION. DISPLAY FUNCTION LOWER-CASE(V). STOP RUN.", vec!["abc"]);
cobol_test!(test_str_fn_reverse, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(3) VALUE 'ABC'. PROCEDURE DIVISION. DISPLAY FUNCTION REVERSE(V). STOP RUN.", vec!["CBA"]);
cobol_test!(test_str_fn_length, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE 'ABC'. PROCEDURE DIVISION. DISPLAY FUNCTION LENGTH(V). STOP RUN.", vec!["05"]);
cobol_test!(test_str_fn_byte_length, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE 'ABC'. PROCEDURE DIVISION. DISPLAY FUNCTION BYTE-LENGTH(V). STOP RUN.", vec!["05"]);
cobol_test!(test_str_fn_trim_trailing, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE 'ABC  '. PROCEDURE DIVISION. DISPLAY '[' FUNCTION TRIM(V TRAILING) ']'. STOP RUN.", vec!["[ABC]"]);
cobol_test!(test_str_fn_trim_leading, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE '  ABC'. PROCEDURE DIVISION. DISPLAY '[' FUNCTION TRIM(V LEADING) ']'. STOP RUN.", vec!["[ABC]"]);
cobol_test!(test_str_fn_trim_both, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE ' ABC '. PROCEDURE DIVISION. DISPLAY '[' FUNCTION TRIM(V) ']'. STOP RUN.", vec!["[ABC]"]);
cobol_test!(test_str_fn_numval, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE '  123'. PROCEDURE DIVISION. DISPLAY FUNCTION NUMVAL(V). STOP RUN.", vec!["123"]);
cobol_test!(test_str_fn_numval_c, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(7) VALUE '$ 123'. PROCEDURE DIVISION. DISPLAY FUNCTION NUMVAL-C(V). STOP RUN.", vec!["123"]);
cobol_test!(test_str_fn_ord, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X VALUE 'A'. PROCEDURE DIVISION. DISPLAY FUNCTION ORD(V). STOP RUN.", vec!["66"]); // 'A' is 65 in ascii, ORD returns 1-based collating sequence position, so 66
cobol_test!(test_str_fn_char, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC 99 VALUE 66. PROCEDURE DIVISION. DISPLAY FUNCTION CHAR(V). STOP RUN.", vec!["A"]);
cobol_test!(test_str_fn_max, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION MAX('A' 'C' 'B'). STOP RUN.", vec!["C"]);
cobol_test!(test_str_fn_min, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION MIN('Z' 'X' 'Y'). STOP RUN.", vec!["X"]);
cobol_test!(test_str_fn_ord_max, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION ORD-MAX('A' 'C' 'B'). STOP RUN.", vec!["2"]);
cobol_test!(test_str_fn_ord_min, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION ORD-MIN('Z' 'X' 'Y'). STOP RUN.", vec!["2"]);
cobol_test!(test_str_fn_current_date, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION CURRENT-DATE NOT = SPACES DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_str_fn_when_compiled, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION WHEN-COMPILED NOT = SPACES DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_str_fn_formatted_current_date, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION FORMATTED-CURRENT-DATE('YYYYMMDD') NOT = SPACES DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_str_fn_test_date_yyyymmdd, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION TEST-DATE-YYYYMMDD(20230101). STOP RUN.", vec!["0"]);
cobol_test!(test_str_fn_test_date_yyyymmdd_invalid_month, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION TEST-DATE-YYYYMMDD(20231301). STOP RUN.", vec!["2"]);
cobol_test!(test_str_fn_test_date_yyyymmdd_invalid_day, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION TEST-DATE-YYYYMMDD(20230132). STOP RUN.", vec!["3"]);
cobol_test!(test_str_fn_integer_of_date, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION INTEGER-OF-DATE(20230101) > 0 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_str_fn_date_of_integer, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION DATE-OF-INTEGER(1). STOP RUN.", vec!["16010101"]);
cobol_test!(test_str_fn_integer_of_day, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION INTEGER-OF-DAY(2023001) > 0 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_str_fn_day_of_integer, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY FUNCTION DAY-OF-INTEGER(1). STOP RUN.", vec!["1601001"]);
cobol_test!(test_str_fn_extract_date_time, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 D PIC X(8) VALUE '20230101'. PROCEDURE DIVISION. DISPLAY FUNCTION EXTRACT-DATE-TIME(D '%Y'). STOP RUN.", vec!["2023"]);
cobol_test!(test_str_fn_substitute, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5) VALUE 'AABAA'. PROCEDURE DIVISION. DISPLAY FUNCTION SUBSTITUTE(V 'A' 'X'). STOP RUN.", vec!["XXBXX"]);
cobol_test!(test_str_fn_locale_date, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION LOCALE-DATE(20230101) NOT = SPACES DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_str_fn_locale_time, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION LOCALE-TIME(120000) NOT = SPACES DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
