use super::helpers::compile_ok;

macro_rules! c {
    ($name:ident, $src:expr) => {
        #[test]
        fn $name() { compile_ok($src); }
    };
}

c!(program_basic_01, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P1.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_initial_02, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P2 INITIAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_common_03, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P3 COMMON.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_recursive_04, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P4 RECURSIVE.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_author_05, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P5.\nAUTHOR. A.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_installation_06, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P6.\nINSTALLATION. LAB.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_date_written_07, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P7.\nDATE-WRITTEN. 20240701.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_date_compiled_08, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P8.\nDATE-COMPILED. 20240701.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_security_09, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P9.\nSECURITY. INTERNAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_remarks_10, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P10.\nREMARKS. SAMPLE.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_entry_11, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P11.\nPROCEDURE DIVISION.\n    ENTRY \"ALT11\".\n    STOP RUN.");
c!(program_entry_two_12, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P12.\nPROCEDURE DIVISION.\n    ENTRY \"ALT12A\".\n    ENTRY \"ALT12B\".\n    STOP RUN.");
c!(program_nested_13, "IDENTIFICATION DIVISION.\nPROGRAM-ID. OUTER13.\nPROCEDURE DIVISION.\n    STOP RUN.\nIDENTIFICATION DIVISION.\nPROGRAM-ID. INNER13.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_repository_14, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P14.\nENVIRONMENT DIVISION.\nCONFIGURATION SECTION.\nREPOSITORY.\n    FUNCTION ALL INTRINSIC.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_multi_file_style_15, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P15.\nPROCEDURE DIVISION.\n    CALL \"P15B\".\n    STOP RUN.");
c!(program_chain_call_16, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P16.\nPROCEDURE DIVISION.\n    CALL \"A16\".\n    CALL \"B16\".\n    STOP RUN.");
c!(program_cancel_17, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P17.\nPROCEDURE DIVISION.\n    CANCEL \"SUB17\".\n    STOP RUN.");
c!(program_goback_18, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P18.\nPROCEDURE DIVISION.\n    GOBACK.");
c!(program_stop_literal_19, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P19.\nPROCEDURE DIVISION.\n    STOP \"DONE\".");
c!(program_id_quoted_20, "IDENTIFICATION DIVISION.\nPROGRAM-ID. \"P20\".\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_with_working_storage_21, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P21.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC 9.\nPROCEDURE DIVISION.\n    MOVE 1 TO X.\n    STOP RUN.");
c!(program_with_linkage_22, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P22.\nDATA DIVISION.\nLINKAGE SECTION.\n01 L PIC X(5).\nPROCEDURE DIVISION USING L.\n    GOBACK.");
c!(program_with_local_storage_23, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P23 RECURSIVE.\nDATA DIVISION.\nLOCAL-STORAGE SECTION.\n01 L PIC 9.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_with_sections_24, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P24.\nPROCEDURE DIVISION.\nMAIN SECTION.\nP1. STOP RUN.");
c!(program_with_paragraphs_25, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P25.\nPROCEDURE DIVISION.\nP1. DISPLAY \"A\".\nP2. STOP RUN.");
c!(program_with_common_and_initial_26, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P26 COMMON INITIAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_with_recursive_and_entry_27, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P27 RECURSIVE.\nPROCEDURE DIVISION.\n    ENTRY \"ALT27\".\n    GOBACK.");
c!(program_with_repository_class_28, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P28.\nENVIRONMENT DIVISION.\nCONFIGURATION SECTION.\nREPOSITORY.\n    CLASS C-REF.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_with_repository_function_29, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P29.\nENVIRONMENT DIVISION.\nCONFIGURATION SECTION.\nREPOSITORY.\n    FUNCTION CURRENT-DATE.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(program_with_repository_interface_30, "IDENTIFICATION DIVISION.\nPROGRAM-ID. P30.\nENVIRONMENT DIVISION.\nCONFIGURATION SECTION.\nREPOSITORY.\n    INTERFACE I-REF.\nPROCEDURE DIVISION.\n    STOP RUN.");