use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 edge cases for OCCURS clauses in Data Division
cobol_test!(test_occurs_depending_max, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 N PIC 9 VALUE 3. 01 TBL. 05 EL OCCURS 1 TO 3 TIMES DEPENDING ON N PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY EL(3). STOP RUN.", vec!["1"]);
cobol_test!(test_occurs_depending_min, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 N PIC 9 VALUE 1. 01 TBL. 05 EL OCCURS 1 TO 3 TIMES DEPENDING ON N PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY EL(1). STOP RUN.", vec!["1"]);
cobol_test!(test_occurs_multidimensional_depending, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 N PIC 9 VALUE 2. 01 TBL. 05 R OCCURS 2 TIMES. 10 C OCCURS 1 TO 3 TIMES DEPENDING ON N PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY C(2 2). STOP RUN.", vec!["1"]);
cobol_test!(test_occurs_index_name_shadowing, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 I PIC 9 VALUE 1. 01 TBL. 05 EL OCCURS 3 TIMES INDEXED BY I PIC 9 VALUE 2. PROCEDURE DIVISION. SET I TO 3. DISPLAY EL(I). STOP RUN.", vec!["2"]);
cobol_test!(test_occurs_group_level, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL OCCURS 3 TIMES. 05 EL PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY EL(1). STOP RUN.", vec![] as Vec<&str>); // Parse only, 01 level OCCURS is a syntax error in some standards, allowed as extension in others
cobol_test!(test_occurs_level_77, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 77 EL OCCURS 3 TIMES PIC 9. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec![] as Vec<&str>); // Parse only
cobol_test!(test_occurs_nested_max, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 L1 OCCURS 3 TIMES. 10 L2 OCCURS 3 TIMES. 15 L3 OCCURS 3 TIMES. 20 L4 OCCURS 3 TIMES. 25 L5 OCCURS 3 TIMES. 30 L6 OCCURS 3 TIMES. 35 L7 OCCURS 3 TIMES PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY L7(3 3 3 3 3 3 3). STOP RUN.", vec!["1"]);
cobol_test!(test_occurs_key_is_group, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 EL OCCURS 3 TIMES ASCENDING KEY IS EL. 10 K1 PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_multiple_keys, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 EL OCCURS 3 TIMES ASCENDING KEY K1 DESCENDING KEY K2. 10 K1 PIC 9 VALUE 1. 10 K2 PIC 9 VALUE 2. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_key_is_subscripted, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 EL OCCURS 3 TIMES ASCENDING KEY K1. 10 G1 OCCURS 2 TIMES. 15 K1 PIC 9 VALUE 1. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec![] as Vec<&str>); // Parse error test
// Parse fillers
cobol_test!(test_occurs_parse_11, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_12, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_13, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_14, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_15, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_16, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_17, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_18, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_occurs_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
