use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 specific tests for CALL BY CONTENT
cobol_test!(test_call_content_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X VALUE 'A'. PROCEDURE DIVISION. CALL 'S1' BY CONTENT A. DISPLAY A. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 B PIC X. PROCEDURE DIVISION USING B. MOVE 'B' TO B. EXIT PROGRAM. END PROGRAM S1.", vec!["A"]);
cobol_test!(test_call_content_literal, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. CALL 'S1' BY CONTENT 'A'. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 B PIC X. PROCEDURE DIVISION USING B. DISPLAY B. EXIT PROGRAM. END PROGRAM S1.", vec!["A"]);
cobol_test!(test_call_content_length_of, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE 'ABC'. PROCEDURE DIVISION. CALL 'S1' BY CONTENT LENGTH OF A. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 B PIC 9. PROCEDURE DIVISION USING B. DISPLAY B. EXIT PROGRAM. END PROGRAM S1.", vec!["3"]);
cobol_test!(test_call_content_mixed, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X VALUE 'A'. 01 C PIC X VALUE 'C'. PROCEDURE DIVISION. CALL 'S1' BY CONTENT A BY REFERENCE C. DISPLAY A C. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 B PIC X. 01 D PIC X. PROCEDURE DIVISION USING B D. MOVE 'X' TO B D. EXIT PROGRAM. END PROGRAM S1.", vec!["AX"]);
cobol_test!(test_call_content_group, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 G. 05 A PIC X VALUE 'A'. 05 B PIC X VALUE 'B'. PROCEDURE DIVISION. CALL 'S1' BY CONTENT G. DISPLAY G. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 G2. 05 C PIC X. 05 D PIC X. PROCEDURE DIVISION USING G2. MOVE 'X' TO C. EXIT PROGRAM. END PROGRAM S1.", vec!["AB"]);
cobol_test!(test_call_content_omitted, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. CALL 'S1' BY CONTENT OMITTED. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. PROCEDURE DIVISION. DISPLAY 'OK'. EXIT PROGRAM. END PROGRAM S1.", vec!["OK"]);
cobol_test!(test_call_content_address_of, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X VALUE 'A'. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO ADDRESS OF A. CALL 'S1' BY CONTENT P. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 P2 USAGE POINTER. PROCEDURE DIVISION USING P2. IF P2 NOT = NULL DISPLAY 'Y' END-IF. EXIT PROGRAM. END PROGRAM S1.", vec!["Y"]);
cobol_test!(test_call_content_multiple, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X VALUE 'A'. 01 B PIC X VALUE 'B'. PROCEDURE DIVISION. CALL 'S1' BY CONTENT A B. DISPLAY A B. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. S1. DATA DIVISION. LINKAGE SECTION. 01 C PIC X. 01 D PIC X. PROCEDURE DIVISION USING C D. MOVE 'X' TO C D. EXIT PROGRAM. END PROGRAM S1.", vec!["AB"]);
cobol_test!(test_call_content_parse_9, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_10, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_11, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_12, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_13, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_14, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_15, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_16, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_17, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_18, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_call_content_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
