use super::helpers::compile_ok;

#[test]
fn read_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    READ F INVALID KEY DISPLAY \"MISS\" END-READ.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    WRITE REC INVALID KEY DISPLAY \"MISS\" END-WRITE.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn rewrite_invalid_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    REWRITE REC INVALID KEY DISPLAY \"MISS\" END-REWRITE.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn delete_invalid_key_case_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    DELETE F INVALID KEY DISPLAY \"MISS\" END-DELETE.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn start_invalid_key_case_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nWORKING-STORAGE SECTION.\n01 WK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    START F KEY IS GREATER THAN WK INVALID KEY DISPLAY \"MISS\" END-START.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn relative_read_invalid_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT RF.\n    READ RF INVALID KEY DISPLAY \"MISS\" END-READ.\n    CLOSE RF.\n    STOP RUN.");
}

#[test]
fn relative_write_invalid_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN OUTPUT RF.\n    WRITE RR INVALID KEY DISPLAY \"MISS\" END-WRITE.\n    CLOSE RF.\n    STOP RUN.");
}

#[test]
fn relative_rewrite_invalid_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK ACCESS MODE IS RANDOM.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O RF.\n    REWRITE RR INVALID KEY DISPLAY \"MISS\" END-REWRITE.\n    CLOSE RF.\n    STOP RUN.");
}

#[test]
fn relative_delete_invalid_key_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK ACCESS MODE IS RANDOM.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O RF.\n    DELETE RF INVALID KEY DISPLAY \"MISS\" END-DELETE.\n    CLOSE RF.\n    STOP RUN.");
}

#[test]
fn invalid_key_with_status_code_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS INDEXED ACCESS MODE IS DYNAMIC RECORD KEY IS K FILE STATUS IS FS.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nWORKING-STORAGE SECTION.\n01 FS PIC XX.\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    READ F INVALID KEY DISPLAY FS END-READ.\n    CLOSE F.\n    STOP RUN.");
}