use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 distinct tests for Object Oriented COBOL
cobol_test!(test_oo_class_def, "IDENTIFICATION DIVISION. CLASS-ID. C. ENVIRONMENT DIVISION. CONFIGURATION SECTION. REPOSITORY. CLASS C IS 'C'. IDENTIFICATION DIVISION. FACTORY. PROCEDURE DIVISION. END FACTORY. IDENTIFICATION DIVISION. OBJECT. PROCEDURE DIVISION. END OBJECT. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_invoke_factory, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. CONFIGURATION SECTION. REPOSITORY. CLASS C IS 'C'. PROCEDURE DIVISION. INVOKE C 'NEW' RETURNING O. DISPLAY 'OK'. STOP RUN.", vec![] as Vec<&str>); // Parsing
cobol_test!(test_oo_invoke_method, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. INVOKE O 'M1'. DISPLAY 'OK'. STOP RUN.", vec![] as Vec<&str>);
cobol_test!(test_oo_invoke_returning, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. INVOKE O 'M1' RETURNING R. DISPLAY 'OK'. STOP RUN.", vec![] as Vec<&str>);
cobol_test!(test_oo_invoke_using, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. INVOKE O 'M1' USING X Y. DISPLAY 'OK'. STOP RUN.", vec![] as Vec<&str>);
cobol_test!(test_oo_object_reference, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 O USAGE OBJECT REFERENCE. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_object_reference_typed, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. CONFIGURATION SECTION. REPOSITORY. CLASS C IS 'C'. DATA DIVISION. WORKING-STORAGE SECTION. 01 O USAGE OBJECT REFERENCE C. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_factory_method, "IDENTIFICATION DIVISION. CLASS-ID. C. IDENTIFICATION DIVISION. FACTORY. PROCEDURE DIVISION. METHOD-ID. M1. PROCEDURE DIVISION. END METHOD M1. END FACTORY. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_object_method, "IDENTIFICATION DIVISION. CLASS-ID. C. IDENTIFICATION DIVISION. OBJECT. PROCEDURE DIVISION. METHOD-ID. M1. PROCEDURE DIVISION. END METHOD M1. END OBJECT. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_method_returning, "IDENTIFICATION DIVISION. CLASS-ID. C. IDENTIFICATION DIVISION. OBJECT. PROCEDURE DIVISION. METHOD-ID. M1. DATA DIVISION. LINKAGE SECTION. 01 R PIC X. PROCEDURE DIVISION RETURNING R. END METHOD M1. END OBJECT. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_method_using, "IDENTIFICATION DIVISION. CLASS-ID. C. IDENTIFICATION DIVISION. OBJECT. PROCEDURE DIVISION. METHOD-ID. M1. DATA DIVISION. LINKAGE SECTION. 01 P PIC X. PROCEDURE DIVISION USING P. END METHOD M1. END OBJECT. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_inherits, "IDENTIFICATION DIVISION. CLASS-ID. C INHERITS B. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_interfaces, "IDENTIFICATION DIVISION. CLASS-ID. C IMPLEMENTS I. END CLASS C.", vec![] as Vec<&str>);
cobol_test!(test_oo_interface_def, "IDENTIFICATION DIVISION. INTERFACE-ID. I. PROCEDURE DIVISION. METHOD-ID. M1. PROCEDURE DIVISION. END METHOD M1. END INTERFACE I.", vec![] as Vec<&str>);
cobol_test!(test_oo_exception, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. INVOKE O 'M1' ON EXCEPTION DISPLAY 'E' NOT ON EXCEPTION DISPLAY 'N' END-INVOKE. STOP RUN.", vec![] as Vec<&str>);
cobol_test!(test_oo_parse_16, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_17, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_18, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_oo_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
