use super::helpers::compile_ok;

#[test]
fn select_assign_literal_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT CUST ASSIGN TO \"cust.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD CUST.\n01 R PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_optional_assign_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT OPTIONAL CUST ASSIGN TO \"cust.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD CUST.\n01 R PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_to_disk_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT CUST ASSIGN TO DISK.\nDATA DIVISION.\nFILE SECTION.\nFD CUST.\n01 R PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_to_printer_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LISTING ASSIGN TO PRINTER.\nDATA DIVISION.\nFILE SECTION.\nFD LISTING.\n01 R PIC X(80).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_line_sequential_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT TXT ASSIGN TO \"cust.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD TXT.\n01 R PIC X(80).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_indexed_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT IDX ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD IDX.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_relative_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT REL ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD REL.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_with_file_status_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT CUST ASSIGN TO \"cust.dat\" FILE STATUS IS FS.\nDATA DIVISION.\nFILE SECTION.\nFD CUST.\n01 R PIC X(10).\nWORKING-STORAGE SECTION.\n01 FS PIC XX.\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_with_access_mode_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT CUST ASSIGN TO \"cust.dat\" ACCESS MODE IS SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD CUST.\n01 R PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn select_assign_with_reserve_areas_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT CUST ASSIGN TO \"cust.dat\" RESERVE 1 AREAS.\nDATA DIVISION.\nFILE SECTION.\nFD CUST.\n01 R PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}