use super::helpers::compile_ok;

#[test]
fn write_basic_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE R.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_from_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nWORKING-STORAGE SECTION.\n01 W PIC X(20).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE R FROM W.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_after_advancing_lines_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE R AFTER ADVANCING 2 LINES.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_after_advancing_page_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE R AFTER ADVANCING PAGE.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE REC INVALID KEY DISPLAY \"DUP\" END-WRITE.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_not_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE REC NOT INVALID KEY DISPLAY \"OK\" END-WRITE.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn write_line_sequential_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    OPEN OUTPUT LF.\n    WRITE LR.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn write_sequential_from_hold_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT SF ASSIGN TO \"s.dat\" ORGANIZATION IS SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD SF.\n01 SR PIC X(30).\nWORKING-STORAGE SECTION.\n01 HOLD PIC X(30).\nPROCEDURE DIVISION.\n    OPEN OUTPUT SF.\n    WRITE SR FROM HOLD.\n    CLOSE SF.\n    STOP RUN.",
    );
}

#[test]
fn write_relative_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN OUTPUT RF.\n    WRITE RR INVALID KEY DISPLAY \"BAD\" END-WRITE.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn write_with_status_code_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" FILE STATUS IS FS.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nWORKING-STORAGE SECTION.\n01 FS PIC XX.\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    WRITE R.\n    CLOSE F.\n    STOP RUN.");
}