use super::helpers::compile_ok;

macro_rules! c { ($name:ident, $src:expr) => { #[test] fn $name() { compile_ok($src); } }; }

c!(dd_levels_01, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D1.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 G.\n   05 A PIC 9.\n   10 B PIC 9.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_level_77_02, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D2.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n77 X PIC 9.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_pic_x_03, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D3.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_pic_9_04, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D4.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_usage_comp_05, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D5.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(4) COMP.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_value_clause_06, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D6.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9 VALUE 1.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_occurs_07, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D7.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 TBL.\n   05 E PIC 9 OCCURS 5 TIMES.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_odo_08, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D8.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 CNT PIC 9.\n01 TBL.\n   05 E PIC 9 OCCURS 1 TO 5 TIMES DEPENDING ON CNT.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_indexed_09, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D9.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 TBL.\n   05 E PIC 9 OCCURS 5 TIMES INDEXED BY IDX.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_redefines_10, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D10.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 A PIC X(4).\n01 B REDEFINES A PIC 9(4).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_renames_11, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D11.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 G.\n   05 A PIC X.\n   05 B PIC X.\n66 AB RENAMES A THRU B.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_88_level_12, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D12.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 S PIC X.\n   88 READY VALUE \"Y\".\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_numeric_edited_13, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D13.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 E PIC ZZZ9.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_sign_leading_14, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D14.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(4) SIGN LEADING.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_justified_15, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D15.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 T PIC X(10) JUSTIFIED RIGHT.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_sync_16, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D16.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9(4) SYNCHRONIZED.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_blank_zero_17, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D17.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 E PIC ZZZ9 BLANK WHEN ZERO.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_alignment_group_18, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D18.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 G.\n   05 A PIC X.\n   05 B PIC 9(4) COMP.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_record_layout_19, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D19.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 REC.\n   05 ID PIC 9(5).\n   05 NAME PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_group_nested_20, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D20.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 G1.\n   05 G2.\n      10 A PIC X.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_external_21, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D21.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC X(4) EXTERNAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_global_22, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D22.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC X(4) GLOBAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_constant_23, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D23.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 PI PIC 9V99 CONSTANT VALUE 3.14.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_pointer_24, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D24.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P USAGE POINTER.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_program_pointer_25, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D25.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P USAGE PROGRAM-POINTER.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_function_pointer_26, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D26.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P USAGE FUNCTION-POINTER.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_object_ref_27, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D27.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 O USAGE OBJECT REFERENCE.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_national_28, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D28.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC N(5).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_binary_29, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D29.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 B PIC S9(9) COMP-5.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dd_packed_30, "IDENTIFICATION DIVISION.\nPROGRAM-ID. D30.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P PIC S9(5)V99 COMP-3.\nPROCEDURE DIVISION.\n    STOP RUN.");