use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 distinct tests for XML JSON Parse
cobol_test!(test_xml_parse_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '<A>1</A>'. PROCEDURE DIVISION. XML PARSE DOC PROCESSING PROCEDURE P1. DISPLAY 'OK'. STOP RUN. P1 SECTION. EXIT.", vec!["OK"]);
cobol_test!(test_xml_parse_exception, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '<A>1</A>'. PROCEDURE DIVISION. XML PARSE DOC PROCESSING PROCEDURE P1 ON EXCEPTION DISPLAY 'E' NOT ON EXCEPTION DISPLAY 'N'. STOP RUN. P1 SECTION. EXIT.", vec!["N"]);
cobol_test!(test_xml_parse_file, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 F PIC X(20) VALUE 'a.xml'. PROCEDURE DIVISION. XML PARSE FILE F PROCESSING PROCEDURE P1. DISPLAY 'OK'. STOP RUN. P1 SECTION. EXIT.", vec!["OK"]); // Parse only
cobol_test!(test_xml_parse_with_encoding, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '<A>1</A>'. PROCEDURE DIVISION. XML PARSE DOC WITH ENCODING 1208 PROCESSING PROCEDURE P1. DISPLAY 'OK'. STOP RUN. P1 SECTION. EXIT.", vec!["OK"]);
cobol_test!(test_xml_parse_returning, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '<A>1</A>'. 01 R PIC 9. PROCEDURE DIVISION. XML PARSE DOC PROCESSING PROCEDURE P1 RETURNING R. DISPLAY 'OK'. STOP RUN. P1 SECTION. EXIT.", vec!["OK"]);
cobol_test!(test_json_parse_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '{\"A\":1}'. 01 R. 05 A PIC 9. PROCEDURE DIVISION. JSON PARSE DOC INTO R. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_json_parse_exception, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '{\"A\":1}'. 01 R. 05 A PIC 9. PROCEDURE DIVISION. JSON PARSE DOC INTO R ON EXCEPTION DISPLAY 'E' NOT ON EXCEPTION DISPLAY 'N'. STOP RUN.", vec!["N"]);
cobol_test!(test_json_parse_name, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '{\"A\":1}'. 01 R. 05 B PIC 9. PROCEDURE DIVISION. JSON PARSE DOC INTO R NAME A IS 'A'. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_json_parse_suppress, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '{\"A\":1}'. 01 R. 05 A PIC 9. 05 B PIC 9. PROCEDURE DIVISION. JSON PARSE DOC INTO R SUPPRESS B. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_json_parse_with_detail, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 DOC PIC X(20) VALUE '{\"A\":1}'. 01 R. 05 A PIC 9. PROCEDURE DIVISION. JSON PARSE DOC INTO R WITH DETAIL. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_11, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_12, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_13, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_14, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_15, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_16, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_17, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_18, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_parse_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
