use super::helpers::compile_ok;

#[test]
fn read_at_end_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    READ F AT END DISPLAY \"EOF\" END-READ.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn read_into_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nWORKING-STORAGE SECTION.\n01 W PIC X(20).\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    READ F INTO W AT END DISPLAY \"EOF\" END-READ.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn read_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT IFILE ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD IFILE.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT IFILE.\n    READ IFILE INVALID KEY DISPLAY \"MISS\" END-READ.\n    CLOSE IFILE.\n    STOP RUN.",
    );
}

#[test]
fn read_not_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT IFILE ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD IFILE.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT IFILE.\n    READ IFILE NOT INVALID KEY DISPLAY \"FOUND\" END-READ.\n    CLOSE IFILE.\n    STOP RUN.",
    );
}

#[test]
fn read_next_record_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\" ORGANIZATION IS SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    READ F NEXT RECORD AT END DISPLAY \"EOF\" END-READ.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn read_with_lock_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    READ F WITH LOCK AT END DISPLAY \"EOF\" END-READ.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn read_indexed_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT IFILE ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD IFILE.\n01 REC.\n   05 K PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT IFILE.\n    READ IFILE KEY IS K INVALID KEY DISPLAY \"MISS\" END-READ.\n    CLOSE IFILE.\n    STOP RUN.",
    );
}

#[test]
fn read_relative_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT RF.\n    READ RF INVALID KEY DISPLAY \"MISS\" END-READ.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn read_at_end_with_flag_move_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nWORKING-STORAGE SECTION.\n01 EOF-FLAG PIC X VALUE \"N\".\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    READ F AT END MOVE \"Y\" TO EOF-FLAG END-READ.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn read_after_start_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT IFILE ASSIGN TO \"i.dat\" ORGANIZATION IS INDEXED RECORD KEY IS K.\nDATA DIVISION.\nFILE SECTION.\nFD IFILE.\n01 REC.\n   05 K PIC 9(5).\nWORKING-STORAGE SECTION.\n01 WK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O IFILE.\n    START IFILE KEY IS EQUAL TO WK END-START.\n    READ IFILE NEXT RECORD AT END DISPLAY \"EOF\" END-READ.\n    CLOSE IFILE.\n    STOP RUN.");
}