use super::helpers::compile_ok;

#[test]
fn line_sequential_select_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_write_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    OPEN OUTPUT LF.\n    WRITE LR.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_open_input_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    OPEN INPUT LF.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_open_extend_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    OPEN EXTEND LF.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_read_at_end_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    OPEN INPUT LF.\n    READ LF AT END DISPLAY \"EOF\" END-READ.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_read_into_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nWORKING-STORAGE SECTION.\n01 HOLD PIC X(80).\nPROCEDURE DIVISION.\n    OPEN INPUT LF.\n    READ LF INTO HOLD AT END DISPLAY \"EOF\" END-READ.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_write_from_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nWORKING-STORAGE SECTION.\n01 HOLD PIC X(80).\nPROCEDURE DIVISION.\n    OPEN OUTPUT LF.\n    WRITE LR FROM HOLD.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_close_no_rewind_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    OPEN INPUT LF.\n    CLOSE LF WITH NO REWIND.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_with_status_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL FILE STATUS IS FS.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nWORKING-STORAGE SECTION.\n01 FS PIC XX.\nPROCEDURE DIVISION.\n    OPEN INPUT LF.\n    CLOSE LF.\n    STOP RUN.",
    );
}

#[test]
fn line_sequential_access_mode_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT LF ASSIGN TO \"l.txt\" ORGANIZATION IS LINE SEQUENTIAL ACCESS MODE IS SEQUENTIAL.\nDATA DIVISION.\nFILE SECTION.\nFD LF.\n01 LR PIC X(80).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}