use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

cobol_test!(test_rep_initiate, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 TYPE IS PAGE HEADING. 05 LINE 1 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. INITIATE R. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_generate, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 D TYPE IS DETAIL. 05 LINE 1 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. GENERATE D. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_terminate, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 TYPE IS PAGE FOOTING. 05 LINE 1 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. TERMINATE R. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_page_limit, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R PAGE LIMIT 60 LINES HEADING 1 FIRST DETAIL 5 LAST DETAIL 50 FOOTING 55. 01 TYPE IS DETAIL. 05 LINE 1 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_line_plus, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 TYPE IS DETAIL. 05 LINE PLUS 2 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_next_group_plus, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 TYPE IS DETAIL NEXT GROUP PLUS 2. 05 LINE 1 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_next_group_next_page, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 TYPE IS DETAIL NEXT GROUP NEXT PAGE. 05 LINE 1 COL 1 PIC X VALUE 'A'. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_sum_reset, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 C PIC 9. 01 X PIC 9. REPORT SECTION. RD R CONTROLS ARE FINAL C. 01 TYPE IS CONTROL FOOTING C. 05 COL 1 PIC 9 SUM X RESET ON FINAL. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_sum_up, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 X PIC 9. REPORT SECTION. RD R. 01 TYPE IS CONTROL FOOTING FINAL. 05 COL 1 PIC 9 SUM X UP. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_rep_sum_cross_footing, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. REPORT SECTION. RD R. 01 TYPE IS CONTROL FOOTING FINAL. 05 S1 COL 1 PIC 9. 05 S2 COL 2 PIC 9. 05 S3 COL 3 PIC 9 SUM S1 S2. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
