use super::helpers::compile_ok;

macro_rules! c { ($name:ident, $src:expr) => { #[test] fn $name() { compile_ok($src); } }; }

c!(proc_basic_01, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR1.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(proc_using_02, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR2.\nDATA DIVISION.\nLINKAGE SECTION.\n01 L PIC X(5).\nPROCEDURE DIVISION USING L.\n    GOBACK.");
c!(proc_returning_03, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR3.\nPROCEDURE DIVISION RETURNING R.\n    MOVE 1 TO R.\n    GOBACK.");
c!(proc_call_lit_04, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR4.\nPROCEDURE DIVISION.\n    CALL \"SUB4\".\n    STOP RUN.");
c!(proc_call_ident_05, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR5.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 PGM PIC X(8) VALUE \"SUB5\".\nPROCEDURE DIVISION.\n    CALL PGM.\n    STOP RUN.");
c!(proc_call_ref_06, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR6.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC 9 VALUE 1.\nPROCEDURE DIVISION.\n    CALL \"SUB6\" USING BY REFERENCE X.\n    STOP RUN.");
c!(proc_call_content_07, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR7.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC 9 VALUE 1.\nPROCEDURE DIVISION.\n    CALL \"SUB7\" USING BY CONTENT X.\n    STOP RUN.");
c!(proc_call_value_08, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR8.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC 9 VALUE 1.\nPROCEDURE DIVISION.\n    CALL \"SUB8\" USING BY VALUE X.\n    STOP RUN.");
c!(proc_call_returning_09, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR9.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 R PIC 99.\nPROCEDURE DIVISION.\n    CALL \"SUB9\" RETURNING R.\n    STOP RUN.");
c!(proc_call_exception_10, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR10.\nPROCEDURE DIVISION.\n    CALL \"SUB10\" ON EXCEPTION DISPLAY \"E\" NOT ON EXCEPTION DISPLAY \"O\" END-CALL.\n    STOP RUN.");
c!(proc_cancel_11, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR11.\nPROCEDURE DIVISION.\n    CANCEL \"SUB11\".\n    STOP RUN.");
c!(proc_cancel_ident_12, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR12.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 PGM PIC X(8) VALUE \"SUB12\".\nPROCEDURE DIVISION.\n    CANCEL PGM.\n    STOP RUN.");
c!(proc_chain_calls_13, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR13.\nPROCEDURE DIVISION.\n    CALL \"A13\".\n    CALL \"B13\".\n    CALL \"C13\".\n    STOP RUN.");
c!(proc_dynamic_call_14, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR14.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 PGM PIC X(8).\nPROCEDURE DIVISION.\n    CALL PGM.\n    STOP RUN.");
c!(proc_static_call_15, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR15.\nPROCEDURE DIVISION.\n    CALL \"STATIC15\".\n    STOP RUN.");
c!(proc_goback_16, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR16.\nPROCEDURE DIVISION.\n    GOBACK.");
c!(proc_stop_run_17, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR17.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(proc_exit_program_18, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR18.\nPROCEDURE DIVISION.\n    EXIT PROGRAM.");
c!(proc_go_to_19, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR19.\nPROCEDURE DIVISION.\n    GO TO L1.\nL1. STOP RUN.");
c!(proc_alter_20, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR20.\nPROCEDURE DIVISION.\n    ALTER L1 TO PROCEED TO L2.\nL1. DISPLAY \"A\".\nL2. STOP RUN.");
c!(proc_perform_21, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR21.\nPROCEDURE DIVISION.\n    PERFORM P1.\n    STOP RUN.\nP1. DISPLAY \"P\".");
c!(proc_perform_thru_22, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR22.\nPROCEDURE DIVISION.\n    PERFORM P1 THRU P2.\n    STOP RUN.\nP1. DISPLAY \"1\".\nP2. DISPLAY \"2\".");
c!(proc_perform_times_23, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR23.\nPROCEDURE DIVISION.\n    PERFORM 3 TIMES DISPLAY \"X\" END-PERFORM.\n    STOP RUN.");
c!(proc_perform_until_24, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR24.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 I PIC 9 VALUE 0.\nPROCEDURE DIVISION.\n    PERFORM UNTIL I > 2 ADD 1 TO I END-PERFORM.\n    STOP RUN.");
c!(proc_perform_vary_25, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR25.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 I PIC 9.\nPROCEDURE DIVISION.\n    PERFORM VARYING I FROM 1 BY 1 UNTIL I > 3 DISPLAY I END-PERFORM.\n    STOP RUN.");
c!(proc_section_26, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR26.\nPROCEDURE DIVISION.\n    PERFORM MAIN-SEC.\n    STOP RUN.\nMAIN-SEC SECTION.\nP1. DISPLAY \"M\".");
c!(proc_using_two_27, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR27.\nDATA DIVISION.\nLINKAGE SECTION.\n01 A PIC X(5).\n01 B PIC 9.\nPROCEDURE DIVISION USING A B.\n    GOBACK.");
c!(proc_returning_compute_28, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR28.\nPROCEDURE DIVISION RETURNING R.\n    COMPUTE R = 1 + 1.\n    GOBACK.");
c!(proc_call_two_args_29, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR29.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 A PIC 9.\n01 B PIC 9.\nPROCEDURE DIVISION.\n    CALL \"SUB29\" USING A B.\n    STOP RUN.");
c!(proc_call_mix_args_30, "IDENTIFICATION DIVISION.\nPROGRAM-ID. PR30.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 A PIC 9.\n01 B PIC 9.\nPROCEDURE DIVISION.\n    CALL \"SUB30\" USING BY REFERENCE A BY CONTENT B.\n    STOP RUN.");