use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

cobol_test!(test_sort_asc_desc_mixed, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. SELECT IN-F ASSIGN TO 'i'. SELECT OUT-F ASSIGN TO 'o'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. 05 K2 PIC X. FD IN-F. 01 IR PIC X(2). FD OUT-F. 01 OR-REC PIC X(2). PROCEDURE DIVISION. SORT SW ON ASCENDING KEY K1 DESCENDING KEY K2 USING IN-F GIVING OUT-F. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_collating, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. SELECT IN-F ASSIGN TO 'i'. SELECT OUT-F ASSIGN TO 'o'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. FD IN-F. 01 IR PIC X. FD OUT-F. 01 OR-REC PIC X. PROCEDURE DIVISION. SORT SW ON ASCENDING KEY K1 COLLATING SEQUENCE NATIVE USING IN-F GIVING OUT-F. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_duplicates, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. SELECT IN-F ASSIGN TO 'i'. SELECT OUT-F ASSIGN TO 'o'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. FD IN-F. 01 IR PIC X. FD OUT-F. 01 OR-REC PIC X. PROCEDURE DIVISION. SORT SW ON ASCENDING KEY K1 WITH DUPLICATES IN ORDER USING IN-F GIVING OUT-F. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_input_procedure, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. SELECT OUT-F ASSIGN TO 'o'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. FD OUT-F. 01 OR-REC PIC X. PROCEDURE DIVISION. SORT SW ON ASCENDING KEY K1 INPUT PROCEDURE INP-PROC GIVING OUT-F. DISPLAY 'OK'. STOP RUN. INP-PROC SECTION. EXIT.", vec!["OK"]);
cobol_test!(test_sort_output_procedure, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. SELECT IN-F ASSIGN TO 'i'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. FD IN-F. 01 IR PIC X. PROCEDURE DIVISION. SORT SW ON ASCENDING KEY K1 USING IN-F OUTPUT PROCEDURE OUT-PROC. DISPLAY 'OK'. STOP RUN. OUT-PROC SECTION. EXIT.", vec!["OK"]);
cobol_test!(test_merge_asc_desc_mixed, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT MW ASSIGN TO 'w'. SELECT IN1 ASSIGN TO 'i1'. SELECT IN2 ASSIGN TO 'i2'. SELECT OUT-F ASSIGN TO 'o'. DATA DIVISION. FILE SECTION. SD MW. 01 MR. 05 K1 PIC 9. 05 K2 PIC X. FD IN1. 01 I1R PIC X(2). FD IN2. 01 I2R PIC X(2). FD OUT-F. 01 OR-REC PIC X(2). PROCEDURE DIVISION. MERGE MW ON ASCENDING KEY K1 DESCENDING KEY K2 USING IN1 IN2 GIVING OUT-F. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_merge_output_procedure, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT MW ASSIGN TO 'w'. SELECT IN1 ASSIGN TO 'i1'. SELECT IN2 ASSIGN TO 'i2'. DATA DIVISION. FILE SECTION. SD MW. 01 MR. 05 K1 PIC 9. FD IN1. 01 I1R PIC X. FD IN2. 01 I2R PIC X. PROCEDURE DIVISION. MERGE MW ON ASCENDING KEY K1 USING IN1 IN2 OUTPUT PROCEDURE OUT-PROC. DISPLAY 'OK'. STOP RUN. OUT-PROC SECTION. EXIT.", vec!["OK"]);
cobol_test!(test_sort_table, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 EL OCCURS 3 TIMES ASCENDING KEY K INDEXED BY I. 10 K PIC 9. PROCEDURE DIVISION. SORT EL ON ASCENDING KEY K. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_release, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. PROCEDURE DIVISION. INP-PROC SECTION. MOVE 1 TO K1. RELEASE SR. STOP RUN.", vec![] as Vec<&str>); // Parsing
cobol_test!(test_return, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT SW ASSIGN TO 'w'. DATA DIVISION. FILE SECTION. SD SW. 01 SR. 05 K1 PIC 9. PROCEDURE DIVISION. OUT-PROC SECTION. RETURN SW AT END DISPLAY 'EOF' END-RETURN. STOP RUN.", vec![] as Vec<&str>);
