use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 specific tests for PROCEDURE DIVISION SORT STATEMENT
cobol_test!(test_sort_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT S ASSIGN TO 's'. DATA DIVISION. FILE SECTION. SD S. 01 R. 05 K PIC X. PROCEDURE DIVISION. SORT S ON ASCENDING KEY K INPUT PROCEDURE IN-PROC OUTPUT PROCEDURE OUT-PROC. STOP RUN. IN-PROC SECTION. MOVE 'B' TO R. RELEASE R. MOVE 'A' TO R. RELEASE R. GO TO IN-PROC-EXIT. IN-PROC-EXIT. EXIT. OUT-PROC SECTION. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. GO TO OUT-PROC-EXIT. OUT-PROC-EXIT. EXIT.", vec!["A", "B", "END", "B"]);
cobol_test!(test_sort_descending, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT S ASSIGN TO 's'. DATA DIVISION. FILE SECTION. SD S. 01 R. 05 K PIC X. PROCEDURE DIVISION. SORT S ON DESCENDING KEY K INPUT PROCEDURE IN-PROC OUTPUT PROCEDURE OUT-PROC. STOP RUN. IN-PROC SECTION. MOVE 'A' TO R. RELEASE R. MOVE 'B' TO R. RELEASE R. GO TO IN-PROC-EXIT. IN-PROC-EXIT. EXIT. OUT-PROC SECTION. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. GO TO OUT-PROC-EXIT. OUT-PROC-EXIT. EXIT.", vec!["B", "A", "END", "A"]);
cobol_test!(test_sort_multiple_keys, "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT S ASSIGN TO 's'. DATA DIVISION. FILE SECTION. SD S. 01 R. 05 K1 PIC X. 05 K2 PIC X. PROCEDURE DIVISION. SORT S ON ASCENDING KEY K1 DESCENDING KEY K2 INPUT PROCEDURE IN-PROC OUTPUT PROCEDURE OUT-PROC. STOP RUN. IN-PROC SECTION. MOVE 'B2' TO R. RELEASE R. MOVE 'A1' TO R. RELEASE R. MOVE 'A2' TO R. RELEASE R. GO TO IN-PROC-EXIT. IN-PROC-EXIT. EXIT. OUT-PROC SECTION. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. RETURN S AT END DISPLAY 'END' END-RETURN. DISPLAY R. GO TO OUT-PROC-EXIT. OUT-PROC-EXIT. EXIT.", vec!["A2", "A1", "B2", "END", "B2"]); // A comes before B. Within A, descending K2 means 2 comes before 1.
cobol_test!(test_sort_parse_4, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_5, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_6, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_7, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_8, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_9, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_10, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_11, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_12, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_13, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_14, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_15, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_16, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_17, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_18, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_sort_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
