use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 edge cases for Condition Logic
cobol_test!(test_cond_complex_and_or, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 1. 01 B PIC 9 VALUE 1. 01 C PIC 9 VALUE 0. PROCEDURE DIVISION. IF A = 1 AND B = 1 OR C = 1 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_complex_and_or_prec, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 0. 01 B PIC 9 VALUE 1. 01 C PIC 9 VALUE 1. PROCEDURE DIVISION. IF A = 1 AND B = 1 OR C = 1 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_complex_and_or_parens, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 0. 01 B PIC 9 VALUE 1. 01 C PIC 9 VALUE 1. PROCEDURE DIVISION. IF A = 1 AND (B = 1 OR C = 1) DISPLAY 'Y' ELSE DISPLAY 'N' END-IF. STOP RUN.", vec!["N"]);
cobol_test!(test_cond_not_and, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 0. 01 B PIC 9 VALUE 1. PROCEDURE DIVISION. IF NOT A = 1 AND B = 1 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_not_parens, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 0. 01 B PIC 9 VALUE 1. PROCEDURE DIVISION. IF NOT (A = 1 AND B = 1) DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_abbreviated_combined_1, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 1. PROCEDURE DIVISION. IF A = 1 OR 2 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_abbreviated_combined_2, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 2. PROCEDURE DIVISION. IF A = 1 OR 2 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_abbreviated_combined_3, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 3. PROCEDURE DIVISION. IF A = 1 OR 2 DISPLAY 'Y' ELSE DISPLAY 'N' END-IF. STOP RUN.", vec!["N"]);
cobol_test!(test_cond_abbreviated_combined_not, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC 9 VALUE 3. PROCEDURE DIVISION. IF A NOT = 1 AND 2 DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_class_numeric, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE '123'. PROCEDURE DIVISION. IF A IS NUMERIC DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_class_not_numeric, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE '12A'. PROCEDURE DIVISION. IF A IS NOT NUMERIC DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_class_alphabetic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE 'ABC'. PROCEDURE DIVISION. IF A IS ALPHABETIC DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_class_not_alphabetic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE 'AB1'. PROCEDURE DIVISION. IF A IS NOT ALPHABETIC DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_class_alphabetic_lower, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE 'abc'. PROCEDURE DIVISION. IF A IS ALPHABETIC-LOWER DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_class_alphabetic_upper, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC X(3) VALUE 'ABC'. PROCEDURE DIVISION. IF A IS ALPHABETIC-UPPER DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_sign_positive, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC S9 VALUE 1. PROCEDURE DIVISION. IF A IS POSITIVE DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_sign_negative, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC S9 VALUE -1. PROCEDURE DIVISION. IF A IS NEGATIVE DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_sign_zero, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 A PIC S9 VALUE 0. PROCEDURE DIVISION. IF A IS ZERO DISPLAY 'Y' END-IF. STOP RUN.", vec!["Y"]);
cobol_test!(test_cond_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_cond_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
