use super::helpers::{compile_ok, run_prints};

// ═══════════════════════════════════════════════════════════
// COBOL 2023: Modern intrinsic functions
// Tests for COBOL 2023 standard intrinsic functions not already
// covered in test_intrinsics.rs (which covers basic math, trig,
// string, date/time, statistical, and conversion intrinsics).
// ═══════════════════════════════════════════════════════════

#[test]
fn formatted_date() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATE PIC X(10).
PROCEDURE DIVISION.
    MOVE FUNCTION FORMATTED-DATE("YYYY-MM-DD" 20240101) TO WS-DATE.
    DISPLAY WS-DATE.
    STOP RUN.
"#);
}

#[test]
fn formatted_time() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-TIME PIC X(8).
PROCEDURE DIVISION.
    MOVE FUNCTION FORMATTED-TIME("HH:MM:SS" 123000) TO WS-TIME.
    DISPLAY WS-TIME.
    STOP RUN.
"#);
}

#[test]
fn date_of_integer() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATE PIC 9(8).
01 WS-INT PIC 9(7) VALUE 738886.
PROCEDURE DIVISION.
    COMPUTE WS-DATE = FUNCTION DATE-OF-INTEGER(WS-INT).
    DISPLAY WS-DATE.
    STOP RUN.
"#);
}

#[test]
fn integer_of_date() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATE PIC 9(8) VALUE 20240101.
01 WS-INT PIC 9(7).
PROCEDURE DIVISION.
    COMPUTE WS-INT = FUNCTION INTEGER-OF-DATE(WS-DATE).
    DISPLAY WS-INT.
    STOP RUN.
"#);
}

#[test]
fn integer_of_date_runtime_day_difference() {
    let output = run_prints(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DIFF PIC 9(4).
PROCEDURE DIVISION.
    COMPUTE WS-DIFF =
        FUNCTION INTEGER-OF-DATE(20240215) -
        FUNCTION INTEGER-OF-DATE(20240116).
    DISPLAY WS-DIFF.
    STOP RUN.
"#);

    assert_eq!(output, vec!["30"]);
}

#[test]
fn day_of_integer() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DAY PIC 9(7).
PROCEDURE DIVISION.
    COMPUTE WS-DAY = FUNCTION DAY-OF-INTEGER(738886).
    DISPLAY WS-DAY.
    STOP RUN.
"#);
}

#[test]
fn annuity() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-RESULT PIC 9(5)V99.
PROCEDURE DIVISION.
    COMPUTE WS-RESULT = FUNCTION ANNUITY(0.05 12).
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn present_value() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-RESULT PIC 9(7)V99.
PROCEDURE DIVISION.
    COMPUTE WS-RESULT = FUNCTION PRESENT-VALUE(0.08 1000).
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn test_numval() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(10) VALUE "12345".
01 WS-NUM PIC 9(10).
01 WS-VALID PIC 9(1).
PROCEDURE DIVISION.
    COMPUTE WS-VALID = FUNCTION TEST-NUMVAL(WS-STR).
    COMPUTE WS-NUM = FUNCTION NUMVAL(WS-STR).
    DISPLAY WS-NUM.
    STOP RUN.
"#);
}

#[test]
fn chained_intrinsics() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-RESULT PIC 9(5).
01 WS-VAL PIC 9(5) VALUE 25.
PROCEDURE DIVISION.
    COMPUTE WS-RESULT = FUNCTION ABS(FUNCTION SQRT(WS-VAL)).
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn intrinsic_in_expression() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-A PIC 9(3) VALUE 10.
01 WS-B PIC 9(3) VALUE 20.
01 WS-RESULT PIC 9(5).
PROCEDURE DIVISION.
    COMPUTE WS-RESULT = FUNCTION MAX(WS-A WS-B) + 5.
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn concatenate_multi() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-FIRST PIC X(10) VALUE "Hello".
01 WS-SEP PIC X(1) VALUE " ".
01 WS-LAST PIC X(10) VALUE "World".
01 WS-RESULT PIC X(30).
PROCEDURE DIVISION.
    MOVE FUNCTION CONCATENATE(WS-FIRST WS-SEP WS-LAST)
        TO WS-RESULT.
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn substitute_multiple() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(30) VALUE "Hello World".
01 WS-RESULT PIC X(30).
PROCEDURE DIVISION.
    MOVE FUNCTION SUBSTITUTE(WS-STR "Hello" "Goodbye")
        TO WS-RESULT.
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn when_compiled_intrinsic() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-COMPILED PIC X(21).
PROCEDURE DIVISION.
    MOVE FUNCTION WHEN-COMPILED TO WS-COMPILED.
    DISPLAY WS-COMPILED.
    STOP RUN.
"#);
}
