use super::helpers::compile_ok;

#[test]
fn report_control_heading_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. RC1.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 DEPT-HEAD TYPE CONTROL HEADING WS-DEPT.\n   03 COL 1 VALUE \"DEPT\".\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn report_control_footing_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. RC2.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 DEPT-FOOT TYPE CONTROL FOOTING WS-DEPT.\n   03 COL 1 VALUE \"TOTAL\".\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn report_sum_clause_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. RC3.\nDATA DIVISION.\nREPORT SECTION.\nRD R1.\n01 D1 TYPE DETAIL.\n   03 COL 1 PIC 9(5) SUM WS-AMT.\nWORKING-STORAGE SECTION.\n01 WS-AMT PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn report_reset_on_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. RC4.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 D1 TYPE DETAIL.\n   03 COL 1 PIC 9(5) SUM WS-AMT RESET ON WS-DEPT.\nWORKING-STORAGE SECTION.\n01 WS-AMT PIC 9(5).\n01 WS-DEPT PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn report_controls_multiple_control_items_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. RC5.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT WS-TEAM.\n01 H1 TYPE CONTROL HEADING WS-DEPT.\n   03 COL 1 VALUE \"D\".\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\n01 WS-TEAM PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn report_controls_page_heading_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. RC6.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 P1 TYPE PAGE HEADING.\n   03 COL 1 VALUE \"PAGE\".\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn report_controls_page_footing_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. RC7.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 P2 TYPE PAGE FOOTING.\n   03 COL 1 VALUE \"END\".\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn report_controls_detail_with_source_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. RC8.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 D1 TYPE DETAIL.\n   03 COL 1 SOURCE WS-NAME.\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\n01 WS-NAME PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn report_controls_final_footing_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. RC9.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE FINAL.\n01 F1 TYPE CONTROL FOOTING FINAL.\n   03 COL 1 VALUE \"FINAL\".\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn report_controls_next_group_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. RC10.\nDATA DIVISION.\nREPORT SECTION.\nRD R1 CONTROLS ARE WS-DEPT.\n01 D1 TYPE DETAIL.\n   03 NEXT GROUP PLUS 1.\n   03 COL 1 VALUE \"ROW\".\nWORKING-STORAGE SECTION.\n01 WS-DEPT PIC X(4).\nPROCEDURE DIVISION.\n    STOP RUN.");
}
