use super::helpers::parse_ok;

#[test]
fn configuration_section_source_and_object_computer_parse() {
    let src = r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
CONFIGURATION SECTION.
SOURCE-COMPUTER. IBM-Z.
OBJECT-COMPUTER. IBM-Z.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 X PIC 9 VALUE 1.
PROCEDURE DIVISION.
    DISPLAY X.
    STOP RUN.
"#;
    assert!(parse_ok(src));
}

#[test]
fn configuration_section_special_names_decimal_point_parse() {
    let src = r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
CONFIGURATION SECTION.
SPECIAL-NAMES.
    DECIMAL-POINT IS COMMA.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 N PIC 9V99 VALUE 12,34.
PROCEDURE DIVISION.
    DISPLAY N.
    STOP RUN.
"#;
    assert!(parse_ok(src));
}

#[test]
fn input_output_section_with_io_control_currently_rejected() {
    let src = r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT F ASSIGN TO "f.dat"
        ORGANIZATION IS SEQUENTIAL.
I-O-CONTROL.
DATA DIVISION.
FILE SECTION.
FD F.
01 R PIC X(20).
PROCEDURE DIVISION.
    OPEN OUTPUT F.
    MOVE "A" TO R.
    WRITE R.
    CLOSE F.
    STOP RUN.
"#;
    assert!(!parse_ok(src));
}

#[test]
fn report_section_rd_with_page_limit_currently_rejected() {
    let src = r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
REPORT SECTION.
RD SALES-REPORT
    PAGE LIMIT IS 60
    FIRST DETAIL 5
    LAST DETAIL 55.
01 H1 TYPE PAGE HEADING.
   03 LINE 1 COLUMN 1 VALUE "SALES REPORT".
01 D1 TYPE DETAIL.
   03 LINE PLUS 1 COLUMN 1 SOURCE WS-NAME.
WORKING-STORAGE SECTION.
01 WS-NAME PIC X(20) VALUE "ITEM".
PROCEDURE DIVISION.
    STOP RUN.
"#;
    assert!(!parse_ok(src));
}
