use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    };
}

// 30 distinct tests for declaratives and error handling
cobol_test!(
    test_decl_use_global,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE GLOBAL AFTER STANDARD ERROR PROCEDURE ON F. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_input,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON INPUT. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_output,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON OUTPUT. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_io,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON I-O. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_extend,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON EXTEND. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_multiple_files,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F1 ASSIGN TO 'a'. SELECT F2 ASSIGN TO 'b'. DATA DIVISION. FILE SECTION. FD F1. 01 R1 PIC X. FD F2. 01 R2 PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON F1 F2. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_resume_next,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON INPUT. D-PARA. RESUME NEXT STATEMENT. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_resume_label,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER STANDARD ERROR PROCEDURE ON INPUT. D-PARA. RESUME M-PARA. END DECLARATIVES. M SECTION. M-PARA. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_trigger_read,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON F. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. READ F. STOP RUN.",
    vec!["ERR"] /* mock file fail */
);
cobol_test!(
    test_decl_trigger_write,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON F. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. WRITE R. STOP RUN.",
    vec!["ERR"] /* mock */
);
cobol_test!(
    test_decl_trigger_open,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON F. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. OPEN INPUT F. STOP RUN.",
    vec!["ERR"] /* mock */
);
cobol_test!(
    test_decl_trigger_close,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON F. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. OPEN INPUT F. CLOSE F. STOP RUN.",
    vec!["ERR"] /* mock */
);
cobol_test!(
    test_decl_no_trigger_valid,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON INPUT. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_nested_program,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. M SECTION. CALL 'SUB'. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. SUB. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON INPUT. D-PARA. DISPLAY 'SUB ERR'. END DECLARATIVES. S SECTION. DISPLAY 'SUB OK'. EXIT PROGRAM. END PROGRAM SUB.",
    vec!["SUB OK"]
);
cobol_test!(
    test_decl_nested_program_global,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE GLOBAL AFTER ERROR ON INPUT. D-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. CALL 'SUB'. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. SUB. PROCEDURE DIVISION. S SECTION. DISPLAY 'SUB OK'. EXIT PROGRAM. END PROGRAM SUB.",
    vec!["SUB OK"]
);
cobol_test!(
    test_decl_priority,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D1 SECTION. USE AFTER ERROR ON F. D1-PARA. DISPLAY 'F-ERR'. D2 SECTION. USE AFTER ERROR ON INPUT. D2-PARA. DISPLAY 'IN-ERR'. END DECLARATIVES. M SECTION. OPEN INPUT F. STOP RUN.",
    vec!["F-ERR"]
);
cobol_test!(
    test_decl_file_status_check,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a' FILE STATUS IS FS. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. WORKING-STORAGE SECTION. 01 FS PIC XX. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON F. D-PARA. DISPLAY FS. END DECLARATIVES. M SECTION. OPEN INPUT F. STOP RUN.",
    vec!["35"]
);
cobol_test!(
    test_decl_use_for_debugging,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. CONFIGURATION SECTION. SOURCE-COMPUTER. X WITH DEBUGGING MODE. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE FOR DEBUGGING ON ALL PROCEDURES. D-PARA. DISPLAY 'DBG'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["DBG", "OK"]
);
cobol_test!(
    test_decl_use_for_debugging_section,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. CONFIGURATION SECTION. SOURCE-COMPUTER. X WITH DEBUGGING MODE. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE FOR DEBUGGING ON M SECTION. D-PARA. DISPLAY 'DBG'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["DBG", "OK"]
);
cobol_test!(
    test_decl_use_for_debugging_file,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. CONFIGURATION SECTION. SOURCE-COMPUTER. X WITH DEBUGGING MODE. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE FOR DEBUGGING ON F. D-PARA. DISPLAY 'DBG'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_for_debugging_identifier,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. CONFIGURATION SECTION. SOURCE-COMPUTER. X WITH DEBUGGING MODE. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE FOR DEBUGGING ON V. D-PARA. DISPLAY 'DBG'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_multiple_use_statements,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D1 SECTION. USE AFTER ERROR ON INPUT. D1-PARA. DISPLAY 'IN'. D2 SECTION. USE AFTER ERROR ON OUTPUT. D2-PARA. DISPLAY 'OUT'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_perform_inside,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON INPUT. D-PARA. PERFORM H-PARA. H-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_go_to_inside,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON INPUT. D-PARA. GO TO H-PARA. H-PARA. DISPLAY 'ERR'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_go_to_outside_error,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON INPUT. D-PARA. GO TO M-PARA. END DECLARATIVES. M SECTION. M-PARA. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
); // Should technically parse error or runtime err on some strict compilers
cobol_test!(
    test_decl_call_inside,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON INPUT. D-PARA. CALL 'SUB'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_nested_use_global,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. ENVIRONMENT DIVISION. INPUT-OUTPUT SECTION. FILE-CONTROL. SELECT F ASSIGN TO 'a'. DATA DIVISION. FILE SECTION. FD F. 01 R PIC X. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE GLOBAL AFTER ERROR ON F. D-PARA. DISPLAY 'G-ERR'. END DECLARATIVES. M SECTION. CALL 'SUB'. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. SUB. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER ERROR ON F. D-PARA. DISPLAY 'L-ERR'. END DECLARATIVES. S SECTION. OPEN INPUT F. EXIT PROGRAM. END PROGRAM SUB.",
    vec!["L-ERR"]
);
cobol_test!(
    test_decl_use_exception,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER EXCEPTION CONDITION. D-PARA. DISPLAY 'EXC'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_exception_object,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER EXCEPTION OBJECT O. D-PARA. DISPLAY 'EXC'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_decl_use_invalid_key,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DECLARATIVES. D SECTION. USE AFTER INVALID KEY. D-PARA. DISPLAY 'KEY'. END DECLARATIVES. M SECTION. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
