use super::helpers::compile_ok;

#[test]
fn relative_file_select_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\"\n        ORGANIZATION IS RELATIVE\n        ACCESS MODE IS RANDOM\n        RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}

#[test]
fn relative_read_invalid_key_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O RF.\n    READ RF INVALID KEY DISPLAY \"MISS\" END-READ.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_open_input_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT RF.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_open_output_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN OUTPUT RF.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_write_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN OUTPUT RF.\n    WRITE RR INVALID KEY DISPLAY \"BAD\" END-WRITE.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_rewrite_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O RF.\n    REWRITE RR INVALID KEY DISPLAY \"BAD\" END-REWRITE.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_delete_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN I-O RF.\n    DELETE RF INVALID KEY DISPLAY \"BAD\" END-DELETE.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_start_equal_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT RF.\n    START RF KEY IS EQUAL TO RK INVALID KEY DISPLAY \"BAD\" END-START.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_read_next_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS RANDOM RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    OPEN INPUT RF.\n    READ RF NEXT RECORD AT END DISPLAY \"EOF\" END-READ.\n    CLOSE RF.\n    STOP RUN.",
    );
}

#[test]
fn relative_access_dynamic_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT RF ASSIGN TO \"r.dat\" ORGANIZATION IS RELATIVE ACCESS MODE IS DYNAMIC RELATIVE KEY IS RK.\nDATA DIVISION.\nFILE SECTION.\nFD RF.\n01 RR PIC X(20).\nWORKING-STORAGE SECTION.\n01 RK PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.",
    );
}