use super::helpers::compile_ok;

// ═══════════════════════════════════════════════════════════
// COBOL 2023: Modern data features
// ═══════════════════════════════════════════════════════════

#[test]
fn typedef_basic() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-AMOUNT PIC 9(7)V99.
PROCEDURE DIVISION.
    TYPEDEF AMOUNT-TYPE AS PIC 9(7)V99.
    STOP RUN.
"#);
}

#[test]
fn validate_statement() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-INPUT PIC X(20).
PROCEDURE DIVISION.
    VALIDATE WS-INPUT.
    STOP RUN.
"#);
}

#[test]
fn allocate_and_free() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-PTR USAGE POINTER.
PROCEDURE DIVISION.
    ALLOCATE WS-PTR.
    FREE WS-PTR.
    STOP RUN.
"#);
}

#[test]
fn data_item_late_binding() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DYNAMIC.
   05 WS-NAME PIC X(30) VALUE "Default".
   05 WS-AGE PIC 9(3) VALUE 0.
01 WS-TABLE.
   05 WS-ENTRY OCCURS 100 TIMES.
      10 WS-KEY PIC X(10).
      10 WS-VAL PIC 9(5).
PROCEDURE DIVISION.
    DISPLAY WS-NAME.
    STOP RUN.
"#);
}

#[test]
fn data_item_occurs_depending() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-COUNT PIC 9(3) VALUE 5.
01 WS-TABLE.
   05 WS-ITEM OCCURS 1 TO 100 TIMES
      DEPENDING ON WS-COUNT PIC X(10).
PROCEDURE DIVISION.
    DISPLAY WS-COUNT.
    STOP RUN.
"#);
}

#[test]
fn data_item_redefines() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATE PIC 9(8) VALUE 20240101.
01 WS-DATE-PARTS REDEFINES WS-DATE.
   05 WS-YEAR PIC 9(4).
   05 WS-MONTH PIC 9(2).
   05 WS-DAY PIC 9(2).
PROCEDURE DIVISION.
    DISPLAY WS-YEAR.
    STOP RUN.
"#);
}

#[test]
fn data_item_88_level_conditions() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STATUS PIC X(1) VALUE "A".
   88 WS-ACTIVE VALUE "A".
   88 WS-INACTIVE VALUE "I".
   88 WS-DELETED VALUE "D".
01 WS-SCORE PIC 9(3) VALUE 85.
   88 WS-PASS VALUE 60 THRU 100.
   88 WS-FAIL VALUE 0 THRU 59.
PROCEDURE DIVISION.
    SET WS-ACTIVE TO TRUE.
    DISPLAY WS-STATUS.
    STOP RUN.
"#);
}

#[test]
fn data_item_national_usage() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-UTF8 PIC X(50) USAGE NATIONAL.
01 WS-GLOBAL PIC X(20) GLOBAL.
01 WS-EXTERNAL PIC X(20) EXTERNAL.
PROCEDURE DIVISION.
    DISPLAY WS-UTF8.
    STOP RUN.
"#);
}

#[test]
fn data_item_comp_variants() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-BIN PIC 9(9) USAGE BINARY.
01 WS-COMP PIC 9(9) USAGE COMP.
01 WS-COMP3 PIC 9(9) USAGE COMP-3.
01 WS-DISP PIC 9(9) USAGE DISPLAY.
01 WS-PTR USAGE POINTER.
PROCEDURE DIVISION.
    DISPLAY WS-BIN.
    STOP RUN.
"#);
}

#[test]
fn data_item_indexed_table() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-TABLE.
   05 WS-ROW OCCURS 10 TIMES
      INDEXED BY WS-IDX.
      10 WS-COL PIC X(5).
PROCEDURE DIVISION.
    DISPLAY WS-COL(1).
    STOP RUN.
"#);
}
