use super::helpers::compile_ok;

#[test]
fn open_input_output_io_extend_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    CLOSE F.\n    OPEN OUTPUT F.\n    CLOSE F.\n    OPEN I-O F.\n    CLOSE F.\n    OPEN EXTEND F.\n    CLOSE F.\n    STOP RUN.",
    );
}

#[test]
fn close_with_no_rewind_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    CLOSE F WITH NO REWIND.\n    STOP RUN.",
    );
}

#[test]
fn open_input_only_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN INPUT F.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn open_output_only_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn open_io_only_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn open_extend_only_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN EXTEND F.\n    CLOSE F.\n    STOP RUN.");
}

#[test]
fn open_multiple_files_same_mode_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1 F2.\n    CLOSE F1 F2.\n    STOP RUN.");
}

#[test]
fn close_with_lock_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN I-O F.\n    CLOSE F WITH LOCK.\n    STOP RUN.");
}

#[test]
fn open_input_output_mixed_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1.\n    OPEN OUTPUT F2.\n    CLOSE F1 F2.\n    STOP RUN.");
}

#[test]
fn open_output_then_extend_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F ASSIGN TO \"f.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F.\n01 R PIC X(20).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F.\n    CLOSE F.\n    OPEN EXTEND F.\n    CLOSE F.\n    STOP RUN.");
}