use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

cobol_test!(test_str_delim_size, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(2) VALUE 'AB'. 01 R PIC X(4). PROCEDURE DIVISION. STRING S1 DELIMITED BY SIZE INTO R. DISPLAY R. STOP RUN.", vec!["AB  "]);
cobol_test!(test_str_delim_literal, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(5) VALUE 'A*B*C'. 01 R PIC X(4). PROCEDURE DIVISION. STRING S1 DELIMITED BY '*' INTO R. DISPLAY R. STOP RUN.", vec!["A   "]);
cobol_test!(test_str_delim_space, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(5) VALUE 'A B C'. 01 R PIC X(4). PROCEDURE DIVISION. STRING S1 DELIMITED BY SPACE INTO R. DISPLAY R. STOP RUN.", vec!["A   "]);
cobol_test!(test_str_delim_multiple_sources, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(3) VALUE 'A*B'. 01 S2 PIC X(3) VALUE 'C*D'. 01 R PIC X(6). PROCEDURE DIVISION. STRING S1 S2 DELIMITED BY '*' INTO R. DISPLAY R. STOP RUN.", vec!["AC    "]);
cobol_test!(test_str_delim_multiple_delims, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(3) VALUE 'A*B'. 01 S2 PIC X(3) VALUE 'C-D'. 01 R PIC X(6). PROCEDURE DIVISION. STRING S1 DELIMITED BY '*' S2 DELIMITED BY '-' INTO R. DISPLAY R. STOP RUN.", vec!["AC    "]);
cobol_test!(test_str_pointer, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(2) VALUE 'AB'. 01 R PIC X(4) VALUE SPACES. 01 P PIC 9 VALUE 2. PROCEDURE DIVISION. STRING S1 DELIMITED BY SIZE INTO R WITH POINTER P. DISPLAY R. STOP RUN.", vec![" AB "]);
cobol_test!(test_str_overflow_trigger, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(5) VALUE 'ABCDE'. 01 R PIC X(2). PROCEDURE DIVISION. STRING S1 DELIMITED BY SIZE INTO R ON OVERFLOW DISPLAY 'OVF'. STOP RUN.", vec!["OVF"]);
cobol_test!(test_str_overflow_no_trigger, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(2) VALUE 'AB'. 01 R PIC X(5). PROCEDURE DIVISION. STRING S1 DELIMITED BY SIZE INTO R ON OVERFLOW DISPLAY 'OVF' NOT ON OVERFLOW DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_str_pointer_update, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X(2) VALUE 'AB'. 01 R PIC X(5). 01 P PIC 9 VALUE 1. PROCEDURE DIVISION. STRING S1 DELIMITED BY SIZE INTO R WITH POINTER P. DISPLAY P. STOP RUN.", vec!["3"]);
cobol_test!(test_str_mixed_sizes, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S1 PIC X VALUE 'A'. 01 S2 PIC X(2) VALUE 'BC'. 01 R PIC X(4). PROCEDURE DIVISION. STRING S1 S2 DELIMITED BY SIZE INTO R. DISPLAY R. STOP RUN.", vec!["ABC "]);
