use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

// 30 distinct tests for XML JSON Generate
cobol_test!(test_xml_gen_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. XML GENERATE DOC FROM R. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_count, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). 01 C PIC 9. PROCEDURE DIVISION. XML GENERATE DOC FROM R COUNT IN C. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_file, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 F PIC X(20) VALUE 'a.xml'. PROCEDURE DIVISION. XML GENERATE FILE F FROM R. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_with_encoding, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. XML GENERATE DOC FROM R WITH ENCODING 1208. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_with_xml_declaration, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. XML GENERATE DOC FROM R WITH XML-DECLARATION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_with_attributes, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. XML GENERATE DOC FROM R WITH ATTRIBUTES. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_name, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 B PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. XML GENERATE DOC FROM R NAME B IS 'A'. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_suppress, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 05 B PIC 9 VALUE 2. 01 DOC PIC X(20). PROCEDURE DIVISION. XML GENERATE DOC FROM R SUPPRESS B. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_exception, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(2). PROCEDURE DIVISION. XML GENERATE DOC FROM R ON EXCEPTION DISPLAY 'E' NOT ON EXCEPTION DISPLAY 'N'. STOP RUN.", vec!["E"]); // Overflow mock
cobol_test!(test_json_gen_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. JSON GENERATE DOC FROM R. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_json_gen_name, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 B PIC 9 VALUE 1. 01 DOC PIC X(20). PROCEDURE DIVISION. JSON GENERATE DOC FROM R NAME B IS 'A'. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_json_gen_suppress, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 05 B PIC 9 VALUE 2. 01 DOC PIC X(20). PROCEDURE DIVISION. JSON GENERATE DOC FROM R SUPPRESS B. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_json_gen_count, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 R. 05 A PIC 9 VALUE 1. 01 DOC PIC X(20). 01 C PIC 9. PROCEDURE DIVISION. JSON GENERATE DOC FROM R COUNT IN C. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_14, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_15, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_16, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_17, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_18, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_19, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_20, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_21, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_22, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_23, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_24, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_25, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_26, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_27, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_28, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_29, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_xml_gen_parse_30, "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
