use super::helpers::compile_ok;

macro_rules! c { ($name:ident, $src:expr) => { #[test] fn $name() { compile_ok($src); } }; }

c!(dt_numeric_01, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T1.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9(5).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_signed_02, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T2.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(5).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_binary_03, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T3.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(4) COMP.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_comp4_04, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T4.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(4) COMP-4.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_comp5_05, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T5.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(9) COMP-5.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_comp3_06, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T6.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC S9(5)V99 COMP-3.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_comp1_07, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T7.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 F USAGE COMP-1.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_comp2_08, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T8.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 F USAGE COMP-2.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_decfloat16_09, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T9.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 F USAGE FLOAT-DECIMAL-16.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_decfloat34_10, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T10.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 F USAGE FLOAT-DECIMAL-34.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_boolean_11, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T11.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 B USAGE BOOLEAN.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_national_12, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T12.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC N(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_utf8_13, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T13.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 U PIC U(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_alphanumeric_14, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T14.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 A PIC X(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_alphabetic_15, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T15.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 A PIC A(10).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_group_16, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T16.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 G.\n   05 A PIC X(5).\n   05 B PIC 9(3).\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_object_ref_17, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T17.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 O USAGE OBJECT REFERENCE.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_pointer_18, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T18.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P USAGE POINTER.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_prog_ptr_19, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T19.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P USAGE PROGRAM-POINTER.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_func_ptr_20, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T20.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 P USAGE FUNCTION-POINTER.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_external_21, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T21.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC X(4) EXTERNAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_global_22, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T22.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 X PIC X(4) GLOBAL.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_any_length_23, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T23.\nDATA DIVISION.\nLINKAGE SECTION.\n01 X PIC X ANY LENGTH.\nPROCEDURE DIVISION USING X.\n    GOBACK.");
c!(dt_typedef_24, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T24.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 T1 PIC 9(4) IS TYPEDEF.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_constant_25, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T25.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 PI PIC 9V99 CONSTANT VALUE 3.14.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_display_numeric_26, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T26.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9(6) DISPLAY.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_edited_numeric_27, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T27.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 E PIC ZZ,ZZ9.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_bool_literal_28, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T28.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 B USAGE BOOLEAN VALUE TRUE.\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_national_literal_29, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T29.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC N(5) VALUE N\"HELLO\".\nPROCEDURE DIVISION.\n    STOP RUN.");
c!(dt_object_ref_null_30, "IDENTIFICATION DIVISION.\nPROGRAM-ID. T30.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 O USAGE OBJECT REFERENCE VALUE NULL.\nPROCEDURE DIVISION.\n    STOP RUN.");