use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    };
}

// 30 distinct tests for Pointers
cobol_test!(
    test_ptr_set_address_of,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X VALUE 'A'. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO ADDRESS OF V. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_set_null,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO NULL. IF P = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_set_nulls,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO NULLS. IF P = NULLS DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_set_pointer,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X VALUE 'A'. 01 P1 USAGE POINTER. 01 P2 USAGE POINTER. PROCEDURE DIVISION. SET P1 TO ADDRESS OF V. SET P2 TO P1. IF P1 = P2 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_compare_equal,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X VALUE 'A'. 01 P1 USAGE POINTER. 01 P2 USAGE POINTER. PROCEDURE DIVISION. SET P1 TO ADDRESS OF V. SET P2 TO ADDRESS OF V. IF P1 = P2 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_compare_not_equal,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V1 PIC X VALUE 'A'. 01 V2 PIC X VALUE 'B'. 01 P1 USAGE POINTER. 01 P2 USAGE POINTER. PROCEDURE DIVISION. SET P1 TO ADDRESS OF V1. SET P2 TO ADDRESS OF V2. IF P1 NOT = P2 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_compare_null,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO NULL. IF P = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_add_offset,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO NULL. SET P UP BY 5. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_sub_offset,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. SET P TO NULL. SET P DOWN BY 5. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_linkage,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. LINKAGE SECTION. 01 V PIC X. PROCEDURE DIVISION. SET ADDRESS OF V TO P. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_procedure,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE PROGRAM-POINTER. PROCEDURE DIVISION. SET P TO ENTRY 'SUB'. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_procedure_null,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE PROGRAM-POINTER. PROCEDURE DIVISION. SET P TO NULL. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_procedure_compare,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P1 USAGE PROGRAM-POINTER. 01 P2 USAGE PROGRAM-POINTER. PROCEDURE DIVISION. SET P1 TO ENTRY 'SUB'. SET P2 TO P1. IF P1 = P2 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_call,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE PROGRAM-POINTER. PROCEDURE DIVISION. SET P TO ENTRY 'SUB'. CALL P. STOP RUN. IDENTIFICATION DIVISION. PROGRAM-ID. SUB. PROCEDURE DIVISION. DISPLAY 'SUB'. EXIT PROGRAM. END PROGRAM SUB.",
    vec!["SUB"]
);
cobol_test!(
    test_ptr_redefines,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. 01 N REDEFINES P PIC 9(8) COMP-5. PROCEDURE DIVISION. SET P TO NULL. IF N = 0 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_sync,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER SYNC. PROCEDURE DIVISION. SET P TO NULL. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_array,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 P USAGE POINTER OCCURS 3 TIMES. PROCEDURE DIVISION. SET P(1) TO NULL. IF P(1) = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_array_set,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 TBL. 05 P USAGE POINTER OCCURS 3 TIMES. 01 V PIC X. PROCEDURE DIVISION. SET P(2) TO ADDRESS OF V. IF P(2) NOT = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_group_move,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 G1. 05 P1 USAGE POINTER. 01 G2. 05 P2 USAGE POINTER. PROCEDURE DIVISION. SET P1 TO NULL. MOVE G1 TO G2. IF P2 = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_allocate,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. ALLOCATE 10 CHARACTERS RETURNING P. IF P NOT = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_free,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. ALLOCATE 10 CHARACTERS RETURNING P. FREE P. IF P = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_allocate_initialized,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER. PROCEDURE DIVISION. ALLOCATE 10 CHARACTERS INITIALIZED RETURNING P. IF P NOT = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_based,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 B PIC X BASED. 01 P USAGE POINTER. PROCEDURE DIVISION. ALLOCATE B RETURNING P. SET ADDRESS OF B TO P. MOVE 'A' TO B. DISPLAY B. STOP RUN.",
    vec!["A"]
);
cobol_test!(
    test_ptr_function,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. PROCEDURE DIVISION. IF FUNCTION ADDR('A') NOT = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_value_null,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P USAGE POINTER VALUE NULL. PROCEDURE DIVISION. IF P = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_based_length,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 B PIC X(5) BASED. 01 P USAGE POINTER. PROCEDURE DIVISION. ALLOCATE B RETURNING P. SET ADDRESS OF B TO P. IF LENGTH OF B = 5 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_allocate_length_of,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 V PIC X(5). 01 P USAGE POINTER. PROCEDURE DIVISION. ALLOCATE LENGTH OF V CHARACTERS RETURNING P. IF P NOT = NULL DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_set_address_of_linkage,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P1 USAGE POINTER. LINKAGE SECTION. 01 L PIC X. PROCEDURE DIVISION. SET P1 TO ADDRESS OF L. DISPLAY 'OK'. STOP RUN.",
    vec!["OK"]
);
cobol_test!(
    test_ptr_compare_greater,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P1 USAGE POINTER. 01 P2 USAGE POINTER. PROCEDURE DIVISION. SET P1 TO NULL. SET P2 TO NULL. SET P2 UP BY 1. IF P2 > P1 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
cobol_test!(
    test_ptr_compare_less,
    "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 P1 USAGE POINTER. 01 P2 USAGE POINTER. PROCEDURE DIVISION. SET P1 TO NULL. SET P2 TO NULL. SET P2 UP BY 1. IF P1 < P2 DISPLAY 'Y' END-IF. STOP RUN.",
    vec!["Y"]
);
