use super::helpers::compile_ok;

#[test]
fn open_two_files_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1 F2.\n    CLOSE F1 F2.\n    STOP RUN.",
    );
}

#[test]
fn mixed_open_modes_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1.\n    OPEN OUTPUT F2.\n    CLOSE F1 F2.\n    STOP RUN.",
    );
}

#[test]
fn open_three_files_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\n    SELECT F3 ASSIGN TO \"c.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nFD F3.\n01 R3 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1 F2 F3.\n    CLOSE F1 F2 F3.\n    STOP RUN.");
}

#[test]
fn open_input_and_io_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1.\n    OPEN I-O F2.\n    CLOSE F1 F2.\n    STOP RUN.");
}

#[test]
fn open_output_and_extend_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN OUTPUT F1.\n    OPEN EXTEND F2.\n    CLOSE F1 F2.\n    STOP RUN.");
}

#[test]
fn close_subset_then_rest_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1 F2.\n    CLOSE F1.\n    CLOSE F2.\n    STOP RUN.");
}

#[test]
fn open_same_statement_multiple_modes_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1 OUTPUT F2.\n    CLOSE F1 F2.\n    STOP RUN.");
}

#[test]
fn share_with_locking_close_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN I-O F1 F2.\n    CLOSE F1 WITH LOCK F2 WITH LOCK.\n    STOP RUN.");
}

#[test]
fn file_sharing_with_status_codes_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\" FILE STATUS IS FS1.\n    SELECT F2 ASSIGN TO \"b.dat\" FILE STATUS IS FS2.\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nWORKING-STORAGE SECTION.\n01 FS1 PIC XX.\n01 FS2 PIC XX.\nPROCEDURE DIVISION.\n    OPEN INPUT F1 F2.\n    CLOSE F1 F2.\n    STOP RUN.");
}

#[test]
fn shared_open_input_output_extend_compiles() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nENVIRONMENT DIVISION.\nINPUT-OUTPUT SECTION.\nFILE-CONTROL.\n    SELECT F1 ASSIGN TO \"a.dat\".\n    SELECT F2 ASSIGN TO \"b.dat\".\n    SELECT F3 ASSIGN TO \"c.dat\".\nDATA DIVISION.\nFILE SECTION.\nFD F1.\n01 R1 PIC X(10).\nFD F2.\n01 R2 PIC X(10).\nFD F3.\n01 R3 PIC X(10).\nPROCEDURE DIVISION.\n    OPEN INPUT F1.\n    OPEN OUTPUT F2.\n    OPEN EXTEND F3.\n    CLOSE F1 F2 F3.\n    STOP RUN.");
}