use super::helpers::compile_ok;

#[test]
fn screen_section_basic_form_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. SCREEN-A.\nDATA DIVISION.\nSCREEN SECTION.\n01 MAIN-SCREEN.\n   05 BLANK SCREEN.\n   05 LINE 2 COLUMN 10 VALUE \"Name:\".\n   05 LINE 2 COLUMN 20 PIC X(20) USING WS-NAME.\nWORKING-STORAGE SECTION.\n01 WS-NAME PIC X(20).\nPROCEDURE DIVISION.\n    DISPLAY MAIN-SCREEN.\n    ACCEPT MAIN-SCREEN.\n    STOP RUN.",
    );
}

#[test]
fn screen_section_menu_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. SCREEN-B.\nDATA DIVISION.\nSCREEN SECTION.\n01 MENU-SCREEN.\n   05 LINE 1 COLUMN 5 VALUE \"1) Add\".\n   05 LINE 2 COLUMN 5 VALUE \"2) Edit\".\n   05 LINE 3 COLUMN 5 VALUE \"3) Exit\".\nWORKING-STORAGE SECTION.\n01 WS-CHOICE PIC 9.\nPROCEDURE DIVISION.\n    DISPLAY MENU-SCREEN.\n    ACCEPT WS-CHOICE.\n    STOP RUN.",
    );
}

#[test]
fn screen_section_validation_loop_compiles() {
    compile_ok(
        "IDENTIFICATION DIVISION.\nPROGRAM-ID. SCREEN-C.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 WS-CHOICE PIC 9 VALUE 0.\nPROCEDURE DIVISION.\n    PERFORM UNTIL WS-CHOICE = 3\n        ACCEPT WS-CHOICE\n        EVALUATE WS-CHOICE\n            WHEN 1 DISPLAY \"ADD\"\n            WHEN 2 DISPLAY \"EDIT\"\n            WHEN 3 DISPLAY \"EXIT\"\n            WHEN OTHER DISPLAY \"INVALID\"\n        END-EVALUATE\n    END-PERFORM.\n    STOP RUN.",
    );
}
