use crate::helpers;

macro_rules! cobol_test {
    ($name:ident, $src:expr, $expected:expr) => {
        #[test]
        fn $name() {
            let out = crate::helpers::run_prints($src);
            assert_eq!(out, $expected);
        }
    }
}

cobol_test!(test_unstr_basic, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B*C'. 01 R1 PIC X. 01 R2 PIC X. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 R2. DISPLAY R1 R2. STOP RUN.", vec!["AB"]);
cobol_test!(test_unstr_all_delim, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(6) VALUE 'A**B*C'. 01 R1 PIC X. 01 R2 PIC X. PROCEDURE DIVISION. UNSTRING S DELIMITED BY ALL '*' INTO R1 R2. DISPLAY R1 R2. STOP RUN.", vec!["AB"]);
cobol_test!(test_unstr_multiple_delims, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B-C'. 01 R1 PIC X. 01 R2 PIC X. 01 R3 PIC X. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' OR '-' INTO R1 R2 R3. DISPLAY R1 R2 R3. STOP RUN.", vec!["ABC"]);
cobol_test!(test_unstr_count_in, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'AB*CD'. 01 R1 PIC X(2). 01 C1 PIC 9. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 COUNT IN C1. DISPLAY C1. STOP RUN.", vec!["2"]);
cobol_test!(test_unstr_tallying_in, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B*C'. 01 R1 PIC X. 01 R2 PIC X. 01 T PIC 9 VALUE 0. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 R2 TALLYING IN T. DISPLAY T. STOP RUN.", vec!["2"]);
cobol_test!(test_unstr_pointer, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B*C'. 01 R1 PIC X. 01 P PIC 9 VALUE 3. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 WITH POINTER P. DISPLAY R1. STOP RUN.", vec!["B"]);
cobol_test!(test_unstr_pointer_update, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B*C'. 01 R1 PIC X. 01 P PIC 9 VALUE 1. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 WITH POINTER P. DISPLAY P. STOP RUN.", vec!["3"]);
cobol_test!(test_unstr_overflow_trigger, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B*C'. 01 R1 PIC X. 01 P PIC 9 VALUE 6. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 WITH POINTER P ON OVERFLOW DISPLAY 'OVF'. STOP RUN.", vec!["OVF"]);
cobol_test!(test_unstr_overflow_no_trigger, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B*C'. 01 R1 PIC X. 01 P PIC 9 VALUE 1. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' INTO R1 WITH POINTER P ON OVERFLOW DISPLAY 'OVF' NOT ON OVERFLOW DISPLAY 'OK'. STOP RUN.", vec!["OK"]);
cobol_test!(test_unstr_delim_in, "IDENTIFICATION DIVISION. PROGRAM-ID. T. DATA DIVISION. WORKING-STORAGE SECTION. 01 S PIC X(5) VALUE 'A*B-C'. 01 R1 PIC X. 01 D1 PIC X. PROCEDURE DIVISION. UNSTRING S DELIMITED BY '*' OR '-' INTO R1 DELIMITER IN D1. DISPLAY D1. STOP RUN.", vec!["*"]);
