//! Runtime checks for C math.h power, root, and remainder functions.


c_run_cases! {
    sqrt_twenty_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", sqrt(25.0)); return 0;", expect: ["5.0"] },
    sqrt_thirty_six => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", sqrt(36.0)); return 0;", expect: ["6.0"] },
    sqrt_forty_nine => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", sqrt(49.0)); return 0;", expect: ["7.0"] },
    sqrt_sixty_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", sqrt(64.0)); return 0;", expect: ["8.0"] },
    sqrt_one_hundred => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", sqrt(100.0)); return 0;", expect: ["10.0"] },
    sqrt_one_hundred_forty_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", sqrt(144.0)); return 0;", expect: ["12"] },
    sqrt_two_point_two_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", sqrt(2.25)); return 0;", expect: ["1.500"] },
    sqrt_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", sqrt(3.0)); return 0;", expect: ["1.732"] },
    sqrt_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", sqrt(5.0)); return 0;", expect: ["2.236"] },
    sqrt_tenth => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", sqrt(0.1)); return 0;", expect: ["0.316"] },
    sqrt_seven => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", sqrt(7.0)); return 0;", expect: ["2.646"] },
    cbrt_eight => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", cbrt(8.0)); return 0;", expect: ["2.0"] },
    cbrt_sixty_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", cbrt(64.0)); return 0;", expect: ["4.0"] },
    cbrt_one_hundred_twenty_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", cbrt(125.0)); return 0;", expect: ["5.0"] },
    cbrt_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", cbrt(1.0)); return 0;", expect: ["1.0"] },
    cbrt_negative_eight => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", cbrt(-8.0)); return 0;", expect: ["-2.0"] },
    cbrt_point_one_two_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", cbrt(0.125)); return 0;", expect: ["0.500"] },
    cbrt_two_hundred_sixteen => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", cbrt(216.0)); return 0;", expect: ["6.0"] },
    hypot_5_12 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", hypot(5.0, 12.0)); return 0;", expect: ["13.0"] },
    hypot_8_15 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", hypot(8.0, 15.0)); return 0;", expect: ["17.0"] },
    hypot_1_1 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", hypot(1.0, 1.0)); return 0;", expect: ["1.414"] },
    hypot_6_8 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", hypot(6.0, 8.0)); return 0;", expect: ["10.0"] },
    hypot_7_24 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", hypot(7.0, 24.0)); return 0;", expect: ["25.0"] },
    hypot_9_40 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", hypot(9.0, 40.0)); return 0;", expect: ["41.0"] },
    hypot_20_21 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", hypot(20.0, 21.0)); return 0;", expect: ["29.0"] },
    pow_two_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(2.0, 5.0)); return 0;", expect: ["32"] },
    pow_three_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(3.0, 3.0)); return 0;", expect: ["27"] },
    pow_five_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(5.0, 2.0)); return 0;", expect: ["25"] },
    pow_ten_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(10.0, 3.0)); return 0;", expect: ["1000"] },
    pow_two_negative_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", pow(2.0, -3.0)); return 0;", expect: ["0.125"] },
    pow_four_negative_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", pow(4.0, -0.5)); return 0;", expect: ["0.500"] },
    pow_eight_one_third => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", pow(8.0, 1.0 / 3.0)); return 0;", expect: ["2.000"] },
    pow_twenty_seven_two_thirds => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", pow(27.0, 2.0 / 3.0)); return 0;", expect: ["9.000"] },
    pow_negative_two_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(-2.0, 3.0)); return 0;", expect: ["-8"] },
    pow_negative_two_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(-2.0, 4.0)); return 0;", expect: ["16"] },
    pow_four_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(4.0, 5.0)); return 0;", expect: ["1024"] },
    pow_six_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", pow(6.0, 2.0)); return 0;", expect: ["36"] },
    fmod_23_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(23, 7)); return 0;", expect: ["2.0"] },
    fmod_negative_23_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(-23, 7)); return 0;", expect: ["-2.0"] },
    fmod_23_negative_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(23, -7)); return 0;", expect: ["2.0"] },
    fmod_7_5_2 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(7.5, 2)); return 0;", expect: ["1.5"] },
    fmod_negative_7_5_2 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(-7.5, 2)); return 0;", expect: ["-1.5"] },
    fmod_1_5_0_4 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(1.5, 0.4)); return 0;", expect: ["0.3"] },
    fmod_8_3_2_1 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(8.3, 2.1)); return 0;", expect: ["2.0"] },
    fmod_negative_8_3_2_1 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", fmod(-8.3, 2.1)); return 0;", expect: ["-2.0"] },
    remainder_23_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(23, 7)); return 0;", expect: ["2.0"] },
    remainder_negative_23_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(-23, 7)); return 0;", expect: ["-2.0"] },
    remainder_7_5_2 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(7.5, 2)); return 0;", expect: ["-0.5"] },
    remainder_negative_7_5_2 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(-7.5, 2)); return 0;", expect: ["0.5"] },
    remainder_15_4 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(15, 4)); return 0;", expect: ["-1.0"] },
    remainder_negative_15_4 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(-15, 4)); return 0;", expect: ["1.0"] },
    remainder_11_3 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.1f\\n\", remainder(11, 3)); return 0;", expect: ["-1.0"] },
    remquo_23_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "int q; double r = remquo(23, 7, &q); printf(\"%d %.1f\\n\", q, r); return 0;", expect: ["3 2.0"] },
    remquo_negative_23_7 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "int q; double r = remquo(-23, 7, &q); printf(\"%d %.1f\\n\", q, r); return 0;", expect: ["-3 -2.0"] },
    remquo_15_4 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "int q; double r = remquo(15, 4, &q); printf(\"%d %.1f\\n\", q, r); return 0;", expect: ["4 -1.0"] },
    remquo_negative_15_4 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "int q; double r = remquo(-15, 4, &q); printf(\"%d %.1f\\n\", q, r); return 0;", expect: ["-4 1.0"] },
    remquo_7_5_2 => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "int q; double r = remquo(7.5, 2, &q); printf(\"%d %.1f\\n\", q, r); return 0;", expect: ["4 -0.5"] },
}
