//! Runtime checks for C math.h floating-point classification macros.

use crate::helpers::*;

c_run_cases! {
    isnan_on_log_negative => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnan(log(-1.0))); return 0;", expect: ["1"] },
    isnan_on_nan_constant => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnan(NAN)); return 0;", expect: ["1"] },
    isnan_on_finite_value => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnan(3.14)); return 0;", expect: ["0"] },
    isnan_on_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnan(1.0)); return 0;", expect: ["0"] },
    isnan_on_negative_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnan(-0.0)); return 0;", expect: ["0"] },
    isinf_on_double_huge_val => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isinf(HUGE_VAL * 2.0)); return 0;", expect: ["1"] },
    isinf_on_negative_infinity => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isinf(-1.0 / 0.0)); return 0;", expect: ["1"] },
    isinf_on_negative_huge_val => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isinf(-HUGE_VAL)); return 0;", expect: ["1"] },
    isinf_on_finite => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isinf(42.0)); return 0;", expect: ["0"] },
    isinf_on_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isinf(0.0)); return 0;", expect: ["0"] },
    isfinite_on_one_point_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isfinite(1.5)); return 0;", expect: ["1"] },
    isfinite_on_negative => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isfinite(-9.0)); return 0;", expect: ["1"] },
    isfinite_on_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isfinite(0.0)); return 0;", expect: ["1"] },
    isfinite_on_infinity => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isfinite(1.0 / 0.0)); return 0;", expect: ["0"] },
    isfinite_on_nan => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isfinite(0.0 / 0.0)); return 0;", expect: ["0"] },
    isnormal_on_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnormal(1.0)); return 0;", expect: ["1"] },
    isnormal_on_pi => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnormal(3.14159)); return 0;", expect: ["1"] },
    isnormal_on_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnormal(0.0)); return 0;", expect: ["0"] },
    isnormal_on_infinity => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnormal(1.0 / 0.0)); return 0;", expect: ["0"] },
    isnormal_on_nan => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnormal(0.0 / 0.0)); return 0;", expect: ["0"] },
    signbit_on_negative => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", signbit(-2.5)); return 0;", expect: ["1"] },
    signbit_on_positive => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", signbit(2.5)); return 0;", expect: ["0"] },
    signbit_on_negative_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", signbit(-0.0)); return 0;", expect: ["1"] },
    signbit_on_positive_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", signbit(0.0)); return 0;", expect: ["0"] },
    fpclassify_nan => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", fpclassify(0.0 / 0.0)); return 0;", expect: ["0"] },
    fpclassify_positive_infinity => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", fpclassify(1.0 / 0.0)); return 0;", expect: ["1"] },
    fpclassify_negative_infinity => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", fpclassify(-1.0 / 0.0)); return 0;", expect: ["1"] },
    fpclassify_positive_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", fpclassify(0.0)); return 0;", expect: ["2"] },
    fpclassify_negative_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", fpclassify(-0.0)); return 0;", expect: ["2"] },
    fpclassify_normal_value => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", fpclassify(2.5)); return 0;", expect: ["4"] },
    isgreater_when_left_larger => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreater(3.0, 2.0)); return 0;", expect: ["1"] },
    isgreater_when_equal => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreater(2.0, 2.0)); return 0;", expect: ["0"] },
    isgreater_when_left_smaller => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreater(1.0, 2.0)); return 0;", expect: ["0"] },
    isless_when_left_smaller => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isless(1.0, 2.0)); return 0;", expect: ["1"] },
    isless_when_equal => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isless(2.0, 2.0)); return 0;", expect: ["0"] },
    isless_when_left_larger => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isless(3.0, 2.0)); return 0;", expect: ["0"] },
    isgreaterequal_when_larger => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreaterequal(3.0, 2.0)); return 0;", expect: ["1"] },
    isgreaterequal_when_equal => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreaterequal(2.0, 2.0)); return 0;", expect: ["1"] },
    isgreaterequal_when_smaller => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreaterequal(1.0, 2.0)); return 0;", expect: ["0"] },
    islessequal_when_smaller => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", islessequal(1.0, 2.0)); return 0;", expect: ["1"] },
    islessequal_when_equal => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", islessequal(2.0, 2.0)); return 0;", expect: ["1"] },
    islessequal_when_larger => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", islessequal(3.0, 2.0)); return 0;", expect: ["0"] },
    isunordered_with_nan => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isunordered(0.0/0.0, 1.0)); return 0;", expect: ["1"] },
    isunordered_with_finite => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isunordered(1.0, 2.0)); return 0;", expect: ["0"] },
    isequal_when_same => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isequal(2.0, 2.0)); return 0;", expect: ["1"] },
    isequal_when_different => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isequal(2.0, 3.0)); return 0;", expect: ["0"] },
    isnotequal_when_different => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnotequal(2.0, 3.0)); return 0;", expect: ["1"] },
    isnotequal_when_same => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isnotequal(2.0, 2.0)); return 0;", expect: ["0"] },
    isgreater_with_negative_numbers => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isgreater(-1.0, -2.0)); return 0;", expect: ["1"] },
    isless_with_negative_numbers => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", isless(-3.0, -2.0)); return 0;", expect: ["1"] },
    signbit_on_negative_infinity => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%d\\n\", signbit(-1.0 / 0.0)); return 0;", expect: ["1"] },
}
