//! Left/right shift semantics — signed, unsigned, zero shift, bit patterns.

use crate::helpers::*;

c_run_cases! {
    unsigned_left_shift_by_one => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=5; printf(\"%u\\n\", u<<1); return 0;", expect: ["10"] },
    unsigned_left_shift_by_four => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=1; printf(\"%u\\n\", u<<4); return 0;", expect: ["16"] },
    unsigned_left_shift_zero_amount => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=42; printf(\"%u\\n\", u<<0); return 0;", expect: ["42"] },
    signed_positive_left_shift_by_two => { includes: ["<stdio.h>"], decls: "", body: "int n=3; printf(\"%d\\n\", n<<2); return 0;", expect: ["12"] },
    signed_negative_right_shift_arithmetic => { includes: ["<stdio.h>"], decls: "", body: "int n=-8; printf(\"%d\\n\", n>>1); return 0;", expect: ["-4"] },
    signed_negative_one_right_shift => { includes: ["<stdio.h>"], decls: "", body: "int n=-1; printf(\"%d\\n\", n>>1); return 0;", expect: ["-1"] },
    unsigned_right_shift_logical => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=8; printf(\"%u\\n\", u>>1); return 0;", expect: ["4"] },
    unsigned_high_bit_right_shift => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x80000000u; printf(\"%u\\n\", u>>31); return 0;", expect: ["1"] },
    left_shift_single_bit_position_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1<<0); return 0;", expect: ["1"] },
    left_shift_single_bit_position_seven => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1<<7); return 0;", expect: ["128"] },
    left_shift_single_bit_position_fifteen => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1<<15); return 0;", expect: ["32768"] },
    signed_negative_sixteen_right_shift_two => { includes: ["<stdio.h>"], decls: "", body: "int n=-16; printf(\"%d\\n\", n>>2); return 0;", expect: ["-4"] },
    unsigned_two_fifty_six_right_shift_eight => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=256; printf(\"%u\\n\", u>>8); return 0;", expect: ["0"] },
    unsigned_char_left_shift_six => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=3; printf(\"%u\\n\", (unsigned)(c<<6)); return 0;", expect: ["192"] },
    short_left_shift_three => { includes: ["<stdio.h>"], decls: "", body: "short s=2; printf(\"%d\\n\", s<<3); return 0;", expect: ["16"] },
    long_left_shift_ten => { includes: ["<stdio.h>"], decls: "", body: "long L=1; printf(\"%ld\\n\", L<<10); return 0;", expect: ["1024"] },
    chained_left_shifts => { includes: ["<stdio.h>"], decls: "", body: "int n=(1<<1)<<2; printf(\"%d\\n\", n); return 0;", expect: ["8"] },
    left_shift_then_mask_low_nibble => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=(0x0Fu<<4)&0xFFu; printf(\"%u\\n\", u); return 0;", expect: ["240"] },
    unsigned_max_right_shift_zero => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=~0u; printf(\"%u\\n\", u>>0); return 0;", expect: ["4294967295"] },
    signed_positive_right_shift_zero => { includes: ["<stdio.h>"], decls: "", body: "int n=99; printf(\"%d\\n\", n>>0); return 0;", expect: ["99"] },
    unsigned_five_left_shift_three => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=5; printf(\"%u\\n\", u<<3); return 0;", expect: ["40"] },
    unsigned_twelve_right_shift_two => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=12; printf(\"%u\\n\", u>>2); return 0;", expect: ["3"] },
    signed_thirty_two_left_shift_one => { includes: ["<stdio.h>"], decls: "", body: "int n=32; printf(\"%d\\n\", n<<1); return 0;", expect: ["64"] },
    signed_sixty_four_right_shift_three => { includes: ["<stdio.h>"], decls: "", body: "int n=64; printf(\"%d\\n\", n>>3); return 0;", expect: ["8"] },
    unsigned_pattern_aa_left_shift_four => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xAAu; printf(\"%x\\n\", u<<4); return 0;", expect: ["aa0"] },
    unsigned_pattern_f0_right_shift_four => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xF0u; printf(\"%x\\n\", u>>4); return 0;", expect: ["f"] },
    signed_negative_thirty_two_right_shift_four => { includes: ["<stdio.h>"], decls: "", body: "int n=-32; printf(\"%d\\n\", n>>4); return 0;", expect: ["-2"] },
    unsigned_one_left_shift_thirty_one => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=1u; printf(\"%u\\n\", u<<31); return 0;", expect: ["2147483648"] },
    unsigned_high_bit_left_shift_one => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x40000000u; printf(\"%u\\n\", u<<1); return 0;", expect: ["2147483648"] },
    shift_result_used_in_addition => { includes: ["<stdio.h>"], decls: "", body: "int n=(1<<3)+1; printf(\"%d\\n\", n); return 0;", expect: ["9"] },
    shift_result_used_in_subtraction => { includes: ["<stdio.h>"], decls: "", body: "int n=(16>>2)-1; printf(\"%d\\n\", n); return 0;", expect: ["3"] },
    unsigned_char_max_left_shift_zero => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=255; printf(\"%u\\n\", (unsigned)(c<<0)); return 0;", expect: ["255"] },
    unsigned_char_one_left_shift_seven => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=1; printf(\"%u\\n\", (unsigned)(c<<7)); return 0;", expect: ["128"] },
    signed_char_positive_left_shift_two => { includes: ["<stdio.h>"], decls: "", body: "signed char c=4; printf(\"%d\\n\", (int)(c<<2)); return 0;", expect: ["16"] },
    unsigned_short_left_shift_eight => { includes: ["<stdio.h>"], decls: "", body: "unsigned short s=1; printf(\"%u\\n\", (unsigned)(s<<8)); return 0;", expect: ["256"] },
    unsigned_short_ff_right_shift_four => { includes: ["<stdio.h>"], decls: "", body: "unsigned short s=0xFF; printf(\"%u\\n\", (unsigned)(s>>4)); return 0;", expect: ["15"] },
    long_right_shift_twenty => { includes: ["<stdio.h>"], decls: "", body: "long L=1048576; printf(\"%ld\\n\", L>>10); return 0;", expect: ["1024"] },
    unsigned_literal_shift_u_suffix => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%u\\n\", 3u<<2); return 0;", expect: ["12"] },
    signed_literal_shift_negative_operand => { includes: ["<stdio.h>"], decls: "", body: "int n=-4; printf(\"%d\\n\", n>>1); return 0;", expect: ["-2"] },
    unsigned_zero_left_shift_five => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0; printf(\"%u\\n\", u<<5); return 0;", expect: ["0"] },
    unsigned_zero_right_shift_five => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0; printf(\"%u\\n\", u>>5); return 0;", expect: ["0"] },
    nested_shift_expression => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=(2u<<2)>>1; printf(\"%u\\n\", u); return 0;", expect: ["4"] },
    shift_with_parenthesized_operand => { includes: ["<stdio.h>"], decls: "", body: "int a=2,b=3; printf(\"%d\\n\", (a+b)<<1); return 0;", expect: ["10"] },
    unsigned_mask_after_left_shift => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=(1u<<10)&0x3FFu; printf(\"%u\\n\", u); return 0;", expect: ["1024"] },
    unsigned_rotate_style_or_shift => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x12345678u; unsigned r=(u<<4)|(u>>28); printf(\"%x\\n\", r); return 0;", expect: ["23456781"] },
    signed_negative_hundred_twenty_eight_right_shift => { includes: ["<stdio.h>"], decls: "", body: "int n=-128; printf(\"%d\\n\", n>>7); return 0;", expect: ["-1"] },
    unsigned_ff_left_shift_eight_masked => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=(0xFFu<<8)&0xFFFFu; printf(\"%u\\n\", u); return 0;", expect: ["65280"] },
    shift_in_conditional_expression => { includes: ["<stdio.h>"], decls: "", body: "int n=1? (2<<2):0; printf(\"%d\\n\", n); return 0;", expect: ["8"] },
    compound_left_shift_assign => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=3; u<<=2; printf(\"%u\\n\", u); return 0;", expect: ["12"] },
    compound_right_shift_assign => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=24; u>>=2; printf(\"%u\\n\", u); return 0;", expect: ["6"] },
    signed_eight_left_shift_zero => { includes: ["<stdio.h>"], decls: "", body: "int n=8; printf(\"%d\\n\", n<<0); return 0;", expect: ["8"] },
    unsigned_deadbeef_right_shift_sixteen => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xDEADBEEFu; printf(\"%x\\n\", u>>16); return 0;", expect: ["dead"] },
    unsigned_low_byte_extract_via_shift => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xABCDu; printf(\"%x\\n\", (u>>8)&0xFFu); return 0;", expect: ["ab"] },
    signed_positive_large_left_shift_one => { includes: ["<stdio.h>"], decls: "", body: "int n=0x4000; printf(\"%d\\n\", n<<1); return 0;", expect: ["32768"] },
}
