//! Additional language runtime semantics — one rule per test.

c_run_cases! {
    add_assign_int => { includes: ["<stdio.h>"], decls: "", body: "int n=1; n+=4; printf(\"%d\\n\", n); return 0;", expect: ["5"] },
    sub_assign_int => { includes: ["<stdio.h>"], decls: "", body: "int n=5; n-=2; printf(\"%d\\n\", n); return 0;", expect: ["3"] },
    mul_assign_int => { includes: ["<stdio.h>"], decls: "", body: "int n=3; n*=3; printf(\"%d\\n\", n); return 0;", expect: ["9"] },
    div_assign_int => { includes: ["<stdio.h>"], decls: "", body: "int n=8; n/=2; printf(\"%d\\n\", n); return 0;", expect: ["4"] },
    mod_assign_int => { includes: ["<stdio.h>"], decls: "", body: "int n=10; n%=3; printf(\"%d\\n\", n); return 0;", expect: ["1"] },
    and_assign_bit => { includes: ["<stdio.h>"], decls: "", body: "int n=7; n&=3; printf(\"%d\\n\", n); return 0;", expect: ["3"] },
    or_assign_bit => { includes: ["<stdio.h>"], decls: "", body: "int n=1; n|=4; printf(\"%d\\n\", n); return 0;", expect: ["5"] },
    xor_assign_bit => { includes: ["<stdio.h>"], decls: "", body: "int n=6; n^=3; printf(\"%d\\n\", n); return 0;", expect: ["5"] },
    shl_assign_bit => { includes: ["<stdio.h>"], decls: "", body: "int n=1; n<<=2; printf(\"%d\\n\", n); return 0;", expect: ["4"] },
    shr_assign_bit => { includes: ["<stdio.h>"], decls: "", body: "int n=8; n>>=1; printf(\"%d\\n\", n); return 0;", expect: ["4"] },
    postfix_dec => { includes: ["<stdio.h>"], decls: "", body: "int n=2; int m=n--; printf(\"%d %d\\n\", m, n); return 0;", expect: ["2 1"] },
    prefix_dec => { includes: ["<stdio.h>"], decls: "", body: "int n=2; int m=--n; printf(\"%d %d\\n\", m, n); return 0;", expect: ["1 1"] },
    logical_and_result => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1 && 0); return 0;", expect: ["0"] },
    logical_or_result => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0 || 1); return 0;", expect: ["1"] },
    equality_ints => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 3==3); return 0;", expect: ["1"] },
    inequality_ints => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 3!=4); return 0;", expect: ["1"] },
    less_than => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 2<5); return 0;", expect: ["1"] },
    greater_equal => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 5>=5); return 0;", expect: ["1"] },
    negation_int => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -3); return 0;", expect: ["-3"] },
    bitwise_not_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", ~0 & 1); return 0;", expect: ["1"] },
    cast_char_to_int => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (int)'0'); return 0;", expect: ["48"] },
    sizeof_pointer => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (int)sizeof(int*)); return 0;", expect: ["8"] },
    sizeof_array_not_pointer => { includes: ["<stdio.h>"], decls: "", body: "int a[4]; printf(\"%d\\n\", (int)sizeof(a)); return 0;", expect: ["16"] },
    string_literal_sizeof_includes_nul => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (int)sizeof(\"ab\")); return 0;", expect: ["3"] },
    struct_sizeof => { includes: ["<stdio.h>"], decls: "struct S { char c; int n; };", body: "printf(\"%d\\n\", (int)sizeof(struct S)); return 0;", expect: ["8"] },
    union_sizeof_max_member => { includes: ["<stdio.h>"], decls: "union U { char c; int n; };", body: "printf(\"%d\\n\", (int)sizeof(union U)); return 0;", expect: ["4"] },
    enum_sizeof_int => { includes: ["<stdio.h>"], decls: "enum E { A };", body: "printf(\"%d\\n\", (int)sizeof(enum E)); return 0;", expect: ["4"] },
    function_pointer_sizeof => { includes: ["<stdio.h>"], decls: "int f(int);", body: "printf(\"%d\\n\", (int)sizeof(&f)); return 0;", expect: ["8"] },
    null_pointer_constant_zero => { includes: ["<stdio.h>"], decls: "", body: "int *p=0; printf(\"%d\\n\", p==NULL); return 0;", expect: ["1"] },
    array_index_from_end_via_pointer => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; int *e=a+2; printf(\"%d\\n\", *e); return 0;", expect: ["3"] },
    struct_assignment_copies => { includes: ["<stdio.h>"], decls: "struct S{int v;};", body: "struct S a={1},b; b=a; printf(\"%d\\n\", b.v); return 0;", expect: ["1"] },
    nested_block_scope => { includes: ["<stdio.h>"], decls: "", body: "{ int x=1; { int y=2; x=y; } } printf(\"%d\\n\", 1); return 0;", expect: ["1"] },
    for_empty_body => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<0;i++){} printf(\"%d\\n\", i); return 0;", expect: ["0"] },
    while_zero_iterations => { includes: ["<stdio.h>"], decls: "", body: "int i=0; while(i<0) i++; printf(\"%d\\n\", i); return 0;", expect: ["0"] },
    switch_first_case => { includes: ["<stdio.h>"], decls: "", body: "switch(1){case 1: printf(\"1\\n\"); break; default: printf(\"d\\n\");} return 0;", expect: ["1"] },
    switch_last_case => { includes: ["<stdio.h>"], decls: "", body: "switch(3){case 1: break; case 3: printf(\"3\\n\"); break;} return 0;", expect: ["3"] },
    if_without_else => { includes: ["<stdio.h>"], decls: "", body: "if(1) printf(\"y\\n\"); return 0;", expect: ["y"] },
    else_branch_taken => { includes: ["<stdio.h>"], decls: "", body: "if(0) printf(\"a\\n\"); else printf(\"b\\n\"); return 0;", expect: ["b"] },
    function_call_args_left_to_right => { includes: ["<stdio.h>"], decls: "int f(int a,int b){return a*10+b;}", body: "printf(\"%d\\n\", f(2,3)); return 0;", expect: ["23"] },
    recursive_factorial_small => { includes: ["<stdio.h>"], decls: "int fact(int n){return n<=1?1:n*fact(n-1);}", body: "printf(\"%d\\n\", fact(5)); return 0;", expect: ["120"] },
    static_local_counter => { includes: ["<stdio.h>"], decls: "int inc(void){static int c=0; return ++c;}", body: "printf(\"%d\\n\", inc()+inc()); return 0;", expect: ["3"] },
    extern_int_linkage => { includes: ["<stdio.h>"], decls: "int g=11;", body: "printf(\"%d\\n\", g); return 0;", expect: ["11"] },
    const_int_read => { includes: ["<stdio.h>"], decls: "const int k=6;", body: "printf(\"%d\\n\", k); return 0;", expect: ["6"] },
    volatile_int_read => { includes: ["<stdio.h>"], decls: "volatile int v=8;", body: "printf(\"%d\\n\", v); return 0;", expect: ["8"] },
    typedef_preserves_semantics => { includes: ["<stdio.h>"], decls: "typedef int myint;", body: "myint x=4; printf(\"%d\\n\", x); return 0;", expect: ["4"] },
    enum_compare => { includes: ["<stdio.h>"], decls: "enum E{A,B};", body: "enum E e=B; printf(\"%d\\n\", e==B); return 0;", expect: ["1"] },
    pointer_to_struct_member => { includes: ["<stdio.h>"], decls: "struct S{int n;};", body: "struct S s={2}; int *p=&s.n; printf(\"%d\\n\", *p); return 0;", expect: ["2"] },
    array_decay_in_assignment => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={3,4}; int *p=a; printf(\"%d\\n\", p[1]); return 0;", expect: ["4"] },
    char_array_string => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"z\"; printf(\"%s\\n\", s); return 0;", expect: ["z"] },
    int_array_init_braces => { includes: ["<stdio.h>"], decls: "", body: "int a[]={9}; printf(\"%d\\n\", a[0]); return 0;", expect: ["9"] },
    multidim_init => { includes: ["<stdio.h>"], decls: "", body: "int m[2][2]={{1,2},{3,4}}; printf(\"%d\\n\", m[1][0]); return 0;", expect: ["3"] },
    question_colon_precedence => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1?2:3); return 0;", expect: ["2"] },
    comma_operator_in_expression => { includes: ["<stdio.h>"], decls: "", body: "int x=(1,2); printf(\"%d\\n\", x); return 0;", expect: ["2"] },
}
