//! inttypes printf/scan macros and misc headers — one macro/API per test.


c_compile_cases! {
    prid8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int8_t v=1; printf(\"%\" PRId8, v); return 0;" },
    prid16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int16_t v=1; printf(\"%\" PRId16, v); return 0;" },
    prid32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int32_t v=1; printf(\"%\" PRId32, v); return 0;" },
    prid64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int64_t v=1; printf(\"%\" PRId64, v); return 0;" },
    prii8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int8_t v=1; printf(\"%\" PRIi8, v); return 0;" },
    prii16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int16_t v=1; printf(\"%\" PRIi16, v); return 0;" },
    prii32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int32_t v=1; printf(\"%\" PRIi32, v); return 0;" },
    prii64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int64_t v=1; printf(\"%\" PRIi64, v); return 0;" },
    priu8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=1; printf(\"%\" PRIu8, v); return 0;" },
    priu16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=1; printf(\"%\" PRIu16, v); return 0;" },
    priu32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=1; printf(\"%\" PRIu32, v); return 0;" },
    priu64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=1; printf(\"%\" PRIu64, v); return 0;" },
    prix8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=15; printf(\"%\" PRIx8, v); return 0;" },
    prix16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=15; printf(\"%\" PRIx16, v); return 0;" },
    prix32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=15; printf(\"%\" PRIx32, v); return 0;" },
    prix64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=15; printf(\"%\" PRIx64, v); return 0;" },
    scnd8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int8_t v=0; sscanf(\"1\", \"%\" SCNd8, &v); return v;" },
    scnd16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int16_t v=0; sscanf(\"1\", \"%\" SCNd16, &v); return v;" },
    scnd32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int32_t v=0; sscanf(\"1\", \"%\" SCNd32, &v); return v;" },
    scnd64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int64_t v=0; sscanf(\"1\", \"%\" SCNd64, &v); return v;" },
    scni8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int8_t v=0; sscanf(\"1\", \"%\" SCNi8, &v); return v;" },
    scni16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int16_t v=0; sscanf(\"1\", \"%\" SCNi16, &v); return v;" },
    scni32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int32_t v=0; sscanf(\"1\", \"%\" SCNi32, &v); return v;" },
    scni64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int64_t v=0; sscanf(\"1\", \"%\" SCNi64, &v); return v;" },
    scnu8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=0; sscanf(\"1\", \"%\" SCNu8, &v); return v;" },
    scnu16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=0; sscanf(\"1\", \"%\" SCNu16, &v); return v;" },
    scnu32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=0; sscanf(\"1\", \"%\" SCNu32, &v); return v;" },
    scnu64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=0; sscanf(\"1\", \"%\" SCNu64, &v); return v;" },
    scnx8_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=0; sscanf(\"f\", \"%\" SCNx8, &v); return v;" },
    scnx16_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=0; sscanf(\"f\", \"%\" SCNx16, &v); return v;" },
    scnx32_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=0; sscanf(\"f\", \"%\" SCNx32, &v); return v;" },
    scnx64_macro => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=0; sscanf(\"f\", \"%\" SCNx64, &v); return v;" },
    int8_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return INT8_C(1);" },
    int16_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return INT16_C(1);" },
    int32_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return INT32_C(1);" },
    int64_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return INT64_C(1);" },
    uint8_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return UINT8_C(1);" },
    uint16_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return UINT16_C(1);" },
    uint32_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return UINT32_C(1);" },
    uint64_c_macro => { includes: ["<stdint.h>"], decls: "", body: "return UINT64_C(1);" },
    int_least8_width => { includes: ["<stdint.h>"], decls: "", body: "return INT_LEAST8_WIDTH;" },
    int_fast16_width => { includes: ["<stdint.h>"], decls: "", body: "return INT_FAST16_WIDTH;" },
    uintptr_max => { includes: ["<stdint.h>"], decls: "", body: "return UINTPTR_MAX > 0;" },
    intmax_min => { includes: ["<stdint.h>"], decls: "", body: "return INTMAX_MIN < 0;" },
    uintmax_max => { includes: ["<stdint.h>"], decls: "", body: "return UINTMAX_MAX > 0;" },
}
