//! Usual arithmetic conversions — mixed signed/unsigned, char promoted to int.


c_run_cases! {
    char_plus_char_promotes_to_int => { includes: ["<stdio.h>"], decls: "", body: "char a='1', b='2'; printf(\"%d\\n\", a+b); return 0;", expect: ["99"] },
    char_minus_char_promotes_to_int => { includes: ["<stdio.h>"], decls: "", body: "char a='d', b='a'; printf(\"%d\\n\", a-b); return 0;", expect: ["3"] },
    char_multiply_char_promotes => { includes: ["<stdio.h>"], decls: "", body: "char a=6, b=7; printf(\"%d\\n\", a*b); return 0;", expect: ["42"] },
    char_plus_int_yields_int => { includes: ["<stdio.h>"], decls: "", body: "char c=10; int n=5; printf(\"%d\\n\", c+n); return 0;", expect: ["15"] },
    int_plus_char_yields_int => { includes: ["<stdio.h>"], decls: "", body: "int n=20; char c=3; printf(\"%d\\n\", n+c); return 0;", expect: ["23"] },
    short_plus_int_promotes_short => { includes: ["<stdio.h>"], decls: "", body: "short s=100; int n=50; printf(\"%d\\n\", s+n); return 0;", expect: ["150"] },
    unsigned_short_plus_int => { includes: ["<stdio.h>"], decls: "", body: "unsigned short us=200; int n=50; printf(\"%u\\n\", us+n); return 0;", expect: ["250"] },
    signed_char_negative_plus_int => { includes: ["<stdio.h>"], decls: "", body: "signed char sc=-5; int n=10; printf(\"%d\\n\", n+sc); return 0;", expect: ["5"] },
    unsigned_char_plus_unsigned_char => { includes: ["<stdio.h>"], decls: "", body: "unsigned char a=200, b=50; printf(\"%u\\n\", (unsigned)(a+b)); return 0;", expect: ["250"] },
    char_literal_arithmetic_value => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 'A'+1); return 0;", expect: ["66"] },
    char_subtract_to_get_index => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", '5'-'0'); return 0;", expect: ["5"] },
    int_plus_unsigned_yields_unsigned => { includes: ["<stdio.h>"], decls: "", body: "int n=3; unsigned u=5u; printf(\"%u\\n\", n+u); return 0;", expect: ["8"] },
    unsigned_plus_negative_int_wraps => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=10u; int n=-3; printf(\"%u\\n\", u+n); return 0;", expect: ["7"] },
    signed_minus_unsigned_converts => { includes: ["<stdio.h>"], decls: "", body: "int n=5; unsigned u=10u; printf(\"%d\\n\", n-u); return 0;", expect: ["-5"] },
    unsigned_minus_smaller_signed => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=20u; int n=5; printf(\"%u\\n\", u-n); return 0;", expect: ["15"] },
    long_plus_int_promotes_to_long => { includes: ["<stdio.h>"], decls: "", body: "long L=100000; int n=23456; printf(\"%ld\\n\", L+n); return 0;", expect: ["123456"] },
    int_plus_long_promotes_to_long => { includes: ["<stdio.h>"], decls: "", body: "int n=1000; long L=2000; printf(\"%ld\\n\", n+L); return 0;", expect: ["3000"] },
    unsigned_long_plus_int => { includes: ["<stdio.h>"], decls: "", body: "unsigned long ul=100; int n=7; printf(\"%lu\\n\", ul+n); return 0;", expect: ["107"] },
    float_plus_int_promotes_int => { includes: ["<stdio.h>"], decls: "", body: "float f=2.5f; int n=2; printf(\"%.1f\\n\", f+n); return 0;", expect: ["4.5"] },
    double_plus_float_promotes_float => { includes: ["<stdio.h>"], decls: "", body: "double d=1.5; float f=1.5f; printf(\"%.1f\\n\", d+f); return 0;", expect: ["3.0"] },
    char_division_promotes_to_int => { includes: ["<stdio.h>"], decls: "", body: "char a=20, b=4; printf(\"%d\\n\", a/b); return 0;", expect: ["5"] },
    char_modulo_promotes_to_int => { includes: ["<stdio.h>"], decls: "", body: "char a=17, b=5; printf(\"%d\\n\", a%b); return 0;", expect: ["2"] },
    usual_arithmetic_int_and_double => { includes: ["<stdio.h>"], decls: "", body: "int n=2; double d=2.5; printf(\"%.1f\\n\", n+d); return 0;", expect: ["4.5"] },
    usual_arithmetic_unsigned_and_double => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=4u; double d=0.5; printf(\"%.1f\\n\", u*d); return 0;", expect: ["2.0"] },
    enum_plus_int_promotes_enum => { includes: ["<stdio.h>"], decls: "enum E{BASE=10};", body: "enum E e=BASE; printf(\"%d\\n\", e+5); return 0;", expect: ["15"] },
    enum_minus_enum_yields_int => { includes: ["<stdio.h>"], decls: "enum E{A=1,B=4};", body: "enum E x=B, y=A; printf(\"%d\\n\", x-y); return 0;", expect: ["3"] },
    bool_in_arithmetic_promotes => { includes: ["<stdio.h>"], decls: "", body: "int t=1, f=0; printf(\"%d\\n\", t+f+1); return 0;", expect: ["2"] },
    unary_plus_on_char => { includes: ["<stdio.h>"], decls: "", body: "char c=7; printf(\"%d\\n\", +c); return 0;", expect: ["7"] },
    unary_minus_on_char => { includes: ["<stdio.h>"], decls: "", body: "char c=7; printf(\"%d\\n\", -c); return 0;", expect: ["-7"] },
    char_shift_promotes_to_int => { includes: ["<stdio.h>"], decls: "", body: "char c=1; printf(\"%d\\n\", c<<4); return 0;", expect: ["16"] },
    unsigned_char_in_comparison_with_int => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=255; printf(\"%d\\n\", c>200); return 0;", expect: ["1"] },
    signed_char_negative_in_addition => { includes: ["<stdio.h>"], decls: "", body: "signed char c=-1; int n=10; printf(\"%d\\n\", n+c); return 0;", expect: ["9"] },
    short_multiply_int => { includes: ["<stdio.h>"], decls: "", body: "short s=12; int n=3; printf(\"%d\\n\", s*n); return 0;", expect: ["36"] },
    int_divide_unsigned => { includes: ["<stdio.h>"], decls: "", body: "int n=10; unsigned u=3u; printf(\"%u\\n\", n/u); return 0;", expect: ["3"] },
    unsigned_divide_int => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=10u; int n=3; printf(\"%u\\n\", u/n); return 0;", expect: ["3"] },
    mixed_width_unsigned_int_add => { includes: ["<stdio.h>"], decls: "", body: "unsigned char uc=100; unsigned int ui=100; printf(\"%u\\n\", uc+ui); return 0;", expect: ["200"] },
    char_in_ternary_with_int => { includes: ["<stdio.h>"], decls: "", body: "char c=5; int n=10; printf(\"%d\\n\", c<n?c:n); return 0;", expect: ["5"] },
    promotion_in_array_index => { includes: ["<stdio.h>"], decls: "", body: "int a[10]={0}; char i=3; a[i]=42; printf(\"%d\\n\", a[3]); return 0;", expect: ["42"] },
    char_bitwise_and_with_int => { includes: ["<stdio.h>"], decls: "", body: "char c=0xF0; int m=0x0F; printf(\"%x\\n\", c&m); return 0;", expect: ["0"] },
    char_bitwise_or_with_int => { includes: ["<stdio.h>"], decls: "", body: "char c=0x0F; int m=0xF0; printf(\"%x\\n\", c|m); return 0;", expect: ["ff"] },
    promotion_preserves_value_in_printf => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=65; printf(\"%c\\n\", c); return 0;", expect: ["A"] },
    wchar_not_in_scope_char_stays => { includes: ["<stdio.h>"], decls: "", body: "char c='z'; printf(\"%d\\n\", c); return 0;", expect: ["122"] },
    int_constant_plus_char_variable => { includes: ["<stdio.h>"], decls: "", body: "char c=2; printf(\"%d\\n\", 10+c); return 0;", expect: ["12"] },
    unsigned_int_minus_char => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=50u; char c=8; printf(\"%u\\n\", u-c); return 0;", expect: ["42"] },
    long_double_literal_with_int => { includes: ["<stdio.h>"], decls: "", body: "int n=1; printf(\"%.1Lf\\n\", 2.0L+n); return 0;", expect: ["3.0"] },
    nested_promotion_in_expression => { includes: ["<stdio.h>"], decls: "", body: "char a=2,b=3; printf(\"%d\\n\", a*b+4); return 0;", expect: ["10"] },
    promotion_with_parentheses => { includes: ["<stdio.h>"], decls: "", body: "char a=5,b=2; printf(\"%d\\n\", (a+b)*2); return 0;", expect: ["14"] },
    unsigned_promotion_in_subtraction_wrap => { includes: ["<stdio.h>"], decls: "", body: "unsigned char uc=0; int n=1; printf(\"%u\\n\", (unsigned)(uc-n)); return 0;", expect: ["4294967295"] },
    char_compare_promotes_for_equality => { includes: ["<stdio.h>"], decls: "", body: "char c=65; printf(\"%d\\n\", c==65); return 0;", expect: ["1"] },
    short_promoted_in_shift_with_int => { includes: ["<stdio.h>"], decls: "", body: "short s=1; int n=4; printf(\"%d\\n\", s<<n); return 0;", expect: ["16"] },
    int_promoted_to_float_in_division => { includes: ["<stdio.h>"], decls: "", body: "int n=7; float f=2.0f; printf(\"%.1f\\n\", n/f); return 0;", expect: ["3.5"] },
    usual_conversion_in_compound_add => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=10; c+=5; printf(\"%u\\n\", (unsigned)c); return 0;", expect: ["15"] },
    usual_conversion_in_compound_mul => { includes: ["<stdio.h>"], decls: "", body: "char c=6; c*=2; printf(\"%d\\n\", (int)c); return 0;", expect: ["12"] },
    promotion_in_function_argument => {
        includes: ["<stdio.h>"],
        decls: "int add(int a, int b){ return a+b; }",
        body: "char x=4,y=5; printf(\"%d\\n\", add(x,y)); return 0;",
        expect: ["9"]
    },
    default_argument_promotion_char => {
        includes: ["<stdio.h>"],
        decls: "int twice(int v){ return v*2; }",
        body: "char c=11; printf(\"%d\\n\", twice(c)); return 0;",
        expect: ["22"]
    },
}
