//! Relational and equality operators — ints, unsigned wrap, pointers.


c_run_cases! {
    int_equality_true => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 7==7); return 0;", expect: ["1"] },
    int_equality_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 7==8); return 0;", expect: ["0"] },
    int_inequality_true => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 3!=5); return 0;", expect: ["1"] },
    int_inequality_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 3!=3); return 0;", expect: ["0"] },
    int_less_than_true => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 2<9); return 0;", expect: ["1"] },
    int_less_than_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 9<2); return 0;", expect: ["0"] },
    int_greater_than_true => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 10>4); return 0;", expect: ["1"] },
    int_greater_than_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 4>10); return 0;", expect: ["0"] },
    int_less_equal_true_equal => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 5<=5); return 0;", expect: ["1"] },
    int_less_equal_true_less => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 3<=7); return 0;", expect: ["1"] },
    int_less_equal_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 8<=2); return 0;", expect: ["0"] },
    int_greater_equal_true_equal => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 6>=6); return 0;", expect: ["1"] },
    int_greater_equal_true_greater => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 9>=1); return 0;", expect: ["1"] },
    int_greater_equal_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1>=9); return 0;", expect: ["0"] },
    negative_int_less_than_positive => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1<1); return 0;", expect: ["1"] },
    negative_int_greater_than_more_negative => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1>-5); return 0;", expect: ["1"] },
    zero_equal_to_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0==0); return 0;", expect: ["1"] },
    zero_less_than_one => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0<1); return 0;", expect: ["1"] },
    unsigned_max_greater_than_zero => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=~0u; printf(\"%d\\n\", u>0u); return 0;", expect: ["1"] },
    unsigned_wrap_minus_one_greater_than_zero => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=(unsigned)-1; printf(\"%d\\n\", u>0u); return 0;", expect: ["1"] },
    signed_minus_one_less_than_unsigned_one => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1<1u); return 0;", expect: ["0"] },
    signed_minus_one_greater_than_unsigned_one => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1>1u); return 0;", expect: ["1"] },
    unsigned_one_less_than_signed_minus_one => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1u<-1); return 0;", expect: ["1"] },
    mixed_unsigned_signed_equality_false => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1==1u); return 0;", expect: ["0"] },
    unsigned_short_wrap_compare => { includes: ["<stdio.h>"], decls: "", body: "unsigned short a=65535, b=0; printf(\"%d\\n\", a>b); return 0;", expect: ["1"] },
    unsigned_char_max_vs_zero => { includes: ["<stdio.h>"], decls: "", body: "unsigned char a=255, b=0; printf(\"%d\\n\", a>b); return 0;", expect: ["1"] },
    pointer_same_address_equal => { includes: ["<stdio.h>"], decls: "", body: "int x=1; int *a=&x, *b=&x; printf(\"%d\\n\", a==b); return 0;", expect: ["1"] },
    pointer_different_address_not_equal => { includes: ["<stdio.h>"], decls: "", body: "int a=1,b=2; printf(\"%d\\n\", &a==&b); return 0;", expect: ["0"] },
    pointer_less_than_same_array_elements => { includes: ["<stdio.h>"], decls: "", body: "int arr[3]={1,2,3}; printf(\"%d\\n\", &arr[0]<&arr[2]); return 0;", expect: ["1"] },
    pointer_greater_than_same_array_elements => { includes: ["<stdio.h>"], decls: "", body: "int arr[3]={1,2,3}; printf(\"%d\\n\", &arr[2]>&arr[0]); return 0;", expect: ["1"] },
    null_pointer_equals_zero => { includes: ["<stdio.h>"], decls: "", body: "int *p=0; printf(\"%d\\n\", p==0); return 0;", expect: ["1"] },
    null_pointer_not_equal_nonzero => { includes: ["<stdio.h>"], decls: "", body: "int x=0; int *p=&x; printf(\"%d\\n\", p!=0); return 0;", expect: ["1"] },
    array_name_equals_pointer_to_first => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={1,2}; printf(\"%d\\n\", a==&a[0]); return 0;", expect: ["1"] },
    array_decay_equality_with_indexed => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; int *p=a; printf(\"%d\\n\", p==a+0); return 0;", expect: ["1"] },
    pointer_offset_not_equal_base => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={1,2}; printf(\"%d\\n\", a==a+1); return 0;", expect: ["0"] },
    void_pointer_cast_compare_equal => { includes: ["<stdio.h>"], decls: "", body: "int x=5; int *ip=&x; void *vp=ip; printf(\"%d\\n\", ip==vp); return 0;", expect: ["1"] },
    char_pointer_compare_ordering => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"ab\"; printf(\"%d\\n\", &s[0]<&s[1]); return 0;", expect: ["1"] },
    struct_member_address_compare => { includes: ["<stdio.h>"], decls: "struct S{int a; int b;};", body: "struct S s; printf(\"%d\\n\", &s.a<&s.b); return 0;", expect: ["1"] },
    function_pointer_equal_to_self => { includes: ["<stdio.h>"], decls: "int id(int x){return x;}", body: "int (*fp)(int)=id; printf(\"%d\\n\", fp==id); return 0;", expect: ["1"] },
    int_equal_after_arithmetic => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 2+3==5); return 0;", expect: ["1"] },
    int_not_equal_after_arithmetic => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 2+3==6); return 0;", expect: ["0"] },
    relational_chain_less_and_less => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1<2 && 2<3); return 0;", expect: ["1"] },
    relational_chain_greater_and_greater => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 5>3 && 3>1); return 0;", expect: ["1"] },
    equality_of_chars_as_ints => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 'A'=='A'); return 0;", expect: ["1"] },
    char_less_than_next_letter => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 'a'<'b'); return 0;", expect: ["1"] },
    enum_constant_equality => { includes: ["<stdio.h>"], decls: "enum E{RED=1, GREEN=2};", body: "enum E e=GREEN; printf(\"%d\\n\", e==2); return 0;", expect: ["1"] },
    enum_less_than_higher_value => { includes: ["<stdio.h>"], decls: "enum E{LOW=0, HIGH=10};", body: "enum E e=LOW; printf(\"%d\\n\", e<HIGH); return 0;", expect: ["1"] },
    long_equal_long => { includes: ["<stdio.h>"], decls: "", body: "long a=100000, b=100000; printf(\"%d\\n\", a==b); return 0;", expect: ["1"] },
    unsigned_long_less_than => { includes: ["<stdio.h>"], decls: "", body: "unsigned long a=5, b=9; printf(\"%d\\n\", a<b); return 0;", expect: ["1"] },
    double_equal_after_cast_truncation => { includes: ["<stdio.h>"], decls: "", body: "double d=3.9; printf(\"%d\\n\", (int)d==3); return 0;", expect: ["1"] },
    pointer_not_equal_after_increment => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={1,2}; int *p=a; printf(\"%d\\n\", p!=p+1); return 0;", expect: ["1"] },
    null_not_equal_dereferenced_address => { includes: ["<stdio.h>"], decls: "", body: "int x=0; int *p=&x; printf(\"%d\\n\", p!=NULL); return 0;", expect: ["1"] },
    unsigned_zero_equal_signed_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0u==0); return 0;", expect: ["1"] },
    signed_negative_equal_self => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -42==-42); return 0;", expect: ["1"] },
    int_less_equal_after_promotion => { includes: ["<stdio.h>"], decls: "", body: "char a=3; int b=3; printf(\"%d\\n\", a<=b); return 0;", expect: ["1"] },
}
