//! Logical && and || — short-circuit evaluation with observable side effects.


c_run_cases! {
    and_skips_rhs_when_lhs_false => { includes: ["<stdio.h>"], decls: "int side=0;", body: "if(0 && (side=1)){} printf(\"%d\\n\", side); return 0;", expect: ["0"] },
    and_evaluates_rhs_when_lhs_true => { includes: ["<stdio.h>"], decls: "int side=0;", body: "if(1 && (side=1)){} printf(\"%d\\n\", side); return 0;", expect: ["1"] },
    or_skips_rhs_when_lhs_true => { includes: ["<stdio.h>"], decls: "int side=0;", body: "if(1 || (side=1)){} printf(\"%d\\n\", side); return 0;", expect: ["0"] },
    or_evaluates_rhs_when_lhs_false => { includes: ["<stdio.h>"], decls: "int side=0;", body: "if(0 || (side=1)){} printf(\"%d\\n\", side); return 0;", expect: ["1"] },
    and_result_zero_when_lhs_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0 && 5); return 0;", expect: ["0"] },
    and_result_one_when_both_nonzero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 3 && 4); return 0;", expect: ["1"] },
    or_result_one_when_lhs_nonzero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 2 || 0); return 0;", expect: ["1"] },
    or_result_zero_when_both_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0 || 0); return 0;", expect: ["0"] },
    not_zero_is_one => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", !0); return 0;", expect: ["1"] },
    not_nonzero_is_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", !7); return 0;", expect: ["0"] },
    double_not_restores_truthiness => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", !!0); return 0;", expect: ["0"] },
    and_chain_short_circuit_middle => { includes: ["<stdio.h>"], decls: "int c=0;", body: "int r = 1 && 0 && (c=1); printf(\"%d %d\\n\", r, c); return 0;", expect: ["0 0"] },
    or_chain_short_circuit_middle => { includes: ["<stdio.h>"], decls: "int c=0;", body: "int r = 0 || 1 || (c=1); printf(\"%d %d\\n\", r, c); return 0;", expect: ["1 0"] },
    and_with_comparison_operands => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (2<3) && (5>1)); return 0;", expect: ["1"] },
    or_with_comparison_operands => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (2>3) || (5>1)); return 0;", expect: ["1"] },
    and_pointer_null_check => { includes: ["<stdio.h>"], decls: "", body: "int *p=0; printf(\"%d\\n\", p && *p); return 0;", expect: ["0"] },
    and_pointer_nonnull_short_circuit => { includes: ["<stdio.h>"], decls: "", body: "int x=4; int *p=&x; printf(\"%d\\n\", p && *p==4); return 0;", expect: ["1"] },
    or_null_coalesce_pattern => { includes: ["<stdio.h>"], decls: "", body: "int *p=0; int *q=&(int){9}; int v = p ? *p : *q; printf(\"%d\\n\", v); return 0;", expect: ["9"] },
    logical_in_while_condition => { includes: ["<stdio.h>"], decls: "int i=0,s=0;", body: "while(i<2 && (s+=1)) i++; printf(\"%d\\n\", s); return 0;", expect: ["2"] },
    logical_in_for_condition => { includes: ["<stdio.h>"], decls: "int s=0;", body: "for(int i=0; i<3 && (s+=i); i++){} printf(\"%d\\n\", s); return 0;", expect: ["0"] },
    logical_in_ternary_guard => { includes: ["<stdio.h>"], decls: "", body: "int x=0; int v = 1 && (x=5) ? x : 0; printf(\"%d\\n\", v); return 0;", expect: ["5"] },
    and_with_assign_side_effect_once => { includes: ["<stdio.h>"], decls: "int n=0;", body: "int r = (n=1) && (n=2); printf(\"%d %d\\n\", r, n); return 0;", expect: ["1 2"] },
    or_with_assign_side_effect_once => { includes: ["<stdio.h>"], decls: "int n=0;", body: "int r = (n=1) || (n=2); printf(\"%d %d\\n\", r, n); return 0;", expect: ["1 1"] },
    nested_and_or_precedence => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1 || 0 && 0); return 0;", expect: ["1"] },
    nested_or_and_precedence => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0 && 1 || 1); return 0;", expect: ["1"] },
    not_of_and_expression => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", !(1 && 1)); return 0;", expect: ["0"] },
    not_of_or_expression => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", !(0 || 0)); return 0;", expect: ["1"] },
    and_with_char_promoted => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 'A' && 'B'); return 0;", expect: ["1"] },
    or_with_zero_char => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", '\\0' || 'x'); return 0;", expect: ["1"] },
    and_float_nonzero_truthy => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0.5 && 1.0); return 0;", expect: ["1"] },
    or_float_zero_falsy => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0.0 || 3.0); return 0;", expect: ["1"] },
    and_negative_int_truthy => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1 && 2); return 0;", expect: ["1"] },
    or_negative_int_truthy => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -1 || 0); return 0;", expect: ["1"] },
    and_in_switch_condition => { includes: ["<stdio.h>"], decls: "", body: "switch(1 && 2){case 1: printf(\"no\\n\"); break; default: printf(\"yes\\n\");} return 0;", expect: ["no"] },
    or_in_if_else_chain => { includes: ["<stdio.h>"], decls: "", body: "if(0 || 0) printf(\"a\\n\"); else printf(\"b\\n\"); return 0;", expect: ["b"] },
    and_rhs_function_call_counted => {
        includes: ["<stdio.h>"],
        decls: "int c=0; int bump(void){return ++c;}",
        body: "int r = 0 && bump(); printf(\"%d %d\\n\", r, c); return 0;",
        expect: ["0 0"]
    },
    or_rhs_function_call_counted => {
        includes: ["<stdio.h>"],
        decls: "int c=0; int bump(void){return ++c;}",
        body: "int r = 1 || bump(); printf(\"%d %d\\n\", r, c); return 0;",
        expect: ["1 0"]
    },
    and_with_bitwise_not_operand => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", !0 && ~0); return 0;", expect: ["1"] },
    or_with_bitwise_zero_operand => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0 | 0 || 1); return 0;", expect: ["1"] },
    logical_result_used_in_addition => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (1 && 1) + (0 || 1)); return 0;", expect: ["2"] },
    logical_result_stored_in_int => { includes: ["<stdio.h>"], decls: "", body: "int a=2&&3, b=0||4; printf(\"%d %d\\n\", a, b); return 0;", expect: ["1 1"] },
    and_empty_rhs_not_evaluated => { includes: ["<stdio.h>"], decls: "int x=1;", body: "int r = 0 && (x=9); printf(\"%d %d\\n\", r, x); return 0;", expect: ["0 1"] },
    or_empty_rhs_not_evaluated => { includes: ["<stdio.h>"], decls: "int x=1;", body: "int r = 1 || (x=9); printf(\"%d %d\\n\", r, x); return 0;", expect: ["1 1"] },
    and_with_question_inside => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1 && (2?3:0)); return 0;", expect: ["1"] },
    or_with_question_inside => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 0 || (0?1:2)); return 0;", expect: ["1"] },
    not_pointer_null => { includes: ["<stdio.h>"], decls: "", body: "int *p=0; printf(\"%d\\n\", !p); return 0;", expect: ["1"] },
    not_pointer_nonnull => { includes: ["<stdio.h>"], decls: "", body: "int x=1; printf(\"%d\\n\", !&x); return 0;", expect: ["0"] },
    and_array_nonnull => { includes: ["<stdio.h>"], decls: "", body: "int a[1]={1}; printf(\"%d\\n\", a && a[0]); return 0;", expect: ["1"] },
    or_with_comma_lhs => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", (0,1) || 0); return 0;", expect: ["1"] },
    and_with_comma_rhs => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1 && (0,2)); return 0;", expect: ["1"] },
}
