//! Switch fallthrough, default placement, nesting, break and continue interaction.

use crate::helpers::*;

c_run_cases! {
    fallthrough_accumulates_two_cases => { includes: ["<stdio.h>"], decls: "", body: "int x=0; switch(1){ case 1: x++; case 2: x++; break; } printf(\"%d\\n\", x); return 0;", expect: ["2"] },
    fallthrough_three_cases_before_break => { includes: ["<stdio.h>"], decls: "", body: "int x=0; switch(1){ case 1: x++; case 2: x++; case 3: x++; break; } printf(\"%d\\n\", x); return 0;", expect: ["3"] },
    fallthrough_stops_at_break_after_chain => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: printf(\"1\\n\"); case 2: printf(\"2\\n\"); break; case 3: printf(\"3\\n\"); } return 0;", expect: ["2"] },
    fallthrough_into_default_label => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"a\\n\"); default: printf(\"d\\n\"); } return 0;", expect: ["a", "d"] },
    default_first_still_jumps_to_matching_case => { includes: ["<stdio.h>"], decls: "", body: "switch(5){ default: printf(\"d\\n\"); break; case 5: printf(\"5\\n\"); break; } return 0;", expect: ["5"] },
    default_in_middle_unmatched_hits_default => { includes: ["<stdio.h>"], decls: "", body: "switch(8){ case 1: printf(\"1\\n\"); break; default: printf(\"d\\n\"); break; case 2: printf(\"2\\n\"); break; } return 0;", expect: ["d"] },
    default_in_middle_matched_case_skips_default => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: printf(\"1\\n\"); break; default: printf(\"d\\n\"); break; case 2: printf(\"2\\n\"); break; } return 0;", expect: ["2"] },
    nested_switch_inner_break_only_exits_inner => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(2){ case 2: printf(\"in\\n\"); break; default: printf(\"bad\\n\"); } printf(\"out\\n\"); break; } return 0;", expect: ["in", "out"] },
    nested_switch_outer_fallthrough_reaches_inner => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(3){ case 3: printf(\"i\\n\"); break; } case 2: printf(\"o\\n\"); break; } return 0;", expect: ["i", "o"] },
    nested_switch_inner_default => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(9){ default: printf(\"d\\n\"); break; } break; } return 0;", expect: ["d"] },
    break_in_switch_inside_for_continues_loop => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<2;i++){ switch(i){ case 0: printf(\"0\\n\"); break; case 1: printf(\"1\\n\"); break; } printf(\"loop\\n\"); } return 0;", expect: ["0", "loop", "1", "loop"] },
    continue_in_switch_inside_for_skips_rest => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<3;i++){ switch(i){ case 0: continue; case 1: printf(\"1\\n\"); break; default: printf(\"d\\n\"); } } return 0;", expect: ["1", "d"] },
    continue_in_switch_case_before_other_case => { includes: ["<stdio.h>"], decls: "", body: "int i,s=0; for(i=0;i<3;i++){ switch(i){ case 0: s+=1; continue; case 1: s+=10; break; default: s+=100; } } printf(\"%d\\n\", s); return 0;", expect: ["11"] },
    fallthrough_with_printf_sequence => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"A\\n\"); case 2: printf(\"B\\n\"); break; case 3: printf(\"C\\n\"); } return 0;", expect: ["A", "B"] },
    fallthrough_from_default_to_case_after => { includes: ["<stdio.h>"], decls: "", body: "switch(0){ default: printf(\"d\\n\"); case 1: printf(\"1\\n\"); break; } return 0;", expect: ["d", "1"] },
    case_group_shared_body_no_fallthrough_out => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: case 2: printf(\"g\\n\"); break; default: printf(\"x\\n\"); } return 0;", expect: ["g"] },
    switch_on_expression_with_fallthrough_add => { includes: ["<stdio.h>"], decls: "", body: "int v=1,t=0; switch(v+0){ case 1: t+=1; case 2: t+=2; break; default: t=9; } printf(\"%d\\n\", t); return 0;", expect: ["3"] },
    break_prevents_fallthrough_to_next_case => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"1\\n\"); break; case 2: printf(\"2\\n\"); break; } return 0;", expect: ["1"] },
    fallthrough_into_case_with_declaration_block => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"a\\n\"); case 2: { int z=3; printf(\"%d\\n\", z); } break; } return 0;", expect: ["a", "3"] },
    nested_switch_both_match_inner_then_outer_break => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(1){ case 1: printf(\"i\\n\"); break; } printf(\"o\\n\"); break; default: printf(\"d\\n\"); } return 0;", expect: ["i", "o"] },
    switch_in_while_with_fallthrough_once => { includes: ["<stdio.h>"], decls: "", body: "int i=0; while(i<1){ switch(i){ case 0: printf(\"0\\n\"); i++; case 1: printf(\"1\\n\"); break; } } return 0;", expect: ["0", "1"] },
    default_only_switch_unmatched => { includes: ["<stdio.h>"], decls: "", body: "switch(4){ default: printf(\"only\\n\"); break; } return 0;", expect: ["only"] },
    fallthrough_char_cases => { includes: ["<stdio.h>"], decls: "", body: "char c='a'; switch(c){ case 'a': printf(\"a\\n\"); case 'b': printf(\"b\\n\"); break; default: printf(\"d\\n\"); } return 0;", expect: ["a", "b"] },
    switch_zero_case_fallthrough_to_one => { includes: ["<stdio.h>"], decls: "", body: "switch(0){ case 0: printf(\"0\\n\"); case 1: printf(\"1\\n\"); break; } return 0;", expect: ["0", "1"] },
    negative_case_with_fallthrough => { includes: ["<stdio.h>"], decls: "", body: "switch(-1){ case -1: printf(\"n\\n\"); case 0: printf(\"z\\n\"); break; } return 0;", expect: ["n", "z"] },
    enum_value_switch_fallthrough => { includes: ["<stdio.h>"], decls: "enum E{T1=1,T2=2};", body: "enum E v=T1; switch(v){ case T1: printf(\"1\\n\"); case T2: printf(\"2\\n\"); break; } return 0;", expect: ["1", "2"] },
    nested_switch_continue_in_for_outer => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<2;i++){ switch(i){ case 0: switch(0){ case 0: continue; } break; case 1: printf(\"1\\n\"); break; } } return 0;", expect: ["1"] },
    switch_break_does_not_exit_enclosing_while => { includes: ["<stdio.h>"], decls: "", body: "int i=0; while(i<2){ switch(i){ case 0: printf(\"0\\n\"); break; case 1: printf(\"1\\n\"); break; } i++; } return 0;", expect: ["0", "1"] },
    fallthrough_stops_before_unreached_case => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: printf(\"1\\n\"); case 2: printf(\"2\\n\"); break; case 3: printf(\"3\\n\"); } return 0;", expect: ["2"] },
    default_fallthrough_into_case_after => { includes: ["<stdio.h>"], decls: "", body: "switch(99){ default: printf(\"d\\n\"); case 100: printf(\"100\\n\"); break; } return 0;", expect: ["d", "100"] },
    sparse_cases_with_fallthrough_gap => { includes: ["<stdio.h>"], decls: "", body: "switch(10){ case 10: printf(\"10\\n\"); case 20: printf(\"20\\n\"); break; case 30: printf(\"30\\n\"); } return 0;", expect: ["10", "20"] },
    switch_inside_if_with_fallthrough => { includes: ["<stdio.h>"], decls: "", body: "int x=1; if(x){ switch(x){ case 1: printf(\"a\\n\"); case 2: printf(\"b\\n\"); break; } } return 0;", expect: ["a", "b"] },
    nested_default_in_inner_outer_case_break => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 2: switch(5){ default: printf(\"in\\n\"); break; } printf(\"out\\n\"); break; } return 0;", expect: ["in", "out"] },
    fallthrough_assignments_accumulate => { includes: ["<stdio.h>"], decls: "", body: "int a=0; switch(1){ case 1: a+=1; case 2: a+=2; break; case 3: a+=4; } printf(\"%d\\n\", a); return 0;", expect: ["3"] },
    continue_only_skips_switch_tail_not_case_fallthrough => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<2;i++){ switch(i){ case 0: printf(\"0\\n\"); continue; case 1: printf(\"1\\n\"); break; } printf(\"t\\n\"); } return 0;", expect: ["0", "1", "t"] },
    switch_with_empty_case_fallthrough => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: case 2: printf(\"x\\n\"); break; default: printf(\"d\\n\"); } return 0;", expect: ["x"] },
    double_nested_switch_inner_match => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(2){ case 2: switch(3){ case 3: printf(\"deep\\n\"); break; } break; } break; } return 0;", expect: ["deep"] },
    fallthrough_from_matched_default_path => { includes: ["<stdio.h>"], decls: "", body: "switch(7){ case 1: printf(\"1\\n\"); break; default: printf(\"d\\n\"); case 7: printf(\"7\\n\"); break; } return 0;", expect: ["7"] },
    break_after_fallthrough_sequence => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"1\\n\"); case 2: printf(\"2\\n\"); case 3: printf(\"3\\n\"); break; case 4: printf(\"4\\n\"); } return 0;", expect: ["1", "2", "3"] },
    switch_do_while_with_continue_in_case => { includes: ["<stdio.h>"], decls: "", body: "int i=0; do{ switch(i){ case 0: i++; continue; case 1: printf(\"1\\n\"); break; } }while(0); return 0;", expect: ["1"] },
    case_with_braces_fallthrough_to_printf => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: { printf(\"a\\n\"); } case 2: printf(\"b\\n\"); break; } return 0;", expect: ["a", "b"] },
    outer_switch_fallthrough_enters_inner_switch => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(1){ case 1: printf(\"i\\n\"); break; } case 2: printf(\"o\\n\"); break; } return 0;", expect: ["i", "o"] },
    unmatched_hits_default_without_fallthrough_out => { includes: ["<stdio.h>"], decls: "", body: "switch(6){ case 1: printf(\"1\\n\"); break; default: printf(\"d\\n\"); break; case 2: printf(\"2\\n\"); break; } return 0;", expect: ["d"] },
    switch_char_promoted_matches_ascii_case => { includes: ["<stdio.h>"], decls: "", body: "char c='Z'; switch(c){ case 'Z': printf(\"z\\n\"); break; default: printf(\"d\\n\"); } return 0;", expect: ["z"] },
    fallthrough_multiple_printf_then_break => { includes: ["<stdio.h>"], decls: "", body: "switch(3){ case 3: printf(\"3\\n\"); case 4: printf(\"4\\n\"); case 5: printf(\"5\\n\"); break; } return 0;", expect: ["3", "4", "5"] },
    nested_inner_fallthrough_outer_break => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(1){ case 1: printf(\"a\\n\"); case 2: printf(\"b\\n\"); break; } break; default: printf(\"d\\n\"); } return 0;", expect: ["a", "b"] },
    switch_last_case_fallthrough_out_of_switch => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: printf(\"1\\n\"); break; case 2: printf(\"2\\n\"); } printf(\"end\\n\"); return 0;", expect: ["2", "end"] },
    default_between_cases_unmatched_value => { includes: ["<stdio.h>"], decls: "", body: "switch(50){ case 10: printf(\"10\\n\"); break; default: printf(\"mid\\n\"); break; case 20: printf(\"20\\n\"); break; } return 0;", expect: ["mid"] },
}
