//! stdint types, signals, setjmp, regex compile breadth.

use crate::helpers::*;

c_compile_cases! {
    stdint_int8_t => { includes: ["<stdint.h>"], decls: "", body: "int8_t x=1; return x;" },
    stdint_uint8_t => { includes: ["<stdint.h>"], decls: "", body: "uint8_t x=1; return x;" },
    stdint_int16_t => { includes: ["<stdint.h>"], decls: "", body: "int16_t x=1; return x;" },
    stdint_uint16_t => { includes: ["<stdint.h>"], decls: "", body: "uint16_t x=1; return x;" },
    stdint_int32_t => { includes: ["<stdint.h>"], decls: "", body: "int32_t x=1; return x;" },
    stdint_uint32_t => { includes: ["<stdint.h>"], decls: "", body: "uint32_t x=1; return x;" },
    stdint_int64_t => { includes: ["<stdint.h>"], decls: "", body: "int64_t x=1; return x;" },
    stdint_uint64_t => { includes: ["<stdint.h>"], decls: "", body: "uint64_t x=1; return x;" },
    stdint_intptr_t => { includes: ["<stdint.h>"], decls: "", body: "intptr_t p=0; return (int)p;" },
    stdint_uintptr_t => { includes: ["<stdint.h>"], decls: "", body: "uintptr_t p=0; return (int)p;" },
    stdint_ptrdiff_t => { includes: ["<stddef.h>"], decls: "", body: "ptrdiff_t d=1; return (int)d;" },
    stdint_size_t => { includes: ["<stddef.h>"], decls: "", body: "size_t s=1; return (int)s;" },
    signal_sigabrt => { includes: ["<signal.h>"], decls: "", body: "return SIGABRT;" },
    signal_sigfpe => { includes: ["<signal.h>"], decls: "", body: "return SIGFPE;" },
    signal_sigill => { includes: ["<signal.h>"], decls: "", body: "return SIGILL;" },
    signal_sigint => { includes: ["<signal.h>"], decls: "", body: "return SIGINT;" },
    signal_sigsegv => { includes: ["<signal.h>"], decls: "", body: "return SIGSEGV;" },
    signal_sigterm => { includes: ["<signal.h>"], decls: "", body: "return SIGTERM;" },
    signal_sigaction_compile => { includes: ["<signal.h>"], decls: "", body: "struct sigaction sa={0}; sigaction(SIGINT,&sa,0); return 0;" },
    signal_pthread_sigmask => { includes: ["<signal.h>"], decls: "", body: "sigset_t s; sigemptyset(&s); return 0;" },
    setjmp_buffer => { includes: ["<setjmp.h>"], decls: "", body: "jmp_buf b; return setjmp(b);" },
    longjmp_compile => { includes: ["<setjmp.h>"], decls: "", body: "jmp_buf b; if(!setjmp(b)) longjmp(b,1); return 0;" },
    regex_regcomp_extended => { includes: ["<regex.h>"], decls: "", body: "regex_t r; regcomp(&r,\"a\",REG_EXTENDED); regfree(&r); return 0;" },
    regex_regexec_nomatch => { includes: ["<regex.h>"], decls: "", body: "regex_t r; regcomp(&r,\"z\",0); regexec(&r,\"a\",0,0,0); regfree(&r); return 0;" },
    wchar_mbsinit => { includes: ["<wchar.h>"], decls: "", body: "mbstate_t st; return mbsinit(&st);" },
    wchar_btowc => { includes: ["<wchar.h>"], decls: "", body: "return btowc('a');" },
    wchar_wctob => { includes: ["<wchar.h>"], decls: "", body: "return wctob(L'a');" },
    time_clock_t => { includes: ["<time.h>"], decls: "", body: "clock_t c=clock(); return c>=0;" },
    time_time_t => { includes: ["<time.h>"], decls: "", body: "time_t t=0; return (int)t;" },
    errno_edomain => { includes: ["<errno.h>"], decls: "", body: "return EDOM;" },
    errno_erange => { includes: ["<errno.h>"], decls: "", body: "return ERANGE;" },
}
