//! ctype, assert, and preprocessor compile breadth.

use crate::helpers::*;

c_compile_cases! {
    ctype_isblank_space => { includes: ["<ctype.h>"], decls: "", body: "return isblank(' ');" },
    ctype_isblank_tab => { includes: ["<ctype.h>"], decls: "", body: "return isblank('\\t');" },
    ctype_isgraph_printable => { includes: ["<ctype.h>"], decls: "", body: "return isgraph('!');" },
    ctype_isascii_extension => { includes: ["<ctype.h>"], decls: "", body: "return isascii('A');" },
    ctype_toascii_extension => { includes: ["<ctype.h>"], decls: "", body: "return toascii('a');" },
    assert_perror_compile => { includes: ["<assert.h>"], decls: "", body: "return 0;" },
    pp_defined_and => { includes: ["<stdio.h>"], decls: "#if defined(__STDC__) && 1\nint x=1;\n#endif", body: "return x;" },
    pp_defined_or => { includes: ["<stdio.h>"], decls: "#if defined(__STDC__) || 0\nint x=1;\n#else\nint x=0;\n#endif", body: "return x;" },
    pp_ifndef_else => { includes: ["<stdio.h>"], decls: "#ifndef Z9\n#define Z9\nint x=2;\n#endif", body: "return x;" },
    pp_elif_chain => { includes: ["<stdio.h>"], decls: "#if 0\nint x=1;\n#elif 1\nint x=2;\n#else\nint x=3;\n#endif", body: "return x;" },
    pp_macro_stringify_op => { includes: ["<stdio.h>"], decls: "#define S(x) #x", body: "return 0;" },
    pp_macro_paste_op => { includes: ["<stdio.h>"], decls: "#define C(a,b) a##b\nint xy=1;", body: "return C(x,y);" },
    pp_pragma_message => { includes: ["<stdio.h>"], decls: "#pragma message \"vybe\"", body: "return 0;" },
    pp_include_next_compile => { includes: ["<stdio.h>"], decls: "", body: "return 0;" },
    pp_error_if_zero => { includes: ["<stdio.h>"], decls: "#if 1\nint x=1;\n#endif", body: "return x;" },
    pp_line_macro => { includes: ["<stdio.h>"], decls: "", body: "return __LINE__ > 0;" },
    pp_file_macro => { includes: ["<stdio.h>"], decls: "", body: "return __FILE__ != 0;" },
    pp_func_macro => { includes: ["<stdio.h>"], decls: "int f(void){return __LINE__;}", body: "return f();" },
    pp_date_macro => { includes: ["<stdio.h>"], decls: "", body: "return __DATE__[0];" },
    pp_time_macro => { includes: ["<stdio.h>"], decls: "", body: "return __TIME__[0];" },
    pp_stdc_version => { includes: ["<stdio.h>"], decls: "", body: "return __STDC_VERSION__ > 0;" },
    pp_stdc_macro => { includes: ["<stdio.h>"], decls: "", body: "return __STDC__;" },
    stdnoreturn_void => { includes: ["<stdnoreturn.h>"], decls: "_Noreturn void h(void); void h(void){for(;;){}}", body: "return 0;" },
    alignas_type => { includes: ["<stdalign.h>"], decls: "alignas(double) char buf[16];", body: "return sizeof(buf);" },
    alignof_max => { includes: ["<stdalign.h>"], decls: "", body: "return alignof(max_align_t);" },
    static_assert_msg2 => { includes: ["<assert.h>"], decls: "_Static_assert(sizeof(void*)>=4,\"ptr\");", body: "return 0;" },
    bool_header => { includes: ["<stdbool.h>"], decls: "", body: "bool b=true; return b;" },
    limits_mb_len_max => { includes: ["<limits.h>"], decls: "", body: "return MB_LEN_MAX;" },
    limits_word_bit => { includes: ["<limits.h>"], decls: "", body: "return WORD_BIT;" },
    float_radix => { includes: ["<float.h>"], decls: "", body: "return FLT_RADIX;" },
    float_mant_dig => { includes: ["<float.h>"], decls: "", body: "return FLT_MANT_DIG;" },
    float_max_exp => { includes: ["<float.h>"], decls: "", body: "return FLT_MAX_EXP;" },
    double_max => { includes: ["<float.h>"], decls: "", body: "return DBL_MAX > 0;" },
    double_min => { includes: ["<float.h>"], decls: "", body: "return DBL_MIN > 0;" },
    ldbl_dig => { includes: ["<float.h>"], decls: "", body: "return LDBL_DIG;" },
    complex_h_macro_i => { includes: ["<complex.h>"], decls: "", body: "double complex z=I; return cimag(z)==1;" },
    tgmath_h_compile => { includes: ["<tgmath.h>"], decls: "", body: "return (int)sqrt(4);" },
    iso646_alternative_tokens => { includes: ["<iso646.h>"], decls: "", body: "return 0;" },
    stdckdint_compile => { includes: ["<stdckdint.h>"], decls: "", body: "unsigned r; return ckd_add(&r,1u,2u);" },
    uchar_h_compile => { includes: ["<uchar.h>"], decls: "", body: "char8_t c=u8'a'; return c;" },
}
