//! complex.h, stdatomic.h, limits.h, float.h — one API/macro per test.

c_run_cases! {
    complex_carg => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=1+1*I; printf(\"%.3f\\n\", carg(z)); return 0;", expect: ["0.785"] },
    complex_conj => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=conj(1+2*I); printf(\"%.1f %.1f\\n\", creal(z), cimag(z)); return 0;", expect: ["1.0 -2.0"] },
    complex_cexp => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=cexp(0); printf(\"%.1f\\n\", creal(z)); return 0;", expect: ["1.0"] },
    complex_clog => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=clog(1); printf(\"%.1f\\n\", creal(z)); return 0;", expect: ["0.0"] },
    complex_cpow => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=cpow(2,1); printf(\"%.0f\\n\", creal(z)); return 0;", expect: ["2"] },
    complex_csqrt => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=csqrt(4); printf(\"%.0f\\n\", creal(z)); return 0;", expect: ["2"] },
    complex_csin => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=csin(0); printf(\"%.1f\\n\", creal(z)); return 0;", expect: ["0.0"] },
    complex_ccos => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=ccos(0); printf(\"%.1f\\n\", creal(z)); return 0;", expect: ["1.0"] },
    complex_ctan => { includes: ["<stdio.h>", "<complex.h>"], decls: "", body: "double complex z=ctan(0); printf(\"%.1f\\n\", creal(z)); return 0;", expect: ["0.0"] },
    limits_char_bit => { includes: ["<stdio.h>", "<limits.h>"], decls: "", body: "printf(\"%d\\n\", CHAR_BIT); return 0;", expect: ["8"] },
    limits_int_max => { includes: ["<stdio.h>", "<limits.h>"], decls: "", body: "printf(\"%d\\n\", INT_MAX > 0); return 0;", expect: ["1"] },
    float_dig => { includes: ["<stdio.h>", "<float.h>"], decls: "", body: "printf(\"%d\\n\", FLT_DIG > 0); return 0;", expect: ["1"] },
    float_epsilon => { includes: ["<stdio.h>", "<float.h>"], decls: "", body: "printf(\"%d\\n\", FLT_EPSILON > 0.0f); return 0;", expect: ["1"] },
}

c_compile_cases! {
    complex_cproj => { includes: ["<complex.h>"], decls: "", body: "double complex z = cproj(1+2*I); return (int)creal(z);" },
    complex_csinh => { includes: ["<complex.h>"], decls: "", body: "double complex z = csinh(0); return (int)creal(z);" },
    complex_ccosh => { includes: ["<complex.h>"], decls: "", body: "double complex z = ccosh(0); return (int)creal(z);" },
    complex_ctanh => { includes: ["<complex.h>"], decls: "", body: "double complex z = ctanh(0); return (int)creal(z);" },
    complex_casin => { includes: ["<complex.h>"], decls: "", body: "double complex z = casin(0); return (int)creal(z);" },
    complex_cacos => { includes: ["<complex.h>"], decls: "", body: "double complex z = cacos(1); return (int)creal(z);" },
    complex_catan => { includes: ["<complex.h>"], decls: "", body: "double complex z = catan(0); return (int)creal(z);" },
    atomic_exchange => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_int x=0; return atomic_exchange(&x,1);" },
    atomic_fetch_or => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_int x=1; atomic_fetch_or(&x,2); return atomic_load(&x);" },
    atomic_fetch_and => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_int x=3; atomic_fetch_and(&x,1); return atomic_load(&x);" },
    atomic_fetch_xor => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_int x=3; atomic_fetch_xor(&x,1); return atomic_load(&x);" },
    atomic_thread_fence => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_thread_fence(memory_order_seq_cst); return 0;" },
    atomic_signal_fence => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_signal_fence(memory_order_seq_cst); return 0;" },
    atomic_flag_clear => { includes: ["<stdatomic.h>"], decls: "", body: "atomic_flag f=ATOMIC_FLAG_INIT; atomic_flag_clear(&f); return 0;" },
    atomic_is_lock_free => { includes: ["<stdatomic.h>"], decls: "", body: "return atomic_is_lock_free(&(atomic_int){0});" },
    limits_schar_min => { includes: ["<limits.h>"], decls: "", body: "return SCHAR_MIN;" },
    limits_uchar_max => { includes: ["<limits.h>"], decls: "", body: "return UCHAR_MAX;" },
    limits_shrt_max => { includes: ["<limits.h>"], decls: "", body: "return SHRT_MAX;" },
    limits_long_max => { includes: ["<limits.h>"], decls: "", body: "return LONG_MAX > 0;" },
    limits_llong_max => { includes: ["<limits.h>"], decls: "", body: "return LLONG_MAX > 0;" },
    float_max => { includes: ["<float.h>"], decls: "", body: "return FLT_MAX > 0;" },
    float_min => { includes: ["<float.h>"], decls: "", body: "return FLT_MIN > 0;" },
    double_dig => { includes: ["<float.h>"], decls: "", body: "return DBL_DIG;" },
    assert_macro_compile => { includes: ["<assert.h>"], decls: "", body: "assert(1); return 0;" },
    locale_setlocale => { includes: ["<locale.h>"], decls: "", body: "return setlocale(LC_ALL,\"C\") != 0;" },
    locale_lc_ctype => { includes: ["<locale.h>"], decls: "", body: "return LC_CTYPE;" },
}
