//! Bitwise AND, OR, XOR, NOT — distinct bit patterns and complements.

c_run_cases! {
    bitwise_and_ff_with_0f => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xFF & 0x0F); return 0;", expect: ["f"] },
    bitwise_and_aa_with_55 => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xAA & 0x55); return 0;", expect: ["0"] },
    bitwise_and_f0_with_0f => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xF0 & 0x0F); return 0;", expect: ["0"] },
    bitwise_and_cc_with_cf => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xCC & 0xCF); return 0;", expect: ["cc"] },
    bitwise_and_identical_operands => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0x37 & 0x37); return 0;", expect: ["37"] },
    bitwise_and_with_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 42 & 0); return 0;", expect: ["0"] },
    bitwise_and_with_all_ones_byte => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xAB & 0xFF); return 0;", expect: ["ab"] },
    bitwise_or_ff_with_00 => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xFF | 0x00); return 0;", expect: ["ff"] },
    bitwise_or_aa_with_55 => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xAA | 0x55); return 0;", expect: ["ff"] },
    bitwise_or_f0_with_0f => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xF0 | 0x0F); return 0;", expect: ["ff"] },
    bitwise_or_with_zero_preserves => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 17 | 0); return 0;", expect: ["17"] },
    bitwise_or_identical_operands => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0x24 | 0x24); return 0;", expect: ["24"] },
    bitwise_xor_ff_with_ff => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xFF ^ 0xFF); return 0;", expect: ["0"] },
    bitwise_xor_aa_with_55 => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xAA ^ 0x55); return 0;", expect: ["ff"] },
    bitwise_xor_f0_with_0f => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0xF0 ^ 0x0F); return 0;", expect: ["ff"] },
    bitwise_xor_same_operand_zero => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 99 ^ 99); return 0;", expect: ["0"] },
    bitwise_xor_with_zero_identity => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0x5A ^ 0); return 0;", expect: ["5a"] },
    bitwise_xor_toggle_low_bit => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", 0x10 ^ 0x01); return 0;", expect: ["11"] },
    unary_not_zero_byte => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=0; printf(\"%u\\n\", (unsigned)(~c & 0xFF)); return 0;", expect: ["255"] },
    unary_not_all_ones_byte => { includes: ["<stdio.h>"], decls: "", body: "unsigned char c=0xFF; printf(\"%u\\n\", (unsigned)(~c & 0xFF)); return 0;", expect: ["0"] },
    unary_not_zero_int => { includes: ["<stdio.h>"], decls: "", body: "int n=0; printf(\"%d\\n\", ~n + 1); return 0;", expect: ["0"] },
    unary_not_one_int => { includes: ["<stdio.h>"], decls: "", body: "int n=1; printf(\"%d\\n\", ~n); return 0;", expect: ["-2"] },
    unary_not_masked_to_byte => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x00FF00FFu; printf(\"%x\\n\", (~u) & 0xFFu); return 0;", expect: ["0"] },
    bitwise_and_short_operands => { includes: ["<stdio.h>"], decls: "", body: "short a=0x0C, b=0x0A; printf(\"%d\\n\", a & b); return 0;", expect: ["8"] },
    bitwise_or_short_operands => { includes: ["<stdio.h>"], decls: "", body: "short a=0x0C, b=0x0A; printf(\"%d\\n\", a | b); return 0;", expect: ["14"] },
    bitwise_xor_short_operands => { includes: ["<stdio.h>"], decls: "", body: "short a=0x0C, b=0x0A; printf(\"%d\\n\", a ^ b); return 0;", expect: ["6"] },
    bitwise_and_unsigned_char => { includes: ["<stdio.h>"], decls: "", body: "unsigned char a=0x3C, b=0x0F; printf(\"%u\\n\", (unsigned)(a & b)); return 0;", expect: ["12"] },
    bitwise_or_unsigned_char => { includes: ["<stdio.h>"], decls: "", body: "unsigned char a=0x30, b=0x0F; printf(\"%u\\n\", (unsigned)(a | b)); return 0;", expect: ["63"] },
    bitwise_xor_unsigned_char => { includes: ["<stdio.h>"], decls: "", body: "unsigned char a=0xF0, b=0x0F; printf(\"%u\\n\", (unsigned)(a ^ b)); return 0;", expect: ["255"] },
    bitwise_and_long_operands => { includes: ["<stdio.h>"], decls: "", body: "long a=0x1234, b=0x1030; printf(\"%lx\\n\", a & b); return 0;", expect: ["1030"] },
    bitwise_or_long_operands => { includes: ["<stdio.h>"], decls: "", body: "long a=0x1000, b=0x0040; printf(\"%lx\\n\", a | b); return 0;", expect: ["1040"] },
    bitwise_xor_long_operands => { includes: ["<stdio.h>"], decls: "", body: "long a=0xAAAA, b=0x5555; printf(\"%lx\\n\", a ^ b); return 0;", expect: ["ffff"] },
    chained_and_or_precedence => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", (0xF0 | 0x0C) & 0xFF); return 0;", expect: ["fc"] },
    chained_xor_and_mask => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%x\\n\", (0xAA ^ 0x55) & 0x0F); return 0;", expect: ["f"] },
    double_xor_restores_original => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xDEAD; printf(\"%x\\n\", (u ^ 0xFFFF) ^ 0xFFFF); return 0;", expect: ["dead"] },
    and_clears_high_nibble => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xA5; printf(\"%x\\n\", u & 0x0F); return 0;", expect: ["5"] },
    or_sets_high_nibble => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x05; printf(\"%x\\n\", u | 0xF0); return 0;", expect: ["f5"] },
    xor_swaps_bit_pattern => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0b1010; printf(\"%u\\n\", u ^ 0b1111); return 0;", expect: ["5"] },
    not_then_and_masks => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x0F; printf(\"%x\\n\", (~u) & 0xFF); return 0;", expect: ["f0"] },
    bitwise_and_in_conditional => { includes: ["<stdio.h>"], decls: "", body: "int n=(0x08 & 0x04)?1:0; printf(\"%d\\n\", n); return 0;", expect: ["0"] },
    bitwise_or_in_conditional => { includes: ["<stdio.h>"], decls: "", body: "int n=(0x01 | 0x02)?1:0; printf(\"%d\\n\", n); return 0;", expect: ["1"] },
    compound_and_assign => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xFF; u &= 0x0F; printf(\"%x\\n\", u); return 0;", expect: ["f"] },
    compound_or_assign => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xF0; u |= 0x0F; printf(\"%x\\n\", u); return 0;", expect: ["ff"] },
    compound_xor_assign => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xAA; u ^= 0xFF; printf(\"%x\\n\", u); return 0;", expect: ["55"] },
    parity_check_via_xor => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0b1101; int parity=u^(u>>1)^(u>>2)^(u>>3); printf(\"%d\\n\", parity & 1); return 0;", expect: ["1"] },
    even_parity_via_xor => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0b1110; int parity=u^(u>>1)^(u>>2)^(u>>3); printf(\"%d\\n\", parity & 1); return 0;", expect: ["1"] },
    clear_bit_with_and_not => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0xFF; u &= ~(1u<<3); printf(\"%x\\n\", u); return 0;", expect: ["f7"] },
    set_bit_with_or => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0; u |= (1u<<4); printf(\"%x\\n\", u); return 0;", expect: ["10"] },
    toggle_bit_with_xor => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0x10; u ^= (1u<<4); printf(\"%x\\n\", u); return 0;", expect: ["0"] },
    extract_bit_with_and_shift => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=0b101100; printf(\"%d\\n\", (u>>4)&1u); return 0;", expect: ["0"] },
    merge_nibbles_with_or_shift => { includes: ["<stdio.h>"], decls: "", body: "unsigned hi=0xA, lo=0xB; printf(\"%x\\n\", (hi<<4)|lo); return 0;", expect: ["ab"] },
    bitwise_not_unsigned_max => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=~0u; printf(\"%u\\n\", u); return 0;", expect: ["4294967295"] },
    bitwise_and_preserves_common_bits => { includes: ["<stdio.h>"], decls: "", body: "unsigned a=0b11001100, b=0b10101010; printf(\"%u\\n\", a & b); return 0;", expect: ["136"] },
    bitwise_or_combines_all_bits => { includes: ["<stdio.h>"], decls: "", body: "unsigned a=0b11000000, b=0b00001111; printf(\"%u\\n\", a | b); return 0;", expect: ["207"] },
    bitwise_xor_difference_bits => { includes: ["<stdio.h>"], decls: "", body: "unsigned a=0b11110000, b=0b10101010; printf(\"%u\\n\", a ^ b); return 0;", expect: ["90"] },
}
