//! Wide-char and misc compile breadth — one API per test.

use crate::helpers::*;

c_compile_cases! {
    wchar_wcscat => { includes: ["<wchar.h>"], decls: "", body: "wchar_t d[8]=L\"a\"; wcscat(d,L\"b\"); return d[1];" },
    wchar_wcsncat => { includes: ["<wchar.h>"], decls: "", body: "wchar_t d[8]=L\"a\"; wcsncat(d,L\"bc\",1); return d[1];" },
    wchar_wcsncpy => { includes: ["<wchar.h>"], decls: "", body: "wchar_t d[4]; wcsncpy(d,L\"abc\",2); return d[0];" },
    wchar_wcsdup => { includes: ["<wchar.h>", "<stdlib.h>"], decls: "", body: "wchar_t *s=wcsdup(L\"x\"); free(s); return 0;" },
    wchar_wcsstr => { includes: ["<wchar.h>"], decls: "", body: "return wcsstr(L\"abc\",L\"b\") != 0;" },
    wchar_wcspbrk => { includes: ["<wchar.h>"], decls: "", body: "return wcspbrk(L\"abc\",L\"b\") != 0;" },
    wchar_wcsspn => { includes: ["<wchar.h>"], decls: "", body: "return (int)wcsspn(L\"abc\",L\"ab\");" },
    wchar_wcscspn => { includes: ["<wchar.h>"], decls: "", body: "return (int)wcscspn(L\"abc\",L\"b\");" },
    wchar_wcstok => { includes: ["<wchar.h>"], decls: "", body: "wchar_t s[]=L\"a:b\"; wcstok(s,L\":\"); return 0;" },
    wchar_wcscmp => { includes: ["<wchar.h>"], decls: "", body: "return wcscmp(L\"a\",L\"a\");" },
    wchar_wcscoll => { includes: ["<wchar.h>"], decls: "", body: "return wcscoll(L\"a\",L\"a\");" },
    wchar_wcsxfrm => { includes: ["<wchar.h>"], decls: "", body: "wchar_t d[4]; return wcsxfrm(d,L\"a\",4);" },
    wchar_wcwidth => { includes: ["<wchar.h>"], decls: "", body: "return wcwidth(L'a');" },
    wchar_wcswidth => { includes: ["<wchar.h>"], decls: "", body: "return wcswidth(L\"a\",1);" },
    wchar_wprintf_compile => { includes: ["<wchar.h>", "<stdio.h>"], decls: "", body: "return wprintf(L\"%d\\n\",1);" },
    wchar_swprintf_compile => { includes: ["<wchar.h>"], decls: "", body: "wchar_t b[8]; return swprintf(b,8,L\"%d\",1);" },
    wchar_fwprintf_compile => { includes: ["<wchar.h>", "<stdio.h>"], decls: "", body: "return fwprintf(stdout,L\"%d\\n\",1);" },
    wchar_wscanf_compile => { includes: ["<wchar.h>"], decls: "", body: "wchar_t b[2]; return wscanf(L\"%1ls\",b);" },
    wchar_swscanf_compile => { includes: ["<wchar.h>"], decls: "", body: "wchar_t b[2]; return swscanf(L\"a\",L\"%1ls\",b);" },
    wchar_fwscanf_compile => { includes: ["<wchar.h>", "<stdio.h>"], decls: "", body: "return fwscanf(stdin,L\"%d\", (int[]){0});" },
    wchar_wmemmove => { includes: ["<wchar.h>"], decls: "", body: "wchar_t s[3]=L\"abc\"; wmemmove(s+1,s,2); return s[0];" },
    wchar_wmemcmp => { includes: ["<wchar.h>"], decls: "", body: "return wmemcmp(L\"a\",L\"b\",1);" },
    wchar_wmemchr => { includes: ["<wchar.h>"], decls: "", body: "return wmemchr(L\"abc\",L'b',3) != 0;" },
    wchar_wmemset => { includes: ["<wchar.h>"], decls: "", body: "wchar_t d[2]; wmemset(d,L'x',2); return d[0];" },
    wchar_wmemcpy => { includes: ["<wchar.h>"], decls: "", body: "wchar_t d[2]; wmemcpy(d,L\"a\",2); return d[0];" },
    wchar_wcsnlen => { includes: ["<wchar.h>"], decls: "", body: "return (int)wcsnlen(L\"ab\",3);" },
    locale_localeconv => { includes: ["<locale.h>"], decls: "", body: "return localeconv() != 0;" },
    locale_lconv_decimal => { includes: ["<locale.h>"], decls: "", body: "return localeconv()->decimal_point[0];" },
    assert_static_compile => { includes: ["<assert.h>"], decls: "", body: "static_assert(1,\"\"); return 0;" },
    stdio_clearerr => { includes: ["<stdio.h>"], decls: "", body: "clearerr(stdin); return 0;" },
    stdio_feof_stdin => { includes: ["<stdio.h>"], decls: "", body: "return feof(stdin);" },
    stdio_ferror_stdin => { includes: ["<stdio.h>"], decls: "", body: "return ferror(stdin);" },
    stdio_fileno_compile => { includes: ["<stdio.h>"], decls: "", body: "return fileno(stdout);" },
    stdio_fdopen_compile => { includes: ["<stdio.h>"], decls: "", body: "return 0;" },
    stdio_popen_compile => { includes: ["<stdio.h>"], decls: "", body: "FILE *p=popen(\"true\",\"r\"); if(p) pclose(p); return 0;" },
    stdio_freopen_compile => { includes: ["<stdio.h>"], decls: "", body: "FILE *f=freopen(\"/tmp/vybe_fr.txt\",\"w\",stdout); if(f) fclose(f); return 0;" },
    stdio_setvbuf_compile => { includes: ["<stdio.h>"], decls: "", body: "char b[BUFSIZ]; setvbuf(stdout,b,_IOLBF,BUFSIZ); return 0;" },
    stdio_setbuf_compile => { includes: ["<stdio.h>"], decls: "", body: "char b[BUFSIZ]; setbuf(stdout,b); return 0;" },
    stdio_fgetpos_compile => { includes: ["<stdio.h>"], decls: "", body: "FILE *f=tmpfile(); fpos_t p; if(f){fgetpos(f,&p); fclose(f);} return 0;" },
    stdio_fsetpos_compile => { includes: ["<stdio.h>"], decls: "", body: "FILE *f=tmpfile(); fpos_t p; if(f){fsetpos(f,&p); fclose(f);} return 0;" },
    stdio_getdelim_compile => { includes: ["<stdio.h>"], decls: "", body: "char *l=0; size_t n=0; return 0;" },
    stdio_getline_compile => { includes: ["<stdio.h>"], decls: "", body: "char *l=0; size_t n=0; return 0;" },
    stdio_rename_compile => { includes: ["<stdio.h>"], decls: "", body: "rename(\"/tmp/a\",\"/tmp/b\"); return 0;" },
    stdio_remove_compile => { includes: ["<stdio.h>"], decls: "", body: "remove(\"/tmp/none\"); return 0;" },
    stdio_tmpnam_compile => { includes: ["<stdio.h>"], decls: "", body: "char b[L_tmpnam]; tmpnam(b); return 0;" },
    threads_thrd_detach => { includes: ["<threads.h>"], decls: "int w(void *a){(void)a;return 0;}", body: "thrd_t t; thrd_create(&t,w,0); thrd_detach(t); return 0;" },
    threads_mtx_timedlock => { includes: ["<threads.h>"], decls: "", body: "mtx_t m; mtx_init(&m,mtx_plain); mtx_timedlock(&m,0); mtx_unlock(&m); mtx_destroy(&m); return 0;" },
    threads_cnd_timedwait => { includes: ["<threads.h>"], decls: "", body: "cnd_t c; mtx_t m; cnd_init(&c); mtx_init(&m,mtx_plain); cnd_timedwait(&c,&m,0); cnd_destroy(&c); mtx_destroy(&m); return 0;" },
    fenv_feraiseexcept => { includes: ["<fenv.h>"], decls: "", body: "feraiseexcept(FE_INVALID); return 0;" },
    fenv_fetestexcept_div => { includes: ["<fenv.h>"], decls: "", body: "return fetestexcept(FE_DIVBYZERO);" },
}
