//! wchar.h string/memory operations — runtime output via narrow printf or wctob.


c_run_cases! {
    wcslen_empty_string => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t s[] = L\"\"; printf(\"%d\\n\", (int)wcslen(s)); return 0;", expect: ["0"] },
    wcslen_three_chars => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t s[] = L\"xyz\"; printf(\"%d\\n\", (int)wcslen(s)); return 0;", expect: ["3"] },
    wcslen_after_wcscpy => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[6]; wcscpy(d, L\"four\"); printf(\"%d\\n\", (int)wcslen(d)); return 0;", expect: ["4"] },
    wcscpy_first_char_narrow => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[4]; wcscpy(d, L\"hi\"); printf(\"%c\\n\", (char)wctob(d[0])); return 0;", expect: ["h"] },
    wcscpy_last_char_narrow => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[4]; wcscpy(d, L\"hi\"); printf(\"%c\\n\", (char)wctob(d[1])); return 0;", expect: ["i"] },
    wcscmp_equal_strings => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcscmp(L\"same\", L\"same\")); return 0;", expect: ["0"] },
    wcscmp_less_than => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcscmp(L\"abc\", L\"abd\") < 0); return 0;", expect: ["1"] },
    wcscmp_greater_than => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcscmp(L\"xyz\", L\"xy\") > 0); return 0;", expect: ["1"] },
    wcsncmp_equal_prefix => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcsncmp(L\"prefix\", L\"prefixed\", 6)); return 0;", expect: ["0"] },
    wcsncmp_diff_at_limit => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcsncmp(L\"abX\", L\"abY\", 3)); return 0;", expect: ["0"] },
    wcsncmp_diff_beyond_limit => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcsncmp(L\"abX\", L\"abY\", 4) != 0); return 0;", expect: ["1"] },
    wcsncmp_zero_count => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcsncmp(L\"a\", L\"b\", 0)); return 0;", expect: ["0"] },
    wcschr_first_match => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcschr(L\"alpha\", L'a'); printf(\"%lc\\n\", *p); return 0;", expect: ["a"] },
    wcschr_middle_match => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcschr(L\"beta\", L't'); printf(\"%lc\\n\", *p); return 0;", expect: ["t"] },
    wcschr_not_found_null => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcschr(L\"abc\", L'z') == 0); return 0;", expect: ["1"] },
    wcsrchr_single_occurrence => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcsrchr(L\"solo\", L'o'); printf(\"%lc\\n\", *p); return 0;", expect: ["o"] },
    wcsrchr_last_of_many => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcsrchr(L\"banana\", L'a'); printf(\"%d\\n\", (int)(p - L\"banana\")); return 0;", expect: ["5"] },
    wcsrchr_not_found => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcsrchr(L\"abc\", L'z') == 0); return 0;", expect: ["1"] },
    wcsncpy_copies_prefix => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[5]; wcsncpy(d, L\"hello\", 3); d[3]=L'\\0'; printf(\"%lc\\n\", d[2]); return 0;", expect: ["l"] },
    wcsncpy_zero_fill_pad => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[5]={L'!'}; wcsncpy(d, L\"ab\", 4); printf(\"%d\\n\", d[3]==L'\\0'); return 0;", expect: ["1"] },
    wcscat_appends_suffix => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[8]=L\"go\"; wcscat(d, L\"al\"); printf(\"%d\\n\", (int)wcslen(d)); return 0;", expect: ["4"] },
    wcscat_second_char => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[8]=L\"a\"; wcscat(d, L\"bc\"); printf(\"%lc\\n\", d[2]); return 0;", expect: ["c"] },
    wcsncat_limited_append => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[8]=L\"a\"; wcsncat(d, L\"bcd\", 2); printf(\"%d\\n\", (int)wcslen(d)); return 0;", expect: ["3"] },
    wcsncat_preserves_prefix => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[8]=L\"xy\"; wcsncat(d, L\"zzz\", 1); printf(\"%lc\\n\", d[0]); return 0;", expect: ["x"] },
    wcsstr_finds_substring => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcsstr(L\"needle\", L\"eed\"); printf(\"%lc\\n\", *p); return 0;", expect: ["e"] },
    wcsstr_at_start => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcsstr(L\"start\", L\"sta\"); printf(\"%d\\n\", p == L\"start\"); return 0;", expect: ["1"] },
    wcsstr_not_found => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcsstr(L\"abc\", L\"xyz\") == 0); return 0;", expect: ["1"] },
    wcspbrk_first_set_char => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wcspbrk(L\"hello\", L\"el\"); printf(\"%lc\\n\", *p); return 0;", expect: ["e"] },
    wcspbrk_no_match => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wcspbrk(L\"abc\", L\"xyz\") == 0); return 0;", expect: ["1"] },
    wcsspn_initial_segment => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcsspn(L\"abcde\", L\"abc\")); return 0;", expect: ["3"] },
    wcsspn_full_match => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcsspn(L\"aaa\", L\"a\")); return 0;", expect: ["3"] },
    wcsspn_empty_accept => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcsspn(L\"abc\", L\"\")); return 0;", expect: ["0"] },
    wcscspn_until_first_reject => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcscspn(L\"abcde\", L\"cd\")); return 0;", expect: ["2"] },
    wcscspn_no_reject_chars => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcscspn(L\"abc\", L\"xyz\")); return 0;", expect: ["3"] },
    wcsnlen_shorter_than_max => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcsnlen(L\"ab\", 10)); return 0;", expect: ["2"] },
    wcsnlen_capped_by_max => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcsnlen(L\"abcdef\", 3)); return 0;", expect: ["3"] },
    wcsnlen_empty_bounded => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", (int)wcsnlen(L\"\", 5)); return 0;", expect: ["0"] },
    wmemcmp_equal_blocks => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wmemcmp(L\"ab\", L\"ab\", 2)); return 0;", expect: ["0"] },
    wmemcmp_less_block => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wmemcmp(L\"a\", L\"b\", 1) < 0); return 0;", expect: ["1"] },
    wmemcmp_partial_count => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wmemcmp(L\"aX\", L\"aY\", 1)); return 0;", expect: ["0"] },
    wmemchr_finds_wide_char => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t *p = wmemchr(L\"abc\", L'b', 3); printf(\"%lc\\n\", *p); return 0;", expect: ["b"] },
    wmemchr_not_in_range => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%d\\n\", wmemchr(L\"abc\", L'z', 3) == 0); return 0;", expect: ["1"] },
    wmemset_fills_buffer => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[3]; wmemset(d, L'q', 3); printf(\"%lc\\n\", d[1]); return 0;", expect: ["q"] },
    wmemcpy_copies_wide => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[3]; wmemcpy(d, L\"xy\", 2); printf(\"%lc\\n\", d[0]); return 0;", expect: ["x"] },
    wmemcpy_second_element => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t d[3]; wmemcpy(d, L\"xy\", 2); printf(\"%lc\\n\", d[1]); return 0;", expect: ["y"] },
    btowc_lowercase_ascii => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%c\\n\", (char)btowc('m')); return 0;", expect: ["m"] },
    wctob_digit_ascii => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "printf(\"%c\\n\", (char)wctob(L'7')); return 0;", expect: ["7"] },
    wcstombs_narrow_first_byte => { includes: ["<stdio.h>", "<wchar.h>", "<stdlib.h>"], decls: "", body: "char b[8]; wcstombs(b, L\"Z\", 8); printf(\"%c\\n\", b[0]); return 0;", expect: ["Z"] },
    mbstowcs_wide_first_char => { includes: ["<stdio.h>", "<wchar.h>", "<stdlib.h>"], decls: "", body: "wchar_t w[4]; mbstowcs(w, \"Q\", 4); printf(\"%lc\\n\", w[0]); return 0;", expect: ["Q"] },
    wcsdup_matches_source => { includes: ["<stdio.h>", "<wchar.h>", "<stdlib.h>"], decls: "", body: "wchar_t *p = wcsdup(L\"dup\"); printf(\"%d\\n\", wcscmp(p, L\"dup\")); free(p); return 0;", expect: ["0"] },
    wcsdup_independent_copy => { includes: ["<stdio.h>", "<wchar.h>", "<stdlib.h>"], decls: "", body: "wchar_t *p = wcsdup(L\"ok\"); p[0]=L'N'; printf(\"%lc\\n\", p[0]); free(p); return 0;", expect: ["N"] },
}
