//! Pointer ordering and null comparisons within one array object.


c_run_cases! {
    same_array_less_equal_low_index => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[0]<=&a[2]); return 0;", expect: ["1"] },
    same_array_less_equal_equal_index => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[1]<=&a[1]); return 0;", expect: ["1"] },
    same_array_less_equal_false_high_first => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[3]<=&a[1]); return 0;", expect: ["0"] },
    same_array_greater_equal_high_index => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[3]>=&a[1]); return 0;", expect: ["1"] },
    same_array_greater_equal_equal_index => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[2]>=&a[2]); return 0;", expect: ["1"] },
    same_array_greater_equal_false_low_first => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[0]>=&a[2]); return 0;", expect: ["0"] },
    one_past_end_greater_than_last_element => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; printf(\"%d\\n\", &a[3]>&a[2]); return 0;", expect: ["1"] },
    one_past_end_not_less_than_itself => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; printf(\"%d\\n\", &a[3]<&a[3]); return 0;", expect: ["0"] },
    one_past_end_equal_to_self => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; printf(\"%d\\n\", &a[3]==&a[3]); return 0;", expect: ["1"] },
    base_not_greater_than_one_past_end => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; printf(\"%d\\n\", &a[0]>&a[3]); return 0;", expect: ["0"] },
    pointer_after_increment_less_than_end => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0}; int *p=a; p+=2; printf(\"%d\\n\", p<&a[5]); return 0;", expect: ["1"] },
    pointer_at_end_not_less_than_end => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0}; int *p=&a[5]; printf(\"%d\\n\", p<&a[5]); return 0;", expect: ["0"] },
    null_pointer_equals_null_macro => { includes: ["<stdio.h>", "<stddef.h>"], decls: "", body: "int *p=NULL; printf(\"%d\\n\", p==NULL); return 0;", expect: ["1"] },
    null_pointer_not_equal_valid_address => { includes: ["<stdio.h>", "<stddef.h>"], decls: "", body: "int x=0; printf(\"%d\\n\", NULL==&x); return 0;", expect: ["0"] },
    null_pointer_not_equal_nonnull => { includes: ["<stdio.h>"], decls: "", body: "int x=1; int *p=&x; printf(\"%d\\n\", p!=0); return 0;", expect: ["1"] },
    null_inequality_with_explicit_zero => { includes: ["<stdio.h>"], decls: "", body: "int *p=0; printf(\"%d\\n\", p!=0); return 0;", expect: ["0"] },
    char_array_lexicographic_address_order => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"abc\"; printf(\"%d\\n\", &s[0]<&s[2]); return 0;", expect: ["1"] },
    char_array_reverse_address_order_false => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"abc\"; printf(\"%d\\n\", &s[2]<&s[0]); return 0;", expect: ["0"] },
    multidim_same_row_pointer_order => { includes: ["<stdio.h>"], decls: "", body: "int m[2][3]={{1,2,3},{4,5,6}}; printf(\"%d\\n\", &m[0][0]<&m[0][2]); return 0;", expect: ["1"] },
    multidim_same_row_end_vs_start => { includes: ["<stdio.h>"], decls: "", body: "int m[2][3]={{1,2,3},{4,5,6}}; printf(\"%d\\n\", &m[1][0]>&m[1][0]); return 0;", expect: ["0"] },
    multidim_row_start_less_than_next_row => { includes: ["<stdio.h>"], decls: "", body: "int m[2][2]={{1,2},{3,4}}; printf(\"%d\\n\", &m[0][1]<&m[1][0]); return 0;", expect: ["1"] },
    decayed_array_name_equals_element_address => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={0}; printf(\"%d\\n\", a+1==&a[1]); return 0;", expect: ["1"] },
    incremented_pointer_not_equal_base => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={0}; int *p=a; p++; printf(\"%d\\n\", p==a); return 0;", expect: ["0"] },
    decremented_end_pointer_equals_last => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={0}; int *p=&a[3]; p--; printf(\"%d\\n\", p==&a[2]); return 0;", expect: ["1"] },
    struct_member_array_element_order => { includes: ["<stdio.h>"], decls: "struct S{int a[3];};", body: "struct S s={{1,2,3}}; printf(\"%d\\n\", &s.a[0]<&s.a[2]); return 0;", expect: ["1"] },
    struct_members_distinct_addresses => { includes: ["<stdio.h>"], decls: "struct S{int x; int y;};", body: "struct S s; printf(\"%d\\n\", &s.x!=&s.y); return 0;", expect: ["1"] },
    pointer_from_subscript_equals_ampersand_index => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; int *p=a; printf(\"%d\\n\", p+3==&a[3]); return 0;", expect: ["1"] },
    const_pointer_compare_same_slot => { includes: ["<stdio.h>"], decls: "", body: "const int a[2]={1,2}; const int *p=a; printf(\"%d\\n\", p==&a[0]); return 0;", expect: ["1"] },
    void_pointer_cast_preserves_equality => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={1,2}; int *ip=&a[1]; void *vp=ip; printf(\"%d\\n\", ip==vp); return 0;", expect: ["1"] },
    void_pointer_cast_preserves_inequality => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={1,2}; void *v0=&a[0]; void *v1=&a[1]; printf(\"%d\\n\", v0!=v1); return 0;", expect: ["1"] },
    loop_pointer_reaches_end_sentinel => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; int *p=a; while(p<&a[3]) p++; printf(\"%d\\n\", p==&a[3]); return 0;", expect: ["1"] },
    short_array_pointer_less_chain => { includes: ["<stdio.h>"], decls: "", body: "short a[5]={0}; printf(\"%d\\n\", &a[1]<&a[4]); return 0;", expect: ["1"] },
    double_array_pointer_ordering => { includes: ["<stdio.h>"], decls: "", body: "double a[3]={1,2,3}; printf(\"%d\\n\", &a[2]>&a[0]); return 0;", expect: ["1"] },
    string_literal_pointer_char_order => { includes: ["<stdio.h>"], decls: "", body: "char *s=\"xy\"; printf(\"%d\\n\", &s[0]<&s[1]); return 0;", expect: ["1"] },
    stack_var_not_equal_heap_null => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "int x=0; int *h=0; printf(\"%d\\n\", &x!=h); return 0;", expect: ["1"] },
    function_local_array_compare_adjacent => { includes: ["<stdio.h>"], decls: "int cmp(void){ int a[2]={1,2}; return &a[0]<&a[1]; }", body: "printf(\"%d\\n\", cmp()); return 0;", expect: ["1"] },
    pointer_difference_zero_implies_equal => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", &a[2]-&a[2]==0); return 0;", expect: ["1"] },
    pointer_difference_positive_implies_less => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; printf(\"%d\\n\", (&a[0]<&a[3])==(&a[3]-&a[0]>0)); return 0;", expect: ["1"] },
    null_compare_false_with_address_of => { includes: ["<stdio.h>"], decls: "", body: "int v=0; printf(\"%d\\n\", 0==&v); return 0;", expect: ["0"] },
    array_param_address_matches_caller_element => {
        includes: ["<stdio.h>"],
        decls: "int same(int *p, int *q){ return p==q; }",
        body: "int a[2]={0}; printf(\"%d\\n\", same(a,&a[0])); return 0;",
        expect: ["1"]
    },
    array_param_second_slot_address => {
        includes: ["<stdio.h>"],
        decls: "int same(int *p, int *q){ return p==q; }",
        body: "int a[2]={0}; printf(\"%d\\n\", same(a+1,&a[1])); return 0;",
        expect: ["1"]
    },
    nested_block_pointer_still_same_array => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={0}; int *outer=a; { int *inner=a+1; printf(\"%d\\n\", outer<inner); } return 0;", expect: ["1"] },
    ternary_selects_greater_pointer => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={0}; int *p=&a[0]; int *q=&a[2]; int *r = p<q ? q : p; printf(\"%d\\n\", r==&a[2]); return 0;", expect: ["1"] },
    compare_after_round_trip_increment => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; int *p=a; p++; p--; printf(\"%d\\n\", p==a); return 0;", expect: ["1"] },
    unsigned_array_pointer_less_equal_last => { includes: ["<stdio.h>"], decls: "", body: "unsigned a[3]={1,2,3}; printf(\"%d\\n\", &a[2]<=&a[2]); return 0;", expect: ["1"] },
    long_array_first_vs_one_past => { includes: ["<stdio.h>"], decls: "", body: "long a[2]={1,2}; printf(\"%d\\n\", &a[0]<&a[2]); return 0;", expect: ["1"] },
    enum_indexed_addresses_ordered => { includes: ["<stdio.h>"], decls: "enum{LO=0,HI=2};", body: "int a[3]={0}; printf(\"%d\\n\", &a[LO]<&a[HI]); return 0;", expect: ["1"] },
    static_array_file_scope_compare => { includes: ["<stdio.h>"], decls: "static int sa[2]={1,2};", body: "printf(\"%d\\n\", &sa[0]!=&sa[1]); return 0;", expect: ["1"] },
}
