//! Runtime checks for C math.h exponential and logarithmic functions.

use crate::helpers::*;

c_run_cases! {
    exp_negative_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(-1.0)); return 0;", expect: ["0.368"] },
    exp_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(2.0)); return 0;", expect: ["7.389"] },
    exp_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(0.5)); return 0;", expect: ["1.649"] },
    exp_negative_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(-2.0)); return 0;", expect: ["0.135"] },
    exp_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(3.0)); return 0;", expect: ["20.086"] },
    exp_point_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(0.1)); return 0;", expect: ["1.105"] },
    exp_negative_point_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(-0.5)); return 0;", expect: ["0.607"] },
    exp_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp(4.0)); return 0;", expect: ["54.598"] },
    log_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(2.0)); return 0;", expect: ["0.693"] },
    log_ten => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(10.0)); return 0;", expect: ["2.303"] },
    log_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(0.5)); return 0;", expect: ["-0.693"] },
    log_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(4.0)); return 0;", expect: ["1.386"] },
    log_point_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(0.1)); return 0;", expect: ["-2.303"] },
    log_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(3.0)); return 0;", expect: ["1.099"] },
    log_twenty => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(20.0)); return 0;", expect: ["2.996"] },
    log_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log(5.0)); return 0;", expect: ["1.609"] },
    log10_ten => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(10.0)); return 0;", expect: ["1.000"] },
    log10_fifty => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(50.0)); return 0;", expect: ["1.699"] },
    log10_tenth => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(0.1)); return 0;", expect: ["-1.000"] },
    log10_ten_thousand => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(10000.0)); return 0;", expect: ["4.000"] },
    log10_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(2.0)); return 0;", expect: ["0.301"] },
    log10_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(5.0)); return 0;", expect: ["0.699"] },
    log10_twenty => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(20.0)); return 0;", expect: ["1.301"] },
    log10_million => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log10(1000000.0)); return 0;", expect: ["6.000"] },
    log2_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(2.0)); return 0;", expect: ["1.000"] },
    log2_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(4.0)); return 0;", expect: ["2.000"] },
    log2_thirty_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(32.0)); return 0;", expect: ["5.000"] },
    log2_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(0.5)); return 0;", expect: ["-1.000"] },
    log2_thousand_twenty_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(1024.0)); return 0;", expect: ["10.000"] },
    log2_sixty_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(64.0)); return 0;", expect: ["6.000"] },
    log2_sixteen => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(16.0)); return 0;", expect: ["4.000"] },
    log2_one_twenty_eight => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log2(128.0)); return 0;", expect: ["7.000"] },
    exp2_negative_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp2(-1.0)); return 0;", expect: ["0.500"] },
    exp2_zero => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp2(0.0)); return 0;", expect: ["1.000"] },
    exp2_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", exp2(5.0)); return 0;", expect: ["32"] },
    exp2_negative_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp2(-2.0)); return 0;", expect: ["0.250"] },
    exp2_ten => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", exp2(10.0)); return 0;", expect: ["1024"] },
    exp2_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp2(1.0)); return 0;", expect: ["2.000"] },
    exp2_four => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.0f\\n\", exp2(4.0)); return 0;", expect: ["16"] },
    exp2_negative_three => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", exp2(-3.0)); return 0;", expect: ["0.125"] },
    expm1_negative_point_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", expm1(-0.1)); return 0;", expect: ["-0.095"] },
    expm1_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", expm1(1.0)); return 0;", expect: ["1.718"] },
    expm1_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", expm1(0.5)); return 0;", expect: ["0.649"] },
    expm1_negative_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", expm1(-1.0)); return 0;", expect: ["-0.632"] },
    expm1_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", expm1(2.0)); return 0;", expect: ["6.389"] },
    expm1_point_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", expm1(0.05)); return 0;", expect: ["0.051"] },
    log1p_negative_point_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(-0.1)); return 0;", expect: ["-0.105"] },
    log1p_one => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(1.0)); return 0;", expect: ["0.693"] },
    log1p_two => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(2.0)); return 0;", expect: ["1.099"] },
    log1p_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(0.5)); return 0;", expect: ["0.405"] },
    log1p_negative_half => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(-0.5)); return 0;", expect: ["-0.693"] },
    log1p_nine => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(9.0)); return 0;", expect: ["2.303"] },
    log1p_point_five => { includes: ["<stdio.h>", "<math.h>"], decls: "", body: "printf(\"%.3f\\n\", log1p(0.05)); return 0;", expect: ["0.049"] },
}
