//! inttypes.h PRI* macros — fixed values with asserted printf output.

use crate::helpers::*;

c_run_cases! {
    prid8_negative_ten => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int8_t v=-10; printf(\"%\" PRId8 \"\\n\", v); return 0;", expect: ["-10"] },
    prid16_negative_hundred => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int16_t v=-100; printf(\"%\" PRId16 \"\\n\", v); return 0;", expect: ["-100"] },
    prid32_negative_million => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int32_t v=-1000000; printf(\"%\" PRId32 \"\\n\", v); return 0;", expect: ["-1000000"] },
    prid64_negative_billion => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int64_t v=-1000000000LL; printf(\"%\" PRId64 \"\\n\", v); return 0;", expect: ["-1000000000"] },
    prii8_positive_forty_two => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int8_t v=42; printf(\"%\" PRIi8 \"\\n\", v); return 0;", expect: ["42"] },
    prii16_positive_two_fifty_five => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int16_t v=255; printf(\"%\" PRIi16 \"\\n\", v); return 0;", expect: ["255"] },
    prii32_zero => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int32_t v=0; printf(\"%\" PRIi32 \"\\n\", v); return 0;", expect: ["0"] },
    prii64_positive_trillion => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int64_t v=1000000000000LL; printf(\"%\" PRIi64 \"\\n\", v); return 0;", expect: ["1000000000000"] },
    priu8_max_byte => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=255; printf(\"%\" PRIu8 \"\\n\", v); return 0;", expect: ["255"] },
    priu16_sixty_five_k => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=65000; printf(\"%\" PRIu16 \"\\n\", v); return 0;", expect: ["65000"] },
    priu32_pattern_value => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=305419896U; printf(\"%\" PRIu32 \"\\n\", v); return 0;", expect: ["305419896"] },
    priu64_large_unsigned => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=18446744073709551615ULL; printf(\"%\" PRIu64 \"\\n\", v); return 0;", expect: ["18446744073709551615"] },
    prio8_octal_seventeen => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=15; printf(\"%\" PRIo8 \"\\n\", v); return 0;", expect: ["17"] },
    prio16_octal_four_digits => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=511; printf(\"%\" PRIo16 \"\\n\", v); return 0;", expect: ["777"] },
    prio32_octal_zero => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=0; printf(\"%\" PRIo32 \"\\n\", v); return 0;", expect: ["0"] },
    prio64_octal_eight => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=8; printf(\"%\" PRIo64 \"\\n\", v); return 0;", expect: ["10"] },
    prix8_hex_ff => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=255; printf(\"%\" PRIx8 \"\\n\", v); return 0;", expect: ["ff"] },
    prix16_hex_abcd => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=0xabcd; printf(\"%\" PRIx16 \"\\n\", v); return 0;", expect: ["abcd"] },
    prix32_hex_deadbeef => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=0xdeadbeefU; printf(\"%\" PRIx32 \"\\n\", v); return 0;", expect: ["deadbeef"] },
    prix64_hex_cafe => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=0xcafeULL; printf(\"%\" PRIx64 \"\\n\", v); return 0;", expect: ["cafe"] },
    prix8_uppercase_ab => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint8_t v=0xab; printf(\"%\" PRIX8 \"\\n\", v); return 0;", expect: ["AB"] },
    prix16_uppercase_face => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint16_t v=0xface; printf(\"%\" PRIX16 \"\\n\", v); return 0;", expect: ["FACE"] },
    prix32_uppercase_babe => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint32_t v=0xbabeU; printf(\"%\" PRIX32 \"\\n\", v); return 0;", expect: ["BABE"] },
    prix64_uppercase_feed => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint64_t v=0xfeedULL; printf(\"%\" PRIX64 \"\\n\", v); return 0;", expect: ["FEED"] },
    pridptr_null_as_zero => { includes: ["<stdio.h>", "<inttypes.h>", "<stdint.h>"], decls: "", body: "void *p=0; printf(\"%\" PRIdPTR \"\\n\", (intptr_t)p); return 0;", expect: ["0"] },
    priuptr_small_address => { includes: ["<stdio.h>", "<inttypes.h>", "<stdint.h>"], decls: "", body: "uintptr_t u=4096; printf(\"%\" PRIuPTR \"\\n\", u); return 0;", expect: ["4096"] },
    prixptr_hex_pattern => { includes: ["<stdio.h>", "<inttypes.h>", "<stdint.h>"], decls: "", body: "uintptr_t u=0x1000; printf(\"%\" PRIxPTR \"\\n\", u); return 0;", expect: ["1000"] },
    prioptr_octal_sixty_four => { includes: ["<stdio.h>", "<inttypes.h>", "<stdint.h>"], decls: "", body: "uintptr_t u=64; printf(\"%\" PRIoPTR \"\\n\", u); return 0;", expect: ["100"] },
    pridmax_negative_one => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "intmax_t v=-1; printf(\"%\" PRIdMAX \"\\n\", v); return 0;", expect: ["-1"] },
    priimax_positive_ninety_nine => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "intmax_t v=99; printf(\"%\" PRIiMAX \"\\n\", v); return 0;", expect: ["99"] },
    priumax_unsigned_twelve => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uintmax_t v=12; printf(\"%\" PRIuMAX \"\\n\", v); return 0;", expect: ["12"] },
    priomax_octal_twenty => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uintmax_t v=16; printf(\"%\" PRIoMAX \"\\n\", v); return 0;", expect: ["20"] },
    prixmax_hex_twenty_six => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uintmax_t v=26; printf(\"%\" PRIxMAX \"\\n\", v); return 0;", expect: ["1a"] },
    prixmax_uppercase_thirty_four => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uintmax_t v=34; printf(\"%\" PRIXMAX \"\\n\", v); return 0;", expect: ["22"] },
    pridleast8_five => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_least8_t v=5; printf(\"%\" PRIdLEAST8 \"\\n\", v); return 0;", expect: ["5"] },
    pridleast16_minus_three => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_least16_t v=-3; printf(\"%\" PRIdLEAST16 \"\\n\", v); return 0;", expect: ["-3"] },
    pridleast32_seven => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_least32_t v=7; printf(\"%\" PRIdLEAST32 \"\\n\", v); return 0;", expect: ["7"] },
    pridleast64_eight => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_least64_t v=8; printf(\"%\" PRIdLEAST64 \"\\n\", v); return 0;", expect: ["8"] },
    priuleast8_nine => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_least8_t v=9; printf(\"%\" PRIuLEAST8 \"\\n\", v); return 0;", expect: ["9"] },
    priuleast16_eleven => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_least16_t v=11; printf(\"%\" PRIuLEAST16 \"\\n\", v); return 0;", expect: ["11"] },
    priuleast32_thirteen => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_least32_t v=13; printf(\"%\" PRIuLEAST32 \"\\n\", v); return 0;", expect: ["13"] },
    priuleast64_fifteen => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_least64_t v=15; printf(\"%\" PRIuLEAST64 \"\\n\", v); return 0;", expect: ["15"] },
    pridfast8_twenty => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_fast8_t v=20; printf(\"%\" PRIdFAST8 \"\\n\", v); return 0;", expect: ["20"] },
    pridfast16_twenty_one => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_fast16_t v=21; printf(\"%\" PRIdFAST16 \"\\n\", v); return 0;", expect: ["21"] },
    pridfast32_twenty_two => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_fast32_t v=22; printf(\"%\" PRIdFAST32 \"\\n\", v); return 0;", expect: ["22"] },
    pridfast64_twenty_three => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "int_fast64_t v=23; printf(\"%\" PRIdFAST64 \"\\n\", v); return 0;", expect: ["23"] },
    priufast8_twenty_four => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_fast8_t v=24; printf(\"%\" PRIuFAST8 \"\\n\", v); return 0;", expect: ["24"] },
    priufast16_twenty_five => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_fast16_t v=25; printf(\"%\" PRIuFAST16 \"\\n\", v); return 0;", expect: ["25"] },
    priufast32_twenty_six => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_fast32_t v=26; printf(\"%\" PRIuFAST32 \"\\n\", v); return 0;", expect: ["26"] },
    priufast64_twenty_seven => { includes: ["<stdio.h>", "<inttypes.h>"], decls: "", body: "uint_fast64_t v=27; printf(\"%\" PRIuFAST64 \"\\n\", v); return 0;", expect: ["27"] },
}
