//! ctype.h is* — distinct probe characters per classification function.

c_run_cases! {
    isalpha_on_m_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalpha('m')!=0); return 0;", expect: ["1"] },
    isalpha_on_4_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalpha('4')!=0); return 0;", expect: ["0"] },
    isdigit_on_7_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isdigit('7')!=0); return 0;", expect: ["1"] },
    isdigit_on_k_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isdigit('K')!=0); return 0;", expect: ["0"] },
    isalnum_on_b_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalnum('B')!=0); return 0;", expect: ["1"] },
    isalnum_on_hash_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalnum('#')!=0); return 0;", expect: ["0"] },
    isupper_on_r_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isupper('R')!=0); return 0;", expect: ["1"] },
    isupper_on_r_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isupper('r')!=0); return 0;", expect: ["0"] },
    islower_on_j_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", islower('j')!=0); return 0;", expect: ["1"] },
    islower_on_j_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", islower('J')!=0); return 0;", expect: ["0"] },
    isxdigit_on_c_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isxdigit('C')!=0); return 0;", expect: ["1"] },
    isxdigit_on_p_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isxdigit('P')!=0); return 0;", expect: ["0"] },
    ispunct_on_colon_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", ispunct(':')!=0); return 0;", expect: ["1"] },
    ispunct_on_9_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", ispunct('9')!=0); return 0;", expect: ["0"] },
    isspace_on_tab_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isspace('\\t')!=0); return 0;", expect: ["1"] },
    isspace_on_v_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isspace('v')!=0); return 0;", expect: ["0"] },
    isblank_on_space_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isblank(' ')!=0); return 0;", expect: ["1"] },
    isblank_on_newline_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isblank('\\n')!=0); return 0;", expect: ["0"] },
    isprint_on_tilde_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isprint('~')!=0); return 0;", expect: ["1"] },
    isprint_on_bell_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isprint('\\a')!=0); return 0;", expect: ["0"] },
    iscntrl_on_cr_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", iscntrl('\\r')!=0); return 0;", expect: ["1"] },
    iscntrl_on_w_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", iscntrl('w')!=0); return 0;", expect: ["0"] },
    isgraph_on_dollar_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isgraph('$')!=0); return 0;", expect: ["1"] },
    isgraph_on_space_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isgraph(' ')!=0); return 0;", expect: ["0"] },
    isalpha_on_q_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalpha('Q')!=0); return 0;", expect: ["1"] },
    isdigit_on_0_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isdigit('0')!=0); return 0;", expect: ["1"] },
    isxdigit_on_f_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isxdigit('f')!=0); return 0;", expect: ["1"] },
    isxdigit_on_g_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isxdigit('g')!=0); return 0;", expect: ["0"] },
    ispunct_on_brace_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", ispunct('{')!=0); return 0;", expect: ["1"] },
    isspace_on_newline_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isspace('\\n')!=0); return 0;", expect: ["1"] },
    isblank_on_tab_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isblank('\\t')!=0); return 0;", expect: ["1"] },
    isprint_on_digit_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isprint('3')!=0); return 0;", expect: ["1"] },
    iscntrl_on_esc_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", iscntrl('\\x1b')!=0); return 0;", expect: ["1"] },
    isgraph_on_plus_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isgraph('+')!=0); return 0;", expect: ["1"] },
    isalnum_on_8_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalnum('8')!=0); return 0;", expect: ["1"] },
    isupper_on_z_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isupper('Z')!=0); return 0;", expect: ["1"] },
    islower_on_z_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", islower('z')!=0); return 0;", expect: ["1"] },
    isalpha_on_underscore_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalpha('_')!=0); return 0;", expect: ["0"] },
    isdigit_on_plus_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isdigit('+')!=0); return 0;", expect: ["0"] },
    ispunct_on_comma_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", ispunct(',')!=0); return 0;", expect: ["1"] },
    isspace_on_formfeed_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isspace('\\f')!=0); return 0;", expect: ["1"] },
    isprint_on_space_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isprint(' ')!=0); return 0;", expect: ["1"] },
    iscntrl_on_null_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", iscntrl('\\0')!=0); return 0;", expect: ["1"] },
    isgraph_on_letter_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isgraph('n')!=0); return 0;", expect: ["1"] },
    isalnum_on_at_reject => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isalnum('@')!=0); return 0;", expect: ["0"] },
    isxdigit_on_9_accept => { includes: ["<stdio.h>", "<ctype.h>"], decls: "", body: "printf(\"%d\\n\", isxdigit('9')!=0); return 0;", expect: ["1"] },
}
