//! stdlib.h conversions, div family, atexit registration, getenv assertions.

c_run_cases! {
    strtol_leading_whitespace => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"   77\", 0, 10)); return 0;", expect: ["77"] },
    strtol_leading_plus_sign => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"+15\", 0, 10)); return 0;", expect: ["15"] },
    strtol_trailing_non_numeric => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "char *e; printf(\"%ld\\n\", strtol(\"99px\", &e, 10)); return 0;", expect: ["99"] },
    strtol_endptr_at_suffix => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "char *e; strtol(\"42end\", &e, 10); printf(\"%c\\n\", *e); return 0;", expect: ["e"] },
    strtol_base_zero_hex_prefix => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"0x20\", 0, 0)); return 0;", expect: ["32"] },
    strtol_base_zero_octal_prefix => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"020\", 0, 0)); return 0;", expect: ["16"] },
    strtol_base_zero_plain_decimal => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"31\", 0, 0)); return 0;", expect: ["31"] },
    strtol_hex_uppercase => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"AB\", 0, 16)); return 0;", expect: ["171"] },
    strtol_hex_lowercase => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"cd\", 0, 16)); return 0;", expect: ["205"] },
    strtol_empty_returns_zero => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"\", 0, 10)); return 0;", expect: ["0"] },
    strtol_only_sign_returns_zero => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%ld\\n\", strtol(\"-\", 0, 10)); return 0;", expect: ["0"] },
    strtoul_large_unsigned => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%lu\\n\", strtoul(\"4000000000\", 0, 10)); return 0;", expect: ["4000000000"] },
    strtoul_hex_ff => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%lu\\n\", strtoul(\"ff\", 0, 16)); return 0;", expect: ["255"] },
    strtoul_octal_ten => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%lu\\n\", strtoul(\"12\", 0, 8)); return 0;", expect: ["10"] },
    strtoll_negative_large => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%lld\\n\", strtoll(\"-5000000000\", 0, 10)); return 0;", expect: ["-5000000000"] },
    strtoll_positive_hex => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%lld\\n\", strtoll(\"0x10\", 0, 0)); return 0;", expect: ["16"] },
    strtoull_max_range => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%llu\\n\", strtoull(\"18446744073709551615\", 0, 10)); return 0;", expect: ["18446744073709551615"] },
    strtoull_with_suffix_endptr => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "char *e; strtoull(\"100u\", &e, 10); printf(\"%c\\n\", *e); return 0;", expect: ["u"] },
    strtod_leading_whitespace => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%.2f\\n\", strtod(\"  2.50\", 0)); return 0;", expect: ["2.50"] },
    strtod_negative_fraction => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%.1f\\n\", strtod(\"-0.5\", 0)); return 0;", expect: ["-0.5"] },
    strtod_exponent_negative => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%.3f\\n\", strtod(\"1e-2\", 0)); return 0;", expect: ["0.010"] },
    strtod_hex_not_parsed => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "char *e; printf(\"%.0f\\n\", strtod(\"0x1.0\", &e)); return 0;", expect: ["0"] },
    strtof_single_precision => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%.2f\\n\", (double)strtof(\"6.25\", 0)); return 0;", expect: ["6.25"] },
    strtold_long_double => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%.1f\\n\", (double)strtold(\"9.5\", 0)); return 0;", expect: ["9.5"] },
    div_negative_dividend => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "div_t r = div(-10, 3); printf(\"%d %d\\n\", r.quot, r.rem); return 0;", expect: ["-3 1"] },
    div_zero_remainder => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "div_t r = div(20, 5); printf(\"%d %d\\n\", r.quot, r.rem); return 0;", expect: ["4 0"] },
    div_small_values => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "div_t r = div(7, 2); printf(\"%d\\n\", r.rem); return 0;", expect: ["1"] },
    ldiv_long_negative => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "ldiv_t r = ldiv(-17L, 5L); printf(\"%ld %ld\\n\", r.quot, r.rem); return 0;", expect: ["-3 2"] },
    ldiv_long_quotient_only => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "ldiv_t r = ldiv(100L, 9L); printf(\"%ld\\n\", r.quot); return 0;", expect: ["11"] },
    ldiv_long_remainder_only => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "ldiv_t r = ldiv(100L, 9L); printf(\"%ld\\n\", r.rem); return 0;", expect: ["1"] },
    lldiv_longlong_negative => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "lldiv_t r = lldiv(-25LL, 4LL); printf(\"%lld %lld\\n\", r.quot, r.rem); return 0;", expect: ["-6 1"] },
    lldiv_longlong_quotient => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "lldiv_t r = lldiv(50LL, 6LL); printf(\"%lld\\n\", r.quot); return 0;", expect: ["8"] },
    lldiv_longlong_remainder => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "lldiv_t r = lldiv(50LL, 6LL); printf(\"%lld\\n\", r.rem); return 0;", expect: ["2"] },
    getenv_path_non_null => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%d\\n\", getenv(\"PATH\") != 0); return 0;", expect: ["1"] },
    getenv_missing_var_null => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "printf(\"%d\\n\", getenv(\"__VYBE_NO_SUCH_ENV__\") == 0); return 0;", expect: ["1"] },
    getenv_after_setenv_value => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "setenv(\"VYBE_STDTEST\", \"alpha\", 1); printf(\"%s\\n\", getenv(\"VYBE_STDTEST\")); return 0;", expect: ["alpha"] },
    getenv_setenv_overwrite => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "setenv(\"VYBE_OVR\", \"one\", 1); setenv(\"VYBE_OVR\", \"two\", 1); printf(\"%s\\n\", getenv(\"VYBE_OVR\")); return 0;", expect: ["two"] },
    getenv_unsetenv_removed => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "setenv(\"VYBE_TMP\", \"x\", 1); unsetenv(\"VYBE_TMP\"); printf(\"%d\\n\", getenv(\"VYBE_TMP\") == 0); return 0;", expect: ["1"] },
    putenv_updates_value => { includes: ["<stdio.h>", "<stdlib.h>"], decls: "", body: "setenv(\"VYBE_PUT\", \"old\", 1); putenv(\"VYBE_PUT=new\"); printf(\"%s\\n\", getenv(\"VYBE_PUT\")); return 0;", expect: ["new"] },
}

c_compile_cases! {
    atexit_single_handler_compile => { includes: ["<stdlib.h>"], decls: "void h(void){}", body: "atexit(h); return 0;" },
    atexit_two_handlers_compile => { includes: ["<stdlib.h>"], decls: "void a(void){} void b(void){}", body: "atexit(a); atexit(b); return 0;" },
    atexit_three_handlers_lifo_compile => { includes: ["<stdlib.h>"], decls: "void f(void){} void g(void){} void h(void){}", body: "atexit(f); atexit(g); atexit(h); return 0;" },
    atexit_after_other_stmts_compile => { includes: ["<stdlib.h>"], decls: "void done(void){}", body: "int x=1; (void)x; atexit(done); return 0;" },
    atexit_with_static_function_compile => { includes: ["<stdlib.h>"], decls: "static void s(void){}", body: "atexit(s); return 0;" },
    atexit_null_check_compile => { includes: ["<stdlib.h>"], decls: "void z(void){}", body: "return atexit(z) == 0;" },
    atexit_multiple_same_handler_compile => { includes: ["<stdlib.h>"], decls: "void same(void){}", body: "atexit(same); atexit(same); return 0;" },
    atexit_before_return_compile => { includes: ["<stdlib.h>"], decls: "void fin(void){}", body: "atexit(fin); return 0;" },
    atexit_nested_scope_compile => { includes: ["<stdlib.h>"], decls: "void outer(void){}", body: "{ atexit(outer); } return 0;" },
    atexit_with_conditional_compile => { includes: ["<stdlib.h>"], decls: "void c(void){}", body: "if (1) atexit(c); return 0;" },
    atexit_void_returning_handler_compile => { includes: ["<stdlib.h>"], decls: "void vr(void){ return; }", body: "atexit(vr); return 0;" },
}
