//! goto forward and backward jumps, labels inside loops and switch.


c_run_cases! {
    goto_forward_skips_dead_statement => { includes: ["<stdio.h>"], decls: "", body: "printf(\"a\\n\"); goto end; printf(\"skip\\n\"); end: printf(\"b\\n\"); return 0;", expect: ["a", "b"] },
    goto_backward_counts_three_times => { includes: ["<stdio.h>"], decls: "", body: "int n=0; again: n++; if(n<3) goto again; printf(\"%d\\n\", n); return 0;", expect: ["3"] },
    goto_from_if_branch_to_shared_label => { includes: ["<stdio.h>"], decls: "", body: "int v=1; if(v) goto L; printf(\"no\\n\"); L: printf(\"yes\\n\"); return 0;", expect: ["yes"] },
    goto_from_else_branch_to_cleanup => { includes: ["<stdio.h>"], decls: "", body: "int v=0; if(v) printf(\"yes\\n\"); else goto done; printf(\"mid\\n\"); done: printf(\"end\\n\"); return 0;", expect: ["end"] },
    goto_exits_inner_for_early => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<5;i++){ if(i==2) goto out; printf(\"%d\\n\", i); } out: printf(\"done\\n\"); return 0;", expect: ["0", "1", "done"] },
    goto_exits_while_from_middle => { includes: ["<stdio.h>"], decls: "", body: "int i=0; while(i<4){ i++; if(i==3) goto stop; printf(\"%d\\n\", i); } stop: printf(\"x\\n\"); return 0;", expect: ["1", "2", "x"] },
    goto_inside_do_while_restarts_once => { includes: ["<stdio.h>"], decls: "", body: "int i=0; do{ i++; if(i==1) goto retry; printf(\"%d\\n\", i); break; retry: printf(\"r\\n\"); }while(0); return 0;", expect: ["r"] },
    goto_from_switch_case_to_after_switch => { includes: ["<stdio.h>"], decls: "", body: "switch(2){ case 1: printf(\"1\\n\"); break; case 2: goto leave; case 3: printf(\"3\\n\"); } leave: printf(\"out\\n\"); return 0;", expect: ["out"] },
    goto_within_switch_case_body => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"a\\n\"); goto inner; inner: printf(\"b\\n\"); break; } return 0;", expect: ["a", "b"] },
    goto_backward_in_switch_case_loop => { includes: ["<stdio.h>"], decls: "", body: "int x=1; switch(x){ case 1: { int k=0; loop: k++; if(k<2) goto loop; printf(\"%d\\n\", k); } break; } return 0;", expect: ["2"] },
    goto_over_declaration_with_braced_case => { includes: ["<stdio.h>"], decls: "", body: "goto L; L: { int z=4; printf(\"%d\\n\", z); } return 0;", expect: ["4"] },
    goto_error_path_skips_success_print => { includes: ["<stdio.h>"], decls: "", body: "int ok=0; if(!ok) goto fail; printf(\"ok\\n\"); fail: printf(\"fail\\n\"); return 0;", expect: ["fail"] },
    goto_chain_through_two_labels => { includes: ["<stdio.h>"], decls: "", body: "goto A; A: goto B; B: printf(\"1\\n\"); return 0;", expect: ["1"] },
    goto_from_nested_if_to_outer_label => { includes: ["<stdio.h>"], decls: "", body: "int a=1,b=2; if(a){ if(b) goto fin; } printf(\"no\\n\"); fin: printf(\"fin\\n\"); return 0;", expect: ["fin"] },
    goto_breaks_out_of_nested_loops => { includes: ["<stdio.h>"], decls: "", body: "int i,j; for(i=0;i<2;i++) for(j=0;j<2;j++){ if(i==1&&j==1) goto done; } done: printf(\"1\\n\"); return 0;", expect: ["1"] },
    goto_forward_to_label_after_return_path => { includes: ["<stdio.h>"], decls: "", body: "int x=5; if(x>0) goto pos; printf(\"neg\\n\"); return 1; pos: printf(\"pos\\n\"); return 0;", expect: ["pos"] },
    goto_backward_decrement_until_zero => { includes: ["<stdio.h>"], decls: "", body: "int n=3; top: n--; if(n>=0){ printf(\"%d\\n\", n); goto top; } return 0;", expect: ["2", "1", "0"] },
    goto_in_function_to_single_return => {
        includes: ["<stdio.h>"],
        decls: "int pick(int v){ if(v<0) goto bad; return v; bad: return -1; }",
        body: "printf(\"%d\\n\", pick(-1)); return 0;",
        expect: ["-1"]
    },
    goto_in_function_success_path => {
        includes: ["<stdio.h>"],
        decls: "int pick(int v){ if(v<0) goto bad; return v; bad: return -1; }",
        body: "printf(\"%d\\n\", pick(4)); return 0;",
        expect: ["4"]
    },
    goto_skips_switch_default => { includes: ["<stdio.h>"], decls: "", body: "goto end; switch(0){ default: printf(\"d\\n\"); } end: printf(\"e\\n\"); return 0;", expect: ["e"] },
    goto_into_switch_after_case_label => { includes: ["<stdio.h>"], decls: "", body: "goto entry; switch(1){ case 1: entry: printf(\"hit\\n\"); break; } return 0;", expect: ["hit"] },
    goto_from_for_increment_section => { includes: ["<stdio.h>"], decls: "", body: "int i=0; for(;i<3;i++){ if(i==1) goto out; printf(\"%d\\n\", i); } out: printf(\"o\\n\"); return 0;", expect: ["0", "o"] },
    goto_clears_nested_block_without_running => { includes: ["<stdio.h>"], decls: "", body: "goto out; { printf(\"in\\n\"); } out: printf(\"out\\n\"); return 0;", expect: ["out"] },
    goto_backward_while_one_iteration_print => { includes: ["<stdio.h>"], decls: "", body: "int t=0; start: t++; printf(\"%d\\n\", t); if(t<2) goto start; return 0;", expect: ["1", "2"] },
    goto_from_case_fallthrough_region => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"a\\n\"); case 2: goto end; printf(\"b\\n\"); } end: printf(\"z\\n\"); return 0;", expect: ["a", "z"] },
    goto_label_before_declaration_in_block => { includes: ["<stdio.h>"], decls: "", body: "goto L; { L: int v=2; printf(\"%d\\n\", v); } return 0;", expect: ["2"] },
    goto_multiple_forward_targets_via_condition => { includes: ["<stdio.h>"], decls: "", body: "int s=2; if(s==1) goto one; if(s==2) goto two; goto three; one: printf(\"1\\n\"); goto end; two: printf(\"2\\n\"); goto end; three: printf(\"3\\n\"); end: return 0;", expect: ["2"] },
    goto_exits_switch_inside_loop => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<2;i++){ switch(i){ case 1: goto leave; default: printf(\"%d\\n\", i); } } leave: printf(\"x\\n\"); return 0;", expect: ["0", "x"] },
    goto_from_nested_switch_to_outer_label => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: switch(2){ case 2: goto out; } break; } out: printf(\"1\\n\"); return 0;", expect: ["1"] },
    goto_backward_with_accumulator => { includes: ["<stdio.h>"], decls: "", body: "int sum=0,n=3; again: sum+=n; n--; if(n>0) goto again; printf(\"%d\\n\", sum); return 0;", expect: ["6"] },
    goto_forward_past_empty_statement => { includes: ["<stdio.h>"], decls: "", body: "goto L;; L: printf(\"1\\n\"); return 0;", expect: ["1"] },
    goto_from_while_to_function_epilogue => {
        includes: ["<stdio.h>"],
        decls: "int run(void){ int i=0; while(1){ if(i==2) goto done; i++; } done: return i; }",
        body: "printf(\"%d\\n\", run()); return 0;",
        expect: ["2"]
    },
    goto_skips_else_after_if_goto => { includes: ["<stdio.h>"], decls: "", body: "int x=1; if(x) goto L; else printf(\"e\\n\"); L: printf(\"L\\n\"); return 0;", expect: ["L"] },
    goto_in_nested_for_inner_only => { includes: ["<stdio.h>"], decls: "", body: "int i,j; for(i=0;i<2;i++){ for(j=0;j<2;j++){ if(j==1) goto next; printf(\"%d%d\\n\", i,j); } next: ; } return 0;", expect: ["00", "10"] },
    goto_to_label_after_switch_break_path => { includes: ["<stdio.h>"], decls: "", body: "switch(1){ case 1: printf(\"s\\n\"); break; } goto tail; tail: printf(\"t\\n\"); return 0;", expect: ["s", "t"] },
    goto_backward_switch_case_counter => { includes: ["<stdio.h>"], decls: "", body: "int c=0; switch(0){ default: tick: c++; if(c<2) goto tick; printf(\"%d\\n\", c); } return 0;", expect: ["2"] },
    goto_from_if_in_while_to_after_while => { includes: ["<stdio.h>"], decls: "", body: "int i=0; while(i<5){ if(i==2) goto exit; i++; } exit: printf(\"%d\\n\", i); return 0;", expect: ["2"] },
    goto_forward_across_variable_init => { includes: ["<stdio.h>"], decls: "", body: "int a=1; goto M; int b=2; (void)b; M: printf(\"%d\\n\", a); return 0;", expect: ["1"] },
    goto_cleanup_after_partial_work => { includes: ["<stdio.h>"], decls: "", body: "int step=1; if(step==1){ printf(\"work\\n\"); goto cleanup; } printf(\"more\\n\"); cleanup: printf(\"clean\\n\"); return 0;", expect: ["work", "clean"] },
    goto_from_do_while_condition_false_path => { includes: ["<stdio.h>"], decls: "", body: "int i=0; do{ i++; if(i==1) goto fin; }while(0); printf(\"no\\n\"); fin: printf(\"%d\\n\", i); return 0;", expect: ["1"] },
    goto_label_same_name_as_variable_ok => { includes: ["<stdio.h>"], decls: "", body: "int end=0; goto end_label; end_label: printf(\"%d\\n\", end); return 0;", expect: ["0"] },
    goto_from_nested_block_to_function_scope_label => { includes: ["<stdio.h>"], decls: "", body: "int v=0; { if(1) goto mark; } mark: v=3; printf(\"%d\\n\", v); return 0;", expect: ["3"] },
    goto_switch_case_with_break_after_target => { includes: ["<stdio.h>"], decls: "", body: "switch(3){ case 3: goto done; printf(\"n\\n\"); done: printf(\"d\\n\"); break; } return 0;", expect: ["d"] },
    goto_forward_then_backward_small_cycle => { includes: ["<stdio.h>"], decls: "", body: "int x=0; start: x++; if(x==1){ goto mid; } printf(\"%d\\n\", x); goto end; mid: goto start; end: return 0;", expect: ["2"] },
    goto_from_for_body_to_outer_label => { includes: ["<stdio.h>"], decls: "", body: "int i; for(i=0;i<4;i++){ if(i==2) goto stop; printf(\"%d\\n\", i); } stop: printf(\"s\\n\"); return 0;", expect: ["0", "1", "s"] },
    goto_in_if_else_ladder_middle => { includes: ["<stdio.h>"], decls: "", body: "int v=2; if(v==1) printf(\"1\\n\"); else if(v==2) goto two; else printf(\"x\\n\"); printf(\"no\\n\"); two: printf(\"2\\n\"); return 0;", expect: ["2"] },
    goto_backward_from_label_after_printf => { includes: ["<stdio.h>"], decls: "", body: "int n=2; top: printf(\"%d\\n\", n); n--; if(n) goto top; return 0;", expect: ["2", "1"] },
}
