//! errno.h — distinct named error constants and strerror output checks.


c_run_cases! {
    errno_starts_at_zero => { includes: ["<stdio.h>", "<errno.h>"], decls: "", body: "errno=0; printf(\"%d\\n\", errno); return 0;", expect: ["0"] },
    errno_assign_and_read => { includes: ["<stdio.h>", "<errno.h>"], decls: "", body: "errno=EINVAL; printf(\"%d\\n\", errno==EINVAL); return 0;", expect: ["1"] },
    strerror_einval_nonempty => { includes: ["<stdio.h>", "<string.h>", "<errno.h>"], decls: "", body: "printf(\"%d\\n\", strerror(EINVAL)[0] != '\\0'); return 0;", expect: ["1"] },
    strerror_erange_nonempty => { includes: ["<stdio.h>", "<string.h>", "<errno.h>"], decls: "", body: "printf(\"%d\\n\", strerror(ERANGE)[0] != '\\0'); return 0;", expect: ["1"] },
    strerror_edomain_nonempty => { includes: ["<stdio.h>", "<string.h>", "<errno.h>"], decls: "", body: "printf(\"%d\\n\", strerror(EDOM)[0] != '\\0'); return 0;", expect: ["1"] },
    perror_sets_no_crash => { includes: ["<stdio.h>", "<errno.h>"], decls: "", body: "errno=EINVAL; perror(\"tag\"); printf(\"1\\n\"); return 0;", expect: ["1"] },
}

c_compile_cases! {
    errno_eperm_constant => { includes: ["<errno.h>"], decls: "", body: "return EPERM;" },
    errno_enoent_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOENT;" },
    errno_esrch_constant => { includes: ["<errno.h>"], decls: "", body: "return ESRCH;" },
    errno_eintr_constant => { includes: ["<errno.h>"], decls: "", body: "return EINTR;" },
    errno_eio_constant => { includes: ["<errno.h>"], decls: "", body: "return EIO;" },
    errno_enxio_constant => { includes: ["<errno.h>"], decls: "", body: "return ENXIO;" },
    errno_e2big_constant => { includes: ["<errno.h>"], decls: "", body: "return E2BIG;" },
    errno_enoexec_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOEXEC;" },
    errno_ebadf_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADF;" },
    errno_echild_constant => { includes: ["<errno.h>"], decls: "", body: "return ECHILD;" },
    errno_eagain_constant => { includes: ["<errno.h>"], decls: "", body: "return EAGAIN;" },
    errno_enomem_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOMEM;" },
    errno_eacces_constant => { includes: ["<errno.h>"], decls: "", body: "return EACCES;" },
    errno_efault_constant => { includes: ["<errno.h>"], decls: "", body: "return EFAULT;" },
    errno_enotblk_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOTBLK;" },
    errno_ebusy_constant => { includes: ["<errno.h>"], decls: "", body: "return EBUSY;" },
    errno_eexist_constant => { includes: ["<errno.h>"], decls: "", body: "return EEXIST;" },
    errno_exdev_constant => { includes: ["<errno.h>"], decls: "", body: "return EXDEV;" },
    errno_enodev_constant => { includes: ["<errno.h>"], decls: "", body: "return ENODEV;" },
    errno_enotdir_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOTDIR;" },
    errno_eisdir_constant => { includes: ["<errno.h>"], decls: "", body: "return EISDIR;" },
    errno_einval_constant => { includes: ["<errno.h>"], decls: "", body: "return EINVAL;" },
    errno_enfile_constant => { includes: ["<errno.h>"], decls: "", body: "return ENFILE;" },
    errno_emfile_constant => { includes: ["<errno.h>"], decls: "", body: "return EMFILE;" },
    errno_enotty_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOTTY;" },
    errno_etxtbsy_constant => { includes: ["<errno.h>"], decls: "", body: "return ETXTBSY;" },
    errno_efbig_constant => { includes: ["<errno.h>"], decls: "", body: "return EFBIG;" },
    errno_enospc_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOSPC;" },
    errno_espipe_constant => { includes: ["<errno.h>"], decls: "", body: "return ESPIPE;" },
    errno_erofs_constant => { includes: ["<errno.h>"], decls: "", body: "return EROFS;" },
    errno_emlink_constant => { includes: ["<errno.h>"], decls: "", body: "return EMLINK;" },
    errno_epipe_constant => { includes: ["<errno.h>"], decls: "", body: "return EPIPE;" },
    errno_edom_constant => { includes: ["<errno.h>"], decls: "", body: "return EDOM;" },
    errno_erange_constant => { includes: ["<errno.h>"], decls: "", body: "return ERANGE;" },
    errno_enomsg_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOMSG;" },
    errno_eidrm_constant => { includes: ["<errno.h>"], decls: "", body: "return EIDRM;" },
    errno_echrng_constant => { includes: ["<errno.h>"], decls: "", body: "return ECHRNG;" },
    errno_el2nsync_constant => { includes: ["<errno.h>"], decls: "", body: "return EL2NSYNC;" },
    errno_el3hlt_constant => { includes: ["<errno.h>"], decls: "", body: "return EL3HLT;" },
    errno_el3rst_constant => { includes: ["<errno.h>"], decls: "", body: "return EL3RST;" },
    errno_elnrng_constant => { includes: ["<errno.h>"], decls: "", body: "return ELNRNG;" },
    errno_eunatch_constant => { includes: ["<errno.h>"], decls: "", body: "return EUNATCH;" },
    errno_enocsi_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOCSI;" },
    errno_el2hlt_constant => { includes: ["<errno.h>"], decls: "", body: "return EL2HLT;" },
    errno_ebade_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADE;" },
    errno_ebadr_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADR;" },
    errno_exfull_constant => { includes: ["<errno.h>"], decls: "", body: "return EXFULL;" },
    errno_enoano_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOANO;" },
    errno_ebadrqc_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADRQC;" },
    errno_ebadslt_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADSLT;" },
    errno_edeadlk_constant => { includes: ["<errno.h>"], decls: "", body: "return EDEADLK;" },
    errno_ebfont_constant => { includes: ["<errno.h>"], decls: "", body: "return EBFONT;" },
    errno_enostr_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOSTR;" },
    errno_enodata_constant => { includes: ["<errno.h>"], decls: "", body: "return ENODATA;" },
    errno_etime_constant => { includes: ["<errno.h>"], decls: "", body: "return ETIME;" },
    errno_enosr_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOSR;" },
    errno_enonet_constant => { includes: ["<errno.h>"], decls: "", body: "return ENONET;" },
    errno_enopkg_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOPKG;" },
    errno_eremote_constant => { includes: ["<errno.h>"], decls: "", body: "return EREMOTE;" },
    errno_enolink_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOLINK;" },
    errno_eadv_constant => { includes: ["<errno.h>"], decls: "", body: "return EADV;" },
    errno_esrmnt_constant => { includes: ["<errno.h>"], decls: "", body: "return ESRMNT;" },
    errno_ecomm_constant => { includes: ["<errno.h>"], decls: "", body: "return ECOMM;" },
    errno_eproto_constant => { includes: ["<errno.h>"], decls: "", body: "return EPROTO;" },
    errno_emultihop_constant => { includes: ["<errno.h>"], decls: "", body: "return EMULTIHOP;" },
    errno_edotdot_constant => { includes: ["<errno.h>"], decls: "", body: "return EDOTDOT;" },
    errno_ebadmsg_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADMSG;" },
    errno_eoverflow_constant => { includes: ["<errno.h>"], decls: "", body: "return EOVERFLOW;" },
    errno_enotuniq_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOTUNIQ;" },
    errno_ebadfd_constant => { includes: ["<errno.h>"], decls: "", body: "return EBADFD;" },
    errno_eremchg_constant => { includes: ["<errno.h>"], decls: "", body: "return EREMCHG;" },
    errno_elibacc_constant => { includes: ["<errno.h>"], decls: "", body: "return ELIBACC;" },
    errno_elibbad_constant => { includes: ["<errno.h>"], decls: "", body: "return ELIBBAD;" },
    errno_elibscn_constant => { includes: ["<errno.h>"], decls: "", body: "return ELIBSCN;" },
    errno_elibmax_constant => { includes: ["<errno.h>"], decls: "", body: "return ELIBMAX;" },
    errno_elibexec_constant => { includes: ["<errno.h>"], decls: "", body: "return ELIBEXEC;" },
    errno_eilseq_constant => { includes: ["<errno.h>"], decls: "", body: "return EILSEQ;" },
    errno_enosys_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOSYS;" },
    errno_eloop_constant => { includes: ["<errno.h>"], decls: "", body: "return ELOOP;" },
    errno_ewouldblock_constant => { includes: ["<errno.h>"], decls: "", body: "return EWOULDBLOCK;" },
    errno_enomsg_not_equal_zero => { includes: ["<errno.h>"], decls: "", body: "return ENOMSG != 0;" },
    errno_einprogress_constant => { includes: ["<errno.h>"], decls: "", body: "return EINPROGRESS;" },
    errno_ealready_constant => { includes: ["<errno.h>"], decls: "", body: "return EALREADY;" },
    errno_enotsock_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOTSOCK;" },
    errno_edestaddrreq_constant => { includes: ["<errno.h>"], decls: "", body: "return EDESTADDRREQ;" },
    errno_emsgsize_constant => { includes: ["<errno.h>"], decls: "", body: "return EMSGSIZE;" },
    errno_eprototype_constant => { includes: ["<errno.h>"], decls: "", body: "return EPROTOTYPE;" },
    errno_enoprotoopt_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOPROTOOPT;" },
    errno_eprotonosupport_constant => { includes: ["<errno.h>"], decls: "", body: "return EPROTONOSUPPORT;" },
    errno_esocktnosupport_constant => { includes: ["<errno.h>"], decls: "", body: "return ESOCKTNOSUPPORT;" },
    errno_eopnotsupp_constant => { includes: ["<errno.h>"], decls: "", body: "return EOPNOTSUPP;" },
    errno_epfnosupport_constant => { includes: ["<errno.h>"], decls: "", body: "return EPFNOSUPPORT;" },
    errno_eafnosupport_constant => { includes: ["<errno.h>"], decls: "", body: "return EAFNOSUPPORT;" },
    errno_eaddrinuse_constant => { includes: ["<errno.h>"], decls: "", body: "return EADDRINUSE;" },
    errno_eaddrnotavail_constant => { includes: ["<errno.h>"], decls: "", body: "return EADDRNOTAVAIL;" },
    errno_enetdown_constant => { includes: ["<errno.h>"], decls: "", body: "return ENETDOWN;" },
    errno_enetunreach_constant => { includes: ["<errno.h>"], decls: "", body: "return ENETUNREACH;" },
    errno_enetreset_constant => { includes: ["<errno.h>"], decls: "", body: "return ENETRESET;" },
    errno_econnaborted_constant => { includes: ["<errno.h>"], decls: "", body: "return ECONNABORTED;" },
    errno_econnreset_constant => { includes: ["<errno.h>"], decls: "", body: "return ECONNRESET;" },
    errno_enobufs_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOBUFS;" },
    errno_eisconn_constant => { includes: ["<errno.h>"], decls: "", body: "return EISCONN;" },
    errno_enotconn_constant => { includes: ["<errno.h>"], decls: "", body: "return ENOTCONN;" },
    errno_eshutdown_constant => { includes: ["<errno.h>"], decls: "", body: "return ESHUTDOWN;" },
    errno_etoomanyrefs_constant => { includes: ["<errno.h>"], decls: "", body: "return ETOOMANYREFS;" },
    errno_etimedout_constant => { includes: ["<errno.h>"], decls: "", body: "return ETIMEDOUT;" },
    errno_econnrefused_constant => { includes: ["<errno.h>"], decls: "", body: "return ECONNREFUSED;" },
    errno_ehostdown_constant => { includes: ["<errno.h>"], decls: "", body: "return EHOSTDOWN;" },
    errno_ehostunreach_constant => { includes: ["<errno.h>"], decls: "", body: "return EHOSTUNREACH;" },
    errno_ealready_positive => { includes: ["<errno.h>"], decls: "", body: "return EALREADY > 0;" },
    errno_ecanceled_constant => { includes: ["<errno.h>"], decls: "", body: "return ECANCELED;" },
}
