//! Pointer +, -, ++, -- step semantics on arrays; one-past-end only in subtraction.

c_run_cases! {
    short_array_plus_two_steps => { includes: ["<stdio.h>"], decls: "", body: "short a[4]={10,20,30,40}; short *p=a; printf(\"%d\\n\", *(p+2)); return 0;", expect: ["30"] },
    short_array_minus_one_step => { includes: ["<stdio.h>"], decls: "", body: "short a[4]={10,20,30,40}; short *p=&a[3]; printf(\"%d\\n\", *(p-1)); return 0;", expect: ["30"] },
    long_array_postfix_increment_reads_then_advances => { includes: ["<stdio.h>"], decls: "", body: "long a[3]={100,200,300}; long *p=a; printf(\"%ld\\n\", *p++); printf(\"%ld\\n\", *p); return 0;", expect: ["100", "200"] },
    long_array_prefix_decrement_before_read => { includes: ["<stdio.h>"], decls: "", body: "long a[3]={100,200,300}; long *p=&a[2]; printf(\"%ld\\n\", *--p); return 0;", expect: ["200"] },
    float_pointer_plus_skips_elements => { includes: ["<stdio.h>"], decls: "", body: "float a[3]={1.0f,2.0f,3.0f}; float *p=a+1; printf(\"%.0f\\n\", *p); return 0;", expect: ["2"] },
    double_pointer_minus_returns_prior_element => { includes: ["<stdio.h>"], decls: "", body: "double a[3]={1.5,2.5,3.5}; double *p=&a[2]; p--; printf(\"%.1f\\n\", *p); return 0;", expect: ["2.5"] },
    unsigned_array_increment_walks_values => { includes: ["<stdio.h>"], decls: "", body: "unsigned a[3]={1u,2u,3u}; unsigned *p=a; unsigned s=0; while(p<a+3){s+=*p; p++;} printf(\"%u\\n\", s); return 0;", expect: ["6"] },
    char_array_prefix_increment_then_deref => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"dog\"; char *p=s; printf(\"%c\\n\", *++p); return 0;", expect: ["o"] },
    char_array_postfix_decrement_from_end => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"dog\"; char *p=s+3; printf(\"%d\\n\", *p--); return 0;", expect: ["0"] },
    int_pointer_plus_equals_advances => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0,1,2,3,4}; int *p=a; p+=3; printf(\"%d\\n\", *p); return 0;", expect: ["3"] },
    int_pointer_minus_equals_rewinds => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0,1,2,3,4}; int *p=&a[4]; p-=2; printf(\"%d\\n\", *p); return 0;", expect: ["2"] },
    ptrdiff_same_element_zero => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={1,2,3,4}; printf(\"%d\\n\", (int)(&a[2]-&a[2])); return 0;", expect: ["0"] },
    ptrdiff_one_past_end_minus_start => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0}; printf(\"%d\\n\", (int)(&a[5]-&a[0])); return 0;", expect: ["5"] },
    ptrdiff_one_past_end_minus_one_before => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={7,8,9}; printf(\"%d\\n\", (int)(&a[3]-&a[2])); return 0;", expect: ["1"] },
    ptrdiff_both_one_past_end_is_zero => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={1,2}; printf(\"%d\\n\", (int)(&a[2]-&a[2])); return 0;", expect: ["0"] },
    decrement_from_one_past_end_reaches_last => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={5,6,7,8}; int *end=&a[4]; end--; printf(\"%d\\n\", *end); return 0;", expect: ["8"] },
    double_increment_advances_two_slots => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={1,2,3,4,5}; int *p=a; p++; p++; printf(\"%d\\n\", *p); return 0;", expect: ["3"] },
    double_decrement_from_last_index => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={1,2,3,4,5}; int *p=&a[4]; p--; p--; printf(\"%d\\n\", *p); return 0;", expect: ["3"] },
    pointer_plus_zero_is_identity => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={4,5,6}; int *p=a+1; printf(\"%d\\n\", *(p+0)); return 0;", expect: ["5"] },
    pointer_minus_zero_is_identity => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={4,5,6}; int *p=&a[2]; printf(\"%d\\n\", *(p-0)); return 0;", expect: ["6"] },
    add_index_expression_in_brackets => { includes: ["<stdio.h>"], decls: "", body: "int a[6]={10,20,30,40,50,60}; int *p=a; printf(\"%d\\n\", p[1+3]); return 0;", expect: ["50"] },
    subtracted_offset_reaches_first => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={11,22,33,44}; int *p=&a[3]; printf(\"%d\\n\", *(p-3)); return 0;", expect: ["11"] },
    struct_array_pointer_steps_by_element => { includes: ["<stdio.h>"], decls: "struct P{int v;};", body: "struct P a[3]={{1},{2},{3}}; struct P *p=a; p++; printf(\"%d\\n\", p->v); return 0;", expect: ["2"] },
    struct_array_pointer_difference_counts => { includes: ["<stdio.h>"], decls: "struct P{int v;};", body: "struct P a[3]={{1},{2},{3}}; printf(\"%d\\n\", (int)(&a[2]-&a[0])); return 0;", expect: ["2"] },
    const_array_pointer_can_read => { includes: ["<stdio.h>"], decls: "", body: "const int a[3]={9,8,7}; const int *p=a+2; printf(\"%d\\n\", *p); return 0;", expect: ["7"] },
    static_local_array_pointer_increment => { includes: ["<stdio.h>"], decls: "int rd(void){ static int a[2]={3,4}; static int i=0; return *(a+(i++%2)); }", body: "int first=rd(); int second=rd(); printf(\"%d %d\\n\", first, second); return 0;", expect: ["3 4"] },
    nested_pointer_offset_via_subscript => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={2,4,6,8}; int *p=a; printf(\"%d\\n\", (p+2)[1]); return 0;", expect: ["8"] },
    reverse_subscript_with_stepped_pointer => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={2,4,6,8}; int *p=a+1; printf(\"%d\\n\", 1[p]); return 0;", expect: ["6"] },
    for_loop_increment_accumulates => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={1,2,3,4}; int *p=a,*e=a+4,s=0; for(;p<e;p++) s+=*p; printf(\"%d\\n\", s); return 0;", expect: ["10"] },
    for_loop_decrement_from_end => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={5,6,7}; int *p=&a[3]; int s=0; while(p>a){ p--; s+=*p; } printf(\"%d\\n\", s); return 0;", expect: ["18"] },
    ptrdiff_after_increment_chain => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0}; int *p=a; p++; p++; p++; printf(\"%d\\n\", (int)(p-a)); return 0;", expect: ["3"] },
    ptrdiff_after_decrement_chain => { includes: ["<stdio.h>"], decls: "", body: "int a[5]={0}; int *p=&a[4]; p--; p--; printf(\"%d\\n\", (int)(p-a)); return 0;", expect: ["2"] },
    char_ptrdiff_counts_bytes => { includes: ["<stdio.h>"], decls: "", body: "char s[]=\"abcde\"; printf(\"%d\\n\", (int)(&s[5]-&s[1])); return 0;", expect: ["4"] },
    wchar_array_pointer_step => { includes: ["<stdio.h>", "<wchar.h>"], decls: "", body: "wchar_t s[] = L\"ab\"; wchar_t *p=s; p++; printf(\"%lc\\n\", *p); return 0;", expect: ["b"] },
    enum_indexed_pointer_read => { includes: ["<stdio.h>"], decls: "enum {IDX=2};", body: "int a[4]={1,2,3,4}; int *p=a+IDX; printf(\"%d\\n\", *p); return 0;", expect: ["3"] },
    pointer_to_middle_plus_negative_offset => { includes: ["<stdio.h>"], decls: "", body: "int a[6]={0,1,2,3,4,5}; int *mid=a+3; printf(\"%d\\n\", *(mid-2)); return 0;", expect: ["1"] },
    pointer_arithmetic_with_sizeof_element => { includes: ["<stdio.h>"], decls: "", body: "int a[2]={42,99}; char *bp=(char*)a; bp+=sizeof(int); printf(\"%d\\n\", *(int*)bp); return 0;", expect: ["99"] },
    array_of_pointers_increment_selects_next => { includes: ["<stdio.h>"], decls: "", body: "int x=1,y=2,z=3; int *a[3]={&x,&y,&z}; int **p=a; p++; printf(\"%d\\n\", **p); return 0;", expect: ["2"] },
    ptrdiff_signed_int_array_span => { includes: ["<stdio.h>"], decls: "", body: "signed char a[8]={0}; printf(\"%d\\n\", (int)(&a[7]-&a[0])); return 0;", expect: ["7"] },
    long_long_pointer_plus_large_offset => { includes: ["<stdio.h>"], decls: "", body: "long long a[4]={1,2,3,4}; long long *p=a+3; printf(\"%lld\\n\", *p); return 0;", expect: ["4"] },
    postfix_increment_returns_old_then_points_next => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={2,3,4}; int *p=a; int old=*p++; printf(\"%d %d\\n\", old, *p); return 0;", expect: ["2 3"] },
    prefix_decrement_then_postfix_increment => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={5,6,7}; int *p=&a[2]; int v=*--p; p++; printf(\"%d %d\\n\", v, *p); return 0;", expect: ["6 7"] },
    pointer_difference_drives_char_copy_length => { includes: ["<stdio.h>"], decls: "", body: "char src[]=\"hi\"; char *a=src,*b=src; while(*b) b++; printf(\"%d\\n\", (int)(b-a)); return 0;", expect: ["2"] },
    one_past_end_diff_without_dereference => { includes: ["<stdio.h>"], decls: "", body: "int a[3]={1,2,3}; int *start=a; int *past=&a[3]; printf(\"%d\\n\", (int)(past-start)); return 0;", expect: ["3"] },
    stepped_pointer_equality_after_round_trip => { includes: ["<stdio.h>"], decls: "", body: "int a[4]={0}; int *p=a+2; p++; p--; printf(\"%d\\n\", (int)(p==a+2)); return 0;", expect: ["1"] },
    unsigned_char_pointer_steps_single_byte => { includes: ["<stdio.h>"], decls: "", body: "unsigned char a[3]={65,66,67}; unsigned char *p=a; p+=2; printf(\"%u\\n\", *p); return 0;", expect: ["67"] },
    int_pointer_subtract_yields_element_count => { includes: ["<stdio.h>"], decls: "", body: "int a[10]={0}; int *lo=a+2; int *hi=a+7; printf(\"%d\\n\", (int)(hi-lo)); return 0;", expect: ["5"] },
    compound_literal_pointer_increment => { includes: ["<stdio.h>"], decls: "", body: "int *p=(int[]){9,8,7}; p++; printf(\"%d\\n\", *p); return 0;", expect: ["8"] },
}
