//! Language runtime batch 3 — distinct behaviors.


c_run_cases! {
    short_circuit_or_second_skipped => { includes: ["<stdio.h>"], decls: "", body: "int x=0; if(1||(x=1)){} printf(\"%d\\n\", x); return 0;", expect: ["0"] },
    short_circuit_and_second_skipped => { includes: ["<stdio.h>"], decls: "", body: "int x=0; if(0&&(x=1)){} printf(\"%d\\n\", x); return 0;", expect: ["0"] },
    assignment_in_condition => { includes: ["<stdio.h>"], decls: "", body: "int x; if((x=3)) printf(\"%d\\n\", x); return 0;", expect: ["3"] },
    nested_conditional => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", 1?2:3?4:5); return 0;", expect: ["2"] },
    switch_fallthrough_no_break => { includes: ["<stdio.h>"], decls: "", body: "int x=0; switch(1){case 1: x++; case 2: x++; break;} printf(\"%d\\n\", x); return 0;", expect: ["2"] },
    labeled_continue_for => { includes: ["<stdio.h>"], decls: "", body: "int s=0; L: for(int i=0;i<3;i++){ if(i==1) continue L; s+=i;} printf(\"%d\\n\", s); return 0;", expect: ["0"] },
    do_while_with_break => { includes: ["<stdio.h>"], decls: "", body: "int i=0; do{ if(++i==2) break; } while(1); printf(\"%d\\n\", i); return 0;", expect: ["2"] },
    for_multiple_updates => { includes: ["<stdio.h>"], decls: "", body: "int i=0,j=0; for(;i<2;i++,j++){} printf(\"%d\\n\", j); return 0;", expect: ["2"] },
    while_continue => { includes: ["<stdio.h>"], decls: "", body: "int i=0,s=0; while(i++<3){ if(i==2) continue; s+=i;} printf(\"%d\\n\", s); return 0;", expect: ["4"] },
    pointer_difference_zero_same => { includes: ["<stdio.h>"], decls: "", body: "int x; printf(\"%d\\n\", (int)(&x-&x)); return 0;", expect: ["0"] },
    array_to_pointer_in_equality => { includes: ["<stdio.h>"], decls: "", body: "int a[1]={1}; int *p=a; printf(\"%d\\n\", p==a); return 0;", expect: ["1"] },
    struct_member_pointer => { includes: ["<stdio.h>"], decls: "struct S{int n;};", body: "struct S s={2}; int *p=&s.n; *p=3; printf(\"%d\\n\", s.n); return 0;", expect: ["3"] },
    union_write_int_read_int => { includes: ["<stdio.h>"], decls: "union U{int i;};", body: "union U u; u.i=9; printf(\"%d\\n\", u.i); return 0;", expect: ["9"] },
    enum_compare_less => { includes: ["<stdio.h>"], decls: "enum E{A,B,C};", body: "enum E e=B; printf(\"%d\\n\", e<A); return 0;", expect: ["0"] },
    typedef_array_type => { includes: ["<stdio.h>"], decls: "typedef int row[3];", body: "row r={1,2,3}; printf(\"%d\\n\", r[2]); return 0;", expect: ["3"] },
    typedef_pointer_type => { includes: ["<stdio.h>"], decls: "typedef int *iptr;", body: "int x=4; iptr p=&x; printf(\"%d\\n\", *p); return 0;", expect: ["4"] },
    function_returns_pointer_static => { includes: ["<stdio.h>"], decls: "int *cell(void){static int v=6; return &v;}", body: "printf(\"%d\\n\", *cell()); return 0;", expect: ["6"] },
    mutual_recursion => { includes: ["<stdio.h>"], decls: "int even(int); int odd(int n){return n==0?1:even(n-1);} int even(int n){return n==0?0:odd(n-1);}", body: "printf(\"%d\\n\", even(4)); return 0;", expect: ["1"] },
    tail_recursive_sum => { includes: ["<stdio.h>"], decls: "int sum(int n,int acc){return n?sum(n-1,acc+n):acc;}", body: "printf(\"%d\\n\", sum(4,0)); return 0;", expect: ["10"] },
    nested_struct_copy => { includes: ["<stdio.h>"], decls: "struct I{int v;}; struct O{struct I i;};", body: "struct O a={{1}},b=a; b.i.v=2; printf(\"%d\\n\", a.i.v); return 0;", expect: ["1"] },
    bitfield_and_mask => { includes: ["<stdio.h>"], decls: "struct F{unsigned a:2;};", body: "struct F f={3}; printf(\"%u\\n\", f.a); return 0;", expect: ["3"] },
    shift_right_signed => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -8>>1); return 0;", expect: ["-4"] },
    unsigned_shift_right => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=8; printf(\"%u\\n\", u>>1); return 0;", expect: ["4"] },
    multiply_negative => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -3*4); return 0;", expect: ["-12"] },
    divide_negative => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -7/3); return 0;", expect: ["-2"] },
    modulo_negative => { includes: ["<stdio.h>"], decls: "", body: "printf(\"%d\\n\", -7%3); return 0;", expect: ["-1"] },
    cast_unsigned_to_signed => { includes: ["<stdio.h>"], decls: "", body: "unsigned u=255; printf(\"%d\\n\", (signed char)u); return 0;", expect: ["-1"] },
    pointer_int_cast_roundtrip => { includes: ["<stdio.h>", "<stdint.h>"], decls: "", body: "int x=11; intptr_t p=(intptr_t)&x; printf(\"%d\\n\", *(int*)p); return 0;", expect: ["11"] },
}
