[package]
name = "vybe_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "vybe"
path = "src/main.rs"

[[bin]]
name = "vybec"
path = "src/vybec.rs"

[lib]
name = "vybe_cli"
path = "src/lib.rs"

[dependencies]
vybe_bytecode = { workspace = true }
vybe_parser_basic = { workspace = true }
vybe_parser_js = { workspace = true }
vybe_compiler_vb = { workspace = true }
vybe_compiler_js = { workspace = true }
vybe_parser_csharp = { workspace = true }
vybe_compiler_csharp = { workspace = true }
vybe_host = { workspace = true }
vybe_forms = { workspace = true }
vybe_project = { workspace = true }
dioxus = { version = "0.7.3", features = ["desktop"] }
