[package]
name = "vybe_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "vybe"
path = "src/main.rs"

[[bin]]
name = "vybec"
path = "src/vybec.rs"

[lib]
name = "vybe_cli"
path = "src/lib.rs"

[dependencies]
vybe_bytecode = { workspace = true }
vybe_parser_basic = { workspace = true }
vybe_parser_js = { workspace = true }
vybe_compiler_vb = { workspace = true }
vybe_compiler_js = { workspace = true }
vybe_parser_csharp = { workspace = true }
vybe_compiler_csharp = { workspace = true }
vybe_parser_dart = { workspace = true }
vybe_compiler_dart = { workspace = true }
vybe_host = { workspace = true }
vybe_forms = { workspace = true }
vybe_project = { workspace = true }
vybe_parser_python = { workspace = true }
vybe_compiler_python = { workspace = true }
winit = "0.30"
tiny-skia = "0.11"
softbuffer = "0.4"
fontdue = "0.9"
rfd = "0.17"
eframe = "0.22"
