//! Force-link every plugin crate this crate depends on.
//!
//! `inventory` collects plugins from linker sections, but Rust drops an rlib
//! that nothing references — so a plugin crate listed only in `[dependencies]`
//! never reaches the registry. This emits one `extern crate` per plugin
//! dependency, read straight from Cargo.toml.
//!
//! The point is that there is no plugin list in code. Adding a plugin is a
//! Cargo edit and nothing else; this file never names one.
//!
//! `[dev-dependencies]` get the same treatment under `#[cfg(test)]`: the
//! unit-test binary is the only build that can see them, and it needs their
//! registrations (the frontends the bundler/dynamic tests compile with) just
//! as much as production needs its own.

use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");
    let manifest = std::fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let mut out = String::from("// @generated by build.rs — see its docs.\n");
    let mut section = "";
    for line in manifest.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            section = match trimmed {
                "[dependencies]" => "deps",
                "[dev-dependencies]" => "dev",
                _ => "",
            };
            continue;
        }
        if section.is_empty() {
            continue;
        }
        let Some(name) = trimmed.split(['=', ' ']).next() else {
            continue;
        };
        let is_plugin = name.starts_with("vybe_platform_") || name.starts_with("vybe_language_");
        if section == "deps" && is_plugin {
            out.push_str(&format!("extern crate {name};\n"));
        } else if section == "dev" && (is_plugin || name.starts_with("vybe")) {
            out.push_str(&format!("#[cfg(test)]\nextern crate {name};\n"));
        }
    }
    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("linked_plugins.rs");
    let mut f = std::fs::File::create(dest).expect("create linked_plugins.rs");
    f.write_all(out.as_bytes())
        .expect("write linked_plugins.rs");
}
