[package]
name = "osbrowser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "System browser transport for Vybe's web engine"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
