use vybec::parser_cobol::parse;
use vybec::compiler_cobol::Compiler;

fn compile_ok(src: &str) {
    let program = parse(src).expect("parse failed");
    let c = Compiler::new();
    let res = c.compile(&program);
    assert!(res.is_ok(), "compile failed for:\n{}\nerror: {:?}", src, res.err());
}

#[test]
fn hello_world() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. HELLO.
PROCEDURE DIVISION.
    DISPLAY "Hello, World!".
    STOP RUN.
"#);
}

#[test]
fn fizzbuzz_full() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. FIZZBUZZ.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-I      PIC 9(3) VALUE 0.
01 WS-MOD3   PIC 9(3) VALUE 0.
01 WS-MOD5   PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I > 100
        COMPUTE WS-MOD3 = FUNCTION MOD(WS-I 3)
        COMPUTE WS-MOD5 = FUNCTION MOD(WS-I 5)
        EVALUATE TRUE
            WHEN WS-MOD3 = 0 AND WS-MOD5 = 0
                DISPLAY "FizzBuzz"
            WHEN WS-MOD3 = 0
                DISPLAY "Fizz"
            WHEN WS-MOD5 = 0
                DISPLAY "Buzz"
            WHEN OTHER
                DISPLAY WS-I
        END-EVALUATE
    END-PERFORM.
    STOP RUN.
"#);
}

#[test]
fn factorial_program() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. FACTORIAL.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-N      PIC 9(3) VALUE 10.
01 WS-RESULT PIC 9(15) VALUE 1.
01 WS-I      PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I > WS-N
        MULTIPLY WS-I BY WS-RESULT
    END-PERFORM.
    DISPLAY "Factorial of " WS-N " = " WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn fibonacci_program() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. FIBONACCI.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-N    PIC 9(3) VALUE 20.
01 WS-A    PIC 9(10) VALUE 0.
01 WS-B    PIC 9(10) VALUE 1.
01 WS-TEMP PIC 9(10) VALUE 0.
01 WS-I    PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I > WS-N
        DISPLAY WS-A
        COMPUTE WS-TEMP = WS-A + WS-B
        MOVE WS-B TO WS-A
        MOVE WS-TEMP TO WS-B
    END-PERFORM.
    STOP RUN.
"#);
}

#[test]
fn temperature_converter() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. TEMPCONV.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-CELSIUS    PIC S9(5)V99 VALUE 0.
01 WS-FAHRENHEIT PIC S9(5)V99 VALUE 0.
01 WS-I          PIC S9(5) VALUE 0.
PROCEDURE DIVISION.
    PERFORM VARYING WS-I FROM 0 BY 10 UNTIL WS-I > 100
        MOVE WS-I TO WS-CELSIUS
        COMPUTE WS-FAHRENHEIT = (WS-CELSIUS * 9 / 5) + 32
        DISPLAY WS-CELSIUS " C = " WS-FAHRENHEIT " F"
    END-PERFORM.
    STOP RUN.
"#);
}

#[test]
fn string_processing() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. STRPROC.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-INPUT   PIC X(50) VALUE "  Hello, COBOL World!  ".
01 WS-TRIMMED PIC X(50).
01 WS-UPPER   PIC X(50).
01 WS-LOWER   PIC X(50).
01 WS-LEN     PIC 9(5).
01 WS-REPLACED PIC X(50).
PROCEDURE DIVISION.
    MOVE FUNCTION TRIM(WS-INPUT) TO WS-TRIMMED.
    MOVE FUNCTION UPPER-CASE(WS-TRIMMED) TO WS-UPPER.
    MOVE FUNCTION LOWER-CASE(WS-TRIMMED) TO WS-LOWER.
    MOVE FUNCTION LENGTH(WS-TRIMMED) TO WS-LEN.
    MOVE FUNCTION SUBSTITUTE(WS-TRIMMED "COBOL" "Vybe") TO WS-REPLACED.
    DISPLAY "Trimmed:  " WS-TRIMMED.
    DISPLAY "Upper:    " WS-UPPER.
    DISPLAY "Lower:    " WS-LOWER.
    DISPLAY "Length:   " WS-LEN.
    DISPLAY "Replaced: " WS-REPLACED.
    STOP RUN.
"#);
}

#[test]
fn employee_record() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. EMPLOYEE.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-EMPLOYEE.
   05 WS-EMP-ID    PIC 9(5)  VALUE 12345.
   05 WS-EMP-NAME  PIC X(30) VALUE "John Smith".
   05 WS-EMP-DEPT  PIC X(20) VALUE "Engineering".
   05 WS-EMP-SAL   PIC 9(7)V99 VALUE 75000.00.
01 WS-BONUS PIC 9(7)V99 VALUE 0.
01 WS-TOTAL PIC 9(8)V99 VALUE 0.
PROCEDURE DIVISION.
    COMPUTE WS-BONUS = WS-EMP-SAL * 0.10.
    COMPUTE WS-TOTAL = WS-EMP-SAL + WS-BONUS.
    DISPLAY "Employee: " WS-EMP-NAME.
    DISPLAY "ID:       " WS-EMP-ID.
    DISPLAY "Dept:     " WS-EMP-DEPT.
    DISPLAY "Salary:   " WS-EMP-SAL.
    DISPLAY "Bonus:    " WS-BONUS.
    DISPLAY "Total:    " WS-TOTAL.
    STOP RUN.
"#);
}

#[test]
fn grade_calculator() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. GRADES.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-SCORE PIC 9(3) VALUE 0.
01 WS-TOTAL PIC 9(5) VALUE 0.
01 WS-COUNT PIC 9(3) VALUE 5.
01 WS-AVG   PIC 9(5)V99 VALUE 0.
01 WS-I     PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    MOVE 0 TO WS-TOTAL.
    ADD 85 TO WS-TOTAL.
    ADD 92 TO WS-TOTAL.
    ADD 78 TO WS-TOTAL.
    ADD 95 TO WS-TOTAL.
    ADD 88 TO WS-TOTAL.
    COMPUTE WS-AVG = WS-TOTAL / WS-COUNT.
    DISPLAY "Average: " WS-AVG.
    EVALUATE TRUE
        WHEN WS-AVG >= 90
            DISPLAY "Grade: A"
        WHEN WS-AVG >= 80
            DISPLAY "Grade: B"
        WHEN WS-AVG >= 70
            DISPLAY "Grade: C"
        WHEN WS-AVG >= 60
            DISPLAY "Grade: D"
        WHEN OTHER
            DISPLAY "Grade: F"
    END-EVALUATE.
    STOP RUN.
"#);
}

#[test]
fn table_processing() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. TABPROC.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-TABLE.
   05 WS-ITEM PIC X(10) OCCURS 5 TIMES.
01 WS-I PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    MOVE "Apple"  TO WS-ITEM(1).
    MOVE "Banana" TO WS-ITEM(2).
    MOVE "Cherry" TO WS-ITEM(3).
    MOVE "Date"   TO WS-ITEM(4).
    MOVE "Fig"    TO WS-ITEM(5).
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I > 5
        DISPLAY "Item " WS-I ": " WS-ITEM(WS-I)
    END-PERFORM.
    STOP RUN.
"#);
}

#[test]
fn paragraph_program() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. PARAPROG.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-RESULT PIC 9(10) VALUE 0.
PROCEDURE DIVISION.
    PERFORM INIT-PARA.
    PERFORM CALC-PARA.
    PERFORM OUTPUT-PARA.
    STOP RUN.
INIT-PARA.
    MOVE 0 TO WS-RESULT.
    DISPLAY "Initialized".
CALC-PARA.
    ADD 100 TO WS-RESULT.
    ADD 200 TO WS-RESULT.
    ADD 300 TO WS-RESULT.
    DISPLAY "Calculated".
OUTPUT-PARA.
    DISPLAY "Result: " WS-RESULT.
"#);
}

#[test]
fn csv_parser() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. CSVPARSE.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-LINE   PIC X(80) VALUE "John,Doe,30,NYC".
01 WS-FIRST  PIC X(20).
01 WS-LAST   PIC X(20).
01 WS-AGE    PIC X(5).
01 WS-CITY   PIC X(20).
PROCEDURE DIVISION.
    UNSTRING WS-LINE DELIMITED BY ","
        INTO WS-FIRST WS-LAST WS-AGE WS-CITY.
    DISPLAY "First: " WS-FIRST.
    DISPLAY "Last:  " WS-LAST.
    DISPLAY "Age:   " WS-AGE.
    DISPLAY "City:  " WS-CITY.
    STOP RUN.
"#);
}

#[test]
fn math_functions_program() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. MATHPROG.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-PI     PIC 9(1)V9(10) VALUE 3.1415926535.
01 WS-R      PIC 9(10)V99 VALUE 0.
01 WS-ANGLE  PIC 9(3) VALUE 45.
PROCEDURE DIVISION.
    COMPUTE WS-R = FUNCTION SQRT(144).
    DISPLAY "SQRT(144) = " WS-R.
    COMPUTE WS-R = FUNCTION ABS(-42).
    DISPLAY "ABS(-42) = " WS-R.
    COMPUTE WS-R = FUNCTION MAX(10 20 30 40 50).
    DISPLAY "MAX = " WS-R.
    COMPUTE WS-R = FUNCTION MIN(10 20 30 40 50).
    DISPLAY "MIN = " WS-R.
    COMPUTE WS-R = FUNCTION SIN(WS-PI).
    DISPLAY "SIN(PI) = " WS-R.
    COMPUTE WS-R = FUNCTION COS(0).
    DISPLAY "COS(0) = " WS-R.
    COMPUTE WS-R = FUNCTION LOG(1).
    DISPLAY "LOG(1) = " WS-R.
    COMPUTE WS-R = FUNCTION EXP(1).
    DISPLAY "EXP(1) = " WS-R.
    COMPUTE WS-R = FUNCTION MEAN(10 20 30).
    DISPLAY "MEAN = " WS-R.
    STOP RUN.
"#);
}

#[test]
fn json_roundtrip() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. JSONRT.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-PERSON.
   05 WS-NAME PIC X(20) VALUE "Alice".
   05 WS-AGE  PIC 9(3)  VALUE 30.
01 WS-JSON   PIC X(200).
01 WS-PARSED.
   05 WS-P-NAME PIC X(20).
   05 WS-P-AGE  PIC 9(3).
PROCEDURE DIVISION.
    JSON GENERATE WS-JSON FROM WS-PERSON.
    DISPLAY "JSON: " WS-JSON.
    JSON PARSE WS-JSON INTO WS-PARSED.
    DISPLAY "Name: " WS-P-NAME.
    STOP RUN.
"#);
}

#[test]
fn bubble_sort() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. BSORT.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-TABLE.
   05 WS-NUM PIC 9(5) OCCURS 5 TIMES.
01 WS-I    PIC 9(3) VALUE 0.
01 WS-J    PIC 9(3) VALUE 0.
01 WS-TEMP PIC 9(5) VALUE 0.
01 WS-SIZE PIC 9(3) VALUE 5.
PROCEDURE DIVISION.
    MOVE 50 TO WS-NUM(1).
    MOVE 30 TO WS-NUM(2).
    MOVE 10 TO WS-NUM(3).
    MOVE 40 TO WS-NUM(4).
    MOVE 20 TO WS-NUM(5).
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I >= WS-SIZE
        PERFORM VARYING WS-J FROM 1 BY 1 UNTIL WS-J >= WS-SIZE
            IF WS-NUM(WS-J) > WS-NUM(WS-J + 1)
                MOVE WS-NUM(WS-J) TO WS-TEMP
                MOVE WS-NUM(WS-J + 1) TO WS-NUM(WS-J)
                MOVE WS-TEMP TO WS-NUM(WS-J + 1)
            END-IF
        END-PERFORM
    END-PERFORM.
    PERFORM VARYING WS-I FROM 1 BY 1 UNTIL WS-I > WS-SIZE
        DISPLAY WS-NUM(WS-I)
    END-PERFORM.
    STOP RUN.
"#);
}

#[test]
fn date_time_operations() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. DATETIME.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATE PIC X(21).
01 WS-TIME PIC X(21).
PROCEDURE DIVISION.
    MOVE FUNCTION CURRENT-DATE TO WS-DATE.
    ACCEPT WS-TIME FROM TIME.
    DISPLAY "Current Date: " WS-DATE.
    DISPLAY "Current Time: " WS-TIME.
    STOP RUN.
"#);
}

#[test]
fn reference_modification_program() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. REFMOD.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-FULL-NAME PIC X(30) VALUE "John Michael Smith".
01 WS-FIRST     PIC X(10).
01 WS-MIDDLE    PIC X(10).
01 WS-LAST      PIC X(10).
PROCEDURE DIVISION.
    MOVE WS-FULL-NAME(1:4) TO WS-FIRST.
    MOVE WS-FULL-NAME(6:7) TO WS-MIDDLE.
    MOVE WS-FULL-NAME(14:5) TO WS-LAST.
    DISPLAY "First:  " WS-FIRST.
    DISPLAY "Middle: " WS-MIDDLE.
    DISPLAY "Last:   " WS-LAST.
    STOP RUN.
"#);
}

#[test]
fn perform_thru_program() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. PTHRU.
PROCEDURE DIVISION.
    PERFORM STEP-1 THRU STEP-3.
    DISPLAY "All steps complete".
    STOP RUN.
STEP-1.
    DISPLAY "Step 1: Initialize".
STEP-2.
    DISPLAY "Step 2: Process".
STEP-3.
    DISPLAY "Step 3: Finalize".
"#);
}

#[test]
fn quadratic_formula() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. QUADRATIC.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-A     PIC S9(5)V99 VALUE 1.
01 WS-B     PIC S9(5)V99 VALUE -5.
01 WS-C     PIC S9(5)V99 VALUE 6.
01 WS-DISC  PIC S9(10)V99 VALUE 0.
01 WS-ROOT1 PIC S9(10)V99 VALUE 0.
01 WS-ROOT2 PIC S9(10)V99 VALUE 0.
PROCEDURE DIVISION.
    COMPUTE WS-DISC = WS-B ** 2 - 4 * WS-A * WS-C.
    COMPUTE WS-ROOT1 = (-1 * WS-B + FUNCTION SQRT(WS-DISC))
                       / (2 * WS-A).
    COMPUTE WS-ROOT2 = (-1 * WS-B - FUNCTION SQRT(WS-DISC))
                       / (2 * WS-A).
    DISPLAY "Root 1: " WS-ROOT1.
    DISPLAY "Root 2: " WS-ROOT2.
    STOP RUN.
"#);
}

#[test]
fn report_generation() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. REPORT.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-HEADER PIC X(60).
01 WS-LINE   PIC X(60).
01 WS-TOTAL  PIC 9(8)V99 VALUE 0.
01 WS-I      PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    STRING "Product" DELIMITED BY SIZE
           "    " DELIMITED BY SIZE
           "Price" DELIMITED BY SIZE
           INTO WS-HEADER.
    DISPLAY WS-HEADER.
    DISPLAY "----------------------------".
    ADD 29.99 TO WS-TOTAL.
    ADD 49.99 TO WS-TOTAL.
    ADD 19.99 TO WS-TOTAL.
    DISPLAY "Total: " WS-TOTAL.
    STOP RUN.
"#);
}
