pub mod opcode;
pub mod value;
pub mod chunk;
pub mod vm;
pub mod error;
pub mod debug;
pub mod fiber;
pub mod event_loop;
pub mod typedef;
pub mod shared_memory;

pub use opcode::Op;
pub use value::Value;
pub use chunk::{Chunk, Import};
pub use vm::{VM, HostFn, HostContext, ImportTarget};
pub use error::VMError;
pub use event_loop::EventLoop;
pub use typedef::{TypeDef, TypeRegistry, Method, FieldDef, ResourceTable};
pub mod component;
pub mod project;
pub use component::{Component, Linker, LinkResult, Interface, FuncSig, ValType, Language, ExportImpl, ModuleResolver, ResolvedModule, ModuleExport, ImportPolicy};
pub use project::ProjectConfig;
pub mod wasm;
