//! `ListControl → {ComboBox, ListBox}` plus `ListView` and `TreeView`.
//!
//! In real .NET `ComboBox` and `ListBox` inherit from `ListControl` (which
//! owns `DataSource`, `DisplayMember`, `ValueMember`, `SelectedValue`).
//! `ListView` and `TreeView` inherit directly from `Control` — they have a
//! richer item model that doesn't fit `ListControl`.

use super::DotnetClass;

pub fn classes() -> &'static [DotnetClass] {
    &[
        DotnetClass {
            name: "ListControl",
            parent: Some("Control"),
            properties: &[
                "DataSource",
                "DisplayMember",
                "FormatInfo",
                "FormatString",
                "FormattingEnabled",
                "SelectedValue",
                "ValueMember",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
            widget_host_module: "vybe:gui",
        },
        DotnetClass {
            name: "ComboBox",
            parent: Some("ListControl"),
            properties: &[
                "AutoCompleteCustomSource",
                "AutoCompleteMode",
                "AutoCompleteSource",
                "DrawMode",
                "DropDownHeight",
                "DropDownStyle",
                "DropDownWidth",
                "DroppedDown",
                "FlatStyle",
                "IntegralHeight",
                "ItemHeight",
                "Items",
                "MaxDropDownItems",
                "MaxLength",
                "SelectedIndex",
                "SelectedItem",
                "SelectedText",
                "SelectionLength",
                "SelectionStart",
                "Sorted",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: Some("new_ComboBox"),
            widget_host_module: "vybe:gui",
        },
        DotnetClass {
            name: "ListBox",
            parent: Some("ListControl"),
            properties: &[
                "BorderStyle",
                "ColumnWidth",
                "CustomTabOffsets",
                "DrawMode",
                "HorizontalExtent",
                "HorizontalScrollbar",
                "IntegralHeight",
                "ItemHeight",
                "Items",
                "MultiColumn",
                "PreferredHeight",
                "ScrollAlwaysVisible",
                "SelectedIndex",
                "SelectedIndices",
                "SelectedItem",
                "SelectedItems",
                "SelectionMode",
                "Sorted",
                "TopIndex",
                "UseTabStops",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: Some("new_ListBox"),
            widget_host_module: "vybe:gui",
        },
        DotnetClass {
            name: "ListView",
            parent: Some("Control"),
            properties: &[
                "Activation",
                "Alignment",
                "AllowColumnReorder",
                "AutoArrange",
                "BackgroundImageTiled",
                "BorderStyle",
                "CheckBoxes",
                "CheckedIndices",
                "CheckedItems",
                "Columns",
                "FullRowSelect",
                "GridLines",
                "Groups",
                "HeaderStyle",
                "HideSelection",
                "HotTracking",
                "HoverSelection",
                "Items",
                "LabelEdit",
                "LabelWrap",
                "LargeImageList",
                "MultiSelect",
                "OwnerDraw",
                "Scrollable",
                "SelectedIndices",
                "SelectedItems",
                "ShowGroups",
                "ShowItemToolTips",
                "SmallImageList",
                "Sorting",
                "StateImageList",
                "TileSize",
                "TopItem",
                "UseCompatibleStateImageBehavior",
                "View",
                "VirtualListSize",
                "VirtualMode",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: Some("new_ListView"),
            widget_host_module: "vybe:gui",
        },
        DotnetClass {
            name: "TreeView",
            parent: Some("Control"),
            properties: &[
                "BorderStyle",
                "CheckBoxes",
                "DrawMode",
                "FullRowSelect",
                "HideSelection",
                "HotTracking",
                "ImageIndex",
                "ImageKey",
                "ImageList",
                "Indent",
                "ItemHeight",
                "LabelEdit",
                "LineColor",
                "Nodes",
                "PathSeparator",
                "Scrollable",
                "SelectedImageIndex",
                "SelectedImageKey",
                "SelectedNode",
                "ShowLines",
                "ShowNodeToolTips",
                "ShowPlusMinus",
                "ShowRootLines",
                "Sorted",
                "StateImageList",
                "TopNode",
                "TreeViewNodeSorter",
                "VisibleCount",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: Some("new_TreeView"),
            widget_host_module: "vybe:gui",
        },
        // A CheckedListBox IS a ListBox with per-item checkboxes, so it
        // inherits the whole list surface by declaring that parent.
        // `vybe_widgets` already has the `checkedlistbox` kind and its default
        // size; only the descriptor entry was missing, and without it a
        // designer could NAME the control while every property write on it was
        // dropped — see [[project_dotnet_strips_and_items_are_menu_elements]].
        DotnetClass {
            name: "CheckedListBox",
            parent: Some("ListBox"),
            properties: &[
                "CheckOnClick",
                "CheckedIndices",
                "CheckedItems",
                "ThreeDCheckBoxes",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
            widget_host_module: "vybe:gui",
        },
    ]
}
