//! `ListControl → {ComboBox, ListBox}` plus `ListView` and `TreeView`.
//!
//! In real .NET `ComboBox` and `ListBox` inherit from `ListControl` (which
//! owns `DataSource`, `DisplayMember`, `ValueMember`, `SelectedValue`).
//! `ListView` and `TreeView` inherit directly from `Control` — they have a
//! richer item model that doesn't fit `ListControl`.

use super::{DotnetClass, DotnetMethod, MethodTarget};

pub fn classes() -> &'static [DotnetClass] {
    &[
        DotnetClass {
            name: "ListControl",
            parent: Some("Control"),
            properties: &[
                "DataSource",
                "DisplayMember",
                "FormatInfo",
                "FormatString",
                "FormattingEnabled",
                "SelectedValue",
                "ValueMember",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ComboBox",
            parent: Some("ListControl"),
            properties: &[
                "AutoCompleteCustomSource",
                "AutoCompleteMode",
                "AutoCompleteSource",
                "DrawMode",
                "DropDownHeight",
                "DropDownStyle",
                "DropDownWidth",
                "DroppedDown",
                "FlatStyle",
                "IntegralHeight",
                "ItemHeight",
                "Items",
                "MaxDropDownItems",
                "MaxLength",
                "SelectedIndex",
                "SelectedItem",
                "SelectedText",
                "SelectionLength",
                "SelectionStart",
                "Sorted",
            ],
            methods: &[],
            ctor_arity: 0,
            // `<select>` — created by the element mapping.
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ListBox",
            parent: Some("ListControl"),
            properties: &[
                "BorderStyle",
                "ColumnWidth",
                "CustomTabOffsets",
                "DrawMode",
                "HorizontalExtent",
                "HorizontalScrollbar",
                "IntegralHeight",
                "ItemHeight",
                "Items",
                "MultiColumn",
                "PreferredHeight",
                "ScrollAlwaysVisible",
                "SelectedIndex",
                "SelectedIndices",
                "SelectedItem",
                "SelectedItems",
                "SelectionMode",
                "Sorted",
                "TopIndex",
                "UseTabStops",
            ],
            methods: &[],
            ctor_arity: 0,
            // `<ul>`
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ListBoxObjectCollection",
            parent: None,
            properties: &[],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "CheckedListBoxObjectCollection",
            parent: None,
            properties: &[],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ControlBindingsCollection",
            parent: None,
            properties: &[],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ListView",
            parent: Some("Control"),
            properties: &[
                "Activation",
                "Alignment",
                "AllowColumnReorder",
                "AutoArrange",
                "BackgroundImageTiled",
                "BorderStyle",
                "CheckBoxes",
                "CheckedIndices",
                "CheckedItems",
                "Columns",
                "FullRowSelect",
                "GridLines",
                "Groups",
                "HeaderStyle",
                "HideSelection",
                "HotTracking",
                "HoverSelection",
                "Items",
                "LabelEdit",
                "LabelWrap",
                "LargeImageList",
                "MultiSelect",
                "OwnerDraw",
                "Scrollable",
                "SelectedIndices",
                "SelectedItems",
                "ShowGroups",
                "ShowItemToolTips",
                "SmallImageList",
                "Sorting",
                "StateImageList",
                "TileSize",
                "TopItem",
                "UseCompatibleStateImageBehavior",
                "View",
                "VirtualListSize",
                "VirtualMode",
            ],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ListViewColumnHeaderCollection",
            parent: None,
            properties: &[],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "ListViewItemCollection",
            parent: None,
            properties: &[],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "TreeView",
            parent: Some("Control"),
            properties: &[
                "BorderStyle",
                "CheckBoxes",
                "DrawMode",
                "FullRowSelect",
                "HideSelection",
                "HotTracking",
                "ImageIndex",
                "ImageKey",
                "ImageList",
                "Indent",
                "ItemHeight",
                "LabelEdit",
                "LineColor",
                "Nodes",
                "PathSeparator",
                "Scrollable",
                "SelectedImageIndex",
                "SelectedImageKey",
                "SelectedNode",
                "ShowLines",
                "ShowNodeToolTips",
                "ShowPlusMinus",
                "ShowRootLines",
                "Sorted",
                "StateImageList",
                "TopNode",
                "TreeViewNodeSorter",
                "VisibleCount",
            ],
            methods: &[],
            ctor_arity: 0,
            // `<ul>` — nesting is what makes it a tree.
            widget_host_fn: None,
        },
        DotnetClass {
            name: "TreeNodeCollection",
            parent: None,
            properties: &[],
            methods: &[DotnetMethod {
                name: "Add",
                arity: 2,
                target: MethodTarget::Common {
                    emit: "dotnet.tree_add_node",
                },
            }],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        DotnetClass {
            name: "TreeNode",
            parent: None,
            properties: &["Text"],
            methods: &[],
            ctor_arity: 0,
            widget_host_fn: None,
        },
        // The item collection is distinct from ListBox options: each item has
        // independent checked state in addition to selection.
        DotnetClass {
            name: "CheckedListBox",
            parent: Some("ListBox"),
            properties: &[
                "CheckOnClick",
                "CheckedIndices",
                "CheckedItems",
                "ThreeDCheckBoxes",
            ],
            methods: &[DotnetMethod {
                name: "GetItemChecked",
                arity: 2,
                target: MethodTarget::Common {
                    emit: "dotnet.checked_list_get",
                },
            }],
            ctor_arity: 0,
            widget_host_fn: None,
        },
    ]
}
