[package]
name = "vybe_language_python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vybe_language_python"

[dependencies]
vybe_compiler = { workspace = true }
inventory = { workspace = true }
vybe_ast = { workspace = true }
vybe_runtime = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }

[dev-dependencies]
vybe_compiler = { workspace = true }
vybe_runtime = { workspace = true }
vybe_ast = { workspace = true }

