[package]
name = "vybe_language_python"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vybe_language_python"

[dependencies]
vybe_ast = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_platform_vybe = { workspace = true, features = ["gui"] }
vybe_emitter = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }

[dev-dependencies]
vybe_compiler = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_ast = { workspace = true }
vybe_emitter = { workspace = true }

[[test]]
name = "python"
path = "tests/python/main.rs"
