//! types, typing, inspect, enum, dataclasses compile coverage.

use crate::helpers::*;

crate::compile_case!(typing_list_int, "from typing import List\nx: List[int] = []\n");
crate::compile_case!(typing_dict_str_int, "from typing import Dict\nx: Dict[str, int] = {}\n");
crate::compile_case!(typing_optional, "from typing import Optional\nx: Optional[int] = None\n");
crate::compile_case!(typing_union, "from typing import Union\nx: Union[int, str] = 1\n");
crate::compile_case!(typing_tuple_fixed, "from typing import Tuple\nx: Tuple[int, str] = (1, 'a')\n");
crate::compile_case!(typing_callable, "from typing import Callable\ndef f(x: Callable[[int], int]) -> int:\n return x(1)\n");
crate::compile_case!(typing_generic, "from typing import TypeVar\nT = TypeVar('T')\n");
crate::compile_case!(typing_literal, "from typing import Literal\nx: Literal['a', 'b'] = 'a'\n");
crate::compile_case!(typing_final, "from typing import final\n@final\nclass C:\n pass\n");
crate::compile_case!(typing_protocol, "from typing import Protocol\nclass P(Protocol):\n def m(self) -> int: ...\n");
crate::compile_case!(typing_namedtuple_typing, "from typing import NamedTuple\nclass P(NamedTuple):\n x: int\n");
crate::compile_case!(typing_typeddict, "from typing import TypedDict\nclass D(TypedDict):\n x: int\n");
crate::compile_case!(typing_newtype, "from typing import NewType\nUserId = NewType('UserId', int)\n");
crate::compile_case!(typing_cast, "from typing import cast\nx = cast(int, '1')\n");
crate::compile_case!(typing_any, "from typing import Any\nx: Any = 1\n");
crate::compile_case!(typing_no_return, "from typing import NoReturn\ndef f() -> NoReturn:\n raise SystemExit()\n");
crate::compile_case!(typing_classvar, "from typing import ClassVar\nclass C:\n x: ClassVar[int] = 1\n");
crate::compile_case!(typing_type_alias, "from typing import TypeAlias\nAlias: TypeAlias = int\n");
crate::compile_case!(typing_paramspec, "from typing import ParamSpec\nP = ParamSpec('P')\n");
crate::compile_case!(typing_typevar_tuple, "from typing import TypeVarTuple\nTs = TypeVarTuple('Ts')\n");
crate::compile_case!(enum_basic, "from enum import Enum\nclass Color(Enum):\n RED = 1\n");
crate::compile_case!(enum_auto, "from enum import Enum, auto\nclass E(Enum):\n A = auto()\n");
crate::compile_case!(enum_intenum, "from enum import IntEnum\nclass E(IntEnum):\n X = 1\n");
crate::compile_case!(enum_flag, "from enum import Flag, auto\nclass F(Flag):\n A = auto()\n");
crate::compile_case!(enum_unique, "from enum import Enum, unique\n@unique\nclass E(Enum):\n A = 1\n");
crate::compile_case!(dataclasses_basic, "from dataclasses import dataclass\n@dataclass\nclass P:\n x: int\n");
crate::compile_case!(dataclasses_frozen, "from dataclasses import dataclass\n@dataclass(frozen=True)\nclass P:\n x: int\n");
crate::compile_case!(dataclasses_field, "from dataclasses import dataclass, field\n@dataclass\nclass P:\n xs: list = field(default_factory=list)\n");
crate::compile_case!(dataclasses_replace, "from dataclasses import dataclass, replace\n@dataclass\nclass P:\n x: int\n");
crate::compile_case!(dataclasses_asdict, "from dataclasses import dataclass, asdict\n@dataclass\nclass P:\n x: int\n");
crate::compile_case!(inspect_signature, "import inspect\ndef f(a, b=1): pass\ninspect.signature(f)\n");
crate::compile_case!(inspect_getmembers, "import inspect\nclass C: pass\ninspect.getmembers(C)\n");
crate::compile_case!(inspect_isfunction, "import inspect\ndef f(): pass\ninspect.isfunction(f)\n");
crate::compile_case!(inspect_isclass, "import inspect\nclass C: pass\ninspect.isclass(C)\n");
crate::compile_case!(inspect_getsource, "import inspect\nimport math\nhasattr(inspect, 'getsource')\n");
crate::compile_case!(inspect_currentframe, "import inspect\ninspect.currentframe()\n");
crate::compile_case!(inspect_stack, "import inspect\ninspect.stack()\n");
crate::compile_case!(types_functiontype, "import types\ndef f(): pass\ntypes.FunctionType\n");
crate::compile_case!(types_methodtype, "import types\nclass C:\n def m(self): pass\ntypes.MethodType\n");
crate::compile_case!(types_simplenamespace, "import types\ntypes.SimpleNamespace(x=1)\n");
crate::compile_case!(types_generictype, "import types\nfrom typing import List\ntypes.GenericAlias\n");
crate::compile_case!(types_uniontype, "import types\ntypes.UnionType\n");
crate::compile_case!(types_memberdescriptor, "import types\nclass C:\n x = 1\n");
crate::compile_case!(types_gettypehints, "import typing\nfrom typing import get_type_hints\ndef f(x: int) -> str: pass\nget_type_hints(f)\n");
crate::compile_case!(abc_abstract, "from abc import ABC, abstractmethod\nclass B(ABC):\n @abstractmethod\n def m(self): pass\n");
crate::compile_case!(abc_register, "from abc import ABC\nclass B(ABC):\n pass\n");
crate::compile_case!(weakref_ref, "import weakref\nclass C: pass\nweakref.ref(C())\n");
crate::compile_case!(weakref_proxy, "import weakref\nclass C: pass\nweakref.proxy(C())\n");
crate::compile_case!(weakref_finalize, "import weakref\nclass C: pass\nweakref.finalize(C(), print)\n");
crate::compile_case!(gc_collect, "import gc\ngc.collect()\n");
crate::compile_case!(gc_get_objects, "import gc\ngc.get_objects()\n");
crate::compile_case!(gc_get_referrers, "import gc\nx = []\ngc.get_referrers(x)\n");
crate::compile_case!(traceback_format_exc, "import traceback\ntry:\n 1/0\nexcept:\n traceback.format_exc()\n");
crate::compile_case!(traceback_print_exc, "import traceback\ntry:\n 1/0\nexcept:\n traceback.print_exc()\n");
crate::compile_case!(warnings_warn, "import warnings\nwarnings.warn('msg')\n");
crate::compile_case!(warnings_filterwarnings, "import warnings\nwarnings.filterwarnings('ignore')\n");
crate::compile_case!(logging_basic, "import logging\nlogging.basicConfig()\n");
crate::compile_case!(logging_getlogger, "import logging\nlogging.getLogger('test')\n");
crate::compile_case!(csv_reader, "import csv\nimport io\ncsv.reader(io.StringIO('a,b\\n1,2'))\n");
crate::compile_case!(csv_writer, "import csv\nimport io\ncsv.writer(io.StringIO())\n");
crate::compile_case!(xml_etree_parse, "import xml.etree.ElementTree as ET\nET.fromstring('<root/>')\n");
crate::compile_case!(html_escape, "import html\nhtml.escape('<')\n");
crate::compile_case!(urllib_parse_quote, "import urllib.parse\nurllib.parse.quote('a b')\n");
crate::compile_case!(urllib_parse_urlencode, "import urllib.parse\nurllib.parse.urlencode({'a': 1})\n");
crate::compile_case!(socket_socket, "import socket\nsocket.socket()\n");
crate::compile_case!(sqlite3_connect, "import sqlite3\nsqlite3.connect(':memory:')\n");
crate::compile_case!(threading_thread, "import threading\nt = threading.Thread(target=lambda: None)\n");
crate::compile_case!(multiprocessing_process, "import multiprocessing\nmultiprocessing.Process\n");
crate::compile_case!(subprocess_popen, "import subprocess\nsubprocess.Popen\n");
crate::compile_case!(asyncio_run, "import asyncio\nasync def main():\n return 1\n");
crate::compile_case!(contextlib_asynccontextmanager, "from contextlib import asynccontextmanager\n@asynccontextmanager\nasync def cm():\n yield 1\n");
crate::compile_case!(pathlib_path, "from pathlib import Path\nPath('.')\n");
crate::compile_case!(pathlib_purepath, "from pathlib import PurePath\nPurePath('a/b')\n");
crate::compile_case!(uuid_uuid4, "import uuid\nuuid.uuid4()\n");
crate::compile_case!(secrets_token, "import secrets\nsecrets.token_hex(8)\n");
crate::compile_case!(hmac_digest, "import hmac\nhmac.new(b'key', b'msg', 'sha256')\n");
crate::compile_case!(ssl_create_default_context, "import ssl\nssl.create_default_context()\n");
crate::compile_case!(http_client, "import http.client\nhttp.client.HTTPConnection\n");
crate::compile_case!(email_message, "from email.message import EmailMessage\nEmailMessage()\n");
crate::compile_case!(json_scanner, "import json\njson.JSONDecoder()\n");
crate::compile_case!(decimal_decimal, "from decimal import Decimal\nDecimal('1.1')\n");
crate::compile_case!(fractions_fraction, "from fractions import Fraction\nFraction(1, 2)\n");
crate::compile_case!(numbers_abc, "import numbers\nnumbers.Integral\n");
crate::compile_case!(cmath_sqrt, "import cmath\ncmath.sqrt(-1)\n");
crate::compile_case!(locale_setlocale, "import locale\nlocale.getlocale()\n");
crate::compile_case!(gettext_gettext, "import gettext\ngettext.gettext\n");
crate::compile_case!(argparse_parser, "import argparse\nargparse.ArgumentParser()\n");
crate::compile_case!(configparser_read, "import configparser\nc = configparser.ConfigParser()\n");
crate::compile_case!(tempfile_mkstemp, "import tempfile\ntempfile.mkstemp()\n");
crate::compile_case!(shutil_copy, "import shutil\nshutil.copy\n");
crate::compile_case!(glob_glob, "import glob\nglob.glob('*')\n");
crate::compile_case!(fnmatch_fnmatch, "import fnmatch\nfnmatch.fnmatch('test.py', '*.py')\n");
crate::compile_case!(linecache_getline, "import linecache\nlinecache.getline(__file__, 1)\n");
crate::compile_case!(platform_system, "import platform\nplatform.system()\n");
crate::compile_case!(sysconfig_get_path, "import sysconfig\nsysconfig.get_path('stdlib')\n");
crate::compile_case!(importlib_metadata, "import importlib\nimportlib.import_module('json')\n");
crate::compile_case!(pkgutil_iter_modules, "import pkgutil\nlist(pkgutil.iter_modules())\n");
crate::compile_case!(unittest_testcase, "import unittest\nclass T(unittest.TestCase):\n def test_x(self):\n  pass\n");
crate::compile_case!(doctest_testmod, "import doctest\ndoctest.testmod\n");
crate::compile_case!(pdb_set_trace, "import pdb\npdb.Pdb\n");
crate::compile_case!(profile_run, "import cProfile\ncProfile.Profile\n");
crate::compile_case!(timeit_timeit, "import timeit\ntimeit.timeit('1+1')\n");
crate::compile_case!(dis_dis, "import dis\ndis.dis(lambda: 1)\n");
crate::compile_case!(ast_parse, "import ast\nast.parse('1+1')\n");
crate::compile_case!(tokenize_tokenize, "import tokenize\nimport io\ntokenize.tokenize(io.BytesIO(b'1').readline)\n");
crate::compile_case!(keyword_iskeyword, "import keyword\nkeyword.iskeyword('def')\n");
crate::compile_case!(builtins_compile, "compile('1+1', '<string>', 'eval')\n");
crate::compile_case!(builtins_eval, "eval('1+1')\n");
crate::compile_case!(builtins_exec, "exec('x=1')\n");
crate::compile_case!(builtins_open, "open(__file__)\n");
crate::compile_case!(io_stringio, "import io\nio.StringIO('hi')\n");
crate::compile_case!(io_bytesio, "import io\nio.BytesIO(b'hi')\n");
crate::compile_case!(mmap_mmap, "import mmap\nhasattr(mmap, 'mmap')\n");
crate::compile_case!(selectors_default, "import selectors\nselectors.DefaultSelector()\n");
crate::compile_case!(signal_signal, "import signal\nsignal.SIGTERM\n");
crate::compile_case!(errno_eacces, "import errno\nerrno.EACCES\n");
crate::compile_case!(ctypes_cdll, "import ctypes\nctypes.CDLL\n");
crate::compile_case!(msvcrt_locking, "try:\n import msvcrt\nexcept ImportError:\n pass\n");
crate::compile_case!(winreg_openkey, "try:\n import winreg\nexcept ImportError:\n pass\n");
crate::compile_case!(venv_create, "import venv\nvenv.EnvBuilder\n");
crate::compile_case!(zipfile_zipfile, "import zipfile\nzipfile.ZipFile\n");
crate::compile_case!(tarfile_open, "import tarfile\ntarfile.open\n");
crate::compile_case!(gzip_compress, "import gzip\ngzip.compress(b'hi')\n");
crate::compile_case!(bz2_compress, "import bz2\nbz2.compress(b'hi')\n");
crate::compile_case!(lzma_compress, "import lzma\nlzma.compress(b'hi')\n");
crate::compile_case!(zlib_crc32, "import zlib\nzlib.crc32(b'hi')\n");
crate::compile_case!(binascii_hexlify, "import binascii\nbinascii.hexlify(b'hi')\n");
crate::compile_case!(quopri_encode, "import quopri\nquopri.encodestring(b'hi')\n");
crate::compile_case!(uu_encode, "try:\n import uu\nexcept ImportError:\n pass\n");
crate::compile_case!(codecs_encode, "import codecs\ncodecs.encode('hi', 'utf-8')\n");
crate::compile_case!(unicodedata_name, "import unicodedata\nunicodedata.name('A')\n");
crate::compile_case!(stringprep, "import stringprep\nstringprep.in_table_a1('a')\n");
crate::compile_case!(readline_parse, "try:\n import readline\nexcept ImportError:\n pass\n");
crate::compile_case!(rlcompleter, "import rlcompleter\nrlcompleter.Completer\n");
crate::compile_case!(cmd_cmd, "import cmd\ncmd.Cmd\n");
crate::compile_case!(shlex_split, "import shlex\nshlex.split('a b')\n");
crate::compile_case!(netrc_netrc, "import netrc\nnetrc.netrc\n");
crate::compile_case!(xdrlib_packer, "from xdrlib import Packer\nPacker()\n");
crate::compile_case!(plistlib_dumps, "import plistlib\nplistlib.dumps({'a': 1})\n");
crate::compile_case!(shelve_open, "import shelve\nshelve.open\n");
crate::compile_case!(dbm_open, "import dbm\ndbm.open\n");
crate::compile_case!(csv_dictreader, "import csv\nimport io\ncsv.DictReader(io.StringIO('a\\n1'))\n");
crate::compile_case!(configparser_sections, "import configparser\nc = configparser.ConfigParser()\nc.sections()\n");
crate::compile_case!(tomllib_loads, "try:\n import tomllib\n tomllib.loads('a=1')\nexcept ImportError:\n pass\n");
crate::compile_case!(zoneinfo_zoneinfo, "from zoneinfo import ZoneInfo\nZoneInfo('UTC')\n");
crate::compile_case!(calendar_month, "import calendar\ncalendar.month(2020, 1)\n");
crate::compile_case!(colorsys_rgb, "import colorsys\ncolorsys.rgb_to_hsv(1, 0, 0)\n");
