//! Extended unpacking: starred, nested, for-loops, function returns, exceptions.

use crate::helpers::*;

crate::runtime_case!(unpack_two, "a, b = 1, 2\nprint(a, b)\n", "1 2");
crate::runtime_case!(unpack_three, "a, b, c = [1, 2, 3]\nprint(c)\n", "3");
crate::runtime_case!(unpack_star_middle, "a, *m, b = [1, 2, 3, 4]\nprint(a, m, b)\n", "1 [2, 3] 4");
crate::runtime_case!(unpack_star_end, "a, *rest = [1, 2, 3]\nprint(a, rest)\n", "1 [2, 3]");
crate::runtime_case!(unpack_star_begin, "*head, tail = [1, 2, 3]\nprint(head, tail)\n", "[1, 2] 3");
crate::runtime_case!(unpack_star_only, "*all, = [1, 2, 3]\nprint(all)\n", "[1, 2, 3]");
crate::runtime_case!(unpack_nested_tuple, "(a, (b, c)) = (1, (2, 3))\nprint(b, c)\n", "2 3");
crate::runtime_case!(unpack_nested_list, "[a, [b, c]] = [1, [2, 3]]\nprint(b)\n", "2");
crate::runtime_case!(unpack_for_loop, "pairs = []\nfor x, y in [(1, 2), (3, 4)]:\n pairs.append(x + y)\nprint(pairs)\n", "[3, 7]");
crate::runtime_case!(unpack_function_return, "def f():\n return 1, 2\na, b = f()\nprint(a + b)\n", "3");
crate::runtime_case!(unpack_swap, "a, b = 1, 2\na, b = b, a\nprint(a, b)\n", "2 1");
crate::runtime_case!(unpack_ignore, "a, _, c = (1, 2, 3)\nprint(a, c)\n", "1 3");
crate::runtime_case!(unpack_string_chars, "a, b, c = 'xyz'\nprint(b)\n", "y");
crate::runtime_case!(unpack_range_tuple, "print(tuple(range(3)))\n", "(0, 1, 2)");
crate::runtime_case!(unpack_enumerate, "for i, v in enumerate(['a', 'b']):\n print(i, v)\n break\n", "0 a");
crate::runtime_case!(unpack_zip, "for a, b in zip([1, 2], [3, 4]):\n print(a + b)\n break\n", "4");
crate::runtime_case!(unpack_dict_items, "for k, v in {'a': 1}.items():\n print(k, v)\n", "a 1");
crate::runtime_case!(unpack_star_in_call, "def f(a, b, c):\n return a + b + c\nprint(f(*[1, 2, 3]))\n", "6");
crate::runtime_case!(unpack_star_mixed_call, "def f(a, b, c):\n return a + b + c\nprint(f(1, *[2, 3]))\n", "6");
crate::runtime_case!(unpack_kwargs_call, "def f(a, b):\n return a + b\nprint(f(**{'a': 1, 'b': 2}))\n", "3");
crate::runtime_case!(unpack_mixed_kwargs, "def f(a, b, c):\n return a + b + c\nprint(f(1, **{'b': 2, 'c': 3}))\n", "6");
crate::runtime_case!(unpack_list_literal, "print([*range(3)])\n", "[0, 1, 2]");
crate::runtime_case!(unpack_tuple_literal, "print((*[1, 2], 3))\n", "(1, 2, 3)");
crate::runtime_case!(unpack_set_literal, "print({*[1, 2], 3})\n", "{1, 2, 3}");
crate::runtime_case!(unpack_dict_literal, "print({**{'a': 1}, 'b': 2})\n", "{'a': 1, 'b': 2}");
crate::runtime_case!(unpack_nested_star, "a, *b, c = 1, 2, 3, 4\nprint(a, b, c)\n", "1 [2, 3] 4");
crate::runtime_case!(unpack_empty_star, "a, *b = [1]\nprint(a, b)\n", "1 []");
crate::runtime_case!(unpack_generator, "a, b = (x for x in [1, 2])\nprint(a, b)\n", "1 2");
crate::runtime_case!(unpack_exception_tuple, "try:\n raise ValueError(1, 2)\nexcept ValueError as e:\n a, b = e.args\n print(a, b)\n", "1 2");
crate::runtime_case!(unpack_slice_assign, "a = [0, 1, 2, 3]\n*a[1:3], = [9, 8]\nprint(a)\n", "[0, 9, 8, 3]");
crate::runtime_case!(unpack_class_attrs, "class P:\n def __init__(self, x, y):\n  self.x = x\n  self.y = y\np = P(1, 2)\nx, y = p.x, p.y\nprint(x, y)\n", "1 2");
crate::runtime_case!(unpack_match_pattern, "t = (1, 2)\nmatch t:\n case (x, y):\n  print(x, y)\n", "1 2");
crate::runtime_case!(unpack_walrus, "(a := 1)\n(b := 2)\nprint(a, b)\n", "1 2");
crate::runtime_case!(unpack_multiple_assignment, "a = b = c = 0\na, b = 1, 2\nprint(a, b, c)\n", "1 2 0");
crate::runtime_case!(unpack_iterable_unwrap, "a, b = iter([10, 20])\nprint(a, b)\n", "10 20");
crate::runtime_case!(unpack_bytes, "a, b = b'xy'\nprint(a, b)\n", "120 121");
crate::runtime_case!(unpack_for_star, "out = []\nfor *mid, last in [(1, 2, 3)]:\n out.append(last)\nprint(out)\n", "[3]");
crate::runtime_case!(unpack_nested_star_for, "for (a, *rest), b in [((1, 2, 3), 4)]:\n print(a, len(rest), b)\n", "1 2 4");
crate::runtime_case!(unpack_tuple_of_lists, "a, (b, c) = 1, [2, 3]\nprint(b, c)\n", "2 3");
crate::runtime_case!(unpack_list_to_vars, "vars = [1, 2, 3]\nx, y, z = vars\nprint(z)\n", "3");
crate::runtime_case!(unpack_chain, "a, *b = 1, 2, 3\n*c, d = b\nprint(a, c, d)\n", "1 [2] 3");
crate::runtime_case!(unpack_bool_tuple, "a, b = True, False\nprint(a, b)\n", "True False");
crate::runtime_case!(unpack_none_tuple, "a, b = None, 1\nprint(a is None, b)\n", "True 1");
crate::runtime_case!(unpack_float_tuple, "a, b = 1.5, 2.5\nprint(a + b)\n", "4.0");
crate::runtime_case!(unpack_complex, "a, b = 1+2j, 3+4j\nprint(a.real, b.imag)\n", "1.0 4.0");
crate::runtime_case!(unpack_set_to_tuple, "t = tuple({1, 2})\nprint(len(t))\n", "2");
crate::runtime_case!(unpack_dict_keys, "k1, k2 = {'a': 1, 'b': 2}\nprint(sorted([k1, k2]))\n", "['a', 'b']");

crate::compile_case!(unpack_too_many_values, "try:\n a, b = [1, 2, 3]\nexcept ValueError:\n pass\n");
crate::compile_case!(unpack_too_few_values, "try:\n a, b, c = [1, 2]\nexcept ValueError:\n pass\n");
crate::compile_case!(unpack_star_assignment, "a, *b, c = range(5)\n");
crate::compile_case!(unpack_nested_mismatch, "try:\n (a, b), c = (1, 2, 3)\nexcept ValueError:\n pass\n");
crate::compile_case!(unpack_async_for, "async def f():\n async for x, in async_items():\n  pass\n");
