//! Extended math module: gcd, lcm, hypot, comb, perm, isclose, frexp, ldexp.


crate::runtime_case!(math_gcd, "import math\nprint(math.gcd(12, 18))\n", "6");
crate::runtime_case!(math_lcm, "import math\nprint(math.lcm(4, 6))\n", "12");
crate::runtime_case!(math_hypot, "import math\nprint(math.hypot(3, 4))\n", "5.0");
crate::runtime_case!(math_factorial, "import math\nprint(math.factorial(5))\n", "120");
crate::runtime_case!(math_comb, "import math\nprint(math.comb(5, 2))\n", "10");
crate::runtime_case!(math_perm, "import math\nprint(math.perm(5, 2))\n", "20");
crate::runtime_case!(math_isclose_true, "import math\nprint(math.isclose(0.1 + 0.2, 0.3))\n", "True");
crate::runtime_case!(math_isclose_false, "import math\nprint(math.isclose(1.0, 2.0))\n", "False");
crate::runtime_case!(math_fabs, "import math\nprint(math.fabs(-3.5))\n", "3.5");
crate::runtime_case!(math_floor, "import math\nprint(math.floor(3.7))\n", "3");
crate::runtime_case!(math_ceil, "import math\nprint(math.ceil(3.2))\n", "4");
crate::runtime_case!(math_trunc, "import math\nprint(math.trunc(-3.7))\n", "-3");
crate::runtime_case!(math_sqrt, "import math\nprint(math.sqrt(9))\n", "3.0");
crate::runtime_case!(math_pow, "import math\nprint(math.pow(2, 3))\n", "8.0");
crate::runtime_case!(math_exp, "import math\nprint(round(math.exp(0), 5))\n", "1.0");
crate::runtime_case!(math_log, "import math\nprint(math.log(math.e))\n", "1.0");
crate::runtime_case!(math_log10, "import math\nprint(math.log10(100))\n", "2.0");
crate::runtime_case!(math_log2, "import math\nprint(math.log2(8))\n", "3.0");
crate::runtime_case!(math_sin_zero, "import math\nprint(math.sin(0))\n", "0.0");
crate::runtime_case!(math_cos_zero, "import math\nprint(math.cos(0))\n", "1.0");
crate::runtime_case!(math_tan_zero, "import math\nprint(math.tan(0))\n", "0.0");
crate::runtime_case!(math_degrees, "import math\nprint(math.degrees(math.pi))\n", "180.0");
crate::runtime_case!(math_radians, "import math\nprint(math.radians(180))\n", "3.141592653589793");
crate::runtime_case!(math_pi, "import math\nprint(math.pi > 3.14)\n", "True");
crate::runtime_case!(math_e, "import math\nprint(math.e > 2.71)\n", "True");
crate::runtime_case!(math_inf, "import math\nprint(math.inf > 0)\n", "True");
crate::runtime_case!(math_nan, "import math\nprint(math.isnan(math.nan))\n", "True");
crate::runtime_case!(math_isfinite, "import math\nprint(math.isfinite(1.0))\n", "True");
crate::runtime_case!(math_isinf, "import math\nprint(math.isinf(math.inf))\n", "True");
crate::runtime_case!(math_copysign, "import math\nprint(math.copysign(1, -1))\n", "-1.0");
crate::runtime_case!(math_fmod, "import math\nprint(math.fmod(7, 4))\n", "3.0");
crate::runtime_case!(math_remainder, "import math\nprint(math.remainder(7, 4))\n", "-1.0");
crate::runtime_case!(math_fsum, "import math\nprint(math.fsum([0.1, 0.2, 0.3]))\n", "0.6");
crate::runtime_case!(math_prod, "import math\nprint(math.prod([2, 3, 4]))\n", "24");
crate::runtime_case!(math_dist, "import math\nprint(math.dist((0, 0), (3, 4)))\n", "5.0");
crate::runtime_case!(math_acos, "import math\nprint(math.acos(1))\n", "0.0");
crate::runtime_case!(math_asin, "import math\nprint(math.asin(0))\n", "0.0");
crate::runtime_case!(math_atan, "import math\nprint(math.atan(0))\n", "0.0");
crate::runtime_case!(math_atan2, "import math\nprint(math.atan2(1, 1) > 0)\n", "True");
crate::runtime_case!(math_sinh, "import math\nprint(math.sinh(0))\n", "0.0");
crate::runtime_case!(math_cosh, "import math\nprint(math.cosh(0))\n", "1.0");
crate::runtime_case!(math_tanh, "import math\nprint(math.tanh(0))\n", "0.0");
crate::runtime_case!(math_asinh, "import math\nprint(math.asinh(0))\n", "0.0");
crate::runtime_case!(math_acosh, "import math\nprint(math.acosh(1))\n", "0.0");
crate::runtime_case!(math_atanh, "import math\nprint(math.atanh(0))\n", "0.0");
crate::runtime_case!(math_frexp, "import math\nm, e = math.frexp(8)\nprint(m, e)\n", "0.5 4");
crate::runtime_case!(math_ldexp, "import math\nprint(math.ldexp(0.5, 4))\n", "8.0");
crate::runtime_case!(math_modf, "import math\nprint(math.modf(3.75)[0] > 0)\n", "True");
crate::runtime_case!(math_ceil_div, "import math\nprint(math.ceil(7 / 2))\n", "4");
crate::runtime_case!(math_gcd_zero, "import math\nprint(math.gcd(0, 5))\n", "5");

crate::compile_case!(math_nextafter, "import math\nmath.nextafter(1.0, 2.0)\n");
crate::compile_case!(math_ulp, "import math\nmath.ulp(1.0)\n");
crate::compile_case!(math_lgamma, "import math\nmath.lgamma(5)\n");
crate::compile_case!(math_erf, "import math\nmath.erf(0)\n");
crate::compile_case!(math_erfc, "import math\nmath.erfc(0)\n");
