//! functools, operator, itertools compile/runtime patterns.

use crate::helpers::*;

crate::runtime_case!(functools_partial, "from functools import partial\nadd2 = partial(lambda x, y: x + y, 1)\nprint(add2(2))\n", "3");
crate::runtime_case!(functools_reduce, "from functools import reduce\nprint(reduce(lambda a, b: a + b, [1, 2, 3]))\n", "6");
crate::runtime_case!(functools_lru_cache, "from functools import lru_cache\n@lru_cache(maxsize=32)\ndef f(n):\n return n * 2\nprint(f(3))\n", "6");
crate::runtime_case!(functools_cache, "from functools import cache\n@cache\ndef f(n):\n return n + 1\nprint(f(1), f(1))\n", "2 2");
crate::runtime_case!(functools_wraps, "from functools import wraps\ndef deco(f):\n @wraps(f)\n def w():\n  return f()\n return w\n@deco\ndef g():\n  '''doc'''\n pass\nprint(g.__name__)\n", "g");
crate::runtime_case!(functools_total_ordering, "from functools import total_ordering\n@total_ordering\nclass C:\n def __init__(self, v):\n  self.v = v\n def __eq__(self, o):\n  return self.v == o.v\n def __lt__(self, o):\n  return self.v < o.v\nprint(C(1) <= C(2))\n", "True");
crate::runtime_case!(functools_cmp_to_key, "from functools import cmp_to_key\nprint(sorted([3, 1, 2], key=cmp_to_key(lambda a, b: a - b)))\n", "[1, 2, 3]");
crate::runtime_case!(operator_add, "import operator\nprint(operator.add(2, 3))\n", "5");
crate::runtime_case!(operator_mul, "import operator\nprint(operator.mul(3, 4))\n", "12");
crate::runtime_case!(operator_itemgetter, "import operator\nget0 = operator.itemgetter(0)\nprint(get0([9, 8]))\n", "9");
crate::runtime_case!(operator_attrgetter, "import operator\nclass P:\n x = 5\nprint(operator.attrgetter('x')(P()))\n", "5");
crate::runtime_case!(operator_methodcaller, "import operator\nprint(operator.methodcaller('upper')('abc'))\n", "ABC");
crate::runtime_case!(operator_contains, "import operator\nprint(operator.contains([1, 2], 2))\n", "True");
crate::runtime_case!(operator_truth, "import operator\nprint(operator.truth(0))\n", "False");
crate::runtime_case!(operator_not_, "import operator\nprint(operator.not_(True))\n", "False");
crate::runtime_case!(operator_eq, "import operator\nprint(operator.eq(1, 1))\n", "True");
crate::runtime_case!(operator_lt, "import operator\nprint(operator.lt(1, 2))\n", "True");
crate::runtime_case!(operator_concat, "import operator\nprint(operator.concat('a', 'b'))\n", "ab");
crate::runtime_case!(operator_getitem, "import operator\nprint(operator.getitem([1, 2], 1))\n", "2");
crate::runtime_case!(operator_setitem, "import operator\na = [1, 2]\noperator.setitem(a, 0, 9)\nprint(a)\n", "[9, 2]");
crate::runtime_case!(itertools_count_take, "import itertools\nprint(next(itertools.count(10)))\n", "10");
crate::runtime_case!(itertools_cycle, "import itertools\nc = itertools.cycle('AB')\nprint(next(c), next(c), next(c))\n", "A B A");
crate::runtime_case!(itertools_repeat, "import itertools\nprint(list(itertools.repeat(7, 3)))\n", "[7, 7, 7]");
crate::runtime_case!(itertools_chain, "import itertools\nprint(list(itertools.chain([1, 2], [3])))\n", "[1, 2, 3]");
crate::runtime_case!(itertools_islice, "import itertools\nprint(list(itertools.islice(range(10), 3)))\n", "[0, 1, 2]");
crate::runtime_case!(itertools_tee, "import itertools\na, b = itertools.tee([1, 2], 2)\nprint(list(a), list(b))\n", "[1, 2] [1, 2]");
crate::runtime_case!(itertools_zip_longest, "import itertools\nprint(list(itertools.zip_longest([1, 2], [3])))\n", "[(1, 3), (2, None)]");
crate::runtime_case!(itertools_product, "import itertools\nprint(list(itertools.product([0, 1], repeat=2)))\n", "[(0, 0), (0, 1), (1, 0), (1, 1)]");
crate::runtime_case!(itertools_permutations, "import itertools\nprint(list(itertools.permutations([1, 2])))\n", "[(1, 2), (2, 1)]");
crate::runtime_case!(itertools_combinations, "import itertools\nprint(list(itertools.combinations([1, 2, 3], 2)))\n", "[(1, 2), (1, 3), (2, 3)]");
crate::runtime_case!(itertools_combinations_with_replacement, "import itertools\nprint(list(itertools.combinations_with_replacement([1, 2], 2)))\n", "[(1, 1), (1, 2), (2, 2)]");
crate::runtime_case!(itertools_accumulate, "import itertools\nprint(list(itertools.accumulate([1, 2, 3, 4])))\n", "[1, 3, 6, 10]");
crate::runtime_case!(itertools_groupby, "import itertools\ndata = [('a', 1), ('a', 2), ('b', 3)]\nprint([k for k, _ in itertools.groupby(data, key=lambda x: x[0])])\n", "['a', 'b']");
crate::runtime_case!(itertools_filterfalse, "import itertools\nprint(list(itertools.filterfalse(lambda x: x > 0, [-1, 0, 1])))\n", "[-1, 0]");
crate::runtime_case!(itertools_takewhile, "import itertools\nprint(list(itertools.takewhile(lambda x: x < 3, [1, 2, 3, 1])))\n", "[1, 2]");
crate::runtime_case!(itertools_dropwhile, "import itertools\nprint(list(itertools.dropwhile(lambda x: x < 3, [1, 2, 3, 1])))\n", "[3, 1]");
crate::runtime_case!(itertools_starmap, "import itertools\nprint(list(itertools.starmap(lambda a, b: a + b, [(1, 2), (3, 4)])))\n", "[3, 7]");
crate::runtime_case!(functools_singledispatch, "from functools import singledispatch\n@singledispatch\ndef f(x):\n return 'd'\n@f.register(int)\ndef _i(x):\n return x\nprint(f('a'), f(2))\n", "d 2");
crate::runtime_case!(operator_pow, "import operator\nprint(operator.pow(2, 3))\n", "8");
crate::runtime_case!(operator_mod, "import operator\nprint(operator.mod(10, 3))\n", "1");
crate::runtime_case!(operator_floordiv, "import operator\nprint(operator.floordiv(7, 2))\n", "3");
crate::runtime_case!(operator_truediv, "import operator\nprint(operator.truediv(7, 2))\n", "3.5");
crate::runtime_case!(operator_neg, "import operator\nprint(operator.neg(5))\n", "-5");
crate::runtime_case!(operator_pos, "import operator\nprint(operator.pos(-5))\n", "-5");
crate::runtime_case!(operator_abs, "import operator\nprint(operator.abs(-5))\n", "5");
crate::runtime_case!(operator_inv, "import operator\nprint(operator.inv(1))\n", "-2");
crate::runtime_case!(operator_lshift, "import operator\nprint(operator.lshift(1, 3))\n", "8");
crate::runtime_case!(operator_rshift, "import operator\nprint(operator.rshift(8, 2))\n", "2");
crate::runtime_case!(operator_and, "import operator\nprint(operator.and_(6, 3))\n", "2");
crate::runtime_case!(operator_or, "import operator\nprint(operator.or_(6, 3))\n", "7");
crate::runtime_case!(operator_xor, "import operator\nprint(operator.xor(6, 3))\n", "5");

crate::compile_case!(functools_partialmethod, "from functools import partialmethod\nclass C:\n def m(self, x):\n  return x\n f = partialmethod(m, 1)\n");
crate::compile_case!(itertools_pairwise, "import itertools\nlist(itertools.pairwise([1,2,3]))\n");
crate::compile_case!(itertools_batched, "import itertools\nlist(itertools.batched([1,2,3], 2))\n");
crate::compile_case!(operator_call, "import operator\noperator.call(lambda: 1)\n");
crate::compile_case!(functools_cached_property, "from functools import cached_property\nclass C:\n @cached_property\n def x(self):\n  return 1\n");
