mod helpers;
mod test_wast_proposals;
mod test_wast_script;
mod test_wat_control_flow;
mod test_wat_execution;
mod test_wat_folded;
mod test_wat_instructions;
mod test_wat_module;
mod test_wat_programs;
