[package]
name = "vybex"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_host = { workspace = true, features = ["gui"] }
vybe_widgets = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
crossbeam-channel = "0.5"
toml = "1.1"
quick-xml = "0.39"

[dev-dependencies]

[[bin]]
name = "vybex"
path = "src/main.rs"

[[test]]
name = "vb"
path = "tests/vb/main.rs"

[[test]]
name = "js"
path = "tests/js/main.rs"

[[test]]
name = "pascal"
path = "tests/pascal/main.rs"

[[test]]
name = "csharp"
path = "tests/csharp/main.rs"

[[test]]
name = "python"
path = "tests/python/main.rs"

[[test]]
name = "php"
path = "tests/php/main.rs"

[[test]]
name = "ruby"
path = "tests/ruby/main.rs"

[[test]]
name = "dart"
path = "tests/dart/main.rs"

[[test]]
name = "cobol"
path = "tests/cobol/main.rs"

[[test]]
name = "emitter"
path = "tests/emitter/main.rs"
