//! Exhaustive operators tests: arithmetic, relational, logical, bitwise, string, length, precedence, associativity (Lua 5.x §3.4.1-§3.4.7)

lua_print! {
    op_add_int => { "print(1 + 2)\n", "3" },
    op_add_flt => { "print(1.5 + 2.5)\n", "4.0" },
    op_add_mixed => { "print(1 + 2.5)\n", "3.5" },
    op_sub_int => { "print(5 - 2)\n", "3" },
    op_sub_flt => { "print(5.5 - 2.5)\n", "3.0" },
    op_sub_mixed => { "print(5.5 - 2)\n", "3.5" },
    op_mul_int => { "print(3 * 4)\n", "12" },
    op_mul_flt => { "print(2.5 * 4.0)\n", "10.0" },
    op_mul_mixed => { "print(3 * 2.5)\n", "7.5" },
    op_div_int => { "print(10 / 2)\n", "5.0" },
    op_div_flt => { "print(10.5 / 2.5)\n", "4.2" },
    op_div_mixed => { "print(10 / 2.5)\n", "4.0" },
    op_idiv_int => { "print(10 // 3)\n", "3" },
    op_idiv_flt => { "print(10.5 // 2.5)\n", "4.0" },
    op_idiv_mixed => { "print(10 // 2.5)\n", "4.0" },
    op_mod_int => { "print(10 % 3)\n", "1" },
    op_mod_flt => { "print(10.5 % 2.5)\n", "0.5" },
    op_mod_mixed => { "print(10 % 2.5)\n", "0.0" },
    op_pow_int => { "print(2 ^ 3)\n", "8.0" },
    op_pow_flt => { "print(2.5 ^ 2.0)\n", "6.25" },
    op_pow_mixed => { "print(2 ^ 2.5 > 5.65 and 2 ^ 2.5 < 5.66)\n", "true" },
    op_unm_int => { "print(-5)\n", "-5" },
    op_unm_flt => { "print(-3.14)\n", "-3.14" },
    op_band_int => { "print(6 & 3)\n", "2" },
    op_bor_int => { "print(6 | 3)\n", "7" },
    op_bxor_int => { "print(6 ~ 3)\n", "5" },
    op_bnot_int => { "print(~6)\n", "-7" },
    op_shl_int => { "print(1 << 3)\n", "8" },
    op_shr_int => { "print(8 >> 3)\n", "1" },
    op_concat_str => { "print(\"a\" .. \"b\")\n", "ab" },
    op_len_str => { "print(#\"abc\")\n", "3" },
    op_len_tbl => { "print(#{1, 2, 3})\n", "3" },
    op_eq_int => { "print(5 == 5)\n", "true" },
    op_eq_flt => { "print(5.0 == 5.0)\n", "true" },
    op_eq_mixed => { "print(5 == 5.0)\n", "true" },
    op_eq_str => { "print(\"a\" == \"a\")\n", "true" },
    op_eq_tbl => { "local t = {}; print(t == t)\n", "true" },
    op_eq_tbl_diff => { "print({} == {})\n", "false" },
    op_ne_int => { "print(5 ~= 6)\n", "true" },
    op_lt_int => { "print(5 < 6)\n", "true" },
    op_le_int => { "print(5 <= 5)\n", "true" },
    op_gt_int => { "print(6 > 5)\n", "true" },
    op_ge_int => { "print(5 >= 5)\n", "true" },
    op_and_falsy => { "print(false and 5)\n", "false" },
    op_and_truthy => { "print(5 and 10)\n", "10" },
    op_or_falsy => { "print(false or 5)\n", "5" },
    op_or_truthy => { "print(5 or 10)\n", "5" },
    op_not_val => { "print(not false)\n", "true" },
    op_precedence_mul_add => { "print(2 + 3 * 4)\n", "14" },
    op_precedence_pow_unm => { "print(-2 ^ 2)\n", "-4.0" },
    op_precedence_concat_add => { "print(\"a\" .. 1 + 2)\n", "a3" },
    op_precedence_bit_shift => { "print(1 + 2 << 1)\n", "6" },
}
