lua_print! {
    test_upvalue_basic => { "local function outer() local a=1; return function() return a end end; print(outer()())", "1" },
    test_upvalue_mutation => { "local function outer() local a=1; return function() a=a+1; return a end end; local f=outer(); print(f()..f())", "23" },
    test_upvalue_shared_between_closures => { "local function outer() local a=1; local function f1() a=a+1; return a end; local function f2() a=a*2; return a end; return f1, f2 end; local f1, f2 = outer(); print(f1()..f2()..f1())", "245" },
    test_upvalue_independent_per_invocation => { "local function outer() local a=1; return function() a=a+1; return a end end; local f1=outer(); local f2=outer(); print(f1()..f2()..f1())", "223" },
    test_upvalue_shadowing => { "local a=1; local function outer() local a=2; return function() return a end end; print(outer()()..a)", "21" },
    test_upvalue_closing_over_loop_variable_while => { "local t={}; local i=1; while i<=3 do local j=i; t[i]=function() return j end; i=i+1 end; print(t[1]()..t[2]()..t[3]())", "123" },
    test_upvalue_closing_over_loop_variable_for_numeric => { "local t={}; for i=1,3 do t[i]=function() return i end end; print(t[1]()..t[2]()..t[3]())", "123" },
    test_upvalue_closing_over_loop_variable_for_generic => { "local t={}; for _, v in ipairs({'a','b'}) do table.insert(t, function() return v end) end; print(t[1]()..t[2]())", "ab" },
    test_upvalue_nested_closures => { "local function f1(x) return function(y) return function(z) return x+y+z end end end; print(f1(1)(2)(3))", "6" },
    test_upvalue_mutation_nested => { "local function f() local a=1; return function() local b=2; return function() a=a+1; b=b+1; return a..b end end end; local c=f()(); print(c()..c())", "2334" },
    test_upvalue_closing_over_arguments => { "local function f(a, b) return function() return a..b end end; print(f(1, 2)())", "12" },
    test_upvalue_recursive_function => { "local f; f = function(n) if n==0 then return 1 else return n * f(n-1) end end; print(f(4))", "24" },
    test_upvalue_local_recursive_function => { "local function f(n) if n==0 then return 1 else return n * f(n-1) end end; print(f(4))", "24" },
    test_upvalue_recursive_function_shadowed => { "local function f(n) if n==0 then return 1 else return n * f(n-1) end end; local g=f; f=function() return 100 end; print(g(4))", "2400" },
    test_upvalue_escaping_scope_goto => { "local f; do local a=1; ::lbl::; f=function() return a end; if a==1 then a=2; goto lbl end end; print(f())", "2" },
    test_upvalue_closure_identity => { "local function f() local a=1; return function() return a end end; local c1=f(); local c2=f(); print(tostring(c1==c2))", "false" },
    test_upvalue_closure_identity_same_scope => { "local t={}; for i=1,2 do local a=1; local function f() return a end; t[i]=f end; print(tostring(t[1]==t[2]))", "false" },
    test_upvalue_closure_identity_same_outer_function => { "local function outer() local function inner() end; return inner, inner end; local f1, f2 = outer(); print(tostring(f1==f2))", "true" },
    test_upvalue_multiple_assignments => { "local function f() local a,b=1,2; return function() return a..b end end; print(f()())", "12" }
}
