lua_print! {
    test_format_string => { "print(string.format('hello %s', 'world'))", "hello world" },
    test_format_string_truncation => { "print(string.format('hello %.3s', 'world'))", "hello wor" },
    test_format_integer => { "print(string.format('%d', 42.0))", "42" },
    test_format_integer_padded => { "print(string.format('%03d', 5))", "005" },
    test_format_integer_signed => { "print(string.format('%+d', 5))", "+5" },
    test_format_integer_space => { "print(string.format('% d', 5))", " 5" },
    test_format_hex => { "print(string.format('%x', 255))", "ff" },
    test_format_hex_upper => { "print(string.format('%X', 255))", "FF" },
    test_format_hex_prefix => { "print(string.format('%#x', 255))", "0xff" },
    test_format_octal => { "print(string.format('%o', 8))", "10" },
    test_format_octal_prefix => { "print(string.format('%#o', 8))", "010" },
    test_format_float => { "print(string.format('%.2f', 3.14159))", "3.14" },
    test_format_float_scientific => { "print(string.format('%.1e', 314.159))", "3.1e+02" },
    test_format_float_scientific_upper => { "print(string.format('%.1E', 314.159))", "3.1E+02" },
    test_format_float_hex => { "print(string.format('%a', 1.5))", "0x1.8p+0" },
    test_format_float_hex_upper => { "print(string.format('%A', 1.5))", "0X1.8P+0" },
    test_format_char => { "print(string.format('%c', 65))", "A" },
    test_format_quoted_string => { "print(string.format('%q', 'a \"b\" \\n c'))", "\"a \\\"b\\\" \\n c\"" },
    test_format_literal_percent => { "print(string.format('%%'))", "%" },
    test_format_missing_arg => { "local ok, err = pcall(function() string.format('%d') end); print(tostring(ok))", "false" },
    test_format_wrong_type => { "local ok, err = pcall(function() string.format('%d', 'abc') end); print(tostring(ok))", "false" },
    test_format_width_asterisk => { "local ok, err = pcall(function() string.format('%*d', 5, 42) end); print(tostring(ok))", "false" }
}
