//! Super type conversion, representation, and lexical checks (Lua 5.x §2.1)

lua_print! {
    type_sup_nil_check_1 => { "print(type(nil))\n", "nil" },
    type_sup_nil_check_2 => { "print(type(nil == nil))\n", "boolean" },
    type_sup_nil_check_3 => { "print(type(nil ~= nil))\n", "boolean" },
    type_sup_bool_true_1 => { "print(type(true))\n", "boolean" },
    type_sup_bool_true_2 => { "print(type(true == true))\n", "boolean" },
    type_sup_bool_true_3 => { "print(type(true ~= true))\n", "boolean" },
    type_sup_bool_false_1 => { "print(type(false))\n", "boolean" },
    type_sup_bool_false_2 => { "print(type(false == false))\n", "boolean" },
    type_sup_bool_false_3 => { "print(type(false ~= false))\n", "boolean" },
    type_sup_number_int_1 => { "print(type(420))\n", "number" },
    type_sup_number_int_2 => { "print(type(420 == 420))\n", "boolean" },
    type_sup_number_int_3 => { "print(type(420 ~= 420))\n", "boolean" },
    type_sup_number_flt_1 => { "print(type(3.1415))\n", "number" },
    type_sup_number_flt_2 => { "print(type(3.1415 == 3.1415))\n", "boolean" },
    type_sup_number_flt_3 => { "print(type(3.1415 ~= 3.1415))\n", "boolean" },
    type_sup_string_check_1 => { "print(type(\"abcd\"))\n", "string" },
    type_sup_string_check_2 => { "print(type(\"abcd\" == \"abcd\"))\n", "boolean" },
    type_sup_string_check_3 => { "print(type(\"abcd\" ~= \"abcd\"))\n", "boolean" },
    type_sup_table_check_1 => { "print(type({1}))\n", "table" },
    type_sup_table_check_2 => { "print(type({1} == {1}))\n", "boolean" },
    type_sup_table_check_3 => { "print(type({1} ~= {1}))\n", "boolean" },
}
