lua_print! {
    test_index_table_basic => { "local t1={a=1}; local t2={}; setmetatable(t2, {__index=t1}); print(t2.a)", "1" },
    test_index_function_basic => { "local t={}; setmetatable(t, {__index=function(tbl, k) return k..k end}); print(t.foo)", "foofoo" },
    test_index_chain_2 => { "local t1={a=10}; local t2={}; setmetatable(t2, {__index=t1}); local t3={}; setmetatable(t3, {__index=t2}); print(t3.a)", "10" },
    test_index_chain_3 => { "local t1={x=99}; local t2=setmetatable({}, {__index=t1}); local t3=setmetatable({}, {__index=t2}); local t4=setmetatable({}, {__index=t3}); print(t4.x)", "99" },
    test_index_chain_function => { "local t1=setmetatable({}, {__index=function(t,k) return k..'1' end}); local t2=setmetatable({}, {__index=t1}); print(t2.z)", "z1" },
    test_index_override_existing => { "local t1={a=1}; setmetatable(t1, {__index=function() return 2 end}); print(t1.a)", "1" },
    test_index_rawget => { "local t=setmetatable({}, {__index={a=1}}); print(rawget(t, 'a') or 'nil')", "nil" },
    test_index_rawget_existing => { "local t=setmetatable({a=2}, {__index={a=1}}); print(rawget(t, 'a'))", "2" },
    test_index_function_receives_table => { "local target; local t={}; setmetatable(t, {__index=function(tbl, k) target=tbl; return 1 end}); print(t.a..' '..tostring(t==target))", "1 true" },
    test_index_function_receives_key => { "local t={}; setmetatable(t, {__index=function(tbl, k) return type(k) end}); print(t[42]..' '..t[true])", "number boolean" },
    test_index_nil_metatable => { "local t={}; print(t.a or 'nil')", "nil" },
    test_index_method_call => { "local class={}; function class:get() return self.x end; local obj=setmetatable({x=5}, {__index=class}); print(obj:get())", "5" },
    test_index_method_call_from_base => { "local base={v=10}; function base:get() return self.v end; local child=setmetatable({v=20}, {__index=base}); print(child:get())", "20" },
    test_index_error_in_handler => { "local t=setmetatable({}, {__index=function() error('boom') end}); local ok, err = pcall(function() return t.a end); print(ok)", "false" },
    test_index_return_multiple_from_handler => { "local t=setmetatable({}, {__index=function() return 1, 2 end}); local a,b = t.a; print(tostring(a)..' '..tostring(b))", "1 nil" },
    test_index_fallback_to_nil => { "local t1={}; local t2=setmetatable({}, {__index=t1}); print(t2.a or 'nil')", "nil" },
    test_index_metamethod_type_string => { "debug.setmetatable('', {__index={upper=string.upper}}); print(('abc'):upper())", "ABC" },
    test_index_metamethod_type_number => { "debug.setmetatable(0, {__index=function(n, k) return n+k end}); print((10)[5])", "15" },
    test_index_metamethod_type_nil => { "debug.setmetatable(nil, {__index=function(n, k) return 'nil_'..k end}); local x=nil; print(x['foo'])", "nil_foo" },
    test_index_metamethod_type_bool => { "debug.setmetatable(true, {__index={a='yes'}}); print(true.a)", "yes" },
    test_index_nested_self => { "local t={}; t.self=t; setmetatable(t, {__index=t}); print(t.self.self == t)", "true" },
    test_index_shadowing => { "local t=setmetatable({a=1}, {__index={a=2, b=3}}); print(t.a..' '..t.b)", "1 3" },
    test_index_using_next => { "local t=setmetatable({}, {__index={a=1}}); print(next(t) or 'nil')", "nil" },
    test_index_using_pairs => { "local t=setmetatable({}, {__index={a=1}}); local c=0; for k,v in pairs(t) do c=c+1 end; print(c)", "0" },
    test_index_non_table_non_function => { "local t={}; setmetatable(t, {__index=42}); local ok = pcall(function() return t.a end); print(ok)", "false" },
    test_index_function_returns_nil => { "local t=setmetatable({}, {__index=function() return nil end}); print(t.a or 'nil')", "nil" },
    test_index_circular_chain => { "local t1={}; local t2=setmetatable({}, {__index=t1}); setmetatable(t1, {__index=t2}); local ok = pcall(function() return t2.a end); print(ok)", "false" },
    test_index_upvalue_closure => { "local count=0; local t=setmetatable({}, {__index=function() count=count+1; return count end}); print(t.a..' '..t.b)", "1 2" }
}
