lua_print! {
    test_newindex_table_basic => { "local t1={}; local t2={}; setmetatable(t2, {__newindex=t1}); t2.a=1; print(t1.a..' '..(t2.a or 'nil'))", "1 nil" },
    test_newindex_function_basic => { "local target, key, val; local t={}; setmetatable(t, {__newindex=function(tbl, k, v) target=tbl; key=k; val=v end}); t.a=10; print(key..' '..val..' '..tostring(t==target))", "a 10 true" },
    test_newindex_chain_2 => { "local t1={}; local t2={}; setmetatable(t2, {__newindex=t1}); local t3={}; setmetatable(t3, {__newindex=t2}); t3.a=5; print(t1.a)", "5" },
    test_newindex_chain_3 => { "local t1={}; local t2=setmetatable({}, {__newindex=t1}); local t3=setmetatable({}, {__newindex=t2}); local t4=setmetatable({}, {__newindex=t3}); t4.x=99; print(t1.x)", "99" },
    test_newindex_chain_function => { "local k1, v1; local t1=setmetatable({}, {__newindex=function(t,k,v) k1=k; v1=v end}); local t2=setmetatable({}, {__newindex=t1}); t2.z=42; print(k1..' '..v1)", "z 42" },
    test_newindex_ignore_existing => { "local t1={a=1}; setmetatable(t1, {__newindex=function() error('should not run') end}); t1.a=2; print(t1.a)", "2" },
    test_newindex_rawset => { "local t=setmetatable({}, {__newindex=function() error('boom') end}); rawset(t, 'a', 1); print(t.a)", "1" },
    test_newindex_rawset_existing => { "local t=setmetatable({a=1}, {__newindex=function() error('boom') end}); rawset(t, 'a', 2); print(t.a)", "2" },
    test_newindex_function_modifies_table => { "local t={}; setmetatable(t, {__newindex=function(tbl, k, v) rawset(tbl, k, v*2) end}); t.a=5; print(t.a)", "10" },
    test_newindex_function_modifies_other_table => { "local other={}; local t={}; setmetatable(t, {__newindex=function(tbl, k, v) other[k]=v end}); t.a=5; print((t.a or 'nil')..' '..other.a)", "nil 5" },
    test_newindex_method_call_imitation => { "local class={}; function class:set(k, v) rawset(self, k, v) end; local obj=setmetatable({}, {__newindex=function(t,k,v) class.set(t,k,v) end}); obj.x=5; print(obj.x)", "5" },
    test_newindex_error_in_handler => { "local t=setmetatable({}, {__newindex=function() error('boom') end}); local ok, err = pcall(function() t.a=1 end); print(ok)", "false" },
    test_newindex_fallback_to_nil => { "local t1={}; local t2=setmetatable({}, {__newindex=t1}); t2.a=1; print(t2.a or 'nil')", "nil" },
    test_newindex_metamethod_type_string => { "debug.setmetatable('', {__newindex=function() error('boom') end}); local ok = pcall(function() ('a').b = 1 end); print(ok)", "false" },
    test_newindex_metamethod_type_number => { "debug.setmetatable(0, {__newindex=function(n, k, v) rawset(_G, k, v) end}); (10).foo=42; print(foo)", "42" },
    test_newindex_metamethod_type_nil => { "debug.setmetatable(nil, {__newindex=function(n, k, v) rawset(_G, k, 'nil_'..v) end}); local x=nil; x['foo']='bar'; print(foo)", "nil_bar" },
    test_newindex_metamethod_type_bool => { "debug.setmetatable(true, {__newindex=function(b, k, v) rawset(_G, k, v) end}); true.a=100; print(a)", "100" },
    test_newindex_nested_self => { "local t={}; t.self=t; setmetatable(t, {__newindex=function(tbl, k, v) rawset(tbl, k, v) end}); t.a=1; print(t.self.a)", "1" },
    test_newindex_non_table_non_function => { "local t={}; setmetatable(t, {__newindex=42}); local ok = pcall(function() t.a=1 end); print(ok)", "false" },
    test_newindex_circular_chain => { "local t1={}; local t2=setmetatable({}, {__newindex=t1}); setmetatable(t1, {__newindex=t2}); local ok = pcall(function() t2.a=1 end); print(ok)", "false" },
    test_newindex_upvalue_closure => { "local count=0; local t=setmetatable({}, {__newindex=function(tbl,k,v) count=count+1; rawset(tbl,k,v) end}); t.a=1; t.b=2; t.a=3; print(count)", "2" },
    test_newindex_multiple_assignments => { "local t={}; local target={}; setmetatable(t, {__newindex=target}); t.a, t.b = 1, 2; print(target.a..' '..target.b)", "1 2" },
    test_newindex_proxy_table => { "local data={}; local proxy=setmetatable({}, {__index=data, __newindex=function(t,k,v) if type(v)=='number' then data[k]=v end end}); proxy.a=1; proxy.b='str'; print(proxy.a..' '..(proxy.b or 'nil'))", "1 nil" },
    test_newindex_delete_key => { "local t=setmetatable({}, {__newindex=function(tbl,k,v) if v==nil then rawset(_G, 'deleted', true) end end}); t.a=nil; print(deleted)", "true" },
    test_newindex_set_nil => { "local t=setmetatable({}, {__newindex=function(tbl,k,v) rawset(tbl, k, 'was_nil') end}); t.a=nil; print(t.a)", "was_nil" },
    test_newindex_reentrant => { "local t={}; setmetatable(t, {__newindex=function(tbl,k,v) rawset(tbl, k, v); tbl[k..k]=v end}); t.a=1; print(t.a..' '..t.aa)", "1 1" },
    test_newindex_reentrant_error => { "local t={}; setmetatable(t, {__newindex=function(tbl,k,v) tbl[k]=v end}); local ok = pcall(function() t.a=1 end); print(ok)", "false" }
}
