//! Super control flow assertion tests (Lua 5.x §3.3)

lua_print! {
    ctrl_sup_if_1 => { "local x = 0; if true then x = 111 end; print(x)\n", "111" },
    ctrl_sup_if_2 => { "local x = 0; if true then x = 222 end; print(x)\n", "222" },
    ctrl_sup_if_3 => { "local x = 0; if true then x = 333 end; print(x)\n", "333" },
    ctrl_sup_if_4 => { "local x = 0; if true then x = 444 end; print(x)\n", "444" },
    ctrl_sup_if_5 => { "local x = 0; if true then x = 555 end; print(x)\n", "555" },
    ctrl_sup_if_6 => { "local x = 0; if true then x = 666 end; print(x)\n", "666" },
    ctrl_sup_if_7 => { "local x = 0; if true then x = 777 end; print(x)\n", "777" },
    ctrl_sup_if_8 => { "local x = 0; if true then x = 888 end; print(x)\n", "888" },
    ctrl_sup_if_9 => { "local x = 0; if true then x = 999 end; print(x)\n", "999" },
    ctrl_sup_while_1 => { "local n = 0; while n < 10 do n = n + 1 end; print(n)\n", "10" },
    ctrl_sup_while_2 => { "local n = 0; while n < 11 do n = n + 1 end; print(n)\n", "11" },
    ctrl_sup_while_3 => { "local n = 0; while n < 12 do n = n + 1 end; print(n)\n", "12" },
    ctrl_sup_while_4 => { "local n = 0; while n < 13 do n = n + 1 end; print(n)\n", "13" },
    ctrl_sup_while_5 => { "local n = 0; while n < 14 do n = n + 1 end; print(n)\n", "14" },
    ctrl_sup_while_6 => { "local n = 0; while n < 15 do n = n + 1 end; print(n)\n", "15" },
    ctrl_sup_while_7 => { "local n = 0; while n < 16 do n = n + 1 end; print(n)\n", "16" },
    ctrl_sup_while_8 => { "local n = 0; while n < 17 do n = n + 1 end; print(n)\n", "17" },
    ctrl_sup_while_9 => { "local n = 0; while n < 18 do n = n + 1 end; print(n)\n", "18" },
    ctrl_sup_repeat_1 => { "local n = 0; repeat n = n + 1 until n >= 10; print(n)\n", "10" },
    ctrl_sup_repeat_2 => { "local n = 0; repeat n = n + 1 until n >= 11; print(n)\n", "11" },
    ctrl_sup_repeat_3 => { "local n = 0; repeat n = n + 1 until n >= 12; print(n)\n", "12" },
    ctrl_sup_repeat_4 => { "local n = 0; repeat n = n + 1 until n >= 13; print(n)\n", "13" },
    ctrl_sup_repeat_5 => { "local n = 0; repeat n = n + 1 until n >= 14; print(n)\n", "14" },
    ctrl_sup_repeat_6 => { "local n = 0; repeat n = n + 1 until n >= 15; print(n)\n", "15" },
    ctrl_sup_repeat_7 => { "local n = 0; repeat n = n + 1 until n >= 16; print(n)\n", "16" },
    ctrl_sup_repeat_8 => { "local n = 0; repeat n = n + 1 until n >= 17; print(n)\n", "17" },
    ctrl_sup_repeat_9 => { "local n = 0; repeat n = n + 1 until n >= 18; print(n)\n", "18" },
}
