use super::super::super::class_exports::DotnetClassExport;
use super::super::super::classes::DotnetClass;
use super::super::exceptions::EXCEPTION_HIERARCHY;
use vybe_runtime::component_model::{
    ClassType, ConstructorDef, HostTarget, MethodBody, MethodDef, PropertyDef,
};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    let mut exports = vec![
        DotnetClassExport::with_wrapper(
            "dotnet.System",
            ClassType::new("ValueType").with_parent("Object"),
            DotnetClass {
                name: "ValueType",
                parent: Some("Object"),
                properties: &[],
                methods: &[],
                ctor_arity: 0,
                widget_host_fn: None,
                widget_host_module: "vybe:gui",
            },
        ),
        DotnetClassExport::with_wrapper(
            "dotnet.System",
            ClassType::new("Enum")
                .with_parent("ValueType")
                .with_method(MethodDef::static_method(
                    "IsDefined",
                    2,
                    MethodBody::Common("dotnet.enum_is_defined".into()),
                )),
            DotnetClass {
                name: "Enum",
                parent: Some("ValueType"),
                properties: &[],
                methods: &[],
                ctor_arity: 0,
                widget_host_fn: None,
                widget_host_module: "vybe:gui",
            },
        ),
    ];
    exports.extend(EXCEPTION_HIERARCHY.iter().map(|(name, parent)| {
        let class = if parent.is_empty() {
            ClassType::new(*name)
        } else {
            ClassType::new(*name).with_parent(*parent)
        };
        DotnetClassExport::new("dotnet.System", class)
    }));
    exports.extend(vec![
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Object")
                .with_method(MethodDef::static_method(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.object_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ReferenceEquals",
                    2,
                    MethodBody::Common("dotnet.object_reference_equals".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("BitConverter")
                .with_method(MethodDef::static_method(
                    "IsLittleEndian",
                    0,
                    MethodBody::Common("dotnet.bitconverter_is_little_endian".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.bitconverter_get_bytes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt32",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_number".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt64",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_number".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToDouble",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_number".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBoolean",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_boolean".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToChar",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_char".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.bitconverter_to_string".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Buffer").with_method(MethodDef::static_method(
                "BlockCopy",
                5,
                MethodBody::Common("dotnet.buffer_block_copy".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("GC")
                .with_method(MethodDef::static_method(
                    "MaxGeneration",
                    0,
                    MethodBody::Common("dotnet.gc_zero".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Collect",
                    0,
                    MethodBody::Common("dotnet.gc_noop".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Collect",
                    1,
                    MethodBody::Common("dotnet.gc_noop".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WaitForPendingFinalizers",
                    0,
                    MethodBody::Common("dotnet.gc_noop".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTotalMemory",
                    1,
                    MethodBody::Common("dotnet.gc_total_memory".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CollectionCount",
                    1,
                    MethodBody::Common("dotnet.gc_zero".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetGeneration",
                    1,
                    MethodBody::Common("dotnet.gc_generation".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.RegularExpressions",
            ClassType::new("RegexMatchTimeoutException").with_parent("TimeoutException"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("EncoderFallbackException").with_parent("ArgumentException"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("DecoderFallbackException").with_parent("ArgumentException"),
        ),
        DotnetClassExport::new("dotnet.System", ClassType::new("Attribute")),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("AttributeUsageAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("FlagsAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("STAThreadAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("SerializableAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("ObsoleteAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Reflection",
            ClassType::new("AssemblyTitleAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System.ComponentModel",
            ClassType::new("DescriptionAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("DateTime")
                .with_constructor(ConstructorDef::new(3).with_common_backing("dotnet.datetime_new"))
                .with_method(MethodDef::static_method(
                    "Now",
                    0,
                    MethodBody::Common("dotnet.datetime_now".into()),
                ))
                .with_method(MethodDef::static_method(
                    "UtcNow",
                    0,
                    MethodBody::Common("dotnet.datetime_now".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Today",
                    0,
                    MethodBody::Common("dotnet.datetime_today".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Parse",
                    1,
                    MethodBody::Common("dotnet.datetime_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "DaysInMonth",
                    2,
                    MethodBody::Common("dotnet.datetime_days_in_month".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsLeapYear",
                    1,
                    MethodBody::Common("dotnet.datetime_is_leap_year".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    2,
                    MethodBody::Common("dotnet.datetime_compare".into()),
                ))
                .with_method(MethodDef::new(
                    "AddDays",
                    1,
                    MethodBody::Common("dotnet.datetime_add_days".into()),
                ))
                .with_method(MethodDef::new(
                    "AddHours",
                    1,
                    MethodBody::Common("dotnet.datetime_add_hours".into()),
                ))
                .with_method(MethodDef::new(
                    "AddMonths",
                    1,
                    MethodBody::Common("dotnet.datetime_add_months".into()),
                ))
                .with_method(MethodDef::new(
                    "ToShortDateString",
                    0,
                    MethodBody::Common("dotnet.datetime_to_short_date_string".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Random")
                .with_constructor(ConstructorDef::new(0).with_common_backing("dotnet.random_new"))
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.random_new"))
                .with_method(MethodDef::new(
                    "Next",
                    0,
                    MethodBody::Common("dotnet.random_next".into()),
                ))
                .with_method(MethodDef::new(
                    "Next",
                    1,
                    MethodBody::Common("dotnet.random_next".into()),
                ))
                .with_method(MethodDef::new(
                    "Next",
                    2,
                    MethodBody::Common("dotnet.random_next".into()),
                ))
                .with_method(MethodDef::new(
                    "NextDouble",
                    0,
                    MethodBody::Common("dotnet.random_next_double".into()),
                ))
                .with_method(MethodDef::new(
                    "NextBytes",
                    1,
                    MethodBody::Common("dotnet.random_next_bytes".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("TimeSpan")
                .with_constructor(ConstructorDef::new(3).with_common_backing("dotnet.timespan_new"))
                .with_method(MethodDef::static_method(
                    "FromDays",
                    1,
                    MethodBody::Common("dotnet.timespan_from_days".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromHours",
                    1,
                    MethodBody::Common("dotnet.timespan_from_hours".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromMinutes",
                    1,
                    MethodBody::Common("dotnet.timespan_from_minutes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromSeconds",
                    1,
                    MethodBody::Common("dotnet.timespan_from_seconds".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromMilliseconds",
                    1,
                    MethodBody::Common("dotnet.timespan_from_milliseconds".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Zero",
                    0,
                    MethodBody::Common("dotnet.timespan_zero".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    2,
                    MethodBody::Common("dotnet.timespan_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Add",
                    2,
                    MethodBody::Common("dotnet.timespan_add".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Subtract",
                    2,
                    MethodBody::Common("dotnet.timespan_sub".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Parse",
                    1,
                    MethodBody::Common("dotnet.timespan_parse".into()),
                ))
                .with_method(MethodDef::new(
                    "Negate",
                    0,
                    MethodBody::Common("dotnet.timespan_negate".into()),
                ))
                .with_method(MethodDef::new(
                    "Duration",
                    0,
                    MethodBody::Common("dotnet.timespan_duration".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Array")
                .with_method(MethodDef::new(
                    "GetValue",
                    1,
                    MethodBody::Common("dotnet.array_get_checked".into()),
                ))
                .with_method(MethodDef::new(
                    "SetValue",
                    2,
                    MethodBody::Common("dotnet.array_set_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetValue",
                    2,
                    MethodBody::Common("dotnet.array_get_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetValue",
                    3,
                    MethodBody::Common("dotnet.array_set_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Clear",
                    3,
                    MethodBody::Common("dotnet.array_clear".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Copy",
                    3,
                    MethodBody::Common("dotnet.array_copy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConstrainedCopy",
                    5,
                    MethodBody::Common("dotnet.array_copy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Resize",
                    2,
                    MethodBody::Common("dotnet.array_resize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sort",
                    1,
                    MethodBody::Common("dotnet.array_sort".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Reverse",
                    1,
                    MethodBody::Common("dotnet.array_reverse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Fill",
                    2,
                    MethodBody::Common("dotnet.array_fill".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IndexOf",
                    2,
                    MethodBody::Common("dotnet.array_index_of".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LastIndexOf",
                    2,
                    MethodBody::Common("dotnet.array_last_index_of".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Empty",
                    0,
                    MethodBody::Common("dotnet.array_empty".into()),
                ))
                .with_method(MethodDef::static_method(
                    // .NET returns the match index, or the bitwise complement of
                    // the insertion point (`~i`, i.e. a negative) when absent —
                    // `indexOf` can't express the miss case, so use the shared
                    // comparison-ordered search.
                    "BinarySearch",
                    2,
                    MethodBody::Common("dotnet.array_binary_search".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConvertAll",
                    2,
                    MethodBody::Common("dotnet.array_convert_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CreateInstance",
                    1,
                    MethodBody::Common("dotnet.array_create_instance".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Exists",
                    2,
                    MethodBody::Common("dotnet.array_exists".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Find",
                    2,
                    MethodBody::Common("dotnet.array_find".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindAll",
                    2,
                    MethodBody::Common("dotnet.array_find_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindIndex",
                    2,
                    MethodBody::Common("dotnet.array_find_index".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindLastIndex",
                    2,
                    MethodBody::Common("dotnet.array_find_last_index".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindLast",
                    2,
                    MethodBody::Common("dotnet.array_find_last".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ForEach",
                    2,
                    MethodBody::Common("dotnet.array_for_each".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TrueForAll",
                    2,
                    MethodBody::Common("dotnet.array_true_for_all".into()),
                )),
        ),
        // ── System.Math ────────────────────────────────────────────
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Math")
                .with_method(MethodDef::static_method(
                    "Abs",
                    1,
                    MethodBody::Common("dotnet.system.math.abs".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Floor",
                    1,
                    MethodBody::Common("dotnet.system.math.floor".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Ceiling",
                    1,
                    MethodBody::Common("dotnet.system.math.ceiling".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Ceil",
                    1,
                    MethodBody::Common("dotnet.system.math.ceiling".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sqrt",
                    1,
                    MethodBody::Common("dotnet.system.math.sqrt".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Truncate",
                    1,
                    MethodBody::Common("dotnet.system.math.truncate".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Trunc",
                    1,
                    MethodBody::Common("dotnet.system.math.truncate".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Round",
                    1,
                    MethodBody::Common("dotnet.system.math.round".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Min",
                    2,
                    MethodBody::Common("dotnet.system.math.min".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Max",
                    2,
                    MethodBody::Common("dotnet.system.math.max".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Pow",
                    2,
                    MethodBody::Common("dotnet.system.math.pow".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sin",
                    1,
                    MethodBody::Common("dotnet.system.math.sin".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Cos",
                    1,
                    MethodBody::Common("dotnet.system.math.cos".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Tan",
                    1,
                    MethodBody::Common("dotnet.system.math.tan".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Asin",
                    1,
                    MethodBody::Common("dotnet.system.math.asin".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Acos",
                    1,
                    MethodBody::Common("dotnet.system.math.acos".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Atan",
                    1,
                    MethodBody::Common("dotnet.system.math.atan".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Atan2",
                    2,
                    MethodBody::Common("dotnet.system.math.atan2".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log",
                    1,
                    MethodBody::Common("dotnet.system.math.log".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log",
                    2,
                    MethodBody::Common("dotnet.system.math.log".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log10",
                    1,
                    MethodBody::Common("dotnet.system.math.log10".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log2",
                    1,
                    MethodBody::Common("dotnet.system.math.log2".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Exp",
                    1,
                    MethodBody::Common("dotnet.system.math.exp".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sinh",
                    1,
                    MethodBody::Common("dotnet.system.math.sinh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Cosh",
                    1,
                    MethodBody::Common("dotnet.system.math.cosh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Tanh",
                    1,
                    MethodBody::Common("dotnet.system.math.tanh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sign",
                    1,
                    MethodBody::Common("dotnet.system.math.sign".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Clamp",
                    3,
                    MethodBody::Common("dotnet.system.math.clamp".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Console")
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.console_writeline".into()),
                ))
                // `Console.WriteLine()` — bare newline. Same common; the
                // dispatcher branches on argc.
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    0,
                    MethodBody::Common("dotnet.console_writeline".into()),
                ))
                // `Console.Write(v)` writes with NO trailing newline — a
                // distinct common from WriteLine.
                .with_method(MethodDef::static_method(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.console_write".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ReadLine",
                    0,
                    MethodBody::Common("dotnet.console_readline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Print",
                    1,
                    MethodBody::Common("dotnet.console_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Assert",
                    1,
                    MethodBody::Common("dotnet.console_writeline".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Delegate")
                .with_method(MethodDef::static_method(
                    "Combine",
                    2,
                    MethodBody::Common("delegates.combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Remove",
                    2,
                    MethodBody::Common("delegates.remove".into()),
                )),
        ),
        // `EventArgs.Empty` — the canonical empty event payload. Handlers that
        // carry no data (`EventHandler`) pass it as a non-null placeholder; an
        // empty object satisfies every use that doesn't read a field off it.
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("EventArgs").with_method(MethodDef::static_method(
                "Empty",
                0,
                MethodBody::Common("object.new".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Convert")
                .with_method(MethodDef::static_method(
                    "ToInt32",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToDouble",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "Number")),
                ))
                .with_method(MethodDef::static_method(
                    "ToSingle",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "Number")),
                ))
                .with_method(MethodDef::static_method(
                    "ToDecimal",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "Number")),
                ))
                .with_method(MethodDef::static_method(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.tostring".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBoolean",
                    1,
                    MethodBody::Common("dyn_to_bool".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToChar",
                    1,
                    MethodBody::Common("dotnet.cchar".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToByte",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt64",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToDateTime",
                    1,
                    MethodBody::Common("dotnet.datetime_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64String",
                    1,
                    MethodBody::Common("dotnet.convert_to_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64String",
                    2,
                    MethodBody::Common("dotnet.convert_to_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64String",
                    3,
                    MethodBody::Common("dotnet.convert_to_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromBase64String",
                    1,
                    MethodBody::Common("dotnet.convert_from_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64CharArray",
                    5,
                    MethodBody::Common("dotnet.convert_to_base64_char_array".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("String")
                .with_constructor(
                    ConstructorDef::new(3).with_common_backing("dotnet.string_from_chars"),
                )
                .with_method(MethodDef::static_method(
                    "Format",
                    2,
                    MethodBody::Common("dotnet.string_format".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Join",
                    2,
                    MethodBody::Common("collections.join_sep_first".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Concat",
                    2,
                    MethodBody::Common("str_concat".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Concat",
                    3,
                    MethodBody::Common("dotnet.string_concat".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    2,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    3,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    6,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CompareOrdinal",
                    2,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Equals",
                    3,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsNullOrWhiteSpace",
                    1,
                    MethodBody::Common("dotnet.string_is_null_or_whitespace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsNullOrEmpty",
                    1,
                    MethodBody::Common("dotnet.string_is_null_or_empty".into()),
                ))
                .with_method(MethodDef::new(
                    "Contains",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:string", "includes")),
                ))
                .with_method(MethodDef::new(
                    "Contains",
                    2,
                    MethodBody::Common("dotnet.string_contains".into()),
                ))
                .with_method(MethodDef::new(
                    "StartsWith",
                    1,
                    MethodBody::Common("str_starts_with".into()),
                ))
                .with_method(MethodDef::new(
                    "StartsWith",
                    2,
                    MethodBody::Common("dotnet.string_starts_with".into()),
                ))
                .with_method(MethodDef::new(
                    "EndsWith",
                    1,
                    MethodBody::Common("str_ends_with".into()),
                ))
                .with_method(MethodDef::new(
                    "EndsWith",
                    2,
                    MethodBody::Common("dotnet.string_ends_with".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOf",
                    1,
                    MethodBody::Common("dotnet.string_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOf",
                    2,
                    MethodBody::Common("dotnet.string_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOf",
                    3,
                    MethodBody::Common("dotnet.string_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOfAny",
                    1,
                    MethodBody::Common("dotnet.string_index_of_any".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOfAny",
                    2,
                    MethodBody::Common("dotnet.string_index_of_any".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOf",
                    1,
                    MethodBody::Common("dotnet.string_last_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOf",
                    2,
                    MethodBody::Common("dotnet.string_last_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOf",
                    3,
                    MethodBody::Common("dotnet.string_last_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOfAny",
                    1,
                    MethodBody::Common("dotnet.string_last_index_of_any".into()),
                ))
                .with_method(MethodDef::new(
                    "Substring",
                    1,
                    MethodBody::Common("dotnet.string_substring".into()),
                ))
                .with_method(MethodDef::new(
                    "Substring",
                    2,
                    MethodBody::Common("dotnet.string_substring".into()),
                ))
                .with_method(MethodDef::new(
                    "Chars",
                    1,
                    MethodBody::Common("dotnet.string_char_at_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Chars",
                    2,
                    MethodBody::Common("dotnet.string_char_at_checked".into()),
                ))
                .with_method(MethodDef::new(
                    "PadLeft",
                    1,
                    MethodBody::Common("dotnet.string_pad_left".into()),
                ))
                .with_method(MethodDef::new(
                    "PadLeft",
                    2,
                    MethodBody::Common("dotnet.string_pad_left".into()),
                ))
                .with_method(MethodDef::new(
                    "PadRight",
                    1,
                    MethodBody::Common("dotnet.string_pad_right".into()),
                ))
                .with_method(MethodDef::new(
                    "PadRight",
                    2,
                    MethodBody::Common("dotnet.string_pad_right".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    2,
                    MethodBody::Common("dotnet.string_replace".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    1,
                    MethodBody::Common("dotnet.string_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    2,
                    MethodBody::Common("dotnet.string_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    3,
                    MethodBody::Common("dotnet.string_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Insert",
                    2,
                    MethodBody::Common("dotnet.str_insert".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    1,
                    MethodBody::Common("dotnet.str_remove_start".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    2,
                    MethodBody::Common("dotnet.str_remove_range".into()),
                ))
                .with_method(MethodDef::new(
                    "Trim",
                    1,
                    MethodBody::Common("dotnet.string_trim_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "TrimStart",
                    1,
                    MethodBody::Common("dotnet.string_trim_start_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "TrimEnd",
                    1,
                    MethodBody::Common("dotnet.string_trim_end_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                // `MemoryExtensions.AsSpan` over a string. A `ReadOnlySpan<char>`
                // is the substring itself here — indexing it yields the same
                // single-char strings a `char` is on this runtime.
                // `substr(start, length)` takes a LENGTH, matching .NET exactly;
                // `substring`/`slice` take an END and would need arithmetic.
                .with_method(MethodDef::new(
                    "AsSpan",
                    0,
                    MethodBody::HostCall(HostTarget::new("ecma:object", "valueOf")),
                ))
                .with_method(MethodDef::new(
                    "AsSpan",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:string", "substr")),
                ))
                .with_method(MethodDef::new(
                    "AsSpan",
                    2,
                    MethodBody::HostCall(HostTarget::new("ecma:string", "substr")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Environment")
                .with_property(
                    PropertyDef::new("CurrentDirectory")
                        .with_getter(HostTarget::new("node:process", "cwd")),
                )
                .with_property(
                    PropertyDef::new("NewLine").with_getter(HostTarget::new("node:os", "EOL")),
                )
                .with_property(
                    PropertyDef::new("MachineName")
                        .with_getter(HostTarget::new("node:os", "hostname")),
                )
                .with_property(
                    PropertyDef::new("OSVersion")
                        .with_getter(HostTarget::new("node:os", "version")),
                )
                .with_method(MethodDef::static_method(
                    "UserName",
                    0,
                    MethodBody::Common("dotnet.environment_username".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Version",
                    0,
                    MethodBody::Common("dotnet.environment_version".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ExitCode",
                    0,
                    MethodBody::Common("dotnet.environment_exit_code".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetExitCode",
                    1,
                    MethodBody::Common("dotnet.environment_set_exit_code".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SystemDirectory",
                    0,
                    MethodBody::Common("dotnet.environment_system_directory".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ProcessorCount",
                    0,
                    MethodBody::Common("dotnet.environment_processor_count".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TickCount",
                    0,
                    MethodBody::Common("dotnet.environment_tick_count".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariable",
                    1,
                    MethodBody::Common("dotnet.environment_get".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariable",
                    2,
                    MethodBody::Common("dotnet.environment_get".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetEnvironmentVariable",
                    2,
                    MethodBody::Common("dotnet.environment_set".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetEnvironmentVariable",
                    3,
                    MethodBody::Common("dotnet.environment_set".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariables",
                    0,
                    MethodBody::Common("dotnet.environment_get_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariables",
                    1,
                    MethodBody::Common("dotnet.environment_get_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ExpandEnvironmentVariables",
                    1,
                    MethodBody::Common("dotnet.environment_expand".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFolderPath",
                    1,
                    MethodBody::Common("dotnet.environment_get_folder_path".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetCommandLineArgs",
                    0,
                    MethodBody::Common("dotnet.environment_get_command_line_args".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("EnvironmentVariableTarget")
                .with_method(MethodDef::static_method(
                    "Process",
                    0,
                    MethodBody::Common("dotnet.environment_target_process".into()),
                ))
                .with_method(MethodDef::static_method(
                    "User",
                    0,
                    MethodBody::Common("dotnet.environment_target_user".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Machine",
                    0,
                    MethodBody::Common("dotnet.environment_target_machine".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Environment",
            ClassType::new("SpecialFolder")
                .with_method(MethodDef::static_method(
                    "Personal",
                    0,
                    MethodBody::Common("dotnet.environment_special_folder_personal".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ApplicationData",
                    0,
                    MethodBody::Common("dotnet.environment_special_folder_application_data".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LocalApplicationData",
                    0,
                    MethodBody::Common(
                        "dotnet.environment_special_folder_local_application_data".into(),
                    ),
                ))
                .with_method(MethodDef::static_method(
                    "Desktop",
                    0,
                    MethodBody::Common("dotnet.environment_special_folder_desktop".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.Microsoft.VisualBasic",
            ClassType::new("Strings")
                .with_method(MethodDef::static_method(
                    "Left",
                    2,
                    MethodBody::Common("dotnet.vb_strings_left".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Right",
                    2,
                    MethodBody::Common("dotnet.vb_strings_right".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Mid",
                    2,
                    MethodBody::Common("dotnet.vb_strings_mid".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Mid",
                    3,
                    MethodBody::Common("dotnet.vb_strings_mid".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.Microsoft.VisualBasic",
            ClassType::new("FileSystem")
                .with_method(MethodDef::static_method(
                    "FreeFile",
                    0,
                    MethodBody::Common("dotnet.vb_freefile".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileOpen",
                    3,
                    MethodBody::Common("dotnet.vb_fileopen".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileClose",
                    0,
                    MethodBody::Common("dotnet.vb_fileclose".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileClose",
                    1,
                    MethodBody::Common("dotnet.vb_fileclose".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    1,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    2,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    3,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    4,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    2,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    3,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    4,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LineInput",
                    1,
                    MethodBody::Common("dotnet.vb_lineinput".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Input",
                    1,
                    MethodBody::Common("dotnet.vb_input_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "EOF",
                    1,
                    MethodBody::Common("dotnet.vb_eof".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LOF",
                    1,
                    MethodBody::Common("dotnet.vb_lof".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Loc",
                    1,
                    MethodBody::Common("dotnet.vb_loc".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileAttr",
                    1,
                    MethodBody::Common("dotnet.vb_fileattr".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetAttr",
                    1,
                    MethodBody::Common("dotnet.vb_getattr".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetAttr",
                    2,
                    MethodBody::Common("dotnet.vb_setattr".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Seek",
                    2,
                    MethodBody::Common("dotnet.vb_seek".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Dir",
                    0,
                    MethodBody::Common("dotnet.vb_dir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Dir",
                    1,
                    MethodBody::Common("dotnet.vb_dir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileCopy",
                    2,
                    MethodBody::Common("dotnet.vb_filecopy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Kill",
                    1,
                    MethodBody::Common("dotnet.vb_kill".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileLen",
                    1,
                    MethodBody::Common("dotnet.vb_filelen".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileDateTime",
                    1,
                    MethodBody::Common("dotnet.vb_filedatetime".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CurDir",
                    0,
                    MethodBody::Common("dotnet.vb_curdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ChDir",
                    1,
                    MethodBody::Common("dotnet.vb_chdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MkDir",
                    1,
                    MethodBody::Common("dotnet.vb_mkdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "RmDir",
                    1,
                    MethodBody::Common("dotnet.vb_rmdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Name",
                    2,
                    MethodBody::Common("dotnet.vb_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Rename",
                    2,
                    MethodBody::Common("dotnet.vb_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Get",
                    1,
                    MethodBody::Common("dotnet.vb_get".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Put",
                    1,
                    MethodBody::Common("dotnet.vb_put".into()),
                )),
        ),
    ]);
    exports
}
