use super::super::super::class_exports::DotnetClassExport;
use vybe_runtime::component_model::{
    ClassType, ConstructorDef, HostTarget, MethodBody, MethodDef, PropertyDef,
};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("MemoryStream")
                .with_constructor(ConstructorDef::new(0).with_common_backing("collections.new"))
                .with_method(MethodDef::new(
                    "ToArray",
                    0,
                    MethodBody::Common("collections.clone".into()),
                ))
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("collections.push".into()),
                ))
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("collections.shift".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("FileStream")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.file_open_read"),
                )
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                ))
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "WriteByte",
                    1,
                    MethodBody::Common("dotnet.file_stream_write_byte".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("BinaryReader")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_common_backing("filesystem.read_file"),
                )
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("BinaryWriter")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_common_backing("filesystem.write_file"),
                )
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StreamReader")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.stream_reader_new"),
                )
                .with_method(MethodDef::new(
                    "EndOfStream",
                    0,
                    MethodBody::Common("dotnet.stream_reader_at_end".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadLine",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadToEnd",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StreamWriter")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.stream_writer_new"),
                )
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write_line".into()),
                ))
                .with_method(MethodDef::new(
                    "Flush",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StringReader")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.string_reader_new"),
                )
                .with_method(MethodDef::new(
                    "Peek",
                    0,
                    MethodBody::Common("dotnet.string_reader_peek".into()),
                ))
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.string_reader_read".into()),
                ))
                .with_method(MethodDef::new(
                    "Read",
                    3,
                    MethodBody::Common("dotnet.string_reader_read_buffer".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadBlock",
                    3,
                    MethodBody::Common("dotnet.string_reader_read_buffer".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadLine",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadLineAsync",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadToEnd",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StringWriter")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.string_writer_new"),
                )
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.string_writer_new"),
                )
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "Write",
                    3,
                    MethodBody::Common("dotnet.stream_writer_write_3".into()),
                ))
                .with_method(MethodDef::new(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write_line".into()),
                ))
                .with_method(MethodDef::new(
                    "WriteLineAsync",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write_line_async".into()),
                ))
                .with_method(MethodDef::new(
                    "GetStringBuilder",
                    0,
                    MethodBody::Common("dotnet.string_writer_get_string_builder".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.string_writer_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "Flush",
                    0,
                    MethodBody::Common("dotnet.string_writer_noop".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.string_writer_noop".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.string_writer_noop".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("File")
                // `dotnet.file_*`, not `filesystem.*` directly: the shared
                // lowering answers `null`/`false` — WASI's `result` in each
                // language's idiom — and .NET's idiom is an exception. Binding
                // straight to `filesystem.read_file` let `File.ReadAllText`
                // on a missing file return null, which prints as `0` and
                // concatenates as `""`. The WASI call is the same one; only the
                // failure conversion is .NET's.
                .with_method(MethodDef::static_method(
                    "ReadAllText",
                    1,
                    MethodBody::Common("dotnet.file_read_all_text".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteAllText",
                    2,
                    MethodBody::Common("dotnet.file_write_all_text".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "AppendAllText",
                    2,
                    MethodBody::Common("dotnet.file_append_all_text".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "ReadAllBytes",
                    1,
                    MethodBody::Common("dotnet.file_read_all_bytes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteAllBytes",
                    2,
                    MethodBody::Common("dotnet.file_write_all_bytes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Exists",
                    1,
                    MethodBody::Common("filesystem.exists".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "Delete",
                    1,
                    MethodBody::Common("dotnet.directory_delete".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Delete",
                    2,
                    MethodBody::Common("dotnet.directory_delete".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Copy",
                    2,
                    MethodBody::Common("filesystem.copy".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "Move",
                    2,
                    MethodBody::Common("filesystem.rename".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "ReadAllLines",
                    1,
                    MethodBody::Common("dotnet.file_read_all_lines".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteAllLines",
                    2,
                    MethodBody::Common("dotnet.file_write_all_lines".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Create",
                    1,
                    MethodBody::Common("dotnet.file_create".into()),
                ))
                .with_method(MethodDef::static_method(
                    "OpenRead",
                    1,
                    MethodBody::Common("dotnet.file_open_read".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("FileInfo").with_constructor(
                ConstructorDef::new(1).with_common_backing("dotnet.file_info_new"),
            ),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("Directory")
                .with_method(MethodDef::static_method(
                    "Exists",
                    1,
                    MethodBody::Common("filesystem.is_dir".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "CreateDirectory",
                    1,
                    MethodBody::Common("filesystem.mkdir".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "Delete",
                    1,
                    MethodBody::Common("filesystem.remove".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "Move",
                    2,
                    MethodBody::Common("filesystem.rename".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFiles",
                    1,
                    MethodBody::Common("dotnet.directory_get_files".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFiles",
                    2,
                    MethodBody::Common("dotnet.directory_get_files".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetDirectories",
                    1,
                    MethodBody::Common("dotnet.directory_get_directories".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetCurrentDirectory",
                    0,
                    MethodBody::HostCall(HostTarget::new("node:process", "cwd")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("Path")
                // ⚠The last `node:path` reference on the `Path` class, kept
                // only because `PropertyDef::getter` accepts a `HostTarget`
                // and nothing else — there is no `Common` getter, and widening
                // that enum in `vybe_runtime::component_model` to move one
                // constant character is not a trade worth making. Every METHOD
                // below is now on `primitives::paths`.
                .with_property(
                    PropertyDef::new("DirectorySeparatorChar")
                        .with_getter(HostTarget::new("node:path", "sep")),
                )
                .with_method(MethodDef::static_method(
                    "Combine",
                    2,
                    MethodBody::Common("dotnet.path_combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Combine",
                    3,
                    MethodBody::Common("dotnet.path_combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Combine",
                    4,
                    MethodBody::Common("dotnet.path_combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Join",
                    2,
                    MethodBody::Common("dotnet.path_combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Join",
                    3,
                    MethodBody::Common("dotnet.path_combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Join",
                    4,
                    MethodBody::Common("dotnet.path_combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFileName",
                    1,
                    MethodBody::Common("dotnet.path_get_file_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetExtension",
                    1,
                    MethodBody::Common("path.extension".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetDirectoryName",
                    1,
                    MethodBody::Common("dotnet.path_get_directory_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFileNameWithoutExtension",
                    1,
                    MethodBody::Common("dotnet.path_get_file_name_without_extension".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ChangeExtension",
                    2,
                    MethodBody::Common("dotnet.path_change_extension".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFullPath",
                    1,
                    MethodBody::Common("dotnet.path_get_full_path".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetPathRoot",
                    1,
                    MethodBody::Common("dotnet.path_get_path_root".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTempPath",
                    0,
                    MethodBody::Common("path.temp_path".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTempFileName",
                    0,
                    MethodBody::Common("dotnet.path_get_temp_file_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetRandomFileName",
                    0,
                    MethodBody::Common("dotnet.path_get_random_file_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetInvalidFileNameChars",
                    0,
                    MethodBody::Common("dotnet.path_get_invalid_file_name_chars".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetInvalidPathChars",
                    0,
                    MethodBody::Common("dotnet.path_get_invalid_path_chars".into()),
                ))
                .with_method(MethodDef::static_method(
                    "HasExtension",
                    1,
                    MethodBody::Common("dotnet.path_has_extension".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsPathRooted",
                    1,
                    MethodBody::Common("dotnet.path_is_path_rooted".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetRelativePath",
                    2,
                    MethodBody::Common("dotnet.path_get_relative_path".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TrimEndingDirectorySeparator",
                    1,
                    MethodBody::Common("dotnet.path_trim_ending_directory_separator".into()),
                )),
        ),
    ]
}
