use super::super::super::class_exports::DotnetClassExport;
use vybe_runtime::component_model::{ClassType, ConstructorDef, MethodBody, MethodDef};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Uri")
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.uri_new"))
                .with_constructor(ConstructorDef::new(2).with_common_backing("dotnet.uri_new"))
                .with_method(MethodDef::static_method(
                    "EscapeDataString",
                    1,
                    MethodBody::Common("dotnet.uri_escape_data_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "UnescapeDataString",
                    1,
                    MethodBody::Common("dotnet.uri_unescape_data_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsWellFormedUriString",
                    2,
                    MethodBody::Common("dotnet.uri_is_well_formed".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TryCreate",
                    2,
                    MethodBody::Common("dotnet.uri_try_create".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TryCreate",
                    3,
                    MethodBody::Common("dotnet.uri_try_create".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsBaseOf",
                    2,
                    MethodBody::Common("dotnet.uri_is_base_of".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MakeRelativeUri",
                    2,
                    MethodBody::Common("dotnet.uri_make_relative".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.uri_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "IsBaseOf",
                    1,
                    MethodBody::Common("dotnet.uri_is_base_of".into()),
                ))
                .with_method(MethodDef::new(
                    "MakeRelativeUri",
                    1,
                    MethodBody::Common("dotnet.uri_make_relative".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("UriKind")
                .with_method(MethodDef::static_method(
                    "RelativeOrAbsolute",
                    0,
                    MethodBody::Common("dotnet.uri_kind_relative_or_absolute".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Absolute",
                    0,
                    MethodBody::Common("dotnet.uri_kind_absolute".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Relative",
                    0,
                    MethodBody::Common("dotnet.uri_kind_relative".into()),
                )),
        ),
        DotnetClassExport::new("dotnet.System", ClassType::new("UriHostNameType")),
    ]
}
