use super::super::super::class_exports::DotnetClassExport;
use super::component_classes_common::constructor_class;
use vybe_runtime::component_model::{ClassType, ConstructorDef, MethodBody, MethodDef};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.Data",
            ClassType::new("DataTable")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.datatable_new"),
                )
                .with_method(MethodDef::new(
                    "NewRow",
                    0,
                    MethodBody::Common("dotnet.datatable_new_row".into()),
                ))
                .with_method(MethodDef::new(
                    "AddRow",
                    1,
                    MethodBody::Common("dotnet.datatable_add_row".into()),
                ))
                .with_method(MethodDef::new(
                    "Select",
                    1,
                    MethodBody::Common("dotnet.datatable_select".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data",
            ClassType::new("DataSet")
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.dataset_new"))
                .with_method(MethodDef::new(
                    "Tables",
                    0,
                    MethodBody::Common("dotnet.dataset_tables".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data",
            ClassType::new("DataRow")
                .with_constructor(ConstructorDef::new(0).with_common_backing("dotnet.datarow_new"))
                .with_method(MethodDef::new(
                    "Item",
                    1,
                    MethodBody::Common("dotnet.datarow_item".into()),
                ))
                .with_method(MethodDef::new(
                    "IsNull",
                    1,
                    MethodBody::Common("dotnet.datarow_is_null".into()),
                )),
        ),
        // The cursor a data form navigates with. Registered under its real .NET
        // namespace so `New System.Windows.Forms.BindingSource()` and the bare
        // `New BindingSource()` resolve exactly as before — what changed is
        // WHAT it is: a data object with real fields, not a `vybe:gui` control
        // whose properties were keyed by a control name it never had.
        //
        // `Position`, `DataSource`, `DataMember`, `Filter` and `Sort` are plain
        // struct fields the constructor initializes; only the members that must
        // be COMPUTED from the source (`Count`, `Current`) get accessors, and
        // they register in `tree_register::shared_emit_accessors`.
        //
        // `EndEdit`/`CancelCurrentEdit` are declared no-ops, and truthfully so:
        // there is no pending-edit buffer in this model — a bound control writes
        // through on change — so there is nothing for either verb to commit or
        // discard. `ResetBindings` is the same: `sync_bound_controls` re-reads
        // the source on its own pass.
        DotnetClassExport::new(
            "dotnet.System.Windows.Forms",
            ClassType::new("BindingSource")
                .with_parent("Component")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.bindingsource_new"),
                )
                .with_method(MethodDef::new(
                    "MoveFirst",
                    0,
                    MethodBody::Common("dotnet.bindingsource_move_first".into()),
                ))
                .with_method(MethodDef::new(
                    "MoveNext",
                    0,
                    MethodBody::Common("dotnet.bindingsource_move_next".into()),
                ))
                .with_method(MethodDef::new(
                    "MovePrevious",
                    0,
                    MethodBody::Common("dotnet.bindingsource_move_previous".into()),
                ))
                .with_method(MethodDef::new(
                    "MoveLast",
                    0,
                    MethodBody::Common("dotnet.bindingsource_move_last".into()),
                ))
                .with_method(MethodDef::new(
                    "EndEdit",
                    0,
                    MethodBody::Common("dotnet.winforms_noop".into()),
                ))
                .with_method(MethodDef::new(
                    "CancelCurrentEdit",
                    0,
                    MethodBody::Common("dotnet.winforms_noop".into()),
                ))
                .with_method(MethodDef::new(
                    "ResetBindings",
                    0,
                    MethodBody::Common("dotnet.winforms_noop".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data",
            ClassType::new("DataAdapter")
                .with_constructor(
                    ConstructorDef::new(0)
                        .with_common_backing("dotnet.sql_data_adapter_new"),
                )
                .with_method(MethodDef::new(
                    "Fill",
                    1,
                    MethodBody::Common("dotnet.sql_adapter_fill".into()),
                )),
        ),
        constructor_class("dotnet.System.Drawing", "Point", "vybe:gui", "pointNew"),
        constructor_class("dotnet.System.Drawing", "Size", "vybe:gui", "sizeNew"),
        constructor_class("dotnet.System.Drawing", "SizeF", "vybe:gui", "sizeNew"),
        constructor_class("dotnet.System.Drawing", "Font", "vybe:gui", "fontNew"),
        constructor_class("dotnet.System.Drawing", "Pen", "vybe:gui", "penNew"),
        constructor_class(
            "dotnet.System.Drawing",
            "SolidBrush",
            "vybe:gui",
            "solidBrushNew",
        ),
        constructor_class(
            "dotnet.System.Drawing",
            "HatchBrush",
            "vybe:gui",
            "hatchBrushNew",
        ),
        constructor_class(
            "dotnet.System.Drawing",
            "LinearGradientBrush",
            "vybe:gui",
            "linearGradientBrushNew",
        ),
        constructor_class(
            "dotnet.System.Drawing",
            "Color",
            "vybe:gui",
            "colorFromName",
        ),
        // No `Graphics` entry here: `winforms::component_classes` already
        // declares `dotnet.System.Drawing::Graphics` from the `DotnetClass`
        // table, WITH every drawing method and with `graphicsNew` as its
        // constructor backing, so a second `constructor_class` declaration of
        // the same name in the same namespace is redundant.
        DotnetClassExport::new(
            "dotnet.System.Data.SqlClient",
            ClassType::new("SqlConnection")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_common_backing("dotnet.sql_connection_new"),
                )
                .with_method(MethodDef::new(
                    "Open",
                    0,
                    MethodBody::Common("dotnet.sql_connection_open".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.sql_connection_close".into()),
                ))
                .with_method(MethodDef::new(
                    "CreateCommand",
                    0,
                    MethodBody::Common("dotnet.sql_connection_create_command".into()),
                ))
                .with_method(MethodDef::new(
                    "BeginTransaction",
                    0,
                    MethodBody::Common("dotnet.sql_connection_begin_transaction".into()),
                ))
                .with_method(MethodDef::new(
                    "GetSchema",
                    1,
                    MethodBody::Common("dotnet.sql_connection_get_schema".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.SqlClient",
            ClassType::new("SqlCommand")
                .with_constructor(
                    ConstructorDef::new(2)
                        .with_common_backing("dotnet.sql_command_new"),
                )
                .with_method(MethodDef::new(
                    "ExecuteNonQuery",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_non_query".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteScalar",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_scalar".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteReader",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_reader".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteNonQueryAsync",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_non_query".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteScalarAsync",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_scalar".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteReaderAsync",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_reader".into()),
                ))
                .with_method(MethodDef::new(
                    "CreateParameter",
                    5,
                    MethodBody::Common("dotnet.sql_command_create_parameter".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.SqlClient",
            ClassType::new("SqlDataAdapter")
                .with_constructor(
                    ConstructorDef::new(2)
                        .with_common_backing("dotnet.sql_data_adapter_new"),
                )
                .with_method(MethodDef::new(
                    "Fill",
                    1,
                    MethodBody::Common("dotnet.sql_adapter_fill".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.SqlClient",
            ClassType::new("SqlDataReader")
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.sql_reader_read".into()),
                ))
                .with_method(MethodDef::new(
                    "GetString",
                    1,
                    MethodBody::Common("dotnet.sql_reader_get_string".into()),
                ))
                .with_method(MethodDef::new(
                    "GetValue",
                    1,
                    MethodBody::Common("dotnet.sql_reader_get_value".into()),
                ))
                .with_method(MethodDef::new(
                    "GetName",
                    1,
                    MethodBody::Common("dotnet.sql_reader_get_name".into()),
                ))
                .with_method(MethodDef::new(
                    "IsDBNull",
                    1,
                    MethodBody::Common("dotnet.sql_reader_is_dbnull".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.sql_reader_close".into()),
                ))
                .with_method(MethodDef::new(
                    "GetSchemaTable",
                    0,
                    MethodBody::Common("dotnet.sql_reader_get_schema_table".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.SqlClient",
            ClassType::new("SqlTransaction")
                .with_method(MethodDef::new(
                    "Commit",
                    0,
                    MethodBody::Common("dotnet.sql_transaction_commit".into()),
                ))
                .with_method(MethodDef::new(
                    "Rollback",
                    0,
                    MethodBody::Common("dotnet.sql_transaction_rollback".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.OleDb",
            ClassType::new("OleDbConnection")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.oledb_connection_new"),
                )
                .with_method(MethodDef::new(
                    "Open",
                    0,
                    MethodBody::Common("dotnet.sql_connection_open".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.sql_connection_close".into()),
                ))
                .with_method(MethodDef::new(
                    "CreateCommand",
                    0,
                    MethodBody::Common("dotnet.sql_connection_create_command".into()),
                ))
                .with_method(MethodDef::new(
                    "BeginTransaction",
                    0,
                    MethodBody::Common("dotnet.sql_connection_begin_transaction".into()),
                ))
                .with_method(MethodDef::new(
                    "GetSchema",
                    1,
                    MethodBody::Common("dotnet.sql_connection_get_schema".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.OleDb",
            ClassType::new("OleDbCommand")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.oledb_command_new"),
                )
                .with_method(MethodDef::new(
                    "ExecuteNonQuery",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_non_query".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteScalar",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_scalar".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteReader",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_reader".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteNonQueryAsync",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_non_query".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteScalarAsync",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_scalar".into()),
                ))
                .with_method(MethodDef::new(
                    "ExecuteReaderAsync",
                    0,
                    MethodBody::Common("dotnet.sql_command_execute_reader".into()),
                ))
                .with_method(MethodDef::new(
                    "CreateParameter",
                    5,
                    MethodBody::Common("dotnet.sql_command_create_parameter".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.OleDb",
            ClassType::new("OleDbDataReader")
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.sql_reader_read".into()),
                ))
                .with_method(MethodDef::new(
                    "GetString",
                    1,
                    MethodBody::Common("dotnet.sql_reader_get_string".into()),
                ))
                .with_method(MethodDef::new(
                    "GetValue",
                    1,
                    MethodBody::Common("dotnet.sql_reader_get_value".into()),
                ))
                .with_method(MethodDef::new(
                    "GetName",
                    1,
                    MethodBody::Common("dotnet.sql_reader_get_name".into()),
                ))
                .with_method(MethodDef::new(
                    "IsDBNull",
                    1,
                    MethodBody::Common("dotnet.sql_reader_is_dbnull".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.sql_reader_close".into()),
                ))
                .with_method(MethodDef::new(
                    "GetSchemaTable",
                    0,
                    MethodBody::Common("dotnet.sql_reader_get_schema_table".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.OleDb",
            ClassType::new("OleDbDataAdapter")
                .with_constructor(
                    ConstructorDef::new(2)
                        .with_common_backing("dotnet.sql_data_adapter_new"),
                )
                .with_method(MethodDef::new(
                    "Fill",
                    1,
                    MethodBody::Common("dotnet.sql_adapter_fill".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Data.OleDb",
            ClassType::new("OleDbTransaction")
                .with_method(MethodDef::new(
                    "Commit",
                    0,
                    MethodBody::Common("dotnet.sql_transaction_commit".into()),
                ))
                .with_method(MethodDef::new(
                    "Rollback",
                    0,
                    MethodBody::Common("dotnet.sql_transaction_rollback".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.ADODB",
            ClassType::new("Connection")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.adodb_connection_new"),
                )
                .with_method(MethodDef::new(
                    "Open",
                    0,
                    MethodBody::Common("dotnet.sql_connection_open".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.sql_connection_close".into()),
                ))
                .with_method(MethodDef::new(
                    "Execute",
                    1,
                    MethodBody::Common("dotnet.adodb_connection_execute".into()),
                ))
                .with_method(MethodDef::new(
                    "BeginTrans",
                    0,
                    MethodBody::Common("dotnet.adodb_conn_begin_trans".into()),
                ))
                .with_method(MethodDef::new(
                    "CommitTrans",
                    0,
                    MethodBody::Common("dotnet.adodb_conn_commit_trans".into()),
                ))
                .with_method(MethodDef::new(
                    "RollbackTrans",
                    0,
                    MethodBody::Common("dotnet.adodb_conn_rollback_trans".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.ADODB",
            ClassType::new("Command")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.adodb_command_new"),
                )
                .with_method(MethodDef::new(
                    "Execute",
                    0,
                    MethodBody::Common("dotnet.adodb_command_execute".into()),
                ))
                .with_method(MethodDef::new(
                    "CreateParameter",
                    5,
                    MethodBody::Common("dotnet.adodb_command_create_parameter".into()),
                )),
        ),
        // The parameter collection every command already carries.
        //
        // `wasi:sql` has had `params.add-with-value`, `params.clear` and
        // `params.count` all along, and `make_command_obj` puts a params object
        // on every command it creates — but nothing DECLARED the collection, so
        // `cmd.Parameters.AddWithValue("@name", "Dave")` resolved against
        // nothing. The parameters never reached the query and the host answered
        // "Wrong number of parameters passed to query. Got 0, needed 2".
        DotnetClassExport::new(
            "dotnet.System.Data.SqlClient",
            ClassType::new("SqlParameterCollection")
                .with_method(MethodDef::new(
                    "AddWithValue",
                    2,
                    MethodBody::Common("dotnet.sql_params_add_with_value".into()),
                ))
                .with_method(MethodDef::new(
                    "Add",
                    2,
                    MethodBody::Common("dotnet.sql_params_add_with_value".into()),
                ))
                .with_method(MethodDef::new(
                    "Clear",
                    0,
                    MethodBody::Common("dotnet.sql_params_clear".into()),
                ))
                .with_method(MethodDef::new(
                    "Count",
                    0,
                    MethodBody::Common("dotnet.sql_params_count".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.ADODB",
            ClassType::new("Recordset")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.adodb_recordset_new"),
                )
                .with_method(MethodDef::new(
                    "Open",
                    2,
                    MethodBody::Common("dotnet.adodb_recordset_open".into()),
                ))
                .with_method(MethodDef::new(
                    "MoveNext",
                    0,
                    MethodBody::Common("dotnet.adodb_recordset_move_next".into()),
                ))
                .with_method(MethodDef::new(
                    "MoveFirst",
                    0,
                    MethodBody::Common("dotnet.adodb_recordset_move_first".into()),
                ))
                .with_method(MethodDef::new(
                    "Fields",
                    1,
                    MethodBody::Common("dotnet.adodb_recordset_fields".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.adodb_recordset_close".into()),
                )),
        ),
    ]
}
