use super::super::super::class_exports::DotnetClassExport;
use vybe_runtime::component_model::{ClassType, ConstructorDef, HostTarget, MethodBody, MethodDef};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.Xml.Linq",
            ClassType::new("XElement")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.xml_xelement_new"),
                )
                .with_constructor(
                    ConstructorDef::new(2).with_common_backing("dotnet.xml_xelement_new"),
                )
                .with_method(MethodDef::new(
                    "Name",
                    0,
                    MethodBody::Common("dotnet.xml_xelement_name".into()),
                ))
                .with_method(MethodDef::new(
                    "Value",
                    0,
                    MethodBody::Common("dotnet.xml_value".into()),
                ))
                .with_method(MethodDef::new(
                    "Element",
                    1,
                    MethodBody::Common("dotnet.xml_element".into()),
                ))
                .with_method(MethodDef::new(
                    "Elements",
                    0,
                    MethodBody::Common("dotnet.xml_child_elements".into()),
                ))
                .with_method(MethodDef::new(
                    "Elements",
                    1,
                    MethodBody::Common("dotnet.xml_elements".into()),
                ))
                .with_method(MethodDef::new(
                    "Attribute",
                    1,
                    MethodBody::Common("dotnet.xml_attribute".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.xml_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "Add",
                    1,
                    MethodBody::Common("dotnet.xml_xelement_add".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    0,
                    MethodBody::Common("dotnet.xml_xelement_remove".into()),
                ))
                .with_method(MethodDef::new(
                    "ReplaceNodes",
                    1,
                    MethodBody::Common("dotnet.xml_xelement_replace_nodes".into()),
                ))
                .with_method(MethodDef::new(
                    "SetAttributeValue",
                    2,
                    MethodBody::Common("dotnet.xml_xelement_set_attribute_value".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Xml.Linq",
            ClassType::new("XDocument")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.xml_xdocument_new"),
                )
                .with_method(MethodDef::static_method(
                    "Parse",
                    1,
                    MethodBody::Common("dotnet.xml_xdocument_parse".into()),
                ))
                .with_method(MethodDef::new(
                    "Root",
                    0,
                    MethodBody::Common("dotnet.xml_xdocument_root".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Xml.Linq",
            ClassType::new("XAttribute")
                .with_constructor(
                    ConstructorDef::new(2).with_common_backing("dotnet.xml_xattribute_new"),
                )
                .with_method(MethodDef::new(
                    "Value",
                    0,
                    MethodBody::Common("dotnet.xml_attribute_value".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.xml_attribute_value".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Xml",
            ClassType::new("XmlDocument")
                .with_constructor(
                    ConstructorDef::new(1).with_backing(HostTarget::new("web:dom-parser", "parse")),
                )
                .with_method(MethodDef::new(
                    "Load",
                    1,
                    MethodBody::HostCall(HostTarget::new("web:dom-parser", "load")),
                ))
                .with_method(MethodDef::new(
                    "Save",
                    0,
                    MethodBody::HostCall(HostTarget::new("web:dom-parser", "toString")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Xml.Linq",
            ClassType::new("XName")
                .with_method(MethodDef::new(
                    "LocalName",
                    0,
                    MethodBody::Common("xml.local".into()),
                ))
                .with_method(MethodDef::new(
                    "NamespaceName",
                    0,
                    MethodBody::Common("xml.namespace".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("xml.qualified".into()),
                )),
        ),
    ]
}
