use super::super::super::class_exports::DotnetClassExport;
use vybe_bytecode::component_model::{ClassType, ConstructorDef, MethodBody, MethodDef};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("StringBuilder")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.string_builder_new"),
                )
                .with_method(MethodDef::new(
                    "Append",
                    1,
                    MethodBody::Common("dotnet.sb_append".into()),
                ))
                .with_method(MethodDef::new(
                    "Append",
                    2,
                    MethodBody::Common("dotnet.sb_append".into()),
                ))
                .with_method(MethodDef::new(
                    "Append",
                    3,
                    MethodBody::Common("dotnet.sb_append".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendLine",
                    0,
                    MethodBody::Common("dotnet.sb_append_line".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendLine",
                    1,
                    MethodBody::Common("dotnet.sb_append_line".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendFormat",
                    2,
                    MethodBody::Common("dotnet.sb_append_format".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendFormat",
                    3,
                    MethodBody::Common("dotnet.sb_append_format".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendFormat",
                    4,
                    MethodBody::Common("dotnet.sb_append_format".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendJoin",
                    2,
                    MethodBody::Common("dotnet.sb_append_join".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.sb_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    2,
                    MethodBody::Common("dotnet.sb_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "Clear",
                    0,
                    MethodBody::Common("dotnet.sb_clear".into()),
                ))
                .with_method(MethodDef::new(
                    "Chars",
                    1,
                    MethodBody::Common("dotnet.sb_index_get".into()),
                ))
                .with_method(MethodDef::new(
                    "EnsureCapacity",
                    1,
                    MethodBody::Common("dotnet.sb_ensure_capacity".into()),
                ))
                .with_method(MethodDef::new(
                    "CopyTo",
                    4,
                    MethodBody::Common("dotnet.sb_copy_to".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.sb_equals".into()),
                ))
                .with_method(MethodDef::new(
                    "Insert",
                    2,
                    MethodBody::Common("dotnet.sb_insert".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    2,
                    MethodBody::Common("dotnet.sb_remove".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    2,
                    MethodBody::Common("dotnet.sb_replace".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    4,
                    MethodBody::Common("dotnet.sb_replace".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.RegularExpressions",
            ClassType::new("Regex")
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.regex_new"))
                .with_constructor(ConstructorDef::new(2).with_common_backing("dotnet.regex_new"))
                .with_constructor(ConstructorDef::new(3).with_common_backing("dotnet.regex_new"))
                .with_method(MethodDef::static_method(
                    "IsMatch",
                    2,
                    MethodBody::Common("dotnet.regex_static_is_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsMatch",
                    3,
                    MethodBody::Common("dotnet.regex_static_is_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsMatch",
                    4,
                    MethodBody::Common("dotnet.regex_static_is_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Match",
                    2,
                    MethodBody::Common("dotnet.regex_static_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Match",
                    3,
                    MethodBody::Common("dotnet.regex_static_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Matches",
                    2,
                    MethodBody::Common("dotnet.regex_static_matches".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Matches",
                    3,
                    MethodBody::Common("dotnet.regex_static_matches".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Replace",
                    3,
                    MethodBody::Common("dotnet.regex_static_replace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Replace",
                    4,
                    MethodBody::Common("dotnet.regex_static_replace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Replace",
                    5,
                    MethodBody::Common("dotnet.regex_static_replace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Split",
                    2,
                    MethodBody::Common("dotnet.regex_static_split".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Split",
                    3,
                    MethodBody::Common("dotnet.regex_static_split".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Escape",
                    1,
                    MethodBody::Common("dotnet.regex_escape".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Unescape",
                    1,
                    MethodBody::Common("dotnet.regex_unescape".into()),
                ))
                .with_method(MethodDef::new(
                    "IsMatch",
                    1,
                    MethodBody::Common("dotnet.regex_is_match".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    2,
                    MethodBody::Common("dotnet.regex_replace".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    1,
                    MethodBody::Common("dotnet.regex_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Match",
                    1,
                    MethodBody::Common("dotnet.regex_match".into()),
                ))
                .with_method(MethodDef::new(
                    "Matches",
                    1,
                    MethodBody::Common("dotnet.regex_matches".into()),
                ))
                .with_method(MethodDef::new(
                    "GetGroupNames",
                    0,
                    MethodBody::Common("dotnet.regex_get_group_names".into()),
                ))
                .with_method(MethodDef::new(
                    "GroupNameFromNumber",
                    1,
                    MethodBody::Common("dotnet.regex_group_name_from_number".into()),
                ))
                .with_method(MethodDef::new(
                    "GroupNumberFromName",
                    1,
                    MethodBody::Common("dotnet.regex_group_number_from_name".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.Json",
            ClassType::new("JsonSerializer")
                .with_method(MethodDef::static_method(
                    "Serialize",
                    1,
                    MethodBody::Common("dotnet.json_serialize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Deserialize",
                    1,
                    MethodBody::Common("dotnet.json_deserialize".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("Encoding")
                .with_method(MethodDef::static_method(
                    "UTF8",
                    0,
                    MethodBody::Common("dotnet.encoding_utf8".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ASCII",
                    0,
                    MethodBody::Common("dotnet.encoding_ascii".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Unicode",
                    0,
                    MethodBody::Common("dotnet.encoding_unicode".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Default",
                    0,
                    MethodBody::Common("dotnet.encoding_utf8".into()),
                ))
                .with_method(MethodDef::static_method(
                    "UTF32",
                    0,
                    MethodBody::Common("dotnet.encoding_utf32".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Latin1",
                    0,
                    MethodBody::Common("dotnet.encoding_latin1".into()),
                ))
                .with_method(MethodDef::static_method(
                    "BigEndianUnicode",
                    0,
                    MethodBody::Common("dotnet.encoding_big_endian_unicode".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEncoding",
                    1,
                    MethodBody::Common("dotnet.encoding_get_encoding".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEncoding",
                    3,
                    MethodBody::Common("dotnet.encoding_get_encoding".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Convert",
                    3,
                    MethodBody::Common("dotnet.encoding_convert".into()),
                ))
                .with_method(MethodDef::new(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.encoding_get_bytes".into()),
                ))
                .with_method(MethodDef::new(
                    "GetString",
                    1,
                    MethodBody::Common("dotnet.encoding_get_string".into()),
                ))
                .with_method(MethodDef::new(
                    "GetByteCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_byte_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetCharCount",
                    3,
                    MethodBody::Common("dotnet.encoding_get_char_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetChars",
                    5,
                    MethodBody::Common("dotnet.encoding_get_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "GetPreamble",
                    0,
                    MethodBody::Common("dotnet.encoding_get_preamble".into()),
                ))
                .with_method(MethodDef::new(
                    "GetMaxByteCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_max_byte_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetMaxCharCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_max_char_count".into()),
                ))
                .with_method(MethodDef::new(
                    "Clone",
                    0,
                    MethodBody::Common("dotnet.identity".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.encoding_equals".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("UTF8Encoding")
                .with_parent("Encoding")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.utf8encoding_new"),
                )
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.utf8encoding_new"),
                )
                .with_method(MethodDef::new(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.encoding_get_bytes".into()),
                ))
                .with_method(MethodDef::new(
                    "GetString",
                    1,
                    MethodBody::Common("dotnet.encoding_get_string".into()),
                ))
                .with_method(MethodDef::new(
                    "GetByteCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_byte_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetPreamble",
                    0,
                    MethodBody::Common("dotnet.encoding_get_preamble".into()),
                )),
        ),
    ]
}
