use super::super::super::class_exports::DotnetClassExport;
use super::super::super::classes::DotnetClass;
use super::super::exceptions::EXCEPTION_HIERARCHY;
use vybe_runtime::component_model::{
    ClassType, ConstructorDef, HostTarget, MethodBody, MethodDef, PropertyDef,
};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    let mut exports = vec![
        DotnetClassExport::with_wrapper(
            "dotnet.System",
            ClassType::new("ValueType").with_parent("Object"),
            DotnetClass {
                name: "ValueType",
                parent: Some("Object"),
                properties: &[],
                methods: &[],
                ctor_arity: 0,
                widget_host_fn: None,            },
        ),
        DotnetClassExport::with_wrapper(
            "dotnet.System",
            ClassType::new("Enum")
                .with_parent("ValueType")
                .with_method(MethodDef::static_method(
                    "IsDefined",
                    2,
                    MethodBody::Common("dotnet.enum_is_defined".into()),
                )),
            DotnetClass {
                name: "Enum",
                parent: Some("ValueType"),
                properties: &[],
                methods: &[],
                ctor_arity: 0,
                widget_host_fn: None,            },
        ),
    ];
    exports.extend(EXCEPTION_HIERARCHY.iter().map(|(name, parent)| {
        let class = if parent.is_empty() {
            ClassType::new(*name)
        } else {
            ClassType::new(*name).with_parent(*parent)
        };
        DotnetClassExport::new("dotnet.System", class)
    }));
    exports.extend(vec![
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Object")
                // ⛔ `New Object()` HAD NO CONSTRUCTOR. The root of the type
                // hierarchy carried three static methods and nothing to
                // allocate with, so `Dim o As New Object()` — the first line of
                // most `GCHandle` tests — answered
                // `undefined is not callable`.
                .with_constructor(ConstructorDef::new(0).with_common_backing("dotnet.object_new"))
                .with_method(MethodDef::static_method(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.object_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ReferenceEquals",
                    2,
                    MethodBody::Common("dotnet.object_reference_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.object_to_string_role".into()),
                )),
        ),
        // ⛔ `GCMemoryInfo` IS A REGISTERED TYPE, not a bag of stamped keys.
        // Its members are argc-0 leaves — the shape every other .NET property
        // on the tree already uses — so a read folds by the TYPE's rules and
        // VB's `info.heapcount` and C#'s `info.HeapCount` are one member.
        //
        // ⚠ `HeapCount` DOES NOT EXIST on .NET 10's `GCMemoryInfo` (`CS1061`,
        // measured on the SDK). It is carried because a corpus test reads it,
        // and 1 is at least true of a single-heap runtime; the test is the
        // thing that is wrong.
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("GCMemoryInfo")
                .with_method(MethodDef::new(
                    "HeapCount",
                    0,
                    MethodBody::Common("dotnet.gcinfo_heap_count".into()),
                ))
                .with_method(MethodDef::new(
                    "PauseTimePercentage",
                    0,
                    MethodBody::Common("dotnet.gcinfo_zero".into()),
                ))
                .with_method(MethodDef::new(
                    "TotalPauseDuration",
                    0,
                    MethodBody::Common("dotnet.gcinfo_zero".into()),
                ))
                .with_method(MethodDef::new(
                    "Index",
                    0,
                    MethodBody::Common("dotnet.gcinfo_zero".into()),
                ))
                .with_method(MethodDef::new(
                    "Generation",
                    0,
                    MethodBody::Common("dotnet.gcinfo_zero".into()),
                ))
                .with_method(MethodDef::new(
                    "FragmentedBytes",
                    0,
                    MethodBody::Common("dotnet.gcinfo_zero".into()),
                ))
                .with_method(MethodDef::new(
                    "HeapSizeBytes",
                    0,
                    MethodBody::Common("dotnet.gcinfo_zero".into()),
                ))
                .with_method(MethodDef::new(
                    "TotalAvailableMemoryBytes",
                    0,
                    MethodBody::Common("dotnet.gcinfo_available_bytes".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("BitConverter")
                .with_method(MethodDef::static_method(
                    "IsLittleEndian",
                    0,
                    MethodBody::Common("dotnet.bitconverter_is_little_endian".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.bitconverter_get_bytes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt32",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_number".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt64",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_number".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToDouble",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_number".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBoolean",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_boolean".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToChar",
                    2,
                    MethodBody::Common("dotnet.bitconverter_to_char".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.bitconverter_to_string".into()),
                ))
                // The bit-cast family — moved out of the VB walker, which was
                // rewriting these to `UnaryOp::Reinterpret` itself. The leaves
                // reach the SAME shared emitter, so the concept stays unified
                // and the .NET spelling lives with the rest of System.*.
                .with_method(MethodDef::static_method(
                    "SingleToInt32Bits",
                    1,
                    MethodBody::Common("dotnet.bitconverter_single_to_int32_bits".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Int32BitsToSingle",
                    1,
                    MethodBody::Common("dotnet.bitconverter_int32_bits_to_single".into()),
                ))
                .with_method(MethodDef::static_method(
                    "DoubleToInt64Bits",
                    1,
                    MethodBody::Common("dotnet.bitconverter_double_to_int64_bits".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Int64BitsToDouble",
                    1,
                    MethodBody::Common("dotnet.bitconverter_int64_bits_to_double".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Buffer")
                .with_method(MethodDef::static_method(
                    "BlockCopy",
                    5,
                    MethodBody::Common("dotnet.buffer_block_copy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ByteLength",
                    1,
                    MethodBody::Common("dotnet.buffer_byte_length".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetByte",
                    2,
                    MethodBody::Common("dotnet.buffer_get_byte".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetByte",
                    3,
                    MethodBody::Common("dotnet.buffer_set_byte".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("GC")
                .with_method(MethodDef::static_method(
                    "MaxGeneration",
                    0,
                    MethodBody::Common("dotnet.gc_max_generation".into()),
                ))
                // `AddMemoryPressure`/`RemoveMemoryPressure` have exactly one
                // observable behaviour — rejecting a non-positive argument.
                .with_method(MethodDef::static_method(
                    "AddMemoryPressure",
                    1,
                    MethodBody::Common("dotnet.gc_memory_pressure".into()),
                ))
                .with_method(MethodDef::static_method(
                    "RemoveMemoryPressure",
                    1,
                    MethodBody::Common("dotnet.gc_memory_pressure".into()),
                ))
                .with_method(MethodDef::static_method(
                    "AllocateArray",
                    1,
                    MethodBody::Common("dotnet.gc_allocate_array".into()),
                ))
                .with_method(MethodDef::static_method(
                    "AllocateArray",
                    2,
                    MethodBody::Common("dotnet.gc_allocate_array".into()),
                ))
                .with_method(MethodDef::static_method(
                    "AllocateUninitializedArray",
                    1,
                    MethodBody::Common("dotnet.gc_allocate_array".into()),
                ))
                .with_method(MethodDef::static_method(
                    "AllocateUninitializedArray",
                    2,
                    MethodBody::Common("dotnet.gc_allocate_array".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetGCMemoryInfo",
                    0,
                    MethodBody::Common("dotnet.gc_memory_info".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTotalPauseDuration",
                    0,
                    MethodBody::Common("dotnet.gc_total_pause_duration".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTotalAllocatedBytes",
                    0,
                    MethodBody::Common("dotnet.gc_total_memory".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTotalAllocatedBytes",
                    1,
                    MethodBody::Common("dotnet.gc_total_memory".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetAllocatedBytesForCurrentThread",
                    0,
                    MethodBody::Common("dotnet.gc_total_memory".into()),
                ))
                // Full-GC notification is a REGISTRATION, not a collection: a
                // program registers, then polls. With no background collector
                // there is nothing to notify about, so registering and
                // cancelling both succeed and neither reports.
                .with_method(MethodDef::static_method(
                    "RegisterForFullGCNotification",
                    2,
                    MethodBody::Common("dotnet.gc_noop".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CancelFullGCNotification",
                    0,
                    MethodBody::Common("dotnet.gc_noop".into()),
                ))
                // ⛔ NOT `gc_noop` ANY MORE. These are the collection point:
                // a name dropped under `NameDrop::Defer` made its value
                // eligible, and this is where eligibility becomes a call to the
                // Destructor slot. As no-ops, a VB `Finalize` and a C# `~Foo`
                // compiled correctly and could never run.
                .with_method(MethodDef::static_method(
                    "Collect",
                    0,
                    MethodBody::Common("dotnet.gc_run_finalizers".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Collect",
                    1,
                    MethodBody::Common("dotnet.gc_run_finalizers".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WaitForPendingFinalizers",
                    0,
                    MethodBody::Common("dotnet.gc_run_finalizers".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SuppressFinalize",
                    1,
                    MethodBody::Common("dotnet.gc_suppress_finalize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ReRegisterForFinalize",
                    1,
                    MethodBody::Common("dotnet.gc_re_register_for_finalize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetTotalMemory",
                    1,
                    MethodBody::Common("dotnet.gc_total_memory".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CollectionCount",
                    1,
                    MethodBody::Common("dotnet.gc_collection_count".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetGeneration",
                    1,
                    MethodBody::Common("dotnet.gc_generation".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.RegularExpressions",
            ClassType::new("RegexMatchTimeoutException").with_parent("TimeoutException"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("EncoderFallbackException").with_parent("ArgumentException"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("DecoderFallbackException").with_parent("ArgumentException"),
        ),
        DotnetClassExport::new("dotnet.System", ClassType::new("Attribute")),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("AttributeUsageAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("FlagsAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("STAThreadAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("SerializableAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("ObsoleteAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Reflection",
            ClassType::new("AssemblyTitleAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System.ComponentModel",
            ClassType::new("DescriptionAttribute").with_parent("Attribute"),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("DateTime")
                .with_constructor(ConstructorDef::new(3).with_common_backing("dotnet.datetime_new"))
                .with_constructor(ConstructorDef::new(6).with_common_backing("dotnet.datetime_new"))
                .with_constructor(ConstructorDef::new(7).with_common_backing("dotnet.datetime_new"))
                .with_constructor(ConstructorDef::new(8).with_common_backing("dotnet.datetime_new"))
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.datetime_new"))
                .with_method(MethodDef::static_method(
                    "Now",
                    0,
                    MethodBody::Common("dotnet.datetime_now".into()),
                ))
                .with_method(MethodDef::static_method(
                    "UtcNow",
                    0,
                    MethodBody::Common("dotnet.datetime_now".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Today",
                    0,
                    MethodBody::Common("dotnet.datetime_today".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MinValue",
                    0,
                    MethodBody::Common("dotnet.datetime_min_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MaxValue",
                    0,
                    MethodBody::Common("dotnet.datetime_max_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Parse",
                    1,
                    MethodBody::Common("dotnet.datetime_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Parse",
                    2,
                    MethodBody::Common("dotnet.datetime_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TryParse",
                    1,
                    MethodBody::Common("dotnet.datetime_try_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ParseExact",
                    3,
                    MethodBody::Common("dotnet.datetime_parse_exact".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ParseExact",
                    4,
                    MethodBody::Common("dotnet.datetime_parse_exact".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.datetime_equals_static".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromBinary",
                    1,
                    MethodBody::Common("dotnet.datetime_from_binary".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromFileTimeUtc",
                    1,
                    MethodBody::Common("dotnet.datetime_from_file_time_utc".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromOADate",
                    1,
                    MethodBody::Common("dotnet.datetime_from_oadate".into()),
                ))
                .with_method(MethodDef::static_method(
                    "DaysInMonth",
                    2,
                    MethodBody::Common("dotnet.datetime_days_in_month".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsLeapYear",
                    1,
                    MethodBody::Common("dotnet.datetime_is_leap_year".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    2,
                    MethodBody::Common("dotnet.datetime_compare_static".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SpecifyKind",
                    2,
                    MethodBody::Common("dotnet.datetime_specify_kind".into()),
                ))
                .with_method(MethodDef::new(
                    "AddDays",
                    1,
                    MethodBody::Common("dotnet.datetime_add_days".into()),
                ))
                .with_method(MethodDef::new(
                    "AddHours",
                    1,
                    MethodBody::Common("dotnet.datetime_add_hours".into()),
                ))
                .with_method(MethodDef::new(
                    "AddMonths",
                    1,
                    MethodBody::Common("dotnet.datetime_add_months".into()),
                ))
                .with_method(MethodDef::new(
                    "AddYears",
                    1,
                    MethodBody::Common("dotnet.datetime_add_years".into()),
                ))
                .with_method(MethodDef::new(
                    "Add",
                    1,
                    MethodBody::Common("dotnet.datetime_add_timespan".into()),
                ))
                .with_method(MethodDef::new(
                    "AddTicks",
                    1,
                    MethodBody::Common("dotnet.datetime_add_ticks".into()),
                ))
                .with_method(MethodDef::new(
                    "Subtract",
                    1,
                    MethodBody::Common("dotnet.datetime_subtract_datetime".into()),
                ))
                .with_method(MethodDef::new(
                    "CompareTo",
                    1,
                    MethodBody::Common("dotnet.datetime_compare".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.datetime_equals_instance".into()),
                ))
                .with_method(MethodDef::new(
                    "ToShortDateString",
                    0,
                    MethodBody::Common("dotnet.datetime_to_short_date_string".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.datetime_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.datetime_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    2,
                    MethodBody::Common("dotnet.datetime_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "ToUniversalTime",
                    0,
                    MethodBody::Common("dotnet.datetime_to_universal_time".into()),
                ))
                .with_method(MethodDef::new(
                    "ToLocalTime",
                    0,
                    MethodBody::Common("dotnet.datetime_to_local_time".into()),
                ))
                .with_method(MethodDef::new(
                    "ToBinary",
                    0,
                    MethodBody::Common("dotnet.datetime_to_binary".into()),
                ))
                .with_method(MethodDef::new(
                    "ToFileTimeUtc",
                    0,
                    MethodBody::Common("dotnet.datetime_to_file_time_utc".into()),
                ))
                .with_method(MethodDef::new(
                    "ToOADate",
                    0,
                    MethodBody::Common("dotnet.datetime_to_oadate".into()),
                ))
                .with_method(MethodDef::new(
                    "GetHashCode",
                    0,
                    MethodBody::Common("dotnet.datetime_get_hash_code".into()),
                )),
        ),
        // `System.TimeZoneInfo` — the type was absent from the catalog
        // entirely, so `TimeZoneInfo.Utc.Id` answered `undefined`. Every
        // member is backed by `primitives/datetime.rs`'s tzdb calls; see
        // `core::timezone_adapter`.
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("TimeZoneInfo")
                .with_method(MethodDef::static_method(
                    "Utc",
                    0,
                    MethodBody::Common("dotnet.timezone_utc".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Local",
                    0,
                    MethodBody::Common("dotnet.timezone_local".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindSystemTimeZoneById",
                    1,
                    MethodBody::Common("dotnet.timezone_find_by_id".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConvertTime",
                    2,
                    MethodBody::Common("dotnet.timezone_convert_time".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConvertTimeToUtc",
                    1,
                    MethodBody::Common("dotnet.timezone_convert_to_utc".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConvertTimeFromUtc",
                    2,
                    MethodBody::Common("dotnet.timezone_convert_from_utc".into()),
                ))
                .with_method(MethodDef::new(
                    "GetUtcOffset",
                    1,
                    MethodBody::Common("dotnet.timezone_get_utc_offset".into()),
                ))
                .with_method(MethodDef::new(
                    "IsDaylightSavingTime",
                    1,
                    MethodBody::Common("dotnet.timezone_is_dst".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("DateTimeOffset")
                .with_constructor(
                    ConstructorDef::new(7).with_common_backing("dotnet.datetimeoffset_new"),
                )
                .with_method(MethodDef::static_method(
                    "Now",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_now".into()),
                ))
                .with_method(MethodDef::static_method(
                    "UtcNow",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_utc_now".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MinValue",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_min_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MaxValue",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_max_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Parse",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TryParse",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_try_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromUnixTimeSeconds",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_from_unix_time_seconds".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromUnixTimeMilliseconds",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_from_unix_time_milliseconds".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Subtract",
                    2,
                    MethodBody::Common("dotnet.datetimeoffset_subtract".into()),
                ))
                .with_method(MethodDef::new(
                    "AddHours",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_hours".into()),
                ))
                .with_method(MethodDef::new(
                    "AddDays",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_days".into()),
                ))
                .with_method(MethodDef::new(
                    "AddMinutes",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_minutes".into()),
                ))
                .with_method(MethodDef::new(
                    "AddSeconds",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_seconds".into()),
                ))
                .with_method(MethodDef::new(
                    "AddMilliseconds",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_milliseconds".into()),
                ))
                .with_method(MethodDef::new(
                    "AddTicks",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_ticks".into()),
                ))
                .with_method(MethodDef::new(
                    "Add",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_add_timespan".into()),
                ))
                .with_method(MethodDef::new(
                    "ToUniversalTime",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_to_universal_time".into()),
                ))
                .with_method(MethodDef::new(
                    "ToOffset",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_to_offset".into()),
                ))
                .with_method(MethodDef::new(
                    "ToUnixTimeSeconds",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_to_unix_time_seconds".into()),
                ))
                .with_method(MethodDef::new(
                    "ToUnixTimeMilliseconds",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_to_unix_time_milliseconds".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_equals".into()),
                ))
                .with_method(MethodDef::new(
                    "EqualsExact",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_equals_exact".into()),
                ))
                .with_method(MethodDef::new(
                    "CompareTo",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_compare".into()),
                ))
                .with_method(MethodDef::new(
                    "GetHashCode",
                    0,
                    MethodBody::Common("dotnet.datetimeoffset_get_hash_code".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.datetimeoffset_to_string".into()),
                )),
        ),
        // `Lazy(Of T)` — the type was absent from the catalog entirely, so every
        // member answered "undefined is not callable". `Value` and
        // `IsValueCreated` are computed properties declared in
        // `tree_register::shared_emit_accessors`, not methods.
        // `WeakReference` / `WeakReference(Of T)` — absent from the catalog
        // entirely. `Target` and `IsAlive` are computed properties declared in
        // `tree_register::shared_emit_accessors`, not fields: a field named
        // `Target` would collide with the payload key on a case-insensitive
        // read.
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("WeakReference")
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.weakref_new"))
                .with_constructor(ConstructorDef::new(2).with_common_backing("dotnet.weakref_new"))
                .with_method(MethodDef::new(
                    "SetTarget",
                    1,
                    MethodBody::Common("dotnet.weakref_set_target".into()),
                ))
                // ⛔ ARITY ZERO. The source spells `TryGetTarget(out)` with one
                // argument; the walker desugars that to `wr.TryGetTarget()`
                // plus an assignment, so what reaches the tree is the CORE.
                .with_method(MethodDef::new(
                    "TryGetTarget",
                    0,
                    MethodBody::Common("dotnet.weakref_target".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Lazy")
                .with_constructor(ConstructorDef::new(0).with_common_backing("dotnet.lazy_new"))
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.lazy_new"))
                .with_constructor(ConstructorDef::new(2).with_common_backing("dotnet.lazy_new")),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Random")
                .with_constructor(ConstructorDef::new(0).with_common_backing("dotnet.random_new"))
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.random_new"))
                .with_method(MethodDef::new(
                    "Next",
                    0,
                    MethodBody::Common("dotnet.random_next".into()),
                ))
                .with_method(MethodDef::new(
                    "Next",
                    1,
                    MethodBody::Common("dotnet.random_next".into()),
                ))
                .with_method(MethodDef::new(
                    "Next",
                    2,
                    MethodBody::Common("dotnet.random_next".into()),
                ))
                .with_method(MethodDef::new(
                    "NextDouble",
                    0,
                    MethodBody::Common("dotnet.random_next_double".into()),
                ))
                .with_method(MethodDef::new(
                    "NextBytes",
                    1,
                    MethodBody::Common("dotnet.random_next_bytes".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("TimeSpan")
                // .NET overloads the ctor by arity: (ticks) | (h,m,s) |
                // (d,h,m,s) | (d,h,m,s,ms). Only 3 was registered, and the
                // emitter silently answered Zero for the rest.
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.timespan_new"))
                .with_constructor(ConstructorDef::new(3).with_common_backing("dotnet.timespan_new"))
                .with_constructor(ConstructorDef::new(4).with_common_backing("dotnet.timespan_new"))
                .with_constructor(ConstructorDef::new(5).with_common_backing("dotnet.timespan_new"))
                .with_method(MethodDef::static_method(
                    "FromDays",
                    1,
                    MethodBody::Common("dotnet.timespan_from_days".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromHours",
                    1,
                    MethodBody::Common("dotnet.timespan_from_hours".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromMinutes",
                    1,
                    MethodBody::Common("dotnet.timespan_from_minutes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromSeconds",
                    1,
                    MethodBody::Common("dotnet.timespan_from_seconds".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromMilliseconds",
                    1,
                    MethodBody::Common("dotnet.timespan_from_milliseconds".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Zero",
                    0,
                    MethodBody::Common("dotnet.timespan_zero".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    2,
                    MethodBody::Common("dotnet.timespan_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Add",
                    2,
                    MethodBody::Common("dotnet.timespan_add".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Subtract",
                    2,
                    MethodBody::Common("dotnet.timespan_sub".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Parse",
                    1,
                    MethodBody::Common("dotnet.timespan_parse".into()),
                ))
                .with_method(MethodDef::new(
                    "Negate",
                    0,
                    MethodBody::Common("dotnet.timespan_negate".into()),
                ))
                .with_method(MethodDef::new(
                    "Duration",
                    0,
                    MethodBody::Common("dotnet.timespan_duration".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromTicks",
                    1,
                    MethodBody::Common("dotnet.timespan_from_ticks".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MaxValue",
                    0,
                    MethodBody::Common("dotnet.timespan_max_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MinValue",
                    0,
                    MethodBody::Common("dotnet.timespan_min_value".into()),
                ))
                // Instance halves of the arithmetic surface. Same emitters as
                // the statics: an instance call pushes receiver-then-args, so
                // `a.Add(b)` and `TimeSpan.Add(a, b)` are the same stack.
                .with_method(MethodDef::new(
                    "Add",
                    1,
                    MethodBody::Common("dotnet.timespan_add".into()),
                ))
                .with_method(MethodDef::new(
                    "Subtract",
                    1,
                    MethodBody::Common("dotnet.timespan_sub".into()),
                ))
                .with_method(MethodDef::new(
                    "CompareTo",
                    1,
                    MethodBody::Common("dotnet.timespan_compare".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.timespan_to_string".into()),
                ))
                // The BCL-defined unary negation operator. The walker's
                // operator rewrite turns `-span` into
                // `TimeSpan.op_UnaryNegation(span)` — the same one-arg stack
                // shape as `Negate`, so the same emitter serves both.
                .with_method(MethodDef::static_method(
                    "op_UnaryNegation",
                    1,
                    MethodBody::Common("dotnet.timespan_negate".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Array")
                .with_method(MethodDef::new(
                    "GetValue",
                    1,
                    MethodBody::Common("dotnet.array_get_checked".into()),
                ))
                .with_method(MethodDef::new(
                    "SetValue",
                    2,
                    MethodBody::Common("dotnet.array_set_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetValue",
                    2,
                    MethodBody::Common("dotnet.array_get_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetValue",
                    3,
                    MethodBody::Common("dotnet.array_set_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Clear",
                    3,
                    MethodBody::Common("dotnet.array_clear".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Copy",
                    3,
                    MethodBody::Common("dotnet.array_copy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConstrainedCopy",
                    5,
                    MethodBody::Common("dotnet.array_copy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Resize",
                    2,
                    MethodBody::Common("dotnet.array_resize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sort",
                    1,
                    MethodBody::Common("dotnet.array_sort".into()),
                ))
                // ⛔ NO `Sort` AT ARITY 2 HERE. `Array.Sort` has TWO two-argument
                // overloads and this tree resolves overloads by arity alone, so
                // declaring one silently claims the other: a `Sort/2` bound to
                // `dotnet.array_sort_with_comparer` swallowed
                // `Array.Sort(keys, items)` — the PARALLEL-KEYS form, which
                // sorts `keys` and applies the same permutation to `items` —
                // and it stopped reordering `items` (measured regression).
                // `dotnet.array_sort_with_comparer` exists and is dispatched;
                // it needs a run-time test of whether the second operand is an
                // array or a comparer before it can be declared here.
                .with_method(MethodDef::static_method(
                    "Reverse",
                    1,
                    MethodBody::Common("dotnet.array_reverse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Fill",
                    2,
                    MethodBody::Common("dotnet.array_fill".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IndexOf",
                    2,
                    MethodBody::Common("dotnet.array_index_of".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LastIndexOf",
                    2,
                    MethodBody::Common("dotnet.array_last_index_of".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Empty",
                    0,
                    MethodBody::Common("dotnet.array_empty".into()),
                ))
                .with_method(MethodDef::static_method(
                    // .NET returns the match index, or the bitwise complement of
                    // the insertion point (`~i`, i.e. a negative) when absent —
                    // `indexOf` can't express the miss case, so use the shared
                    // comparison-ordered search.
                    "BinarySearch",
                    2,
                    MethodBody::Common("dotnet.array_binary_search".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConvertAll",
                    2,
                    MethodBody::Common("dotnet.array_convert_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CreateInstance",
                    1,
                    MethodBody::Common("dotnet.array_create_instance".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Exists",
                    2,
                    MethodBody::Common("dotnet.array_exists".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Find",
                    2,
                    MethodBody::Common("dotnet.array_find".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindAll",
                    2,
                    MethodBody::Common("dotnet.array_find_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindIndex",
                    2,
                    MethodBody::Common("dotnet.array_find_index".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindLastIndex",
                    2,
                    MethodBody::Common("dotnet.array_find_last_index".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FindLast",
                    2,
                    MethodBody::Common("dotnet.array_find_last".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ForEach",
                    2,
                    MethodBody::Common("dotnet.array_for_each".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TrueForAll",
                    2,
                    MethodBody::Common("dotnet.array_true_for_all".into()),
                )),
        ),
        // ── System.Math ────────────────────────────────────────────
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Math")
                .with_method(MethodDef::static_method(
                    "Abs",
                    1,
                    MethodBody::Common("dotnet.system.math.abs".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Floor",
                    1,
                    MethodBody::Common("dotnet.system.math.floor".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Ceiling",
                    1,
                    MethodBody::Common("dotnet.system.math.ceiling".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Ceil",
                    1,
                    MethodBody::Common("dotnet.system.math.ceiling".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sqrt",
                    1,
                    MethodBody::Common("dotnet.system.math.sqrt".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Truncate",
                    1,
                    MethodBody::Common("dotnet.system.math.truncate".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Trunc",
                    1,
                    MethodBody::Common("dotnet.system.math.truncate".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Round",
                    1,
                    MethodBody::Common("dotnet.system.math.round".into()),
                ))
                // ⛔ `Round` WAS DECLARED AT ARITY 1 ONLY, and the declared
                // arity is what the unqualified path passes to the emitter.
                // `Math.Round(d, 2)` therefore reached `dotnet.system.math.round`
                // with `argc == 1` while BOTH operands sat on the stack, so it
                // rounded the DIGIT COUNT and answered `2`. The emitter has
                // handled the two- and three-operand forms all along; nothing
                // declared them. `System.Math.Round(d, 2)` was unaffected and
                // passing, which is what made this look like a Complex bug.
                .with_method(MethodDef::static_method(
                    "Round",
                    2,
                    MethodBody::Common("dotnet.system.math.round".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Round",
                    3,
                    MethodBody::Common("dotnet.system.math.round".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Min",
                    2,
                    MethodBody::Common("dotnet.system.math.min".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Max",
                    2,
                    MethodBody::Common("dotnet.system.math.max".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Pow",
                    2,
                    MethodBody::Common("dotnet.system.math.pow".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sin",
                    1,
                    MethodBody::Common("dotnet.system.math.sin".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Cos",
                    1,
                    MethodBody::Common("dotnet.system.math.cos".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Tan",
                    1,
                    MethodBody::Common("dotnet.system.math.tan".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Asin",
                    1,
                    MethodBody::Common("dotnet.system.math.asin".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Acos",
                    1,
                    MethodBody::Common("dotnet.system.math.acos".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Atan",
                    1,
                    MethodBody::Common("dotnet.system.math.atan".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Atan2",
                    2,
                    MethodBody::Common("dotnet.system.math.atan2".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log",
                    1,
                    MethodBody::Common("dotnet.system.math.log".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log",
                    2,
                    MethodBody::Common("dotnet.system.math.log".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log10",
                    1,
                    MethodBody::Common("dotnet.system.math.log10".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Log2",
                    1,
                    MethodBody::Common("dotnet.system.math.log2".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Exp",
                    1,
                    MethodBody::Common("dotnet.system.math.exp".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sinh",
                    1,
                    MethodBody::Common("dotnet.system.math.sinh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Cosh",
                    1,
                    MethodBody::Common("dotnet.system.math.cosh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Tanh",
                    1,
                    MethodBody::Common("dotnet.system.math.tanh".into()),
                ))
                // The INVERSE hyperbolics were missing while their forward
                // forms were registered, so `[math]::Acosh` reached
                // `undefined is not callable` in every .NET-shaped frontend.
                .with_method(MethodDef::static_method(
                    "Asinh",
                    1,
                    MethodBody::Common("dotnet.system.math.asinh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Acosh",
                    1,
                    MethodBody::Common("dotnet.system.math.acosh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Atanh",
                    1,
                    MethodBody::Common("dotnet.system.math.atanh".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sign",
                    1,
                    MethodBody::Common("dotnet.system.math.sign".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Clamp",
                    3,
                    MethodBody::Common("dotnet.system.math.clamp".into()),
                ))
                // `Math.DivRem(a, b)` — .NET 7's TUPLE overload. The older
                // `DivRem(a, b, out r)` reaches the same leaf: the walkers
                // desugar the out-param and call this with two arguments.
                .with_method(MethodDef::static_method(
                    "DivRem",
                    2,
                    MethodBody::Common("dotnet.system.math.div_rem".into()),
                ))
                .with_method(MethodDef::static_method(
                    "BigMul",
                    2,
                    MethodBody::Common("dotnet.system.math.big_mul".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Cbrt",
                    1,
                    MethodBody::Common("dotnet.system.math.cbrt".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Hypot",
                    2,
                    MethodBody::Common("dotnet.system.math.hypot".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FusedMultiplyAdd",
                    3,
                    MethodBody::Common("dotnet.system.math.fused_multiply_add".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ILogB",
                    1,
                    MethodBody::Common("dotnet.system.math.ilogb".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ScaleB",
                    2,
                    MethodBody::Common("dotnet.system.math.scaleb".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Console")
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.console_writeline".into()),
                ))
                // `Console.WriteLine()` — bare newline. Same common; the
                // dispatcher branches on argc.
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    0,
                    MethodBody::Common("dotnet.console_writeline".into()),
                ))
                // `Console.Write(v)` writes with NO trailing newline — a
                // distinct common from WriteLine.
                .with_method(MethodDef::static_method(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.console_write".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ReadLine",
                    0,
                    MethodBody::Common("dotnet.console_readline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Print",
                    1,
                    MethodBody::Common("dotnet.console_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Assert",
                    1,
                    MethodBody::Common("dotnet.console_writeline".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Delegate")
                .with_method(MethodDef::static_method(
                    "Combine",
                    2,
                    MethodBody::Common("delegates.combine".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Remove",
                    2,
                    MethodBody::Common("delegates.remove".into()),
                )),
        ),
        // `EventArgs.Empty` — the canonical empty event payload. Handlers that
        // carry no data (`EventHandler`) pass it as a non-null placeholder; an
        // empty object satisfies every use that doesn't read a field off it.
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("EventArgs").with_method(MethodDef::static_method(
                "Empty",
                0,
                MethodBody::Common("object.new".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Convert")
                .with_method(MethodDef::static_method(
                    "ToInt32",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToDouble",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "Number")),
                ))
                .with_method(MethodDef::static_method(
                    "ToSingle",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "Number")),
                ))
                .with_method(MethodDef::static_method(
                    "ToDecimal",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "Number")),
                ))
                .with_method(MethodDef::static_method(
                    "ToString",
                    1,
                    MethodBody::Common("dotnet.tostring".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBoolean",
                    1,
                    MethodBody::Common("dyn_to_bool".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToChar",
                    1,
                    MethodBody::Common("dotnet.cchar".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToByte",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToInt64",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:number", "parseInt")),
                ))
                .with_method(MethodDef::static_method(
                    "ToDateTime",
                    1,
                    MethodBody::Common("dotnet.datetime_parse".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64String",
                    1,
                    MethodBody::Common("dotnet.convert_to_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64String",
                    2,
                    MethodBody::Common("dotnet.convert_to_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64String",
                    3,
                    MethodBody::Common("dotnet.convert_to_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FromBase64String",
                    1,
                    MethodBody::Common("dotnet.convert_from_base64_string".into()),
                ))
                .with_method(MethodDef::static_method(
                    "__TryFromBase64CharsCore",
                    2,
                    MethodBody::Common("dotnet.convert_try_from_base64_chars".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ToBase64CharArray",
                    5,
                    MethodBody::Common("dotnet.convert_to_base64_char_array".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("String")
                .with_constructor(
                    ConstructorDef::new(3).with_common_backing("dotnet.string_from_chars"),
                )
                .with_method(MethodDef::static_method(
                    "Format",
                    2,
                    MethodBody::Common("dotnet.string_format".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Join",
                    2,
                    MethodBody::Common("dotnet.string_join_sep_first".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Concat",
                    2,
                    MethodBody::Common("str_concat".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Concat",
                    3,
                    MethodBody::Common("dotnet.string_concat".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    2,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    3,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Compare",
                    6,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CompareOrdinal",
                    2,
                    MethodBody::Common("dotnet.string_compare".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Equals",
                    3,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsNullOrWhiteSpace",
                    1,
                    MethodBody::Common("dotnet.string_is_null_or_whitespace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsNullOrEmpty",
                    1,
                    MethodBody::Common("dotnet.string_is_null_or_empty".into()),
                ))
                .with_method(MethodDef::new(
                    "Contains",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:string", "includes")),
                ))
                .with_method(MethodDef::new(
                    "Contains",
                    2,
                    MethodBody::Common("dotnet.string_contains".into()),
                ))
                .with_method(MethodDef::new(
                    "StartsWith",
                    1,
                    MethodBody::Common("str_starts_with".into()),
                ))
                .with_method(MethodDef::new(
                    "StartsWith",
                    2,
                    MethodBody::Common("dotnet.string_starts_with".into()),
                ))
                .with_method(MethodDef::new(
                    "EndsWith",
                    1,
                    MethodBody::Common("str_ends_with".into()),
                ))
                .with_method(MethodDef::new(
                    "EndsWith",
                    2,
                    MethodBody::Common("dotnet.string_ends_with".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOf",
                    1,
                    MethodBody::Common("dotnet.string_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOf",
                    2,
                    MethodBody::Common("dotnet.string_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOf",
                    3,
                    MethodBody::Common("dotnet.string_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOfAny",
                    1,
                    MethodBody::Common("dotnet.string_index_of_any".into()),
                ))
                .with_method(MethodDef::new(
                    "IndexOfAny",
                    2,
                    MethodBody::Common("dotnet.string_index_of_any".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOf",
                    1,
                    MethodBody::Common("dotnet.string_last_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOf",
                    2,
                    MethodBody::Common("dotnet.string_last_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOf",
                    3,
                    MethodBody::Common("dotnet.string_last_index_of".into()),
                ))
                .with_method(MethodDef::new(
                    "LastIndexOfAny",
                    1,
                    MethodBody::Common("dotnet.string_last_index_of_any".into()),
                ))
                .with_method(MethodDef::new(
                    "Substring",
                    1,
                    MethodBody::Common("dotnet.string_substring".into()),
                ))
                .with_method(MethodDef::new(
                    "Substring",
                    2,
                    MethodBody::Common("dotnet.string_substring".into()),
                ))
                .with_method(MethodDef::new(
                    "ToCharArray",
                    0,
                    MethodBody::Common("dotnet.string_to_char_array".into()),
                ))
                .with_method(MethodDef::new(
                    "Chars",
                    1,
                    MethodBody::Common("dotnet.string_char_at_checked".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Chars",
                    2,
                    MethodBody::Common("dotnet.string_char_at_checked".into()),
                ))
                .with_method(MethodDef::new(
                    "PadLeft",
                    1,
                    MethodBody::Common("dotnet.string_pad_left".into()),
                ))
                .with_method(MethodDef::new(
                    "PadLeft",
                    2,
                    MethodBody::Common("dotnet.string_pad_left".into()),
                ))
                .with_method(MethodDef::new(
                    "PadRight",
                    1,
                    MethodBody::Common("dotnet.string_pad_right".into()),
                ))
                .with_method(MethodDef::new(
                    "PadRight",
                    2,
                    MethodBody::Common("dotnet.string_pad_right".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    2,
                    MethodBody::Common("dotnet.string_replace".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    1,
                    MethodBody::Common("dotnet.string_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    2,
                    MethodBody::Common("dotnet.string_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    3,
                    MethodBody::Common("dotnet.string_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Insert",
                    2,
                    MethodBody::Common("dotnet.str_insert".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    1,
                    MethodBody::Common("dotnet.str_remove_start".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    2,
                    MethodBody::Common("dotnet.str_remove_range".into()),
                ))
                // The NO-ARGUMENT forms. Only the char-array overloads were
                // declared, so `s.Trim()` / `s.ToUpper()` had no leaf at all
                // and reached the tree only because a `[value_methods]` profile
                // row answered first — three times over, once per .NET
                // frontend. A member .NET declares is the tree's to declare.
                .with_method(MethodDef::new(
                    "Trim",
                    0,
                    MethodBody::Common("strings.trim".into()),
                ))
                .with_method(MethodDef::new(
                    "TrimStart",
                    0,
                    MethodBody::Common("str_trim_start".into()),
                ))
                .with_method(MethodDef::new(
                    "TrimEnd",
                    0,
                    MethodBody::Common("str_trim_end".into()),
                ))
                .with_method(MethodDef::new(
                    "ToUpper",
                    0,
                    MethodBody::Common("strings.to_upper".into()),
                ))
                .with_method(MethodDef::new(
                    "ToLower",
                    0,
                    MethodBody::Common("strings.to_lower".into()),
                ))
                // ⛔ `ToUpper(CultureInfo)` / `ToLower(CultureInfo)` are NOT
                // declared. Nothing in this tree does culture-aware casing —
                // `culture_adapter` models culture NAMES and formatting, not
                // case mapping — so a leaf here could only accept the culture
                // and discard it, which answers invariant casing for a caller
                // that asked for Turkish. Declaring the arity would make that
                // silent. It stays undeclared until the mapping exists.
                // `Contains(value)`. The declared overload took a comparison
                // argument, so the one-argument spelling every program uses
                // was missing.
                .with_method(MethodDef::new(
                    "Contains",
                    1,
                    MethodBody::Common("str_includes".into()),
                ))
                .with_method(MethodDef::new(
                    "Trim",
                    1,
                    MethodBody::Common("dotnet.string_trim_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "TrimStart",
                    1,
                    MethodBody::Common("dotnet.string_trim_start_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "TrimEnd",
                    1,
                    MethodBody::Common("dotnet.string_trim_end_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    2,
                    MethodBody::Common("dotnet.string_equals".into()),
                ))
                // `MemoryExtensions.AsSpan` over a string. A `ReadOnlySpan<char>`
                // is the substring itself here — indexing it yields the same
                // single-char strings a `char` is on this runtime.
                // `substr(start, length)` takes a LENGTH, matching .NET exactly;
                // `substring`/`slice` take an END and would need arithmetic.
                .with_method(MethodDef::new(
                    "AsSpan",
                    0,
                    MethodBody::HostCall(HostTarget::new("ecma:object", "valueOf")),
                ))
                .with_method(MethodDef::new(
                    "AsSpan",
                    1,
                    MethodBody::HostCall(HostTarget::new("ecma:string", "substr")),
                ))
                .with_method(MethodDef::new(
                    "AsSpan",
                    2,
                    MethodBody::HostCall(HostTarget::new("ecma:string", "substr")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("Environment")
                .with_property(
                    PropertyDef::new("CurrentDirectory")
                        .with_getter(HostTarget::new("node:process", "cwd")),
                )
                .with_property(
                    PropertyDef::new("NewLine").with_getter(HostTarget::new("node:os", "EOL")),
                )
                .with_property(
                    PropertyDef::new("MachineName")
                        .with_getter(HostTarget::new("node:os", "hostname")),
                )
                .with_property(
                    PropertyDef::new("OSVersion")
                        .with_getter(HostTarget::new("node:os", "version")),
                )
                .with_method(MethodDef::static_method(
                    "UserName",
                    0,
                    MethodBody::Common("dotnet.environment_username".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Version",
                    0,
                    MethodBody::Common("dotnet.environment_version".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ExitCode",
                    0,
                    MethodBody::Common("dotnet.environment_exit_code".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetExitCode",
                    1,
                    MethodBody::Common("dotnet.environment_set_exit_code".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SystemDirectory",
                    0,
                    MethodBody::Common("dotnet.environment_system_directory".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ProcessorCount",
                    0,
                    MethodBody::Common("dotnet.environment_processor_count".into()),
                ))
                .with_method(MethodDef::static_method(
                    "TickCount",
                    0,
                    MethodBody::Common("dotnet.environment_tick_count".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariable",
                    1,
                    MethodBody::Common("dotnet.environment_get".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariable",
                    2,
                    MethodBody::Common("dotnet.environment_get".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetEnvironmentVariable",
                    2,
                    MethodBody::Common("dotnet.environment_set".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetEnvironmentVariable",
                    3,
                    MethodBody::Common("dotnet.environment_set".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariables",
                    0,
                    MethodBody::Common("dotnet.environment_get_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEnvironmentVariables",
                    1,
                    MethodBody::Common("dotnet.environment_get_all".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ExpandEnvironmentVariables",
                    1,
                    MethodBody::Common("dotnet.environment_expand".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetFolderPath",
                    1,
                    MethodBody::Common("dotnet.environment_get_folder_path".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetCommandLineArgs",
                    0,
                    MethodBody::Common("dotnet.environment_get_command_line_args".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System",
            ClassType::new("EnvironmentVariableTarget")
                .with_method(MethodDef::static_method(
                    "Process",
                    0,
                    MethodBody::Common("dotnet.environment_target_process".into()),
                ))
                .with_method(MethodDef::static_method(
                    "User",
                    0,
                    MethodBody::Common("dotnet.environment_target_user".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Machine",
                    0,
                    MethodBody::Common("dotnet.environment_target_machine".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Environment",
            ClassType::new("SpecialFolder")
                .with_method(MethodDef::static_method(
                    "Personal",
                    0,
                    MethodBody::Common("dotnet.environment_special_folder_personal".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ApplicationData",
                    0,
                    MethodBody::Common("dotnet.environment_special_folder_application_data".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LocalApplicationData",
                    0,
                    MethodBody::Common(
                        "dotnet.environment_special_folder_local_application_data".into(),
                    ),
                ))
                .with_method(MethodDef::static_method(
                    "Desktop",
                    0,
                    MethodBody::Common("dotnet.environment_special_folder_desktop".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.Microsoft.VisualBasic",
            ClassType::new("Strings")
                .with_method(MethodDef::static_method(
                    "Left",
                    2,
                    MethodBody::Common("dotnet.vb_strings_left".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Right",
                    2,
                    MethodBody::Common("dotnet.vb_strings_right".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Mid",
                    2,
                    MethodBody::Common("dotnet.vb_strings_mid".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Mid",
                    3,
                    MethodBody::Common("dotnet.vb_strings_mid".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.Microsoft.VisualBasic",
            ClassType::new("FileSystem")
                .with_method(MethodDef::static_method(
                    "FreeFile",
                    0,
                    MethodBody::Common("dotnet.vb_freefile".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileOpen",
                    3,
                    MethodBody::Common("dotnet.vb_fileopen".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileClose",
                    0,
                    MethodBody::Common("dotnet.vb_fileclose".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileClose",
                    1,
                    MethodBody::Common("dotnet.vb_fileclose".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    1,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    2,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    3,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PrintLine",
                    4,
                    MethodBody::Common("dotnet.vb_printline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    2,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    3,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteLine",
                    4,
                    MethodBody::Common("dotnet.vb_writeline".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LineInput",
                    1,
                    MethodBody::Common("dotnet.vb_lineinput".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Input",
                    1,
                    MethodBody::Common("dotnet.vb_input_value".into()),
                ))
                .with_method(MethodDef::static_method(
                    "EOF",
                    1,
                    MethodBody::Common("dotnet.vb_eof".into()),
                ))
                .with_method(MethodDef::static_method(
                    "LOF",
                    1,
                    MethodBody::Common("dotnet.vb_lof".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Loc",
                    1,
                    MethodBody::Common("dotnet.vb_loc".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileAttr",
                    1,
                    MethodBody::Common("dotnet.vb_fileattr".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetAttr",
                    1,
                    MethodBody::Common("dotnet.vb_getattr".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SetAttr",
                    2,
                    MethodBody::Common("dotnet.vb_setattr".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Seek",
                    2,
                    MethodBody::Common("dotnet.vb_seek".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Dir",
                    0,
                    MethodBody::Common("dotnet.vb_dir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Dir",
                    1,
                    MethodBody::Common("dotnet.vb_dir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileCopy",
                    2,
                    MethodBody::Common("dotnet.vb_filecopy".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Kill",
                    1,
                    MethodBody::Common("dotnet.vb_kill".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileLen",
                    1,
                    MethodBody::Common("dotnet.vb_filelen".into()),
                ))
                .with_method(MethodDef::static_method(
                    "FileDateTime",
                    1,
                    MethodBody::Common("dotnet.vb_filedatetime".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CurDir",
                    0,
                    MethodBody::Common("dotnet.vb_curdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ChDir",
                    1,
                    MethodBody::Common("dotnet.vb_chdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "MkDir",
                    1,
                    MethodBody::Common("dotnet.vb_mkdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "RmDir",
                    1,
                    MethodBody::Common("dotnet.vb_rmdir".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Name",
                    2,
                    MethodBody::Common("dotnet.vb_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Rename",
                    2,
                    MethodBody::Common("dotnet.vb_name".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Get",
                    1,
                    MethodBody::Common("dotnet.vb_get".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Put",
                    1,
                    MethodBody::Common("dotnet.vb_put".into()),
                )),
        ),
    ]);
    exports
}

/// `System.Numerics.BigInteger` — see `biginteger_adapter`.
///
/// ⛔ Declared where .NET puts it, `System.Numerics`, which is also the
/// namespace `Imports System.Numerics` names. Every member is a STATIC in the
/// tree even where .NET spells it as an instance property (`v.Sign`,
/// `v.IsEven`): the value is a bare ECMA BigInt with no property bag to hang
/// an accessor on, and the instance-call path passes the receiver as argument
/// zero either way.
pub(super) fn biginteger_export() -> DotnetClassExport {
    // `New BigInteger(54)` — built by the same coercion `Parse` uses, so a
    // constructed and a parsed BigInteger are the same value.
    let mut class = ClassType::new("BigInteger")
        .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.bigint_parse"));
    for (name, arity, emit) in [
        ("Abs", 1u8, "dotnet.bigint_abs"),
        ("Negate", 1, "dotnet.bigint_negate"),
        ("Parse", 1, "dotnet.bigint_parse"),
        ("Pow", 2, "dotnet.bigint_pow"),
        ("Min", 2, "dotnet.bigint_min"),
        ("Max", 2, "dotnet.bigint_max"),
        ("Compare", 2, "dotnet.bigint_compare"),
        ("ModPow", 3, "dotnet.bigint_mod_pow"),
        ("GreatestCommonDivisor", 2, "dotnet.bigint_gcd"),
        ("Clamp", 3, "dotnet.bigint_clamp"),
        ("DivRem", 2, "dotnet.bigint_div_rem"),
        ("Log10", 1, "dotnet.bigint_log10"),
        ("Log", 1, "dotnet.bigint_log"),
        // The hidden one-arg core `lowering::try_parse_desugar` calls. It
        // answers NULL on a malformed string and the desugar turns that into
        // `False` plus the out-param write, which is why BigInteger belongs in
        // that function's REFERENCE-shaped list and not the numeric one — a
        // BigInteger's failure value is null, not zero.
        ("TryParse", 1, "dotnet.bigint_try_parse"),
    ] {
        class = class.with_method(MethodDef::static_method(
            name,
            arity,
            MethodBody::Common(emit.into()),
        ));
    }
    for (name, emit) in [
        ("Zero", "dotnet.bigint_zero"),
        ("One", "dotnet.bigint_one"),
        ("MinusOne", "dotnet.bigint_minus_one"),
    ] {
        class = class.with_method(MethodDef::static_method(
            name,
            0,
            MethodBody::Common(emit.into()),
        ));
    }
    for (name, emit) in [
        ("ToString", "dotnet.bigint_to_string"),
        ("Sign", "dotnet.bigint_sign"),
        ("IsZero", "dotnet.bigint_is_zero"),
        ("IsOne", "dotnet.bigint_is_one"),
        ("IsEven", "dotnet.bigint_is_even"),
        ("IsPowerOfTwo", "dotnet.bigint_is_power_of_two"),
        ("ToByteArray", "dotnet.bigint_to_byte_array"),
    ] {
        class = class.with_method(MethodDef::new(name, 0, MethodBody::Common(emit.into())));
    }
    class = class
        // ⛔ A SECOND registration, not a widened one. INSTANCE lookup matches
        // on EXACT arity (`find_instance_method_on`), the opposite of the
        // static path — so `v.ToString("X")` never reached the arity-0
        // `ToString` and fell through to the generic object one. Both point at
        // the same common; the emitter branches on `argc`.
        .with_method(MethodDef::new(
            "ToString",
            1,
            MethodBody::Common("dotnet.bigint_to_string".into()),
        ))
        .with_method(MethodDef::new(
            "CompareTo",
            1,
            MethodBody::Common("dotnet.bigint_compare".into()),
        ))
        .with_method(MethodDef::new(
            "Equals",
            1,
            MethodBody::Common("dotnet.bigint_equals".into()),
        ));
    DotnetClassExport::new("dotnet.System.Numerics", class)
}
