use super::super::super::class_exports::DotnetClassExport;
use vybe_runtime::component_model::{ClassType, ConstructorDef, MethodBody, MethodDef};
use vybe_runtime::component::ValType;

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        // `System.Text.Rune` — ONE Unicode scalar value.
        //
        // Everything but the scalar is derived from it, so the constructor
        // computes `IsAscii`, `IsBmp` and the two encoded lengths once and
        // stores them as fields; the reads are then ordinary field reads with
        // no property machinery. The static classifiers unwrap the scalar and
        // reuse `System.Char`'s tables rather than restating them.
        DotnetClassExport::new(
            "dotnet.System.Text",
            [
                ("IsDigit", "digit"),
                ("IsLetter", "letter"),
                ("IsLetterOrDigit", "letterordigit"),
                ("IsUpper", "upper"),
                ("IsLower", "lower"),
                ("IsWhiteSpace", "whitespace"),
                ("IsPunctuation", "punctuation"),
                ("IsControl", "control"),
            ]
            .into_iter()
            .fold(
                ClassType::new("Rune")
                    .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.rune_new"))
                    .with_method(MethodDef::static_method(
                        "ToUpperInvariant",
                        1,
                        MethodBody::Common("dotnet.rune_to_upper".into()),
                    ))
                    .with_method(MethodDef::static_method(
                        "ToLowerInvariant",
                        1,
                        MethodBody::Common("dotnet.rune_to_lower".into()),
                    ))
                    .with_method(MethodDef::static_method(
                        "ReplacementChar",
                        0,
                        MethodBody::Common("dotnet.rune_replacement_char".into()),
                    ))
                    .with_method(MethodDef::static_method(
                        "GetNumericValue",
                        1,
                        MethodBody::Common("dotnet.rune_numeric_value".into()),
                    ))
                    .with_method(MethodDef::new(
                        "ToString",
                        0,
                        MethodBody::Common("dotnet.rune_to_string".into()),
                    ))
                    .with_method(MethodDef::new(
                        "GetHashCode",
                        0,
                        MethodBody::Common("dotnet.rune_hash".into()),
                    ))
                    .with_method(MethodDef::new(
                        "CompareTo",
                        1,
                        MethodBody::Common("dotnet.rune_compare_to".into()),
                    ))
                    .with_method(MethodDef::new(
                        "Equals",
                        1,
                        MethodBody::Common("dotnet.rune_equals".into()),
                    )),
                |class, (name, kind)| {
                    class.with_method(MethodDef::static_method(
                        name,
                        1,
                        MethodBody::Common(format!("dotnet.rune_is_{kind}")),
                    ))
                },
            ),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("StringBuilder")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.string_builder_new"),
                )
                // `New StringBuilder("seed")` — the backing already accepts it;
                // only the DECLARATION was missing, so reflection had no
                // 1-argument constructor to select.
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_common_backing("dotnet.string_builder_new")
                        .with_params(vec![ValType::String]),
                )
                .with_method(MethodDef::new(
                    "Append",
                    1,
                    MethodBody::Common("dotnet.sb_append".into()),
                ))
                .with_method(MethodDef::new(
                    "Append",
                    2,
                    MethodBody::Common("dotnet.sb_append".into()),
                ))
                .with_method(MethodDef::new(
                    "Append",
                    3,
                    MethodBody::Common("dotnet.sb_append".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendLine",
                    0,
                    MethodBody::Common("dotnet.sb_append_line".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendLine",
                    1,
                    MethodBody::Common("dotnet.sb_append_line".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendFormat",
                    2,
                    MethodBody::Common("dotnet.sb_append_format".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendFormat",
                    3,
                    MethodBody::Common("dotnet.sb_append_format".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendFormat",
                    4,
                    MethodBody::Common("dotnet.sb_append_format".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendJoin",
                    2,
                    MethodBody::Common("dotnet.sb_append_join".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.sb_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    2,
                    MethodBody::Common("dotnet.sb_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "Clear",
                    0,
                    MethodBody::Common("dotnet.sb_clear".into()),
                ))
                .with_method(MethodDef::new(
                    "Chars",
                    1,
                    MethodBody::Common("dotnet.sb_index_get".into()),
                ))
                .with_method(MethodDef::new(
                    "EnsureCapacity",
                    1,
                    MethodBody::Common("dotnet.sb_ensure_capacity".into()),
                ))
                .with_method(MethodDef::new(
                    "CopyTo",
                    4,
                    MethodBody::Common("dotnet.sb_copy_to".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.sb_equals".into()),
                ))
                .with_method(MethodDef::new(
                    "Insert",
                    2,
                    MethodBody::Common("dotnet.sb_insert".into()),
                ))
                .with_method(MethodDef::new(
                    "Remove",
                    2,
                    MethodBody::Common("dotnet.sb_remove".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    2,
                    MethodBody::Common("dotnet.sb_replace".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    4,
                    MethodBody::Common("dotnet.sb_replace".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.RegularExpressions",
            ClassType::new("Regex")
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.regex_new"))
                .with_constructor(ConstructorDef::new(2).with_common_backing("dotnet.regex_new"))
                .with_constructor(ConstructorDef::new(3).with_common_backing("dotnet.regex_new"))
                .with_method(MethodDef::static_method(
                    "IsMatch",
                    2,
                    MethodBody::Common("dotnet.regex_static_is_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsMatch",
                    3,
                    MethodBody::Common("dotnet.regex_static_is_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "IsMatch",
                    4,
                    MethodBody::Common("dotnet.regex_static_is_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Match",
                    2,
                    MethodBody::Common("dotnet.regex_static_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Match",
                    3,
                    MethodBody::Common("dotnet.regex_static_match".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Matches",
                    2,
                    MethodBody::Common("dotnet.regex_static_matches".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Matches",
                    3,
                    MethodBody::Common("dotnet.regex_static_matches".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Replace",
                    3,
                    MethodBody::Common("dotnet.regex_static_replace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Replace",
                    4,
                    MethodBody::Common("dotnet.regex_static_replace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Replace",
                    5,
                    MethodBody::Common("dotnet.regex_static_replace".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Split",
                    2,
                    MethodBody::Common("dotnet.regex_static_split".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Split",
                    3,
                    MethodBody::Common("dotnet.regex_static_split".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Escape",
                    1,
                    MethodBody::Common("dotnet.regex_escape".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Unescape",
                    1,
                    MethodBody::Common("dotnet.regex_unescape".into()),
                ))
                .with_method(MethodDef::new(
                    "IsMatch",
                    1,
                    MethodBody::Common("dotnet.regex_is_match".into()),
                ))
                .with_method(MethodDef::new(
                    "Replace",
                    2,
                    MethodBody::Common("dotnet.regex_replace".into()),
                ))
                .with_method(MethodDef::new(
                    "Split",
                    1,
                    MethodBody::Common("dotnet.regex_split".into()),
                ))
                .with_method(MethodDef::new(
                    "Match",
                    1,
                    MethodBody::Common("dotnet.regex_match".into()),
                ))
                .with_method(MethodDef::new(
                    "Matches",
                    1,
                    MethodBody::Common("dotnet.regex_matches".into()),
                ))
                .with_method(MethodDef::new(
                    "GetGroupNames",
                    0,
                    MethodBody::Common("dotnet.regex_get_group_names".into()),
                ))
                .with_method(MethodDef::new(
                    "GroupNameFromNumber",
                    1,
                    MethodBody::Common("dotnet.regex_group_name_from_number".into()),
                ))
                .with_method(MethodDef::new(
                    "GroupNumberFromName",
                    1,
                    MethodBody::Common("dotnet.regex_group_number_from_name".into()),
                )),
        ),
        // ── System.Security.Cryptography ────────────────────────────────
        //
        // ⛔ TREE LEAVES, NOT SYNTHESIZED CLASSES: the corpus writes the fully
        // qualified `System.Security.Cryptography.SHA256.HashData(...)`, and a
        // dotted path resolves through the tree. Registered here rather than in
        // a language crate so VB reaches the identical surface.
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("AesGcm").with_method(MethodDef::static_method(
                "IsSupported",
                0,
                MethodBody::Common("dotnet.crypto_supported_true".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("ChaCha20Poly1305").with_method(MethodDef::static_method(
                "IsSupported",
                0,
                MethodBody::Common("dotnet.crypto_supported_true".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("SHA3_256").with_method(MethodDef::static_method(
                "IsSupported",
                0,
                MethodBody::Common("dotnet.crypto_supported_false".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("SHA3_384").with_method(MethodDef::static_method(
                "IsSupported",
                0,
                MethodBody::Common("dotnet.crypto_supported_false".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("SHA3_512").with_method(MethodDef::static_method(
                "IsSupported",
                0,
                MethodBody::Common("dotnet.crypto_supported_false".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("AesCcm").with_method(MethodDef::static_method(
                "IsSupported",
                0,
                MethodBody::Common("dotnet.crypto_supported_true".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography.X509Certificates",
            ClassType::new("X509Certificate2").with_method(MethodDef::new(
                "Dispose",
                0,
                MethodBody::Common("dotnet.crypto_incremental_dispose".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("SHA1")
                .with_method(MethodDef::static_method(
                    "HashData",
                    1,
                    MethodBody::Common("dotnet.crypto_sha1".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Create",
                    0,
                    MethodBody::Common("dotnet.crypto_create_sha1".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("MD5")
                .with_method(MethodDef::static_method(
                    "HashData",
                    1,
                    MethodBody::Common("dotnet.crypto_md5".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Create",
                    0,
                    MethodBody::Common("dotnet.crypto_create_md5".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("HashAlgorithm")
                .with_method(MethodDef::new(
                    "ComputeHash",
                    1,
                    MethodBody::Common("dotnet.crypto_compute_hash".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.crypto_incremental_dispose".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("RSA").with_method(MethodDef::static_method(
                "Create",
                1,
                MethodBody::Common("dotnet.crypto_rsa_create".into()),
            ))
            .with_method(MethodDef::new(
                "Dispose",
                0,
                MethodBody::Common("dotnet.crypto_incremental_dispose".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("ECDsa").with_method(MethodDef::static_method(
                "Create",
                1,
                MethodBody::Common("dotnet.crypto_ecdsa_create".into()),
            ))
            .with_method(MethodDef::new(
                "Dispose",
                0,
                MethodBody::Common("dotnet.crypto_incremental_dispose".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("Rfc2898DeriveBytes").with_method(MethodDef::static_method(
                "Pbkdf2",
                5,
                MethodBody::Common("dotnet.crypto_pbkdf2".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography.X509Certificates",
            ClassType::new("CertificateRequest")
                .with_constructor(
                    ConstructorDef::new(4).with_common_backing("dotnet.crypto_cert_request"),
                )
                .with_method(MethodDef::new(
                    "CreateSelfSigned",
                    2,
                    MethodBody::Common("dotnet.crypto_self_signed".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.crypto_incremental_dispose".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("SHA256").with_method(MethodDef::static_method(
                "HashData",
                1,
                MethodBody::Common("dotnet.crypto_sha256".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("SHA512").with_method(MethodDef::static_method(
                "HashData",
                1,
                MethodBody::Common("dotnet.crypto_sha512".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("HMACSHA256").with_method(MethodDef::static_method(
                "HashData",
                2,
                MethodBody::Common("dotnet.crypto_hmac_sha256".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("HMACSHA512").with_method(MethodDef::static_method(
                "HashData",
                2,
                MethodBody::Common("dotnet.crypto_hmac_sha512".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("IncrementalHash")
                .with_method(MethodDef::static_method(
                    "CreateHash",
                    1,
                    MethodBody::Common("dotnet.crypto_incremental_create".into()),
                ))
                .with_method(MethodDef::new(
                    "AppendData",
                    1,
                    MethodBody::Common("dotnet.crypto_incremental_append".into()),
                ))
                .with_method(MethodDef::new(
                    "GetHashAndReset",
                    0,
                    MethodBody::Common("dotnet.crypto_incremental_finish".into()),
                ))
                .with_method(MethodDef::new(
                    "GetCurrentHash",
                    0,
                    MethodBody::Common("dotnet.crypto_incremental_finish".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.crypto_incremental_dispose".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Security.Cryptography",
            ClassType::new("RandomNumberGenerator")
                .with_method(MethodDef::static_method(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.crypto_random_bytes".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetInt32",
                    2,
                    MethodBody::Common("dotnet.crypto_random_int".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetInt32",
                    1,
                    MethodBody::Common("dotnet.crypto_random_int".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.Json",
            ClassType::new("JsonDocument").with_method(MethodDef::static_method(
                "Parse",
                1,
                MethodBody::Common("dotnet.json_document_parse".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.Json",
            ClassType::new("JsonSerializerOptions").with_constructor(
                ConstructorDef::new(0).with_common_backing("dotnet.json_options_new"),
            ),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.Json.Serialization.Metadata",
            ClassType::new("DefaultJsonTypeInfoResolver").with_constructor(
                ConstructorDef::new(0).with_common_backing("dotnet.json_type_info_resolver_new"),
            ),
        ),
        // The five naming policies. Each is a VALUE in .NET — it can be stored
        // in `JsonSerializerOptions.PropertyNamingPolicy` and have
        // `ConvertName` called on it later — so each static mints an object
        // rather than folding at the call site.
        DotnetClassExport::new(
            "dotnet.System.Text.Json",
            ClassType::new("JsonNamingPolicy")
                .with_method(MethodDef::static_method(
                    "SnakeCaseLower",
                    0,
                    MethodBody::Common("dotnet.json_naming_snake_lower".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SnakeCaseUpper",
                    0,
                    MethodBody::Common("dotnet.json_naming_snake_upper".into()),
                ))
                .with_method(MethodDef::static_method(
                    "KebabCaseLower",
                    0,
                    MethodBody::Common("dotnet.json_naming_kebab_lower".into()),
                ))
                .with_method(MethodDef::static_method(
                    "KebabCaseUpper",
                    0,
                    MethodBody::Common("dotnet.json_naming_kebab_upper".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CamelCase",
                    0,
                    MethodBody::Common("dotnet.json_naming_camel".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.Json",
            ClassType::new("JsonSerializer")
                .with_method(MethodDef::static_method(
                    "Serialize",
                    1,
                    MethodBody::Common("dotnet.json_serialize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Deserialize",
                    1,
                    MethodBody::Common("dotnet.json_deserialize".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("Encoding")
                .with_method(MethodDef::static_method(
                    "UTF8",
                    0,
                    MethodBody::Common("dotnet.encoding_utf8".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ASCII",
                    0,
                    MethodBody::Common("dotnet.encoding_ascii".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Unicode",
                    0,
                    MethodBody::Common("dotnet.encoding_unicode".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Default",
                    0,
                    MethodBody::Common("dotnet.encoding_utf8".into()),
                ))
                .with_method(MethodDef::static_method(
                    "UTF32",
                    0,
                    MethodBody::Common("dotnet.encoding_utf32".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Latin1",
                    0,
                    MethodBody::Common("dotnet.encoding_latin1".into()),
                ))
                .with_method(MethodDef::static_method(
                    "BigEndianUnicode",
                    0,
                    MethodBody::Common("dotnet.encoding_big_endian_unicode".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEncoding",
                    1,
                    MethodBody::Common("dotnet.encoding_get_encoding".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetEncoding",
                    3,
                    MethodBody::Common("dotnet.encoding_get_encoding".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Convert",
                    3,
                    MethodBody::Common("dotnet.encoding_convert".into()),
                ))
                .with_method(MethodDef::new(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.encoding_get_bytes".into()),
                ))
                .with_method(MethodDef::new(
                    "GetString",
                    1,
                    MethodBody::Common("dotnet.encoding_get_string".into()),
                ))
                .with_method(MethodDef::new(
                    "GetByteCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_byte_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetCharCount",
                    3,
                    MethodBody::Common("dotnet.encoding_get_char_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetChars",
                    5,
                    MethodBody::Common("dotnet.encoding_get_chars".into()),
                ))
                .with_method(MethodDef::new(
                    "GetPreamble",
                    0,
                    MethodBody::Common("dotnet.encoding_get_preamble".into()),
                ))
                .with_method(MethodDef::new(
                    "GetMaxByteCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_max_byte_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetMaxCharCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_max_char_count".into()),
                ))
                .with_method(MethodDef::new(
                    "Clone",
                    0,
                    MethodBody::Common("dotnet.identity".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.encoding_equals".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text",
            ClassType::new("UTF8Encoding")
                .with_parent("Encoding")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.utf8encoding_new"),
                )
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.utf8encoding_new"),
                )
                .with_method(MethodDef::new(
                    "GetBytes",
                    1,
                    MethodBody::Common("dotnet.encoding_get_bytes".into()),
                ))
                .with_method(MethodDef::new(
                    "GetString",
                    1,
                    MethodBody::Common("dotnet.encoding_get_string".into()),
                ))
                .with_method(MethodDef::new(
                    "GetByteCount",
                    1,
                    MethodBody::Common("dotnet.encoding_get_byte_count".into()),
                ))
                .with_method(MethodDef::new(
                    "GetPreamble",
                    0,
                    MethodBody::Common("dotnet.encoding_get_preamble".into()),
                )),
        ),
    ]
}
