use super::super::super::class_exports::DotnetClassExport;
use vybe_bytecode::component_model::{
    ClassType, ConstructorDef, HostTarget, MethodBody, MethodDef,
};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.Net",
            ClassType::new("WebRequest")
                .with_constructor(
                    ConstructorDef::new(1).with_backing(HostTarget::new("wasi:http", "fetch")),
                )
                .with_method(MethodDef::static_method(
                    "Create",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:http", "fetch")),
                ))
                .with_method(MethodDef::new(
                    "GetResponse",
                    0,
                    MethodBody::HostCall(HostTarget::new("wasi:http", "fetch")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Net",
            ClassType::new("WebClient")
                .with_constructor(
                    ConstructorDef::new(0).with_backing(HostTarget::new("wasi:http", "fetch")),
                )
                .with_method(MethodDef::new(
                    "DownloadString",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:http", "fetch")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Net.Http",
            ClassType::new("HttpClient")
                .with_constructor(
                    ConstructorDef::new(0).with_backing(HostTarget::new("wasi:http", "fetch")),
                )
                .with_method(MethodDef::new(
                    "GetStringAsync",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:http", "fetch")),
                ))
                .with_method(MethodDef::new(
                    "GetAsync",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:http", "fetch")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Net.Sockets",
            ClassType::new("TcpClient")
                .with_constructor(
                    ConstructorDef::new(2).with_common_backing("dotnet.tcp_client_new"),
                )
                .with_method(MethodDef::new(
                    "GetStream",
                    0,
                    MethodBody::Common("dotnet.tcp_client_get_stream".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.tcp_client_close".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Net.Sockets",
            ClassType::new("TcpListener")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.tcp_listener_new"),
                )
                .with_method(MethodDef::new(
                    "Start",
                    0,
                    MethodBody::Common("dotnet.tcp_listener_start".into()),
                ))
                .with_method(MethodDef::new(
                    "Stop",
                    0,
                    MethodBody::Common("dotnet.tcp_listener_stop".into()),
                ))
                .with_method(MethodDef::new(
                    "AcceptTcpClient",
                    0,
                    MethodBody::Common("dotnet.tcp_listener_accept".into()),
                ))
                .with_method(MethodDef::new(
                    "Pending",
                    0,
                    MethodBody::Common("dotnet.tcp_listener_pending".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Net.Sockets",
            ClassType::new("UdpClient")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.udp_client_new"),
                )
                .with_method(MethodDef::new(
                    "Send",
                    4,
                    MethodBody::Common("dotnet.udp_send".into()),
                ))
                .with_method(MethodDef::new(
                    "Receive",
                    0,
                    MethodBody::Common("dotnet.udp_receive".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.udp_close".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Net",
            ClassType::new("Dns")
                .with_method(MethodDef::static_method(
                    "GetHostAddresses",
                    1,
                    MethodBody::Common("dotnet.dns_get_host_addresses".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetHostEntry",
                    1,
                    MethodBody::Common("dotnet.dns_get_host_entry".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetHostName",
                    0,
                    MethodBody::Common("dotnet.dns_get_host_name".into()),
                )),
        ),
    ]
}
