use super::super::super::class_exports::DotnetClassExport;
use vybe_runtime::component_model::{ClassType, ConstructorDef, MethodBody, MethodDef};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    let mut task = ClassType::new("Task")
        .with_constructor(ConstructorDef::new(1).with_common_backing("threading.thread_new"))
        .with_method(MethodDef::new(
            "Start",
            0,
            MethodBody::Common("threading.thread_start".into()),
        ))
        .with_method(MethodDef::new(
            "Wait",
            0,
            MethodBody::Common("dotnet.task_wait".into()),
        ))
        .with_method(MethodDef::static_method(
            "Run",
            1,
            MethodBody::Common("dotnet.task_run".to_string()),
        ))
        .with_method(MethodDef::static_method(
            "Delay",
            1,
            MethodBody::Common("dotnet.task_delay".into()),
        ))
        .with_method(MethodDef::static_method(
            "Delay",
            2,
            MethodBody::Common("dotnet.task_delay".into()),
        ))
        .with_method(MethodDef::static_method(
            "Yield",
            0,
            MethodBody::Common("dotnet.task_yield".into()),
        ))
        .with_method(MethodDef::static_method(
            "FromResult",
            1,
            MethodBody::Common("dotnet.task_from_result".into()),
        ))
        .with_method(MethodDef::new(
            "IsCanceled",
            0,
            MethodBody::Common("dotnet.task_is_canceled".into()),
        ))
        .with_method(MethodDef::new(
            "IsCompleted",
            0,
            MethodBody::Common("dotnet.task_is_completed".into()),
        ))
        .with_method(MethodDef::new(
            "Result",
            0,
            MethodBody::Common("dotnet.task_result".into()),
        ))
        .with_method(MethodDef::new(
            "ContinueWith",
            1,
            MethodBody::Common("dotnet.task_continue_with".into()),
        ));
    // `Task.WhenAll` / `WhenAny` take variadic tasks; overload resolution is by
    // exact arity, so register each width plus the single `IEnumerable` form.
    for n in 1..=8u8 {
        task = task
            .with_method(MethodDef::static_method(
                "WhenAll",
                n,
                MethodBody::Common("dotnet.task_when_all".into()),
            ))
            .with_method(MethodDef::static_method(
                "WhenAny",
                n,
                MethodBody::Common("dotnet.task_when_any".into()),
            ));
    }
    vec![
        DotnetClassExport::new("dotnet.System.Threading.Tasks", task),
        // `TaskCompletionSource(Of T)` — the producer half of a Task. The type
        // was absent from the catalog entirely, so every member answered
        // "undefined is not callable". `Task` is a computed property declared
        // in `tree_register::shared_emit_accessors`, not a method.
        //
        // ⛔ THE `Try*` PAIR IS A SEPARATE REGISTRATION, NOT A FLAG. `SetResult`
        // and `TrySetResult` differ in their RETURN CONTRACT — one throws on a
        // second completion, the other answers `False` — so they route to
        // distinct commons and share their body inside the adapter.
        DotnetClassExport::new(
            "dotnet.System.Threading.Tasks",
            ClassType::new("TaskCompletionSource")
                .with_constructor(ConstructorDef::new(0).with_common_backing("dotnet.tcs_new"))
                .with_constructor(ConstructorDef::new(1).with_common_backing("dotnet.tcs_new"))
                .with_method(MethodDef::new(
                    "SetResult",
                    1,
                    MethodBody::Common("dotnet.tcs_set_result".into()),
                ))
                .with_method(MethodDef::new(
                    "TrySetResult",
                    1,
                    MethodBody::Common("dotnet.tcs_try_set_result".into()),
                ))
                .with_method(MethodDef::new(
                    "SetException",
                    1,
                    MethodBody::Common("dotnet.tcs_set_exception".into()),
                ))
                .with_method(MethodDef::new(
                    "TrySetException",
                    1,
                    MethodBody::Common("dotnet.tcs_try_set_exception".into()),
                ))
                .with_method(MethodDef::new(
                    "SetCanceled",
                    0,
                    MethodBody::Common("dotnet.tcs_set_canceled".into()),
                ))
                .with_method(MethodDef::new(
                    "TrySetCanceled",
                    0,
                    MethodBody::Common("dotnet.tcs_try_set_canceled".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading",
            ClassType::new("Interlocked")
                .with_method(MethodDef::static_method(
                    "Add",
                    2,
                    MethodBody::Common("threading.atomic_add".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "Exchange",
                    2,
                    MethodBody::Common("threading.atomic_xchg".to_string()),
                ))
                .with_method(MethodDef::static_method(
                    "CompareExchange",
                    3,
                    MethodBody::Common("threading.atomic_cmpxchg".to_string()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading",
            ClassType::new("CancellationTokenSource")
                .with_constructor(
                    ConstructorDef::new(0)
                        .with_common_backing("dotnet.cancellation_token_source_new"),
                )
                .with_method(MethodDef::new(
                    "Cancel",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_cancel".into()),
                ))
                .with_method(MethodDef::new(
                    "CancelAfter",
                    1,
                    MethodBody::Common("dotnet.cancellation_token_cancel_after".into()),
                ))
                .with_method(MethodDef::new(
                    "Token",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_source_token".into()),
                ))
                .with_method(MethodDef::new(
                    "IsCancellationRequested",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_is_requested".into()),
                ))
                .with_method(MethodDef::new(
                    "ThrowIfCancellationRequested",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_throw_if_requested".into()),
                ))
                .with_method(MethodDef::new(
                    "Register",
                    1,
                    MethodBody::Common("dotnet.cancellation_token_register".into()),
                ))
                .with_method(MethodDef::new(
                    "CanBeCanceled",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_can_be_canceled".into()),
                ))
                .with_method(MethodDef::new(
                    "WaitHandle",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_wait_handle".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.noop".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CreateLinkedTokenSource",
                    1,
                    MethodBody::Common("dotnet.cancellation_token_linked_source".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CreateLinkedTokenSource",
                    2,
                    MethodBody::Common("dotnet.cancellation_token_linked_source".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading",
            ClassType::new("CancellationToken")
                .with_method(MethodDef::static_method(
                    "None",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_none".into()),
                ))
                .with_method(MethodDef::new(
                    "IsCancellationRequested",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_is_requested".into()),
                ))
                .with_method(MethodDef::new(
                    "ThrowIfCancellationRequested",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_throw_if_requested".into()),
                ))
                .with_method(MethodDef::new(
                    "Register",
                    1,
                    MethodBody::Common("dotnet.cancellation_token_register".into()),
                ))
                .with_method(MethodDef::new(
                    "CanBeCanceled",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_can_be_canceled".into()),
                ))
                .with_method(MethodDef::new(
                    "WaitHandle",
                    0,
                    MethodBody::Common("dotnet.cancellation_token_wait_handle".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading.Tasks",
            ClassType::new("ValueTask").with_method(MethodDef::new(
                "AsTask",
                0,
                MethodBody::Common("dotnet.value_task_as_task".into()),
            )),
        ),
        // `AutoResetEvent` / `ManualResetEvent`. Both arities of `WaitOne` are
        // declared because the dotnet INSTANCE lookup matches name AND exact
        // arity — one row would leave the other spelling unresolved.
        wait_handle_export("AutoResetEvent", "dotnet.auto_reset_event_new"),
        wait_handle_export("ManualResetEvent", "dotnet.manual_reset_event_new"),
        // The abstract base, for its statics. `WaitHandle()` is the DECLARED
        // type of `Dim allDone As WaitHandle() = {a, b}`, so the name must
        // resolve even though nothing constructs one.
        DotnetClassExport::new(
            "dotnet.System.Threading",
            ClassType::new("WaitHandle").with_method(MethodDef::static_method(
                "WaitAll",
                1,
                MethodBody::Common("dotnet.event_wait_all".into()),
            )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading",
            ClassType::new("Thread")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("threading.thread_new"),
                )
                .with_method(MethodDef::new(
                    "Start",
                    0,
                    MethodBody::Common("threading.thread_start".into()),
                ))
                .with_method(MethodDef::new(
                    "Join",
                    0,
                    MethodBody::Common("threading.thread_join".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Sleep",
                    1,
                    MethodBody::Common("threading.sleep".to_string()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading",
            // Callback timer on the event loop — see `emit_threading_timer_new`
            // for why the loop and not a wasi thread.
            ClassType::new("Timer")
                .with_constructor(
                    ConstructorDef::new(4).with_common_backing("dotnet.threading_timer_new"),
                )
                .with_method(MethodDef::new(
                    "Change",
                    2,
                    MethodBody::Common("dotnet.threading_timer_change".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.threading_timer_dispose".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Threading",
            // `Timeout.Infinite` — the -1 sentinel every timer API compares
            // against; a constant, but .NET spells it as a class member.
            ClassType::new("Timeout").with_method(MethodDef::static_method(
                "Infinite",
                0,
                MethodBody::Common("dotnet.timeout_infinite".into()),
            )),
        ),
    ]
}

/// One `WaitHandle` event class. `AutoResetEvent` and `ManualResetEvent` differ
/// ONLY in whether a successful wait consumes the signal, and that difference
/// is carried on the instance by the constructor — so the two classes share
/// every method row rather than being spelled out twice and drifting.
fn wait_handle_export(name: &'static str, ctor: &'static str) -> DotnetClassExport {
    DotnetClassExport::new(
        "dotnet.System.Threading",
        ClassType::new(name)
            .with_constructor(ConstructorDef::new(0).with_common_backing(ctor))
            .with_constructor(ConstructorDef::new(1).with_common_backing(ctor))
            .with_method(MethodDef::new(
                "Set",
                0,
                MethodBody::Common("dotnet.event_set".into()),
            ))
            .with_method(MethodDef::new(
                "Reset",
                0,
                MethodBody::Common("dotnet.event_reset".into()),
            ))
            .with_method(MethodDef::new(
                "WaitOne",
                0,
                MethodBody::Common("dotnet.event_wait_one".into()),
            ))
            .with_method(MethodDef::new(
                "WaitOne",
                1,
                MethodBody::Common("dotnet.event_wait_one".into()),
            ))
            .with_method(MethodDef::new(
                "Close",
                0,
                MethodBody::Common("dotnet.noop".into()),
            ))
            .with_method(MethodDef::new(
                "Dispose",
                0,
                MethodBody::Common("dotnet.noop".into()),
            )),
    )
}

/// `System.Globalization` — `CultureInfo`, `TextInfo`.
///
/// ⛔ `InvariantCulture` / `CurrentCulture` are declared as STATIC methods of
/// arity 0, which is how this tree spells a static property (`Timeout.Infinite`
/// above does the same): "a module member read as a value invokes the leaf".
pub(super) fn globalization_exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.Globalization",
            ClassType::new("CultureInfo")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.get_culture_info"),
                )
                .with_method(MethodDef::static_method(
                    "InvariantCulture",
                    0,
                    MethodBody::Common("dotnet.invariant_culture".into()),
                ))
                .with_method(MethodDef::static_method(
                    "CurrentCulture",
                    0,
                    MethodBody::Common("dotnet.current_culture".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetCultureInfo",
                    1,
                    MethodBody::Common("dotnet.get_culture_info".into()),
                ))
                .with_method(MethodDef::new(
                    "Parent",
                    0,
                    MethodBody::Common("dotnet.culture_parent".into()),
                ))
                .with_method(MethodDef::new(
                    "Clone",
                    0,
                    MethodBody::Common("dotnet.culture_clone".into()),
                ))
                .with_method(MethodDef::new(
                    "Equals",
                    1,
                    MethodBody::Common("dotnet.culture_equals".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetCultures",
                    1,
                    MethodBody::Common("dotnet.get_cultures".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Globalization",
            ClassType::new("TextInfo")
                .with_method(MethodDef::new(
                    "ToTitleCase",
                    1,
                    MethodBody::Common("dotnet.text_info_to_title_case".into()),
                ))
                .with_method(MethodDef::new(
                    "ToUpper",
                    1,
                    MethodBody::Common("dotnet.text_info_to_upper".into()),
                ))
                .with_method(MethodDef::new(
                    "ToLower",
                    1,
                    MethodBody::Common("dotnet.text_info_to_lower".into()),
                )),
        ),
    ]
}
