use super::super::super::class_exports::DotnetClassExport;
use vybe_bytecode::component_model::{
    ClassType, ConstructorDef, HostTarget, MethodBody, MethodDef,
};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("MemoryStream")
                .with_constructor(ConstructorDef::new(0).with_common_backing("collections.new"))
                .with_method(MethodDef::new(
                    "ToArray",
                    0,
                    MethodBody::Common("collections.clone".into()),
                ))
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("collections.push".into()),
                ))
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("collections.shift".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("FileStream")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_backing(HostTarget::new("wasi:filesystem", "readFile")),
                )
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                ))
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("BinaryReader")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_backing(HostTarget::new("wasi:filesystem", "readFile")),
                )
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("BinaryWriter")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_backing(HostTarget::new("wasi:filesystem", "writeFile")),
                )
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StreamReader")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.stream_reader_new"),
                )
                .with_method(MethodDef::new(
                    "EndOfStream",
                    0,
                    MethodBody::Common("dotnet.stream_reader_at_end".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadLine",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadToEnd",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StreamWriter")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.stream_writer_new"),
                )
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write_line".into()),
                ))
                .with_method(MethodDef::new(
                    "Flush",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_writer_flush".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StringReader")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.string_reader_new"),
                )
                .with_method(MethodDef::new(
                    "Peek",
                    0,
                    MethodBody::Common("dotnet.string_reader_peek".into()),
                ))
                .with_method(MethodDef::new(
                    "Read",
                    0,
                    MethodBody::Common("dotnet.string_reader_read".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadLine",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadLineAsync",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ReadToEnd",
                    0,
                    MethodBody::Common("dotnet.stream_reader_read_to_end".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.stream_reader_close".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("StringWriter")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.string_writer_new"),
                )
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.string_writer_new"),
                )
                .with_method(MethodDef::new(
                    "Write",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write".into()),
                ))
                .with_method(MethodDef::new(
                    "WriteLine",
                    1,
                    MethodBody::Common("dotnet.stream_writer_write_line".into()),
                ))
                .with_method(MethodDef::new(
                    "ToString",
                    0,
                    MethodBody::Common("dotnet.string_writer_to_string".into()),
                ))
                .with_method(MethodDef::new(
                    "Flush",
                    0,
                    MethodBody::Common("dotnet.string_writer_noop".into()),
                ))
                .with_method(MethodDef::new(
                    "Close",
                    0,
                    MethodBody::Common("dotnet.string_writer_noop".into()),
                ))
                .with_method(MethodDef::new(
                    "Dispose",
                    0,
                    MethodBody::Common("dotnet.string_writer_noop".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("File")
                .with_method(MethodDef::static_method(
                    "ReadAllText",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "readFile")),
                ))
                .with_method(MethodDef::static_method(
                    "WriteAllText",
                    2,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "writeFile")),
                ))
                .with_method(MethodDef::static_method(
                    "AppendAllText",
                    2,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "appendFile")),
                ))
                .with_method(MethodDef::static_method(
                    "Exists",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "exists")),
                ))
                .with_method(MethodDef::static_method(
                    "Delete",
                    1,
                    MethodBody::Common("dotnet.directory_delete".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Delete",
                    2,
                    MethodBody::Common("dotnet.directory_delete".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Copy",
                    2,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "copy")),
                ))
                .with_method(MethodDef::static_method(
                    "Move",
                    2,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "rename")),
                ))
                .with_method(MethodDef::static_method(
                    "ReadAllLines",
                    1,
                    MethodBody::Common("dotnet.file_read_all_lines".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("Directory")
                .with_method(MethodDef::static_method(
                    "Exists",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "isDir")),
                ))
                .with_method(MethodDef::static_method(
                    "CreateDirectory",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "mkdir")),
                ))
                .with_method(MethodDef::static_method(
                    "Delete",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "remove")),
                ))
                .with_method(MethodDef::static_method(
                    "GetFiles",
                    1,
                    MethodBody::Common("dotnet.directory_get_files".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetDirectories",
                    1,
                    MethodBody::Common("dotnet.directory_get_directories".into()),
                ))
                .with_method(MethodDef::static_method(
                    "GetCurrentDirectory",
                    0,
                    MethodBody::HostCall(HostTarget::new("node:process", "cwd")),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.IO",
            ClassType::new("Path")
                .with_method(MethodDef::static_method(
                    "Combine",
                    2,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathCombine")),
                ))
                .with_method(MethodDef::static_method(
                    "GetFileName",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathGetFileName")),
                ))
                .with_method(MethodDef::static_method(
                    "GetExtension",
                    1,
                    MethodBody::HostCall(HostTarget::new("node:path", "extname")),
                ))
                .with_method(MethodDef::static_method(
                    "GetDirectoryName",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathGetDirectory")),
                ))
                .with_method(MethodDef::static_method(
                    "GetFileNameWithoutExtension",
                    1,
                    MethodBody::HostCall(HostTarget::new(
                        "wasi:filesystem",
                        "pathGetFileNameWithoutExt",
                    )),
                ))
                .with_method(MethodDef::static_method(
                    "ChangeExtension",
                    2,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathChangeExtension")),
                ))
                .with_method(MethodDef::static_method(
                    "GetFullPath",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathGetFullPath")),
                ))
                .with_method(MethodDef::static_method(
                    "GetTempPath",
                    0,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathGetTempPath")),
                ))
                .with_method(MethodDef::static_method(
                    "HasExtension",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathHasExtension")),
                ))
                .with_method(MethodDef::static_method(
                    "IsPathRooted",
                    1,
                    MethodBody::HostCall(HostTarget::new("wasi:filesystem", "pathIsRooted")),
                )),
        ),
    ]
}
