use super::super::super::class_exports::DotnetClassExport;
use vybe_compiler::component_classes::{
    ClassType, ConstructorDef, MethodBody, MethodDef, PropertyDef,
};

pub(super) fn exports() -> Vec<DotnetClassExport> {
    vec![
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("PSSerializer")
                .with_parent("Object")
                .with_method(MethodDef::static_method(
                    "Serialize",
                    1,
                    MethodBody::Common("dotnet.psserializer_serialize".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Deserialize",
                    1,
                    MethodBody::Common("dotnet.psserializer_deserialize".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ErrorRecord")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(4).with_common_backing("dotnet.error_record_new"),
                )
                .with_field("Exception")
                .with_field("exception")
                .with_field("Message")
                .with_field("message")
                .with_field("FullyQualifiedErrorId")
                .with_field("fullyqualifiederrorid")
                .with_field("TargetObject")
                .with_field("targetobject")
                .with_field("CategoryInfo")
                .with_field("categoryinfo")
                .with_field("ErrorDetails")
                .with_field("errordetails")
                .with_field("InvocationInfo")
                .with_field("invocationinfo")
                .with_field("ScriptStackTrace")
                .with_field("scriptstacktrace"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("DebugRecord")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.debug_record_new"),
                )
                .with_field("Message")
                .with_field("message")
                .with_field("InvocationInfo")
                .with_field("invocationinfo"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("WarningRecord")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.warning_record_new"),
                )
                .with_field("Message")
                .with_field("message")
                .with_field("InvocationInfo")
                .with_field("invocationinfo"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("InformationRecord")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(2).with_common_backing("dotnet.information_record_new"),
                )
                .with_field("MessageData")
                .with_field("messagedata")
                .with_field("Source")
                .with_field("source")
                .with_field("Tags")
                .with_field("tags")
                .with_field("TimeGenerated")
                .with_field("timegenerated")
                .with_field("Computer")
                .with_field("computer")
                .with_field("InvocationInfo")
                .with_field("invocationinfo"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ErrorCategoryInfo")
                .with_parent("Object")
                .with_field("Category")
                .with_field("category")
                .with_field("Reason")
                .with_field("reason")
                .with_field("Activity")
                .with_field("activity")
                .with_field("TargetName")
                .with_field("targetname")
                .with_field("TargetType")
                .with_field("targettype"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ErrorCategory")
                .with_parent("Object")
                .with_method(MethodDef::static_method(
                    "AuthenticationError",
                    0,
                    MethodBody::Common("dotnet.error_category_authentication_error".into()),
                ))
                .with_method(MethodDef::static_method(
                    "ConnectionError",
                    0,
                    MethodBody::Common("dotnet.error_category_connection_error".into()),
                ))
                .with_method(MethodDef::static_method(
                    "DeviceError",
                    0,
                    MethodBody::Common("dotnet.error_category_device_error".into()),
                ))
                .with_method(MethodDef::static_method(
                    "InvalidOperation",
                    0,
                    MethodBody::Common("dotnet.error_category_invalid_operation".into()),
                ))
                .with_method(MethodDef::static_method(
                    "PermissionDenied",
                    0,
                    MethodBody::Common("dotnet.error_category_permission_denied".into()),
                ))
                .with_method(MethodDef::static_method(
                    "SyntaxError",
                    0,
                    MethodBody::Common("dotnet.error_category_syntax_error".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WriteError",
                    0,
                    MethodBody::Common("dotnet.error_category_write_error".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ShouldProcessReason")
                .with_parent("Object")
                .with_method(MethodDef::static_method(
                    "None",
                    0,
                    MethodBody::Common("dotnet.should_process_reason_none".into()),
                ))
                .with_method(MethodDef::static_method(
                    "WhatIf",
                    0,
                    MethodBody::Common("dotnet.should_process_reason_whatif".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ConfirmImpact")
                .with_parent("Object")
                .with_method(MethodDef::static_method(
                    "None",
                    0,
                    MethodBody::Common("dotnet.confirm_impact_none".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Low",
                    0,
                    MethodBody::Common("dotnet.confirm_impact_low".into()),
                ))
                .with_method(MethodDef::static_method(
                    "Medium",
                    0,
                    MethodBody::Common("dotnet.confirm_impact_medium".into()),
                ))
                .with_method(MethodDef::static_method(
                    "High",
                    0,
                    MethodBody::Common("dotnet.confirm_impact_high".into()),
                )),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("CmdletBindingAttribute")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(0)
                        .with_common_backing("dotnet.cmdlet_binding_attribute_new"),
                )
                .with_property(PropertyDef::new("SupportsShouldProcess"))
                .with_property(PropertyDef::new("SupportsTransactions"))
                .with_property(PropertyDef::new("SupportsPaging"))
                .with_property(PropertyDef::new("ConfirmImpact"))
                .with_property(PropertyDef::new("DefaultParameterSetName"))
                .with_property(PropertyDef::new("HelpUri"))
                .with_field("SupportsShouldProcess")
                .with_field("supportsshouldprocess")
                .with_field("SupportsTransactions")
                .with_field("supportstransactions")
                .with_field("SupportsPaging")
                .with_field("supportspaging")
                .with_field("ConfirmImpact")
                .with_field("confirmimpact")
                .with_field("DefaultParameterSetName")
                .with_field("defaultparametersetname")
                .with_field("HelpUri")
                .with_field("helpuri"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ParameterAttribute")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.parameter_attribute_new"),
                )
                .with_property(PropertyDef::new("Mandatory"))
                .with_property(PropertyDef::new("ValueFromPipeline"))
                .with_property(PropertyDef::new("ValueFromPipelineByPropertyName"))
                .with_property(PropertyDef::new("Position"))
                .with_property(PropertyDef::new("ParameterSetName"))
                .with_field("Mandatory")
                .with_field("mandatory")
                .with_field("ValueFromPipeline")
                .with_field("valuefrompipeline")
                .with_field("ValueFromPipelineByPropertyName")
                .with_field("valuefrompipelinebypropertyname")
                .with_field("Position")
                .with_field("position")
                .with_field("ParameterSetName")
                .with_field("parametersetname"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("RuntimeDefinedParameter")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(3)
                        .with_common_backing("dotnet.runtime_defined_parameter_new"),
                )
                .with_field("Name")
                .with_field("name")
                .with_field("ParameterType")
                .with_field("parametertype")
                .with_field("Attributes")
                .with_field("attributes"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("RuntimeDefinedParameterDictionary")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(0)
                        .with_common_backing("dotnet.runtime_defined_parameter_dictionary_new"),
                ),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("InvocationInfo")
                .with_parent("Object")
                .with_field("MyCommand")
                .with_field("mycommand")
                .with_field("Line")
                .with_field("line"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("CommandInfo")
                .with_parent("Object")
                .with_field("Name")
                .with_field("name"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ErrorDetails")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.error_details_new"),
                )
                .with_field("Message")
                .with_field("message")
                .with_field("RecommendedAction")
                .with_field("recommendedaction"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ActionPreferenceStopException")
                .with_parent("Exception")
                .with_constructor(
                    ConstructorDef::new(1)
                        .with_common_backing("dotnet.action_preference_stop_exception_new"),
                )
                .with_field("ErrorRecord")
                .with_field("errorrecord"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("PathInfo")
                .with_parent("Object")
                .with_field("Path")
                .with_field("path")
                .with_field("ProviderPath")
                .with_field("providerpath")
                .with_field("Provider")
                .with_field("provider")
                .with_field("Drive")
                .with_field("drive"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("PSDriveInfo")
                .with_parent("Object")
                .with_field("Name")
                .with_field("name")
                .with_field("Root")
                .with_field("root")
                .with_field("Provider")
                .with_field("provider"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("PSCustomObject")
                .with_parent("Object")
                .with_constructor(
                    ConstructorDef::new(0).with_common_backing("dotnet.pscustomobject_new"),
                )
                .with_constructor(
                    ConstructorDef::new(1).with_common_backing("dotnet.pscustomobject_new"),
                ),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ItemNotFoundException").with_parent("Exception"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Management.Automation",
            ClassType::new("ParameterBindingException").with_parent("Exception"),
        ),
        DotnetClassExport::new(
            "dotnet.Microsoft.PowerShell.Commands",
            ClassType::new("MatchInfo").with_parent("Object"),
        ),
        DotnetClassExport::new(
            "dotnet.Microsoft.PowerShell.MarkdownRender",
            ClassType::new("MarkdownInfo").with_parent("Object"),
        ),
        DotnetClassExport::new(
            "dotnet.Markdig.Syntax",
            ClassType::new("ParagraphBlock").with_parent("Object"),
        ),
        DotnetClassExport::new(
            "dotnet.Markdig.Syntax",
            ClassType::new("HeadingBlock").with_parent("Object"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.RegularExpressions",
            ClassType::new("Match")
                .with_parent("Object")
                .with_field("Value")
                .with_field("value")
                .with_field("Success")
                .with_field("success")
                .with_field("Index")
                .with_field("index")
                .with_field("Length")
                .with_field("length")
                .with_field("Groups")
                .with_field("groups")
                .with_field("__groups")
                .with_field("__group_values"),
        ),
        DotnetClassExport::new(
            "dotnet.System.Text.RegularExpressions",
            ClassType::new("Group")
                .with_parent("Object")
                .with_field("Value")
                .with_field("value")
                .with_field("Success")
                .with_field("success")
                .with_field("Length")
                .with_field("length")
                .with_field("Captures")
                .with_field("captures"),
        ),
    ]
}
