//! Deterministic, build-time generation of static parser programs.
//! Generated programs require only vybe_parser at runtime, not this crate.
use std::fmt::Write;
pub use vybe_parser::modules::{Import, Module, ModuleDiagnostic};
use vybe_parser::{
    CompiledGrammar, Diagnostic,
    program::{Instruction, Program},
};

pub fn generate_modules(modules: &[Module<'_>]) -> Result<String, Vec<ModuleDiagnostic>> {
    let linked = vybe_parser::modules::compile(modules)?;
    emit(linked.grammar()).map_err(|errors| {
        errors
            .into_iter()
            .map(|error| ModuleDiagnostic {
                code: error.code,
                message: error.message,
                location: linked.location(error.span),
                related: error
                    .related
                    .into_iter()
                    .map(|(span, message)| (linked.location(span), message))
                    .collect(),
            })
            .collect()
    })
}

/// Emit a self-contained Rust module body with `Parser` and typed `Rule`.
/// Grammar validation happens before emission. The generated backend currently
/// shares the iterative matching engine; it eliminates runtime grammar loading,
/// resolution and owned grammar data, rather than specializing every matcher.
pub fn generate(source: &str) -> Result<String, Vec<Diagnostic>> {
    let grammar = vybe_parser::compile(source)?;
    emit(&grammar)
}

pub fn emit(grammar: &CompiledGrammar) -> Result<String, Vec<Diagnostic>> {
    if !grammar.analysis().errors.is_empty() {
        return Err(grammar.analysis().errors.clone());
    }
    let errors: Vec<_> = grammar
        .syntax()
        .rules
        .iter()
        .filter(|rule| {
            matches!(
                rule.name.as_str(),
                "self" | "Self" | "super" | "crate" | "_"
            )
        })
        .map(|rule| {
            Diagnostic::new(
                "G013",
                "rule name cannot be represented as a Rust identifier",
                rule.name_span,
            )
        })
        .collect();
    if !errors.is_empty() {
        return Err(errors);
    }
    let mut out = String::from(
        "// Generated by vybe_parser_codegen. Do not edit.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n#[allow(non_camel_case_types)]\npub enum Rule {\n",
    );
    for rule in &grammar.syntax().rules {
        writeln!(out, "    r#{},", rule.name).unwrap();
    }
    let synthetic_eoi = grammar.rule_id("EOI").is_none();
    if synthetic_eoi {
        out.push_str("    EOI,\n");
    }
    out.push_str("}\nimpl Rule {\n    pub fn name(self) -> &'static str { match self {\n");
    for rule in &grammar.syntax().rules {
        writeln!(out, "        Self::r#{} => {:?},", rule.name, rule.name).unwrap();
    }
    if synthetic_eoi {
        out.push_str("        Self::EOI => \"EOI\",\n");
    }
    out.push_str("    }}\n    pub fn from_capture(rule: ::vybe_parser::CaptureRule) -> Option<Self> { match rule {\n");
    for (id, rule) in grammar.syntax().rules.iter().enumerate() {
        writeln!(
            out,
            "        ::vybe_parser::CaptureRule::User({id}) => Some(Self::r#{}),",
            rule.name
        )
        .unwrap();
    }
    out.push_str("        ::vybe_parser::CaptureRule::EndOfInput => Some(Self::EOI),\n");
    out.push_str("        _ => None,\n    }}\n}\n#[derive(Debug, Clone, Copy, Default)]\npub struct Parser;\nimpl ::vybe_parser::program::Program for Parser {\n    fn rule_id(&self, name: &str) -> Option<usize> { match name {\n");
    let mut entries: Vec<_> = grammar.entries().collect();
    entries.sort_unstable_by_key(|(name, _)| *name);
    for (name, id) in entries {
        writeln!(out, "        {name:?} => Some({id}),").unwrap();
    }
    out.push_str("        _ => None,\n    }}\n");
    if let Some(class) = grammar.whitespace_class() {
        writeln!(out, "    fn whitespace_class(&self) -> Option<::vybe_parser::lexical::ByteClass> {{ Some(::vybe_parser::lexical::ByteClass({:?})) }}", class.0).unwrap();
    }
    if let Some(class) = grammar.whitespace_prefix_class() {
        writeln!(out, "    fn whitespace_prefix_class(&self) -> Option<::vybe_parser::lexical::ByteClass> {{ Some(::vybe_parser::lexical::ByteClass({:?})) }}", class.0).unwrap();
    }
    out.push_str("    fn scope(&self, id: usize) -> ::vybe_parser::program::Scope { SCOPES[id] }\n    #[inline]\n    fn rule(&self, id: usize) -> ::vybe_parser::program::RuleSpec<'_> { RULES[id] }\n    #[inline]\n    fn instruction(&self, id: usize) -> ::vybe_parser::program::Instruction<'_> { INSTRUCTIONS[id] }\n}\n");
    writeln!(
        out,
        "static RULES: [::vybe_parser::program::RuleSpec<'static>; {}] = [",
        grammar.syntax().rules.len()
    )
    .unwrap();
    for (id, rule) in grammar.syntax().rules.iter().enumerate() {
        writeln!(out, "    ::vybe_parser::program::RuleSpec {{ name: {:?}, mode: ::vybe_parser::RuleMode::{:?}, expression: {}, scope: {} }},", rule.name, rule.mode, rule.expression, grammar.rule(id).scope).unwrap();
    }
    out.push_str("];\n");
    writeln!(
        out,
        "static SCOPES: [::vybe_parser::program::Scope; {}] = [",
        grammar.scopes().len()
    )
    .unwrap();
    for scope in grammar.scopes() {
        writeln!(out, "    ::vybe_parser::program::Scope {{ whitespace: {:?}, comment: {:?}, whitespace_class: {}, whitespace_prefix_class: {} }},", scope.whitespace, scope.comment, byte_class(scope.whitespace_class), byte_class(scope.whitespace_prefix_class)).unwrap();
    }
    out.push_str("];\n");
    writeln!(
        out,
        "static INSTRUCTIONS: [::vybe_parser::program::Instruction<'static>; {}] = {{",
        grammar.syntax().expressions.len()
    )
    .unwrap();
    out.push_str("    use ::vybe_parser::program::Instruction::*;\n    [\n");
    for id in 0..grammar.syntax().expressions.len() {
        writeln!(out, "        {},", instruction(grammar.instruction(id))).unwrap();
    }
    out.push_str("    ]\n};\nimpl Parser {\n    pub fn parse<'g, 'i>(&'g self, rule: Rule, input: &'i str) -> Result<::vybe_parser::ParseTree<'g, 'i>, ::vybe_parser::ParseError> {\n        ::vybe_parser::engine::parse_program(self, rule.name(), input, ::vybe_parser::MatchOptions::default())\n    }\n    pub fn recognize(&self, rule: Rule, input: &str) -> Result<::vybe_parser::Recognition, ::vybe_parser::ParseError> {\n        ::vybe_parser::engine::recognize_program(self, rule.name(), input, ::vybe_parser::MatchOptions::default())\n    }\n}\n");
    out.push_str("impl ::vybe_parser::compat::RuleIdentity for Rule {\n    fn from_capture(capture: ::vybe_parser::CaptureRule) -> Option<Self> { Self::from_capture(capture) }\n}\nimpl Parser {\n    pub fn parse_pairs<'i>(&self, rule: Rule, input: &'i str) -> Result<::vybe_parser::compat::Pairs<'i, Rule>, ::vybe_parser::ParseError> {\n        self.parse(rule, input).map(|tree| tree.into_typed_pairs())\n    }\n}\n");
    Ok(out)
}

fn instruction(op: Instruction<'_>) -> String {
    match op {
        Instruction::Literal { text, insensitive } => {
            format!("Literal {{ text: {text:?}, insensitive: {insensitive} }}")
        }
        Instruction::Range { start, end } => format!("Range {{ start: {start:?}, end: {end:?} }}"),
        Instruction::Call(id) => format!("Call({id})"),
        Instruction::Builtin(builtin) => format!("Builtin(::vybe_parser::Builtin::{builtin:?})"),
        Instruction::Sequence { left, right } => {
            format!("Sequence {{ left: {left}, right: {right} }}")
        }
        Instruction::Choice { left, right } => format!("Choice {{ left: {left}, right: {right} }}"),
        Instruction::Repeat {
            expression,
            min,
            max,
        } => format!("Repeat {{ expression: {expression}, min: {min}, max: {max:?} }}"),
        Instruction::Predicate {
            expression,
            positive,
        } => format!("Predicate {{ expression: {expression}, positive: {positive} }}"),
        Instruction::Group(id) => format!("Group({id})"),
        Instruction::Push(id) => format!("Push({id})"),
        Instruction::PushLiteral(text) => format!("PushLiteral({text:?})"),
        Instruction::PeekSlice { start, end } => {
            format!("PeekSlice {{ start: {start}, end: {end:?} }}")
        }
    }
}

fn byte_class(class: Option<vybe_parser::lexical::ByteClass>) -> String {
    class.map_or_else(
        || "None".into(),
        |class| format!("Some(::vybe_parser::lexical::ByteClass({:?}))", class.0),
    )
}
