use super::helpers::compile_ok;
macro_rules! c { ($name:ident,$src:expr)=>{ #[test] fn $name(){ compile_ok($src); } }; }
c!(char_kind_01,"program p\ncharacter(kind=1,len=4) :: s\nprint *, s\nend program p\n");
c!(char_len_02,"program p\ncharacter(len=8) :: s\nprint *, s\nend program p\n");
c!(char_deferred_03,"program p\ncharacter(len=:), allocatable :: s\nallocate(character(len=3) :: s)\nend program p\n");
c!(char_assumed_04,"subroutine s(x)\ncharacter(len=*) :: x\nend subroutine s\n");
c!(char_assign_05,"program p\ncharacter(len=4) :: s\ns='ab'\nprint *, s\nend program p\n");
c!(char_compare_06,"program p\nlogical :: l\nl = 'a' < 'b'\nprint *, l\nend program p\n");
c!(char_substring_07,"program p\ncharacter(len=5) :: s='hello'\nprint *, s(2:4)\nend program p\n");
c!(char_padding_08,"program p\ncharacter(len=5) :: s\ns='a'\nprint *, s\nend program p\n");
c!(char_blank_interp_09,"program p\ncharacter(len=3) :: s='a b'\nprint *, s\nend program p\n");
c!(char_collation_10,"program p\nlogical :: l\nl = 'a' <= 'b'\nprint *, l\nend program p\n");
c!(char_concat_11,"program p\ncharacter(len=4) :: s\ns='ab'//'cd'\nprint *, s\nend program p\n");
c!(char_trim_12,"program p\ncharacter(len=5) :: s='a   '\nprint *, trim(s)\nend program p\n");
c!(char_adjustl_13,"program p\ncharacter(len=5) :: s='  a  '\nprint *, adjustl(s)\nend program p\n");
c!(char_adjustr_14,"program p\ncharacter(len=5) :: s='a    '\nprint *, adjustr(s)\nend program p\n");
c!(char_repeat_15,"program p\nprint *, repeat('x',3)\nend program p\n");
c!(char_scan_16,"program p\nprint *, scan('abc123','0123456789')\nend program p\n");
c!(char_verify_17,"program p\nprint *, verify('abc','abc')\nend program p\n");
c!(char_index_18,"program p\nprint *, index('fortran','tran')\nend program p\n");
c!(char_len_trim_19,"program p\ncharacter(len=6) :: s='ab    '\nprint *, len_trim(s)\nend program p\n");
c!(char_achar_20,"program p\nprint *, achar(65)\nend program p\n");
c!(char_ichar_21,"program p\nprint *, ichar('A')\nend program p\n");
c!(char_char_22,"program p\nprint *, char(65)\nend program p\n");
c!(char_newline_23,"program p\ncharacter(len=1) :: c\nc = achar(10)\nprint *, ichar(c)\nend program p\n");
c!(char_array_24,"program p\ncharacter(len=3) :: a(2)\na = ['abc','def']\nprint *, a\nend program p\n");
c!(char_section_25,"program p\ncharacter(len=5) :: s='hello'\nprint *, s(:3)\nend program p\n");
c!(char_rhs_expr_26,"program p\ncharacter(len=6) :: s\ns = adjustl('  ab')\nprint *, s\nend program p\n");
c!(char_lhs_sub_27,"program p\ncharacter(len=5) :: s='hello'\ns(1:1)='H'\nprint *, s\nend program p\n");
c!(char_format_write_28,"program p\ncharacter(len=5) :: s='abc'\nwrite(*,'(A)') s\nend program p\n");
c!(char_internal_io_29,"program p\ncharacter(len=20) :: buf\nwrite(buf,'(A)') 'abc'\nprint *, trim(buf)\nend program p\n");
c!(char_case_compare_30,"program p\nlogical :: l\nl = 'A' /= 'a'\nprint *, l\nend program p\n");