use super::helpers::compile_ok;
macro_rules! c { ($name:ident,$src:expr)=>{ #[test] fn $name(){ compile_ok($src); } }; }
c!(alloc_stmt_01,"program p\ninteger, allocatable :: a(:)\nallocate(a(3))\nend program p\n");
c!(dealloc_stmt_02,"program p\ninteger, allocatable :: a(:)\nallocate(a(3))\ndeallocate(a)\nend program p\n");
c!(alloc_stat_03,"program p\ninteger, allocatable :: a(:)\ninteger :: st\nallocate(a(3), stat=st)\nend program p\n");
c!(alloc_source_04,"program p\ninteger, allocatable :: a(:)\nallocate(a(3), source=[1,2,3])\nend program p\n");
c!(alloc_mold_05,"program p\ninteger, allocatable :: a(:), b(:)\nallocate(b(3))\nallocate(a, mold=b)\nend program p\n");
c!(move_alloc_06,"program p\ninteger, allocatable :: a(:), b(:)\nallocate(a(3))\ncall move_alloc(a,b)\nend program p\n");
c!(auto_obj_07,"subroutine s(n)\ninteger :: n\nreal :: a(n)\nend subroutine s\n");
c!(alloc_comp_08,"type :: t\ninteger, allocatable :: a(:)\nend type t\nprogram p\ntype(t)::x\nallocate(x%a(3))\nend program p\n");
c!(deferred_shape_09,"program p\ninteger, allocatable :: a(:,:)\nallocate(a(2,2))\nend program p\n");
c!(assumed_shape_10,"subroutine s(a)\ninteger :: a(:)\nend subroutine s\n");
c!(assumed_rank_11,"subroutine s(a)\ninteger :: a(..)\nend subroutine s\n");
c!(assumed_type_12,"subroutine s(x)\ntype(*) :: x\nend subroutine s\n");
c!(explicit_shape_13,"subroutine s(a)\ninteger :: a(3)\nend subroutine s\n");
c!(deferred_len_char_14,"program p\ncharacter(len=:), allocatable :: s\nallocate(character(len=3) :: s)\nend program p\n");
c!(allocate_scalar_15,"program p\ninteger, allocatable :: x\nallocate(x)\nend program p\n");
c!(dealloc_scalar_16,"program p\ninteger, allocatable :: x\nallocate(x)\ndeallocate(x)\nend program p\n");
c!(alloc_class_17,"type :: t\ninteger::x\nend type t\nprogram p\nclass(t), allocatable :: obj\nallocate(obj)\nend program p\n");
c!(alloc_ptr_target_18,"program p\ninteger, pointer :: p(:)\nallocate(p(3))\nend program p\n");
c!(alloc_char_array_19,"program p\ncharacter(len=4), allocatable :: a(:)\nallocate(a(2))\nend program p\n");
c!(alloc_real_2d_20,"program p\nreal, allocatable :: a(:,:)\nallocate(a(3,4))\nend program p\n");
c!(alloc_logical_21,"program p\nlogical, allocatable :: a(:)\nallocate(a(2))\nend program p\n");
c!(alloc_complex_22,"program p\ncomplex, allocatable :: a(:)\nallocate(a(2))\nend program p\n");
c!(alloc_with_source_scalar_23,"program p\ninteger, allocatable :: x\nallocate(x, source=5)\nend program p\n");
c!(alloc_with_stat_dealloc_24,"program p\ninteger, allocatable :: a(:)\ninteger :: st\nallocate(a(2), stat=st)\ndeallocate(a, stat=st)\nend program p\n");
c!(alloc_nested_comp_25,"type :: t\ninteger, allocatable :: a(:)\nend type t\nprogram p\ntype(t), allocatable :: x\nallocate(x)\nallocate(x%a(2))\nend program p\n");
c!(alloc_default_init_26,"type :: t\ninteger :: x=1\nend type t\nprogram p\ntype(t), allocatable :: a(:)\nallocate(a(2))\nend program p\n");
c!(alloc_rank3_27,"program p\ninteger, allocatable :: a(:,:,:)\nallocate(a(2,2,2))\nend program p\n");
c!(alloc_mold_scalar_28,"program p\ninteger, allocatable :: a,b\nallocate(b)\nallocate(a, mold=b)\nend program p\n");
c!(alloc_source_char_29,"program p\ncharacter(len=:), allocatable :: s\nallocate(character(len=4) :: s)\ns='test'\nend program p\n");
c!(alloc_nullify_ptr_30,"program p\ninteger, pointer :: p(:)\nnullify(p)\nend program p\n");