[package]
name = "vybe_language_pascal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vybe_language_pascal"

[dependencies]
vybe_compiler = { workspace = true }
inventory = { workspace = true }
vybe_ast = { workspace = true }
vybe_runtime = { workspace = true }
vybe_platform_vybe = { workspace = true, features = ["gui"] }
pest = { workspace = true }
pest_derive = { workspace = true }
vybe_platform_plib = { workspace = true }

[dev-dependencies]
vybe_compiler = { workspace = true }
vybe_runtime = { workspace = true }
vybe_ast = { workspace = true }

[[test]]
name = "pascal"
path = "tests/pascal/main.rs"
