//! Force-link every plugin crate in `[dependencies]` so its link-time
//! registration reaches the registry. Generated from Cargo.toml.
//!
//! `inventory` collects plugins from linker sections, but Rust drops an rlib
//! that nothing references — so a plugin crate listed only in `[dependencies]`
//! never reaches the registry. This emits one `extern crate` per plugin
//! dependency, read straight from Cargo.toml.
//!
//! The point is that there is no plugin list in code. Adding a plugin is a
//! Cargo edit and nothing else; this file never names one.

use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");
    let manifest = std::fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let mut out = String::from("// @generated by build.rs — see its docs.\n");
    let mut in_deps = false;
    for line in manifest.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_deps = trimmed == "[dependencies]";
            continue;
        }
        if !in_deps {
            continue;
        }
        let Some(name) = trimmed.split(['=', ' ']).next() else {
            continue;
        };
        if name.starts_with("vybe_platform_") || name.starts_with("vybe_language_") {
            out.push_str(&format!("extern crate {name};\n"));
        }
    }
    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("linked_plugins.rs");
    let mut f = std::fs::File::create(dest).expect("create linked_plugins.rs");
    f.write_all(out.as_bytes()).expect("write linked_plugins.rs");
}
