pub mod menu_bar;
pub mod toolbar;
pub mod project_explorer;
pub mod toolbox_panel;
pub mod properties_panel;
pub mod form_designer;
pub mod code_editor;
pub mod status_bar;
pub mod project_properties;
