pub(crate) mod helpers;
mod test_compile_basics;
mod test_compile_builtins;
mod test_compile_classes;
mod test_compile_control;
mod test_compile_exceptions;
mod test_compile_functions;
mod test_compile_interop;
mod test_compile_programs;
mod test_new_features;
mod test_stdlib_modules;
