use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn sigaction_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\n#include <stdlib.h>\nvoid h(int s) { printf(\"act\"); exit(0); }\nint main() { struct sigaction sa; sa.sa_handler = h; sigemptyset(&sa.sa_mask); sa.sa_flags = 0; sigaction(SIGUSR1, &sa, NULL); raise(SIGUSR1); return 0; }"), vec!["act"]); }
#[test] fn sigemptyset_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; int r = sigemptyset(&s); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigfillset_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; int r = sigfillset(&s); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigaddset_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); int r = sigaddset(&s, SIGINT); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigdelset_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigfillset(&s); int r = sigdelset(&s, SIGINT); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigismember_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); sigaddset(&s, SIGINT); printf(\"%d %d\", sigismember(&s, SIGINT) == 1, sigismember(&s, SIGQUIT) == 0); return 0; }"), vec!["1 1"]); }
#[test] fn sigprocmask_block() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); sigaddset(&s, SIGUSR1); int r = sigprocmask(SIG_BLOCK, &s, NULL); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigprocmask_unblock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); sigaddset(&s, SIGUSR1); sigprocmask(SIG_BLOCK, &s, NULL); int r = sigprocmask(SIG_UNBLOCK, &s, NULL); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigprocmask_setmask() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); int r = sigprocmask(SIG_SETMASK, &s, NULL); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn sigpending_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); sigaddset(&s, SIGUSR1); sigprocmask(SIG_BLOCK, &s, NULL); raise(SIGUSR1); sigset_t p; sigpending(&p); printf(\"%d\", sigismember(&p, SIGUSR1) == 1); return 0; }"), vec!["1"]); }
#[test] fn sigsuspend_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\n#include <unistd.h>\nvoid h(int s) {}\nint main() { signal(SIGALRM, h); sigset_t s; sigemptyset(&s); alarm(1); sigsuspend(&s); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn sigaction_siginfo() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\n#include <stdlib.h>\nvoid h(int s, siginfo_t *info, void *ctx) { printf(\"info\"); exit(0); }\nint main() { struct sigaction sa; sa.sa_sigaction = h; sigemptyset(&sa.sa_mask); sa.sa_flags = SA_SIGINFO; sigaction(SIGUSR1, &sa, NULL); raise(SIGUSR1); return 0; }"), vec!["info"]); }
#[test] fn sigaction_ignore() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { struct sigaction sa; sa.sa_handler = SIG_IGN; sigemptyset(&sa.sa_mask); sa.sa_flags = 0; sigaction(SIGUSR1, &sa, NULL); raise(SIGUSR1); printf(\"ignored\"); return 0; }"), vec!["ignored"]); }
#[test] fn sigaction_old_action() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nvoid h(int s) {}\nint main() { struct sigaction sa, old; sa.sa_handler = h; sigemptyset(&sa.sa_mask); sa.sa_flags = 0; sigaction(SIGUSR1, &sa, NULL); sigaction(SIGUSR1, NULL, &old); printf(\"%d\", old.sa_handler == h); return 0; }"), vec!["1"]); }
#[test] fn sigaction_resethand() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\n#include <stdlib.h>\nint count = 0;\nvoid h(int s) { count++; if(count==2) exit(0); }\nint main() { struct sigaction sa; sa.sa_handler = h; sigemptyset(&sa.sa_mask); sa.sa_flags = SA_RESETHAND; sigaction(SIGUSR1, &sa, NULL); raise(SIGUSR1); /* Second raise will terminate process because handler was reset to DFL */ printf(\"ok\"); return 0; }"), vec!["ok"]); } // the test survives the first raise, prints ok, second raise omitted to avoid crash exit
#[test] fn sigwait_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\n#include <unistd.h>\n#include <sys/wait.h>\nint main() { pid_t p = fork(); if (p==0) { sigset_t s; sigemptyset(&s); sigaddset(&s, SIGUSR1); sigprocmask(SIG_BLOCK, &s, NULL); int sig; sigwait(&s, &sig); printf(\"caught %d\", sig); _exit(0); } sleep(1); kill(p, SIGUSR1); wait(NULL); return 0; }"), vec!["caught 30", "caught 10", "caught 16"]); } // SIGUSR1 can be 10, 16, or 30 depending on OS. We just check output is there.
#[test] fn sigaction_nodefer() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { struct sigaction sa; sa.sa_handler = SIG_IGN; sigemptyset(&sa.sa_mask); sa.sa_flags = SA_NODEFER; sigaction(SIGUSR1, &sa, NULL); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn sigaction_restart() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { struct sigaction sa; sa.sa_handler = SIG_IGN; sigemptyset(&sa.sa_mask); sa.sa_flags = SA_RESTART; sigaction(SIGUSR1, &sa, NULL); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn sigaction_nocldstop() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { struct sigaction sa; sa.sa_handler = SIG_IGN; sigemptyset(&sa.sa_mask); sa.sa_flags = SA_NOCLDSTOP; sigaction(SIGCHLD, &sa, NULL); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn sigprocmask_invalid_how() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <signal.h>\nint main() { sigset_t s; sigemptyset(&s); int r = sigprocmask(99999, &s, NULL); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
