use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn remove_basic() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_remove.txt\", \"w\"); fclose(f); int r = remove(\"test_remove.txt\"); f = fopen(\"test_remove.txt\", \"r\"); printf(\"%d %d\", r == 0, f == NULL); return 0; }"), vec!["1 1"]); }
#[test] fn remove_nonexistent() { assert_eq!(run_c("int main() { int r = remove(\"test_remove_doesnotexist.txt\"); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn rename_basic() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_rename_src.txt\", \"w\"); fclose(f); int r = rename(\"test_rename_src.txt\", \"test_rename_dst.txt\"); FILE *f1 = fopen(\"test_rename_src.txt\", \"r\"); FILE *f2 = fopen(\"test_rename_dst.txt\", \"r\"); printf(\"%d %d %d\", r == 0, f1 == NULL, f2 != NULL); if(f2) fclose(f2); remove(\"test_rename_dst.txt\"); return 0; }"), vec!["1 1 1"]); }
#[test] fn rename_nonexistent_src() { assert_eq!(run_c("int main() { int r = rename(\"test_nonexist_src.txt\", \"test_dst.txt\"); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn rename_overwrite_dst() { assert_eq!(run_c("int main() { FILE *f1 = fopen(\"test_ren_src.txt\", \"w\"); fclose(f1); FILE *f2 = fopen(\"test_ren_dst.txt\", \"w\"); fclose(f2); int r = rename(\"test_ren_src.txt\", \"test_ren_dst.txt\"); printf(\"%d\", r == 0); remove(\"test_ren_dst.txt\"); return 0; }"), vec!["1"]); } // POSIX says it replaces dst silently
#[test] fn remove_open_file() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_rm_open.txt\", \"w\"); int r = remove(\"test_rm_open.txt\"); printf(\"%d\", r == 0 || r != 0); fclose(f); return 0; }"), vec!["1"]); } // Windows fails, POSIX succeeds. Both are "ok"
#[test] fn rename_open_file() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_ren_open.txt\", \"w\"); int r = rename(\"test_ren_open.txt\", \"test_ren_open2.txt\"); printf(\"%d\", r == 0 || r != 0); fclose(f); remove(\"test_ren_open2.txt\"); return 0; }"), vec!["1"]); } // Varies by OS
#[test] fn remove_directory() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { mkdir(\"test_rm_dir\", 0755); int r = remove(\"test_rm_dir\"); /* remove() handles empty dirs in POSIX */ printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rename_directory() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { mkdir(\"test_ren_dir1\", 0755); int r = rename(\"test_ren_dir1\", \"test_ren_dir2\"); printf(\"%d\", r == 0); remove(\"test_ren_dir2\"); return 0; }"), vec!["1"]); }
#[test] fn rename_dir_to_nonempty_dir() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { mkdir(\"test_ren_s\", 0755); mkdir(\"test_ren_d\", 0755); FILE *f = fopen(\"test_ren_d/file.txt\", \"w\"); fclose(f); int r = rename(\"test_ren_s\", \"test_ren_d\"); printf(\"%d\", r != 0); remove(\"test_ren_d/file.txt\"); remove(\"test_ren_s\"); remove(\"test_ren_d\"); return 0; }"), vec!["1"]); } // cannot rename over non-empty dir
#[test] fn rename_same_name() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_ren_same.txt\", \"w\"); fclose(f); int r = rename(\"test_ren_same.txt\", \"test_ren_same.txt\"); printf(\"%d\", r == 0); remove(\"test_ren_same.txt\"); return 0; }"), vec!["1"]); } // renaming to itself does nothing and succeeds
#[test] fn rename_file_to_dir() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { FILE *f = fopen(\"test_file.txt\", \"w\"); fclose(f); mkdir(\"test_dir\", 0755); int r = rename(\"test_file.txt\", \"test_dir\"); printf(\"%d\", r != 0); remove(\"test_file.txt\"); remove(\"test_dir\"); return 0; }"), vec!["1"]); } // cannot overwrite dir with file
#[test] fn rename_dir_to_file() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { FILE *f = fopen(\"test_file2.txt\", \"w\"); fclose(f); mkdir(\"test_dir2\", 0755); int r = rename(\"test_dir2\", \"test_file2.txt\"); printf(\"%d\", r != 0); remove(\"test_file2.txt\"); remove(\"test_dir2\"); return 0; }"), vec!["1"]); } // cannot overwrite file with dir
#[test] fn unlink_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <unistd.h>\nint main() { FILE *f = fopen(\"test_unlink.txt\", \"w\"); fclose(f); int r = unlink(\"test_unlink.txt\"); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn unlink_directory() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\nint main() { mkdir(\"test_ul_dir\", 0755); int r = unlink(\"test_ul_dir\"); printf(\"%d\", r != 0); remove(\"test_ul_dir\"); return 0; }"), vec!["1"]); } // unlink usually fails on dirs
#[test] fn rmdir_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\nint main() { mkdir(\"test_rmdir_d\", 0755); int r = rmdir(\"test_rmdir_d\"); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rmdir_file() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <unistd.h>\nint main() { FILE *f = fopen(\"test_rmdir_f.txt\", \"w\"); fclose(f); int r = rmdir(\"test_rmdir_f.txt\"); printf(\"%d\", r != 0); remove(\"test_rmdir_f.txt\"); return 0; }"), vec!["1"]); }
#[test] fn remove_long_name() { assert_eq!(run_c("int main() { char name[300]; for(int i=0; i<250; i++) name[i] = 'a'; name[250] = '\\0'; int r = remove(name); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn rename_cross_device() { assert_eq!(run_c("int main() { /* We can't strictly test EXDEV, but we can test invalid rename */ int r = rename(\"doesnotexist1\", \"doesnotexist2\"); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn rename_symlink() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <unistd.h>\nint main() { FILE *f = fopen(\"test_ren_sym.txt\", \"w\"); fclose(f); symlink(\"test_ren_sym.txt\", \"test_link\"); rename(\"test_link\", \"test_link2\"); int r = remove(\"test_link2\"); printf(\"%d\", r == 0); remove(\"test_ren_sym.txt\"); return 0; }"), vec!["1"]); } // renames the link itself, not target
