use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn mmap_anonymous_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, -1, 0); printf(\"%d\", p != MAP_FAILED); if(p != MAP_FAILED) munmap(p, 4096); return 0; }"), vec!["1"]); }
#[test] fn mmap_file_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_mmap.txt\", O_CREAT|O_RDWR, 0644); write(fd, \"abcd\", 4); void *p = mmap(NULL, 4, PROT_READ, MAP_PRIVATE, fd, 0); printf(\"%d %c\", p != MAP_FAILED, ((char*)p)[0]); munmap(p, 4); close(fd); unlink(\"test_mmap.txt\"); return 0; }"), vec!["1 a"]); }
#[test] fn mmap_write_shared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_mmap_sh.txt\", O_CREAT|O_RDWR, 0644); write(fd, \"abcd\", 4); void *p = mmap(NULL, 4, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0); ((char*)p)[1] = 'X'; msync(p, 4, MS_SYNC); munmap(p, 4); lseek(fd, 0, SEEK_SET); char b[5]={0}; read(fd, b, 4); printf(\"%s\", b); close(fd); unlink(\"test_mmap_sh.txt\"); return 0; }"), vec!["aXcd"]); }
#[test] fn mmap_write_private() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_mmap_pr.txt\", O_CREAT|O_RDWR, 0644); write(fd, \"abcd\", 4); void *p = mmap(NULL, 4, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0); ((char*)p)[1] = 'X'; munmap(p, 4); lseek(fd, 0, SEEK_SET); char b[5]={0}; read(fd, b, 4); printf(\"%s\", b); close(fd); unlink(\"test_mmap_pr.txt\"); return 0; }"), vec!["abcd"]); }
#[test] fn mmap_invalid_fd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 4096, PROT_READ, MAP_SHARED, -1, 0); printf(\"%d\", p == MAP_FAILED); return 0; }"), vec!["1"]); } // Needs fd if not ANON
#[test] fn mmap_zero_length() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 0, PROT_READ, MAP_PRIVATE|MAP_ANON, -1, 0); printf(\"%d\", p == MAP_FAILED); return 0; }"), vec!["1"]); } // Length 0 is error
#[test] fn munmap_invalid() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { int r = munmap((void*)-1, 4096); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn mprotect_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, -1, 0); int r = mprotect(p, 4096, PROT_READ); printf(\"%d\", r == 0); munmap(p, 4096); return 0; }"), vec!["1"]); }
#[test] fn msync_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_msync.txt\", O_CREAT|O_RDWR, 0644); write(fd, \"abcd\", 4); void *p = mmap(NULL, 4, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0); int r = msync(p, 4, MS_ASYNC); printf(\"%d\", r == 0); munmap(p, 4); close(fd); unlink(\"test_msync.txt\"); return 0; }"), vec!["1"]); }
#[test] fn msync_invalid() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { int r = msync((void*)-1, 4096, MS_SYNC); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn mlock_munlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, -1, 0); int r1 = mlock(p, 4096); if(r1 == 0) munlock(p, 4096); /* May fail if not root or limits exceeded, we just check it compiles */ printf(\"ok\"); munmap(p, 4096); return 0; }"), vec!["ok"]); }
#[test] fn mlockall_munlockall() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { int r1 = mlockall(MCL_CURRENT); if(r1 == 0) munlockall(); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mmap_fixed() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p1 = mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, -1, 0); void *p2 = mmap(p1, 4096, PROT_READ, MAP_PRIVATE|MAP_ANON|MAP_FIXED, -1, 0); printf(\"%d\", p2 == p1 || p2 == MAP_FAILED); if(p1 != MAP_FAILED) munmap(p1, 8192); return 0; }"), vec!["1"]); }
#[test] fn madvise_compile() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, -1, 0); int r = madvise(p, 4096, MADV_NORMAL); printf(\"%d\", r == 0 || r != 0); munmap(p, 4096); return 0; }"), vec!["1"]); }
#[test] fn posix_madvise_compile() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANON, -1, 0); int r = posix_madvise(p, 4096, POSIX_MADV_NORMAL); printf(\"%d\", r == 0 || r != 0); munmap(p, 4096); return 0; }"), vec!["1"]); }
#[test] fn shm_open_unlink() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm\", O_CREAT|O_RDWR, 0644); printf(\"%d\", fd >= 0); if(fd >= 0) { close(fd); shm_unlink(\"/test_shm\"); } return 0; }"), vec!["1"]); }
#[test] fn mmap_read_only_file_write_prot() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_ro.txt\", O_CREAT|O_RDONLY, 0644); void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0); printf(\"%d\", p == MAP_FAILED); close(fd); unlink(\"test_ro.txt\"); return 0; }"), vec!["1"]); } // Can't PROT_WRITE on MAP_SHARED if fd is O_RDONLY
#[test] fn mmap_read_only_file_private_write_prot() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_ro2.txt\", O_CREAT|O_RDONLY, 0644); void *p = mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE, fd, 0); printf(\"%d\", p != MAP_FAILED); if(p != MAP_FAILED) munmap(p, 4096); close(fd); unlink(\"test_ro2.txt\"); return 0; }"), vec!["1"]); } // Allowed because MAP_PRIVATE means writes don't go to fd
#[test] fn mmap_offset() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { long ps = sysconf(_SC_PAGESIZE); int fd = open(\"test_off.txt\", O_CREAT|O_RDWR, 0644); lseek(fd, ps + 4, SEEK_SET); write(fd, \"x\", 1); void *p = mmap(NULL, 4, PROT_READ, MAP_PRIVATE, fd, ps); printf(\"%d\", p != MAP_FAILED); if(p != MAP_FAILED) munmap(p, 4); close(fd); unlink(\"test_off.txt\"); return 0; }"), vec!["1"]); } // offset must be multiple of page size
#[test] fn mprotect_invalid() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { int r = mprotect((void*)-1, 4096, PROT_READ); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
