use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn mutex_init_destroy() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutex_t m; int r1 = pthread_mutex_init(&m, NULL); int r2 = pthread_mutex_destroy(&m); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn mutex_lock_unlock() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_mutex_lock(&m); pthread_mutex_unlock(&m); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mutex_trylock_success() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; int r = pthread_mutex_trylock(&m); printf(\"%d\", r == 0); pthread_mutex_unlock(&m); return 0; }"), vec!["1"]); }
#[test] fn mutex_trylock_fail() { assert_eq!(run_c("#include <pthread.h>\n#include <errno.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_mutex_lock(&m); int r = pthread_mutex_trylock(&m); printf(\"%d\", r != 0); pthread_mutex_unlock(&m); return 0; }"), vec!["1"]); }
#[test] fn mutexattr_init_destroy() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; int r1 = pthread_mutexattr_init(&a); int r2 = pthread_mutexattr_destroy(&a); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn mutexattr_settype_recursive() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); pthread_mutexattr_settype(&a, PTHREAD_MUTEX_RECURSIVE); pthread_mutex_t m; pthread_mutex_init(&m, &a); pthread_mutex_lock(&m); pthread_mutex_lock(&m); pthread_mutex_unlock(&m); pthread_mutex_unlock(&m); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mutexattr_settype_errorcheck() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); pthread_mutexattr_settype(&a, PTHREAD_MUTEX_ERRORCHECK); pthread_mutex_t m; pthread_mutex_init(&m, &a); pthread_mutex_lock(&m); int r = pthread_mutex_lock(&m); printf(\"%d\", r != 0); pthread_mutex_unlock(&m); return 0; }"), vec!["1"]); }
#[test] fn mutexattr_gettype() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); pthread_mutexattr_settype(&a, PTHREAD_MUTEX_RECURSIVE); int type; pthread_mutexattr_gettype(&a, &type); printf(\"%d\", type == PTHREAD_MUTEX_RECURSIVE); return 0; }"), vec!["1"]); }
#[test] fn mutex_static_initializer() { assert_eq!(run_c("#include <pthread.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\nint main() { pthread_mutex_lock(&m); pthread_mutex_unlock(&m); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mutex_recursive_initializer_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <pthread.h>\npthread_mutex_t m = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;\nint main() { pthread_mutex_lock(&m); pthread_mutex_lock(&m); pthread_mutex_unlock(&m); pthread_mutex_unlock(&m); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mutex_errorcheck_initializer_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <pthread.h>\npthread_mutex_t m = PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP;\nint main() { pthread_mutex_lock(&m); int r = pthread_mutex_lock(&m); printf(\"%d\", r != 0); pthread_mutex_unlock(&m); return 0; }"), vec!["1"]); }
#[test] fn mutexattr_setpshared() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); int r = pthread_mutexattr_setpshared(&a, PTHREAD_PROCESS_SHARED); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn mutexattr_getpshared() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); pthread_mutexattr_setpshared(&a, PTHREAD_PROCESS_SHARED); int s; pthread_mutexattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_SHARED); return 0; }"), vec!["1"]); }
#[test] fn mutexattr_setprotocol() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); int r = pthread_mutexattr_setprotocol(&a, PTHREAD_PRIO_INHERIT); /* May not be supported everywhere, so test execution completeness */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mutex_unlock_unlocked_errorcheck() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); pthread_mutexattr_settype(&a, PTHREAD_MUTEX_ERRORCHECK); pthread_mutex_t m; pthread_mutex_init(&m, &a); int r = pthread_mutex_unlock(&m); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn mutex_lock_different_threads() { assert_eq!(run_c("#include <pthread.h>\n#include <unistd.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\nint val = 0;\nvoid* f(void* a) { pthread_mutex_lock(&m); val = 2; pthread_mutex_unlock(&m); return NULL; }\nint main() { pthread_mutex_lock(&m); pthread_t t; pthread_create(&t, NULL, f, NULL); sleep(1); val = 1; pthread_mutex_unlock(&m); pthread_join(t, NULL); printf(\"%d\", val); return 0; }"), vec!["2"]); }
#[test] fn mutex_timedlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <time.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; struct timespec ts; clock_gettime(CLOCK_REALTIME, &ts); ts.tv_sec += 1; int r = pthread_mutex_timedlock(&m, &ts); printf(\"%d\", r == 0); pthread_mutex_unlock(&m); return 0; }"), vec!["1"]); }
#[test] fn mutex_timedlock_timeout() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <time.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_mutex_lock(&m); struct timespec ts; clock_gettime(CLOCK_REALTIME, &ts); ts.tv_nsec += 50000000; if(ts.tv_nsec >= 1000000000) { ts.tv_sec++; ts.tv_nsec -= 1000000000; } int r = pthread_mutex_timedlock(&m, &ts); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn mutex_destroy_locked() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_mutex_lock(&m); int r = pthread_mutex_destroy(&m); /* Destroying locked mutex is UB, check it compiles and runs without crash */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn mutexattr_setrobust() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_mutexattr_t a; pthread_mutexattr_init(&a); int r = pthread_mutexattr_setrobust(&a, PTHREAD_MUTEX_ROBUST); printf(\"%d\", r == 0 || r != 0); return 0; }"), vec!["1"]); } // May fail if unsupported, but valid C
