use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn dlopen_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY); if(!h) h = dlopen(\"libm.so\", RTLD_LAZY); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY); printf(\"%d\", h != NULL); if(h) dlclose(h); return 0; }"), vec!["1"]); }
#[test] fn dlsym_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\n#include <math.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY); if(!h) h = dlopen(\"libm.so\", RTLD_LAZY); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY); if(h) { double (*p_cos)(double) = dlsym(h, \"cos\"); printf(\"%d\", p_cos != NULL); dlclose(h); } else { printf(\"1\"); /* if math lib not found as shared, pass test */ } return 0; }"), vec!["1"]); }
#[test] fn dlerror_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"does_not_exist.so.1.2.3\", RTLD_LAZY); if(!h) { char *err = dlerror(); printf(\"%d\", err != NULL); } else dlclose(h); return 0; }"), vec!["1"]); }
#[test] fn dlclose_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY); if(!h) h = dlopen(\"libm.so\", RTLD_LAZY); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY); if(h) { int r = dlclose(h); printf(\"%d\", r == 0); } else printf(\"1\"); return 0; }"), vec!["1"]); }
#[test] fn dlopen_null() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(NULL, RTLD_LAZY); printf(\"%d\", h != NULL); if(h) dlclose(h); return 0; }"), vec!["1"]); } // NULL opens main program
#[test] fn dlsym_main_program() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint my_global = 42;\nint main() { void *h = dlopen(NULL, RTLD_LAZY); if(h) { int *p = dlsym(h, \"my_global\"); /* May be NULL if not exported dynamically, test runs without crash */ printf(\"ok\"); dlclose(h); } return 0; }"), vec!["ok"]); }
#[test] fn dlopen_rtld_now() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_NOW); if(!h) h = dlopen(\"libm.so\", RTLD_NOW); if(!h) h = dlopen(\"libm.dylib\", RTLD_NOW); printf(\"%d\", h != NULL); if(h) dlclose(h); return 0; }"), vec!["1"]); }
#[test] fn dlopen_rtld_global() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY | RTLD_GLOBAL); if(!h) h = dlopen(\"libm.so\", RTLD_LAZY | RTLD_GLOBAL); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY | RTLD_GLOBAL); printf(\"%d\", h != NULL); if(h) dlclose(h); return 0; }"), vec!["1"]); }
#[test] fn dlopen_rtld_local() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY | RTLD_LOCAL); if(!h) h = dlopen(\"libm.so\", RTLD_LAZY | RTLD_LOCAL); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY | RTLD_LOCAL); printf(\"%d\", h != NULL); if(h) dlclose(h); return 0; }"), vec!["1"]); }
#[test] fn dladdr_compile() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\nint main() { Dl_info info; int r = dladdr((void*)main, &info); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); } // Valid on glibc, macos
#[test] fn dlsym_invalid_handle() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *p = dlsym(NULL, \"cos\"); /* Some OS allow NULL as RTLD_DEFAULT or fail cleanly. Just check no crash */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn dlsym_invalid_symbol() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY); if(!h) h = dlopen(\"libm.so\", RTLD_LAZY); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY); if(h) { void *p = dlsym(h, \"does_not_exist_xyz\"); printf(\"%d\", p == NULL); dlclose(h); } else printf(\"1\"); return 0; }"), vec!["1"]); }
#[test] fn dlerror_cleared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { dlopen(\"nonexistent.so\", RTLD_LAZY); char *e1 = dlerror(); char *e2 = dlerror(); printf(\"%d %d\", e1 != NULL, e2 == NULL); return 0; }"), vec!["1 1"]); } // Second call returns NULL
#[test] fn dlopen_self_close() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <dlfcn.h>\nint main() { void *h = dlopen(NULL, RTLD_LAZY); if(h) { int r = dlclose(h); printf(\"%d\", r == 0); } else printf(\"1\"); return 0; }"), vec!["1"]); }
#[test] fn dlopen_nodelete_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY | RTLD_NODELETE); if(!h) h = dlopen(\"libm.dylib\", RTLD_LAZY | RTLD_NODELETE); if(h) dlclose(h); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn dlinfo_compile() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\n#include <link.h>\nint main() { /* dlinfo is very glibc specific, let's just check compile of macros */ #ifdef RTLD_DI_LINKMAP\n printf(\"ok\");\n#else\n printf(\"ok\");\n#endif\n return 0; }"), vec!["ok"]); }
#[test] fn dlopen_noload_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\nint main() { void *h = dlopen(\"libm.so.6\", RTLD_LAZY | RTLD_NOLOAD); /* Fails if not already loaded, which is fine, just test macro and call */ if(h) dlclose(h); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn dlsym_rtld_default_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\nint main() { void *p = dlsym(RTLD_DEFAULT, \"printf\"); printf(\"%d\", p != NULL); return 0; }"), vec!["1"]); }
#[test] fn dlsym_rtld_next_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\nint main() { void *p = dlsym(RTLD_NEXT, \"printf\"); printf(\"%d\", p != NULL); return 0; }"), vec!["1"]); }
#[test] fn dlvsym_compile_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <dlfcn.h>\nint main() { /* dlvsym needs version string, too complex to predict, check compile */ void *p = dlvsym(RTLD_DEFAULT, \"printf\", \"GLIBC_2.2.5\"); printf(\"ok\"); return 0; }"), vec!["ok"]); }
