use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn shm_open_unlink_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm1\", O_CREAT | O_RDWR, 0644); printf(\"%d\", fd >= 0); if(fd >= 0) { close(fd); shm_unlink(\"/test_shm1\"); } return 0; }"), vec!["1"]); }
#[test] fn shm_unlink_existing() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm2\", O_CREAT | O_RDWR, 0644); int r = shm_unlink(\"/test_shm2\"); printf(\"%d\", r == 0); if(fd >= 0) close(fd); return 0; }"), vec!["1"]); }
#[test] fn shm_ftruncate() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\n#include <sys/stat.h>\nint main() { int fd = shm_open(\"/test_shm3\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 4096); struct stat st; fstat(fd, &st); printf(\"%d\", st.st_size == 4096); close(fd); shm_unlink(\"/test_shm3\"); return 0; }"), vec!["1"]); }
#[test] fn shm_mmap_write_read() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm4\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 4096); void *p = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0); ((char*)p)[0] = 'S'; msync(p, 4096, MS_SYNC); munmap(p, 4096); void *p2 = mmap(NULL, 4096, PROT_READ, MAP_SHARED, fd, 0); printf(\"%c\", ((char*)p2)[0]); munmap(p2, 4096); close(fd); shm_unlink(\"/test_shm4\"); return 0; }"), vec!["S"]); }
#[test] fn shm_open_exclusive() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd1 = shm_open(\"/test_shm5\", O_CREAT | O_RDWR, 0644); int fd2 = shm_open(\"/test_shm5\", O_CREAT | O_EXCL | O_RDWR, 0644); printf(\"%d\", fd2 == -1); close(fd1); shm_unlink(\"/test_shm5\"); return 0; }"), vec!["1"]); }
#[test] fn shm_open_missing_without_creat() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\nint main() { int fd = shm_open(\"/test_shm_missing\", O_RDWR); printf(\"%d\", fd == -1); return 0; }"), vec!["1"]); }
#[test] fn shm_unlink_nonexistent() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main() { int r = shm_unlink(\"/test_shm_missing\"); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn shm_read_only() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd1 = shm_open(\"/test_shm6\", O_CREAT | O_RDWR, 0644); ftruncate(fd1, 4096); close(fd1); int fd2 = shm_open(\"/test_shm6\", O_RDONLY, 0644); void *p = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_SHARED, fd2, 0); printf(\"%d\", p == MAP_FAILED); close(fd2); shm_unlink(\"/test_shm6\"); return 0; }"), vec!["1"]); } // Can't map PROT_WRITE on O_RDONLY
#[test] fn shm_multiple_opens() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd1 = shm_open(\"/test_shm7\", O_CREAT | O_RDWR, 0644); int fd2 = shm_open(\"/test_shm7\", O_RDWR, 0644); printf(\"%d\", fd1 >= 0 && fd2 >= 0 && fd1 != fd2); close(fd1); close(fd2); shm_unlink(\"/test_shm7\"); return 0; }"), vec!["1"]); }
#[test] fn shm_shared_between_processes() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\n#include <sys/wait.h>\nint main() { int fd = shm_open(\"/test_shm8\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 4096); void *p = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0); pid_t pid = fork(); if(pid==0) { ((char*)p)[0] = 'P'; msync(p, 4096, MS_SYNC); _exit(0); } wait(NULL); printf(\"%c\", ((char*)p)[0]); munmap(p, 4096); close(fd); shm_unlink(\"/test_shm8\"); return 0; }"), vec!["P"]); }
#[test] fn shm_name_no_slash() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"test_shm9\", O_CREAT | O_RDWR, 0644); printf(\"%d\", fd >= 0 || fd == -1); if(fd >= 0) { close(fd); shm_unlink(\"test_shm9\"); } return 0; }"), vec!["1"]); } // OS dependent if slash is required
#[test] fn shm_name_long() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\nint main() { char name[300]; name[0] = '/'; for(int i=1; i<250; i++) name[i] = 'a'; name[250] = 0; int fd = shm_open(name, O_CREAT | O_RDWR, 0644); printf(\"%d\", fd == -1); return 0; }"), vec!["1"]); }
#[test] fn shm_fstat_times() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\n#include <sys/stat.h>\nint main() { int fd = shm_open(\"/test_shm10\", O_CREAT | O_RDWR, 0644); struct stat st; fstat(fd, &st); printf(\"%d\", st.st_ctime > 0); close(fd); shm_unlink(\"/test_shm10\"); return 0; }"), vec!["1"]); }
#[test] fn shm_write_read() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm11\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 4096); write(fd, \"abcd\", 4); lseek(fd, 0, SEEK_SET); char b[5]={0}; read(fd, b, 4); printf(\"%s\", b); close(fd); shm_unlink(\"/test_shm11\"); return 0; }"), vec!["abcd"]); }
#[test] fn shm_mmap_private() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm12\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 4096); write(fd, \"x\", 1); void *p = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0); ((char*)p)[0] = 'y'; lseek(fd, 0, SEEK_SET); char b[2]={0}; read(fd, b, 1); printf(\"%s\", b); munmap(p, 4096); close(fd); shm_unlink(\"/test_shm12\"); return 0; }"), vec!["x"]); }
#[test] fn shm_open_invalid_flags() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\nint main() { int fd = shm_open(\"/test_shm13\", 99999, 0644); printf(\"%d\", fd == -1); return 0; }"), vec!["1"]); }
#[test] fn shm_ftruncate_increase() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\n#include <sys/stat.h>\nint main() { int fd = shm_open(\"/test_shm14\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 100); ftruncate(fd, 200); struct stat st; fstat(fd, &st); printf(\"%d\", st.st_size == 200); close(fd); shm_unlink(\"/test_shm14\"); return 0; }"), vec!["1"]); }
#[test] fn shm_mmap_executable() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm15\", O_CREAT | O_RDWR, 0644); ftruncate(fd, 4096); void *p = mmap(NULL, 4096, PROT_READ | PROT_EXEC, MAP_SHARED, fd, 0); /* May fail or succeed depending on OS/mount options, check compile and basic run */ printf(\"ok\"); if(p != MAP_FAILED) munmap(p, 4096); close(fd); shm_unlink(\"/test_shm15\"); return 0; }"), vec!["ok"]); }
#[test] fn shm_fd_cloexec() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm16\", O_CREAT | O_RDWR, 0644); int flags = fcntl(fd, F_GETFD); printf(\"%d\", (flags & FD_CLOEXEC) != 0); close(fd); shm_unlink(\"/test_shm16\"); return 0; }"), vec!["1"]); } // shm_open sets FD_CLOEXEC automatically
#[test] fn shm_zero_size_mmap() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = shm_open(\"/test_shm17\", O_CREAT | O_RDWR, 0644); void *p = mmap(NULL, 0, PROT_READ, MAP_SHARED, fd, 0); printf(\"%d\", p == MAP_FAILED); close(fd); shm_unlink(\"/test_shm17\"); return 0; }"), vec!["1"]); }
