use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn qsort_basic_ints() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {3, 1, 4, 1, 5, 9}; qsort(arr, 6, sizeof(int), cmp); printf(\"%d %d %d\", arr[0], arr[1], arr[5]); return 0; }"), vec!["1 1 9"]); }
#[test] fn qsort_strings() { assert_eq!(run_c("#include <stdlib.h>\n#include <string.h>\nint cmp(const void *a, const void *b) { return strcmp(*(const char**)a, *(const char**)b); }\nint main() { const char *arr[] = {\"zebra\", \"apple\", \"mango\"}; qsort(arr, 3, sizeof(char*), cmp); printf(\"%s %s %s\", arr[0], arr[1], arr[2]); return 0; }"), vec!["apple mango zebra"]); }
#[test] fn qsort_structs() { assert_eq!(run_c("#include <stdlib.h>\nstruct S { int k; char v; }; int cmp(const void *a, const void *b) { return ((struct S*)a)->k - ((struct S*)b)->k; }\nint main() { struct S arr[] = {{5,'e'}, {1,'a'}, {3,'c'}}; qsort(arr, 3, sizeof(struct S), cmp); printf(\"%c %c %c\", arr[0].v, arr[1].v, arr[2].v); return 0; }"), vec!["a c e"]); }
#[test] fn qsort_empty_array() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return 0; }\nint main() { int arr[] = {1}; qsort(arr, 0, sizeof(int), cmp); printf(\"%d\", arr[0]); return 0; }"), vec!["1"]); }
#[test] fn qsort_one_element() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return 0; }\nint main() { int arr[] = {42}; qsort(arr, 1, sizeof(int), cmp); printf(\"%d\", arr[0]); return 0; }"), vec!["42"]); }
#[test] fn qsort_r_gnu() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <stdlib.h>\nint cmp(const void *a, const void *b, void *arg) { int dir = *(int*)arg; return (*(int*)a - *(int*)b) * dir; }\nint main() { int arr[] = {3, 1, 2}; int dir = -1; qsort_r(arr, 3, sizeof(int), cmp, &dir); printf(\"%d %d %d\", arr[0], arr[1], arr[2]); return 0; }"), vec!["3 2 1"]); }
#[test] fn bsearch_found() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {1, 2, 3, 5, 8}; int key = 5; int *res = bsearch(&key, arr, 5, sizeof(int), cmp); printf(\"%d\", res != NULL ? *res : -1); return 0; }"), vec!["5"]); }
#[test] fn bsearch_not_found() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {1, 2, 3, 5, 8}; int key = 4; int *res = bsearch(&key, arr, 5, sizeof(int), cmp); printf(\"%d\", res == NULL); return 0; }"), vec!["1"]); }
#[test] fn bsearch_first_element() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {10, 20, 30}; int key = 10; int *res = bsearch(&key, arr, 3, sizeof(int), cmp); printf(\"%d\", res == &arr[0]); return 0; }"), vec!["1"]); }
#[test] fn bsearch_last_element() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {10, 20, 30}; int key = 30; int *res = bsearch(&key, arr, 3, sizeof(int), cmp); printf(\"%d\", res == &arr[2]); return 0; }"), vec!["1"]); }
#[test] fn bsearch_empty_array() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return 0; }\nint main() { int arr[] = {1}; int key = 1; int *res = bsearch(&key, arr, 0, sizeof(int), cmp); printf(\"%d\", res == NULL); return 0; }"), vec!["1"]); }
#[test] fn qsort_bsearch_combined() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {9, 2, 7, 4}; qsort(arr, 4, sizeof(int), cmp); int key = 7; int *res = bsearch(&key, arr, 4, sizeof(int), cmp); printf(\"%d %d\", arr[2], *res); return 0; }"), vec!["7 7"]); }
#[test] fn bsearch_structs() { assert_eq!(run_c("#include <stdlib.h>\nstruct S { int id; char n; }; int cmp(const void *a, const void *b) { return ((struct S*)a)->id - ((struct S*)b)->id; }\nint main() { struct S arr[] = {{1,'A'}, {2,'B'}, {3,'C'}}; struct S key = {2, 0}; struct S *res = bsearch(&key, arr, 3, sizeof(struct S), cmp); printf(\"%c\", res->n); return 0; }"), vec!["B"]); }
#[test] fn qsort_large_elements() { assert_eq!(run_c("#include <stdlib.h>\nstruct L { int a[100]; int k; }; int cmp(const void *a, const void *b) { return ((struct L*)a)->k - ((struct L*)b)->k; }\nint main() { struct L arr[3] = {0}; arr[0].k = 3; arr[1].k = 1; arr[2].k = 2; qsort(arr, 3, sizeof(struct L), cmp); printf(\"%d %d %d\", arr[0].k, arr[1].k, arr[2].k); return 0; }"), vec!["1 2 3"]); }
#[test] fn bsearch_duplicate_elements() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {1, 2, 2, 2, 3}; int key = 2; int *res = bsearch(&key, arr, 5, sizeof(int), cmp); printf(\"%d\", *res == 2); return 0; }"), vec!["1"]); } // doesn't guarantee which one
#[test] fn qsort_pointer_array() { assert_eq!(run_c("#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (**(int**)a - **(int**)b); }\nint main() { int x=3, y=1, z=2; int *arr[] = {&x, &y, &z}; qsort(arr, 3, sizeof(int*), cmp); printf(\"%d %d %d\", *arr[0], *arr[1], *arr[2]); return 0; }"), vec!["1 2 3"]); }
#[test] fn lfind_basic() { assert_eq!(run_c("#include <search.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[] = {9, 2, 5}; size_t n = 3; int key = 5; int *res = lfind(&key, arr, &n, sizeof(int), cmp); printf(\"%d\", res != NULL ? *res : -1); return 0; }"), vec!["5"]); }
#[test] fn lsearch_basic() { assert_eq!(run_c("#include <search.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { int arr[10] = {9, 2, 5}; size_t n = 3; int key = 7; int *res = lsearch(&key, arr, &n, sizeof(int), cmp); printf(\"%d %d\", *res, (int)n); return 0; }"), vec!["7 4"]); } // inserts 7
#[test] fn tsearch_tfind_basic() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <search.h>\n#include <stdlib.h>\nint cmp(const void *a, const void *b) { return (*(int*)a - *(int*)b); }\nint main() { void *root = NULL; int x=3, y=1, z=2; tsearch(&x, &root, cmp); tsearch(&y, &root, cmp); tsearch(&z, &root, cmp); int key=2; void *res = tfind(&key, &root, cmp); printf(\"%d\", res != NULL); tdestroy(root, free); return 0; }"), vec!["1"]); }
#[test] fn hsearch_basic() { assert_eq!(run_c("#define _GNU_SOURCE\n#include <search.h>\n#include <stdlib.h>\nint main() { hcreate(10); ENTRY e, *ep; e.key = \"foo\"; e.data = (void*)42; hsearch(e, ENTER); e.key = \"foo\"; ep = hsearch(e, FIND); printf(\"%ld\", (long)ep->data); hdestroy(); return 0; }"), vec!["42"]); }
