use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn fcntl_dupfd_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl1.txt\", O_CREAT|O_WRONLY, 0644); int fd2 = fcntl(fd, F_DUPFD, 0); printf(\"%d %d\", fd2 >= 0, fd != fd2); close(fd); close(fd2); unlink(\"test_fcntl1.txt\"); return 0; }"), vec!["1 1"]); }
#[test] fn fcntl_getfd_setfd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl2.txt\", O_CREAT|O_WRONLY, 0644); int flg1 = fcntl(fd, F_GETFD); fcntl(fd, F_SETFD, flg1 | FD_CLOEXEC); int flg2 = fcntl(fd, F_GETFD); printf(\"%d\", (flg2 & FD_CLOEXEC) != 0); close(fd); unlink(\"test_fcntl2.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_getfl_setfl() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl3.txt\", O_CREAT|O_WRONLY, 0644); int flg1 = fcntl(fd, F_GETFL); fcntl(fd, F_SETFL, flg1 | O_APPEND); int flg2 = fcntl(fd, F_GETFL); printf(\"%d\", (flg2 & O_APPEND) != 0); close(fd); unlink(\"test_fcntl3.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_setlk_wrlck() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl4.txt\", O_CREAT|O_RDWR, 0644); struct flock fl = {0}; fl.l_type = F_WRLCK; fl.l_whence = SEEK_SET; fl.l_start = 0; fl.l_len = 0; int r = fcntl(fd, F_SETLK, &fl); printf(\"%d\", r == 0); close(fd); unlink(\"test_fcntl4.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_setlk_rdlck() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl5.txt\", O_CREAT|O_RDWR, 0644); struct flock fl = {0}; fl.l_type = F_RDLCK; fl.l_whence = SEEK_SET; fl.l_start = 0; fl.l_len = 10; int r = fcntl(fd, F_SETLK, &fl); printf(\"%d\", r == 0); close(fd); unlink(\"test_fcntl5.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_setlk_unlck() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl6.txt\", O_CREAT|O_RDWR, 0644); struct flock fl = {0}; fl.l_type = F_WRLCK; fl.l_whence = SEEK_SET; fcntl(fd, F_SETLK, &fl); fl.l_type = F_UNLCK; int r = fcntl(fd, F_SETLK, &fl); printf(\"%d\", r == 0); close(fd); unlink(\"test_fcntl6.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_getlk() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\n#include <sys/wait.h>\nint main() { int fd = open(\"test_fcntl7.txt\", O_CREAT|O_RDWR, 0644); struct flock fl = {0}; fl.l_type = F_WRLCK; fl.l_whence = SEEK_SET; fcntl(fd, F_SETLK, &fl); pid_t p = fork(); if(p==0) { struct flock fl2 = {0}; fl2.l_type = F_WRLCK; fl2.l_whence = SEEK_SET; fcntl(fd, F_GETLK, &fl2); printf(\"%d\", fl2.l_type != F_UNLCK && fl2.l_pid == getppid()); _exit(0); } wait(NULL); close(fd); unlink(\"test_fcntl7.txt\"); return 0; }"), vec!["1"]); }
#[test] fn flock_sh() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_flock1.txt\", O_CREAT|O_RDWR, 0644); int r = flock(fd, LOCK_SH); printf(\"%d\", r == 0); close(fd); unlink(\"test_flock1.txt\"); return 0; }"), vec!["1"]); }
#[test] fn flock_ex() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_flock2.txt\", O_CREAT|O_RDWR, 0644); int r = flock(fd, LOCK_EX); printf(\"%d\", r == 0); close(fd); unlink(\"test_flock2.txt\"); return 0; }"), vec!["1"]); }
#[test] fn flock_un() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_flock3.txt\", O_CREAT|O_RDWR, 0644); flock(fd, LOCK_EX); int r = flock(fd, LOCK_UN); printf(\"%d\", r == 0); close(fd); unlink(\"test_flock3.txt\"); return 0; }"), vec!["1"]); }
#[test] fn flock_nb() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\n#include <unistd.h>\n#include <sys/wait.h>\nint main() { int fd = open(\"test_flock4.txt\", O_CREAT|O_RDWR, 0644); flock(fd, LOCK_EX); pid_t p = fork(); if(p==0) { int r = flock(fd, LOCK_EX | LOCK_NB); printf(\"%d\", r == -1); _exit(0); } wait(NULL); close(fd); unlink(\"test_flock4.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_setlkw_unblocks() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\n#include <sys/wait.h>\nint main() { int fd = open(\"test_fcntl8.txt\", O_CREAT|O_RDWR, 0644); struct flock fl = {0}; fl.l_type = F_WRLCK; fl.l_whence = SEEK_SET; fcntl(fd, F_SETLK, &fl); pid_t p = fork(); if(p==0) { struct flock fl2 = {0}; fl2.l_type = F_WRLCK; fl2.l_whence = SEEK_SET; fcntl(fd, F_SETLKW, &fl2); printf(\"1\"); _exit(0); } sleep(1); fl.l_type = F_UNLCK; fcntl(fd, F_SETLK, &fl); wait(NULL); close(fd); unlink(\"test_fcntl8.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_dupfd_cloexec() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl9.txt\", O_CREAT|O_WRONLY, 0644); int fd2 = fcntl(fd, F_DUPFD_CLOEXEC, 0); int flg = fcntl(fd2, F_GETFD); printf(\"%d\", (flg & FD_CLOEXEC) != 0); close(fd); close(fd2); unlink(\"test_fcntl9.txt\"); return 0; }"), vec!["1"]); }
#[test] fn flock_shared_multiple() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\n#include <unistd.h>\n#include <sys/wait.h>\nint main() { int fd = open(\"test_flock5.txt\", O_CREAT|O_RDWR, 0644); flock(fd, LOCK_SH); pid_t p = fork(); if(p==0) { int r = flock(fd, LOCK_SH | LOCK_NB); printf(\"%d\", r == 0); _exit(0); } wait(NULL); close(fd); unlink(\"test_flock5.txt\"); return 0; }"), vec!["1"]); } // multiple shared locks succeed
#[test] fn fcntl_invalid_cmd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl10.txt\", O_CREAT|O_WRONLY, 0644); int r = fcntl(fd, 99999); printf(\"%d\", r == -1); close(fd); unlink(\"test_fcntl10.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_invalid_fd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\nint main() { int r = fcntl(-1, F_GETFD); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn flock_invalid_fd() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\nint main() { int r = flock(-1, LOCK_SH); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn fcntl_setlk_read_only_fd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl11.txt\", O_CREAT|O_RDONLY, 0644); struct flock fl = {0}; fl.l_type = F_WRLCK; fl.l_whence = SEEK_SET; int r = fcntl(fd, F_SETLK, &fl); printf(\"%d\", r == -1); /* Write lock on read-only fd fails */ close(fd); unlink(\"test_fcntl11.txt\"); return 0; }"), vec!["1"]); }
#[test] fn flock_read_only_fd() { assert_eq!(run_c("#define _BSD_SOURCE\n#define _DEFAULT_SOURCE\n#include <sys/file.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_flock6.txt\", O_CREAT|O_RDONLY, 0644); int r = flock(fd, LOCK_EX); /* Valid on some OS, but typically flock works regardless of open mode */ printf(\"%d\", r == 0 || r == -1); close(fd); unlink(\"test_flock6.txt\"); return 0; }"), vec!["1"]); }
#[test] fn fcntl_lock_unlocked_region() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_fcntl12.txt\", O_CREAT|O_RDWR, 0644); struct flock fl = {0}; fl.l_type = F_UNLCK; fl.l_whence = SEEK_SET; int r = fcntl(fd, F_SETLK, &fl); printf(\"%d\", r == 0); close(fd); unlink(\"test_fcntl12.txt\"); return 0; }"), vec!["1"]); } // Unlocking already unlocked is fine
