use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn cond_init_destroy() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_cond_t c; int r1 = pthread_cond_init(&c, NULL); int r2 = pthread_cond_destroy(&c); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn cond_static_initializer() { assert_eq!(run_c("#include <pthread.h>\npthread_cond_t c = PTHREAD_COND_INITIALIZER;\nint main() { printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn cond_wait_signal() { assert_eq!(run_c("#include <pthread.h>\n#include <unistd.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\npthread_cond_t c = PTHREAD_COND_INITIALIZER;\nint ready = 0;\nvoid* f(void* a) { pthread_mutex_lock(&m); while(!ready) pthread_cond_wait(&c, &m); pthread_mutex_unlock(&m); return (void*)1; }\nint main() { pthread_t t; pthread_create(&t, NULL, f, NULL); sleep(1); pthread_mutex_lock(&m); ready = 1; pthread_cond_signal(&c); pthread_mutex_unlock(&m); void *res; pthread_join(t, &res); printf(\"%ld\", (long)res); return 0; }"), vec!["1"]); }
#[test] fn cond_broadcast() { assert_eq!(run_c("#include <pthread.h>\n#include <unistd.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\npthread_cond_t c = PTHREAD_COND_INITIALIZER;\nint ready = 0, count = 0;\nvoid* f(void* a) { pthread_mutex_lock(&m); while(!ready) pthread_cond_wait(&c, &m); count++; pthread_mutex_unlock(&m); return NULL; }\nint main() { pthread_t t1, t2; pthread_create(&t1, NULL, f, NULL); pthread_create(&t2, NULL, f, NULL); sleep(1); pthread_mutex_lock(&m); ready = 1; pthread_cond_broadcast(&c); pthread_mutex_unlock(&m); pthread_join(t1, NULL); pthread_join(t2, NULL); printf(\"%d\", count); return 0; }"), vec!["2"]); }
#[test] fn cond_timedwait() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <sys/time.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_cond_t c = PTHREAD_COND_INITIALIZER; pthread_mutex_lock(&m); struct timeval tv; gettimeofday(&tv, NULL); struct timespec ts; ts.tv_sec = tv.tv_sec; ts.tv_nsec = tv.tv_usec * 1000 + 50000000; if(ts.tv_nsec >= 1000000000) { ts.tv_sec++; ts.tv_nsec -= 1000000000; } int r = pthread_cond_timedwait(&c, &m, &ts); printf(\"%d\", r != 0); pthread_mutex_unlock(&m); return 0; }"), vec!["1"]); }
#[test] fn condattr_init_destroy() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_condattr_t a; int r1 = pthread_condattr_init(&a); int r2 = pthread_condattr_destroy(&a); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn condattr_setpshared() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_condattr_t a; pthread_condattr_init(&a); int r = pthread_condattr_setpshared(&a, PTHREAD_PROCESS_SHARED); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn condattr_getpshared() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_condattr_t a; pthread_condattr_init(&a); pthread_condattr_setpshared(&a, PTHREAD_PROCESS_SHARED); int s; pthread_condattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_SHARED); return 0; }"), vec!["1"]); }
#[test] fn condattr_setclock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_condattr_t a; pthread_condattr_init(&a); int r = pthread_condattr_setclock(&a, CLOCK_MONOTONIC); printf(\"%d\", r == 0 || r != 0); return 0; }"), vec!["1"]); }
#[test] fn condattr_getclock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_condattr_t a; pthread_condattr_init(&a); pthread_condattr_setclock(&a, CLOCK_MONOTONIC); clockid_t c; int r = pthread_condattr_getclock(&a, &c); printf(\"%d\", r == 0 || r != 0); return 0; }"), vec!["1"]); }
#[test] fn cond_signal_no_waiters() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_cond_t c = PTHREAD_COND_INITIALIZER; int r = pthread_cond_signal(&c); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn cond_broadcast_no_waiters() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_cond_t c = PTHREAD_COND_INITIALIZER; int r = pthread_cond_broadcast(&c); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn cond_wait_spurious_wakeup_handling() { assert_eq!(run_c("#include <pthread.h>\n#include <unistd.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\npthread_cond_t c = PTHREAD_COND_INITIALIZER;\nint ready = 0;\nvoid* f(void* a) { pthread_mutex_lock(&m); while(!ready) pthread_cond_wait(&c, &m); pthread_mutex_unlock(&m); return NULL; }\nint main() { pthread_t t; pthread_create(&t, NULL, f, NULL); sleep(1); pthread_cond_signal(&c); /* fake signal, ready is still 0 */ sleep(1); pthread_mutex_lock(&m); ready = 1; pthread_cond_signal(&c); pthread_mutex_unlock(&m); pthread_join(t, NULL); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn cond_destroy_with_waiters() { assert_eq!(run_c("#include <pthread.h>\nint main() { /* UB to destroy cond with waiters, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn cond_timedwait_in_past() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_cond_t c = PTHREAD_COND_INITIALIZER; pthread_mutex_lock(&m); struct timespec ts = {0, 0}; int r = pthread_cond_timedwait(&c, &m, &ts); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn cond_wait_mutex_not_owned() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER; pthread_cond_t c = PTHREAD_COND_INITIALIZER; /* UB to call wait without owning mutex, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn cond_signal_from_different_mutex() { assert_eq!(run_c("#include <pthread.h>\nint main() { /* UB to wait on same cond with different mutexes concurrently, but signaling from anywhere is ok */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn condattr_default_pshared() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_condattr_t a; pthread_condattr_init(&a); int s; pthread_condattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_PRIVATE); return 0; }"), vec!["1"]); }
#[test] fn condattr_default_clock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_condattr_t a; pthread_condattr_init(&a); clockid_t c; pthread_condattr_getclock(&a, &c); printf(\"%d\", c == CLOCK_REALTIME); return 0; }"), vec!["1"]); }
#[test] fn cond_signal_multiple_times() { assert_eq!(run_c("#include <pthread.h>\nint main() { pthread_cond_t c = PTHREAD_COND_INITIALIZER; pthread_cond_signal(&c); pthread_cond_signal(&c); printf(\"ok\"); return 0; }"), vec!["ok"]); }
