use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn spin_init_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; int r1 = pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); int r2 = pthread_spin_destroy(&s); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn spin_lock_unlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); pthread_spin_lock(&s); pthread_spin_unlock(&s); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_trylock_success() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); int r = pthread_spin_trylock(&s); pthread_spin_unlock(&s); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn spin_trylock_fail() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); pthread_spin_lock(&s); int r = pthread_spin_trylock(&s); pthread_spin_unlock(&s); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn spin_init_pshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; int r = pthread_spin_init(&s, PTHREAD_PROCESS_SHARED); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn spin_lock_threads() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <unistd.h>\npthread_spinlock_t s;\nint val = 0;\nvoid* f(void* a) { pthread_spin_lock(&s); val = 2; pthread_spin_unlock(&s); return NULL; }\nint main() { pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); pthread_spin_lock(&s); pthread_t t; pthread_create(&t, NULL, f, NULL); sleep(1); val = 1; pthread_spin_unlock(&s); pthread_join(t, NULL); printf(\"%d\", val); return 0; }"), vec!["2"]); }
#[test] fn spin_destroy_locked() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to destroy locked spinlock, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_unlock_unlocked() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to unlock unlocked spinlock, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_double_lock_deadlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* Double lock is UB or deadlock, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_init_invalid_pshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; int r = pthread_spin_init(&s, 99999); printf(\"%d\", r != 0 || r == 0); return 0; }"), vec!["1"]); } // May fail or succeed depending on libc leniency
#[test] fn spin_concurrency_stress() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\npthread_spinlock_t s;\nint count = 0;\nvoid* f(void* a) { for(int i=0; i<1000; i++) { pthread_spin_lock(&s); count++; pthread_spin_unlock(&s); } return NULL; }\nint main() { pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); pthread_t t1, t2; pthread_create(&t1, NULL, f, NULL); pthread_create(&t2, NULL, f, NULL); pthread_join(t1, NULL); pthread_join(t2, NULL); printf(\"%d\", count); return 0; }"), vec!["2000"]); }
#[test] fn spin_trylock_stress() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\npthread_spinlock_t s;\nint count = 0;\nvoid* f(void* a) { for(int i=0; i<1000; i++) { while(pthread_spin_trylock(&s) != 0); count++; pthread_spin_unlock(&s); } return NULL; }\nint main() { pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); pthread_t t1, t2; pthread_create(&t1, NULL, f, NULL); pthread_create(&t2, NULL, f, NULL); pthread_join(t1, NULL); pthread_join(t2, NULL); printf(\"%d\", count); return 0; }"), vec!["2000"]); }
#[test] fn spin_vs_mutex_compile() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* check API distinctions */ pthread_spinlock_t s; pthread_mutex_t m; printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_lock_yield() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <sched.h>\nint main() { pthread_spinlock_t s; pthread_spin_init(&s, PTHREAD_PROCESS_PRIVATE); pthread_spin_lock(&s); sched_yield(); pthread_spin_unlock(&s); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_init_twice() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; pthread_spin_init(&s, 0); /* Init twice is UB, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_used_after_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to use after destroy, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_multiple_locks() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s1, s2; pthread_spin_init(&s1, 0); pthread_spin_init(&s2, 0); pthread_spin_lock(&s1); pthread_spin_lock(&s2); pthread_spin_unlock(&s2); pthread_spin_unlock(&s1); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spin_is_busy_wait() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* semantically spins consuming CPU, not easy to test CPU usage, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn spinlock_sizes() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { printf(\"%d\", sizeof(pthread_spinlock_t) > 0); return 0; }"), vec!["1"]); }
#[test] fn spin_process_shared_unsupported() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_spinlock_t s; int r = pthread_spin_init(&s, PTHREAD_PROCESS_SHARED); /* valid to succeed or fail if unsupported */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
