use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn struct_desig_nested_basic() { assert_eq!(run_c("struct Inner { int a; }; struct Outer { struct Inner i; int b; }; int main() { struct Outer o = { .i.a = 5, .b = 10 }; printf(\"%d\", o.i.a + o.b); return 0; }"), vec!["15"]); }
#[test] fn struct_desig_nested_multiple_inner() { assert_eq!(run_c("struct Inner { int a; int b; }; struct Outer { struct Inner i; }; int main() { struct Outer o = { .i.a = 1, .i.b = 2 }; printf(\"%d\", o.i.b); return 0; }"), vec!["2"]); }
#[test] fn struct_desig_nested_array_inner() { assert_eq!(run_c("struct Inner { int arr[2]; }; struct Outer { struct Inner i; }; int main() { struct Outer o = { .i.arr[1] = 42 }; printf(\"%d\", o.i.arr[1]); return 0; }"), vec!["42"]); }
#[test] fn struct_desig_nested_struct_in_array() { assert_eq!(run_c("struct Inner { int a; }; struct Outer { struct Inner arr[2]; }; int main() { struct Outer o = { .arr[1].a = 99 }; printf(\"%d\", o.arr[1].a); return 0; }"), vec!["99"]); }
#[test] fn struct_desig_nested_override() { assert_eq!(run_c("struct Inner { int a; }; struct Outer { struct Inner i; }; int main() { struct Outer o = { .i.a = 1, .i = { 2 } }; printf(\"%d\", o.i.a); return 0; }"), vec!["2"]); }
#[test] fn struct_desig_nested_implicit_zero() { assert_eq!(run_c("struct Inner { int a, b; }; struct Outer { struct Inner i; }; int main() { struct Outer o = { .i.b = 5 }; printf(\"%d\", o.i.a); return 0; }"), vec!["0"]); }
#[test] fn struct_desig_nested_with_braces() { assert_eq!(run_c("struct Inner { int a; }; struct Outer { struct Inner i; }; int main() { struct Outer o = { .i = { .a = 7 } }; printf(\"%d\", o.i.a); return 0; }"), vec!["7"]); }
#[test] fn struct_desig_nested_union() { assert_eq!(run_c("union U { int i; char c; }; struct S { union U u; }; int main() { struct S s = { .u.i = 65 }; printf(\"%d\", s.u.i); return 0; }"), vec!["65"]); }
#[test] fn struct_desig_nested_union_override() { assert_eq!(run_c("union U { int i; char c; }; struct S { union U u; }; int main() { struct S s = { .u.c = 'A', .u.i = 66 }; printf(\"%d\", s.u.i); return 0; }"), vec!["66"]); }
#[test] fn struct_desig_nested_pointer() { assert_eq!(run_c("struct Inner { int a; }; struct Outer { struct Inner *p; }; int main() { struct Inner in = {4}; struct Outer o = { .p = &in }; printf(\"%d\", o.p->a); return 0; }"), vec!["4"]); }
#[test] fn struct_desig_nested_deep() { assert_eq!(run_c("struct A { int x; }; struct B { struct A a; }; struct C { struct B b; }; int main() { struct C c = { .b.a.x = 100 }; printf(\"%d\", c.b.a.x); return 0; }"), vec!["100"]); }
#[test] fn struct_desig_nested_anonymous() { assert_eq!(run_c("struct Outer { struct { int a; }; }; int main() { struct Outer o = { .a = 5 }; printf(\"%d\", o.a); return 0; }"), vec!["5"]); } // C11 allows initializing anon members via their names directly
#[test] fn struct_desig_nested_anonymous_union() { assert_eq!(run_c("struct Outer { union { int i; float f; }; }; int main() { struct Outer o = { .i = 123 }; printf(\"%d\", o.i); return 0; }"), vec!["123"]); }
#[test] fn struct_desig_nested_mixed_unnamed() { assert_eq!(run_c("struct Inner { int a; int b; }; struct Outer { struct Inner i; int c; }; int main() { struct Outer o = { .i = {1, 2}, 3 }; printf(\"%d\", o.c); return 0; }"), vec!["3"]); }
#[test] fn struct_desig_nested_out_of_order() { assert_eq!(run_c("struct Inner { int a; int b; }; struct Outer { struct Inner i; int c; }; int main() { struct Outer o = { .c = 3, .i.b = 2, .i.a = 1 }; printf(\"%d\", o.i.a + o.c); return 0; }"), vec!["4"]); }
