use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn setvbuf_full_buffering() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_f.txt\", \"w\"); char buf[1024]; int res = setvbuf(f, buf, _IOFBF, 1024); printf(\"%d\", res == 0); fclose(f); return 0; }"), vec!["1"]); }
#[test] fn setvbuf_line_buffering() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_l.txt\", \"w\"); char buf[1024]; int res = setvbuf(f, buf, _IOLBF, 1024); printf(\"%d\", res == 0); fclose(f); return 0; }"), vec!["1"]); }
#[test] fn setvbuf_no_buffering() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_n.txt\", \"w\"); int res = setvbuf(f, NULL, _IONBF, 0); printf(\"%d\", res == 0); fclose(f); return 0; }"), vec!["1"]); }
#[test] fn setbuf_custom_buffer() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_buf.txt\", \"w\"); char buf[BUFSIZ]; setbuf(f, buf); fputs(\"X\", f); printf(\"ok\"); fclose(f); return 0; }"), vec!["ok"]); } // setbuf returns void
#[test] fn setbuf_null_buffer() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_buf_null.txt\", \"w\"); setbuf(f, NULL); fputs(\"X\", f); printf(\"ok\"); fclose(f); return 0; }"), vec!["ok"]); } // equiv to _IONBF
#[test] fn setbuffer_basic() { assert_eq!(run_c("#define _BSD_SOURCE\nint main() { FILE *f = fopen(\"test_setbuffer.txt\", \"w\"); char buf[1024]; setbuffer(f, buf, 1024); fputs(\"X\", f); printf(\"ok\"); fclose(f); return 0; }"), vec!["ok"]); }
#[test] fn setlinebuf_basic() { assert_eq!(run_c("#define _BSD_SOURCE\nint main() { FILE *f = fopen(\"test_setlinebuf.txt\", \"w\"); setlinebuf(f); fputs(\"X\", f); printf(\"ok\"); fclose(f); return 0; }"), vec!["ok"]); }
#[test] fn fflush_stdout_line_buffered() { assert_eq!(run_c("int main() { setvbuf(stdout, NULL, _IOLBF, 1024); printf(\"hello\\nworld\"); return 0; }"), vec!["hello", "world"]); }
#[test] fn fflush_stdout_full_buffered() { assert_eq!(run_c("int main() { setvbuf(stdout, NULL, _IOFBF, 1024); printf(\"hello\"); fflush(stdout); return 0; }"), vec!["hello"]); }
#[test] fn fflush_stdout_unbuffered() { assert_eq!(run_c("int main() { setvbuf(stdout, NULL, _IONBF, 0); printf(\"hello\"); return 0; }"), vec!["hello"]); }
#[test] fn setvbuf_after_io() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_late.txt\", \"w\"); fputc('a', f); /* setvbuf after I/O is UB, but let's test a non-crashing flow */ printf(\"ok\"); fclose(f); return 0; }"), vec!["ok"]); }
#[test] fn setvbuf_null_buffer_malloc() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_auto.txt\", \"w\"); int res = setvbuf(f, NULL, _IOFBF, 1024); /* Library allocates buffer */ printf(\"%d\", res == 0); fclose(f); return 0; }"), vec!["1"]); }
#[test] fn fflush_null() { assert_eq!(run_c("int main() { printf(\"out\"); fflush(NULL); /* flushes all open streams */ return 0; }"), vec!["out"]); }
#[test] fn setvbuf_invalid_mode() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_inv.txt\", \"w\"); int res = setvbuf(f, NULL, 9999, 1024); printf(\"%d\", res != 0); fclose(f); return 0; }"), vec!["1"]); } // Non-zero on error
#[test] fn fclose_flushes_buffer() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_close_flush.txt\", \"w\"); setvbuf(f, NULL, _IOFBF, 1024); fputs(\"flushed\", f); fclose(f); f = fopen(\"test_close_flush.txt\", \"r\"); char buf[10]; fgets(buf, sizeof(buf), f); printf(\"%s\", buf); fclose(f); return 0; }"), vec!["flushed"]); }
#[test] fn stdout_is_line_buffered_by_default() { assert_eq!(run_c("int main() { /* C standard: fully buffered if not interactive, line buffered if interactive */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn stderr_is_unbuffered_by_default() { assert_eq!(run_c("int main() { /* standard says unbuffered or line buffered */ fprintf(stderr, \"err\"); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn setvbuf_zero_size() { assert_eq!(run_c("int main() { FILE *f = fopen(\"test_vbuf_z.txt\", \"w\"); char buf[1024]; int res = setvbuf(f, buf, _IOFBF, 0); /* size 0 might fail or act weird, test it handles it */ printf(\"%d\", res == 0 || res != 0); fclose(f); return 0; }"), vec!["1"]); }
#[test] fn setvbuf_very_large_buffer() { assert_eq!(run_c("#include <stdlib.h>\nint main() { FILE *f = fopen(\"test_vbuf_lg.txt\", \"w\"); char *buf = malloc(1024*1024); int res = setvbuf(f, buf, _IOFBF, 1024*1024); printf(\"%d\", res == 0); fclose(f); free(buf); return 0; }"), vec!["1"]); }
#[test] fn setvbuf_stdin() { assert_eq!(run_c("int main() { char buf[1024]; int res = setvbuf(stdin, buf, _IOFBF, 1024); printf(\"%d\", res == 0); return 0; }"), vec!["1"]); }
