use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn posix_regex_compile_success() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; int res = regcomp(&r, \"^[a-z]+$\", REG_EXTENDED); printf(\"%d\", res == 0); regfree(&r); return 0; }"), vec!["1"]); }
#[test] fn posix_regex_compile_error() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; int res = regcomp(&r, \"[\", REG_EXTENDED); printf(\"%d\", res != 0); return 0; }"), vec!["1"]); }
#[test] fn posix_regex_error_message() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; int err = regcomp(&r, \"[\", REG_EXTENDED); char errbuf[100]; regerror(err, &r, errbuf, sizeof(errbuf)); printf(\"%d\", errbuf[0] != '\\0'); return 0; }"), vec!["1"]); }
#[test] fn posix_regex_match_success() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regcomp(&r, \"^[a-z]+$\", REG_EXTENDED); int match = regexec(&r, \"hello\", 0, NULL, 0); printf(\"%d\", match == 0); regfree(&r); return 0; }"), vec!["1"]); }
#[test] fn posix_regex_match_failure() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regcomp(&r, \"^[a-z]+$\", REG_EXTENDED); int match = regexec(&r, \"hello123\", 0, NULL, 0); printf(\"%d\", match == REG_NOMATCH); regfree(&r); return 0; }"), vec!["1"]); }
#[test] fn posix_regex_icase_flag() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regcomp(&r, \"^[a-z]+$\", REG_EXTENDED | REG_ICASE); int match = regexec(&r, \"HELLO\", 0, NULL, 0); printf(\"%d\", match == 0); regfree(&r); return 0; }"), vec!["1"]); }
#[test] fn posix_regex_capture_groups() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regmatch_t pmatch[2]; regcomp(&r, \"h([a-z]+)o\", REG_EXTENDED); int match = regexec(&r, \"hello\", 2, pmatch, 0); printf(\"%d %d %d\", match == 0, (int)pmatch[1].rm_so, (int)pmatch[1].rm_eo); regfree(&r); return 0; }"), vec!["1 1 4"]); } // 'ell' is captured
#[test] fn posix_regex_multiple_capture_groups() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regmatch_t pmatch[3]; regcomp(&r, \"([0-9]+)-([a-z]+)\", REG_EXTENDED); int match = regexec(&r, \"123-abc\", 3, pmatch, 0); printf(\"%d %d %d\", match == 0, (int)(pmatch[1].rm_eo - pmatch[1].rm_so), (int)(pmatch[2].rm_eo - pmatch[2].rm_so)); regfree(&r); return 0; }"), vec!["1 3 3"]); } // 123 is len 3, abc is len 3
#[test] fn posix_regex_nosub_flag() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regmatch_t pmatch[2]; regcomp(&r, \"h([a-z]+)o\", REG_EXTENDED | REG_NOSUB); int match = regexec(&r, \"hello\", 2, pmatch, 0); printf(\"%d\", match == 0); regfree(&r); return 0; }"), vec!["1"]); } // Doesn't crash even if we ask for pmatch
#[test] fn posix_regex_notbol_flag() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regcomp(&r, \"^hello\", REG_EXTENDED); int match = regexec(&r, \"hello\", 0, NULL, REG_NOTBOL); printf(\"%d\", match == REG_NOMATCH); regfree(&r); return 0; }"), vec!["1"]); } // Beginning of line operator ^ fails with NOTBOL
#[test] fn posix_regex_noteol_flag() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regcomp(&r, \"hello$\", REG_EXTENDED); int match = regexec(&r, \"hello\", 0, NULL, REG_NOTEOL); printf(\"%d\", match == REG_NOMATCH); regfree(&r); return 0; }"), vec!["1"]); } // End of line operator $ fails with NOTEOL
#[test] fn posix_regex_newline_flag() { assert_eq!(run_c("#include <regex.h>\nint main() { regex_t r; regcomp(&r, \".*\", REG_EXTENDED | REG_NEWLINE); regmatch_t pmatch[1]; regexec(&r, \"hello\\nworld\", 1, pmatch, 0); printf(\"%d\", (int)(pmatch[0].rm_eo - pmatch[0].rm_so)); regfree(&r); return 0; }"), vec!["5"]); } // Match stops at newline
