use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn getaddrinfo_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_UNSPEC; hints.ai_socktype = SOCK_STREAM; int r = getaddrinfo(\"localhost\", \"http\", &hints, &res); printf(\"%d\", r == 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_invalid_host() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_UNSPEC; hints.ai_socktype = SOCK_STREAM; int r = getaddrinfo(\"this.domain.should.not.exist.xyz\", \"80\", &hints, &res); printf(\"%d\", r != 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn gai_strerror_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <netdb.h>\nint main() { const char *s = gai_strerror(EAI_NONAME); printf(\"%d\", s != NULL && s[0] != '\\0'); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_numeric_host() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_flags = AI_NUMERICHOST; int r = getaddrinfo(\"127.0.0.1\", NULL, &hints, &res); printf(\"%d\", r == 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_numeric_host_fail() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_flags = AI_NUMERICHOST; int r = getaddrinfo(\"localhost\", NULL, &hints, &res); printf(\"%d\", r == EAI_NONAME); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_numeric_serv() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_flags = AI_NUMERICSERV; int r = getaddrinfo(\"127.0.0.1\", \"8080\", &hints, &res); printf(\"%d\", r == 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_numeric_serv_fail() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_flags = AI_NUMERICSERV; int r = getaddrinfo(\"127.0.0.1\", \"http\", &hints, &res); printf(\"%d\", r == EAI_NONAME || r == EAI_SERVICE); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_passive() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_flags = AI_PASSIVE; int r = getaddrinfo(NULL, \"8080\", &hints, &res); printf(\"%d\", r == 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_null_hints() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo *res; int r = getaddrinfo(\"127.0.0.1\", \"80\", NULL, &res); printf(\"%d\", r == 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_null_node_and_service() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; int r = getaddrinfo(NULL, NULL, &hints, &res); printf(\"%d\", r == EAI_NONAME); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); } // POSIX says error if both node and service are null
#[test] fn getaddrinfo_ipv6() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET6; hints.ai_flags = AI_NUMERICHOST; int r = getaddrinfo(\"::1\", NULL, &hints, &res); printf(\"%d\", r == 0 || r != 0); /* some hosts may lack ipv6, test compile/run */ if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getnameinfo_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netdb.h>\n#include <netinet/in.h>\nint main() { struct sockaddr_in sa = {0}; sa.sin_family = AF_INET; sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK); sa.sin_port = htons(80); char host[1024]; char serv[20]; int r = getnameinfo((struct sockaddr*)&sa, sizeof(sa), host, sizeof(host), serv, sizeof(serv), NI_NUMERICHOST | NI_NUMERICSERV); printf(\"%d %s %s\", r == 0, host, serv); return 0; }"), vec!["1 127.0.0.1 80"]); }
#[test] fn getnameinfo_namereqd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netdb.h>\n#include <netinet/in.h>\nint main() { struct sockaddr_in sa = {0}; sa.sin_family = AF_INET; sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK); sa.sin_port = htons(80); char host[1024]; int r = getnameinfo((struct sockaddr*)&sa, sizeof(sa), host, sizeof(host), NULL, 0, NI_NAMEREQD); printf(\"%d\", r == 0 || r == EAI_NONAME); return 0; }"), vec!["1"]); }
#[test] fn getnameinfo_dgram() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netdb.h>\n#include <netinet/in.h>\nint main() { struct sockaddr_in sa = {0}; sa.sin_family = AF_INET; sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK); sa.sin_port = htons(53); char serv[20]; int r = getnameinfo((struct sockaddr*)&sa, sizeof(sa), NULL, 0, serv, sizeof(serv), NI_DGRAM); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_canonname() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_flags = AI_CANONNAME; int r = getaddrinfo(\"localhost\", NULL, &hints, &res); printf(\"%d %d\", r == 0, res != NULL && res->ai_canonname != NULL); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1 1"]); }
#[test] fn getaddrinfo_all() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_UNSPEC; hints.ai_flags = AI_ALL | AI_V4MAPPED; int r = getaddrinfo(\"localhost\", NULL, &hints, &res); printf(\"%d\", r == 0 || r != 0); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn getaddrinfo_socktype_dgram() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_UNSPEC; hints.ai_socktype = SOCK_DGRAM; int r = getaddrinfo(\"127.0.0.1\", \"53\", &hints, &res); printf(\"%d\", r == 0 && res->ai_socktype == SOCK_DGRAM); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1"]); }
#[test] fn freeaddrinfo_null() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <netdb.h>\nint main() { /* Usually safe or UB, check compile */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn gai_strerror_invalid() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <netdb.h>\nint main() { const char *s = gai_strerror(99999); printf(\"%d\", s != NULL); return 0; }"), vec!["1"]); } // Returns some unknown error string
#[test] fn getaddrinfo_protocol() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/types.h>\n#include <sys/socket.h>\n#include <netdb.h>\n#include <netinet/in.h>\nint main() { struct addrinfo hints = {0}, *res; hints.ai_family = AF_INET; hints.ai_protocol = IPPROTO_TCP; int r = getaddrinfo(\"127.0.0.1\", \"80\", &hints, &res); printf(\"%d %d\", r == 0, res->ai_protocol == IPPROTO_TCP); if(r == 0) freeaddrinfo(res); return 0; }"), vec!["1 1"]); }
