use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn rwlock_init_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw; int r1 = pthread_rwlock_init(&rw, NULL); int r2 = pthread_rwlock_destroy(&rw); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn rwlock_static_initializer() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\npthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;\nint main() { printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn rwlock_rdlock_unlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; int r1 = pthread_rwlock_rdlock(&rw); int r2 = pthread_rwlock_unlock(&rw); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn rwlock_wrlock_unlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; int r1 = pthread_rwlock_wrlock(&rw); int r2 = pthread_rwlock_unlock(&rw); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn rwlock_multiple_rdlocks() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; pthread_rwlock_rdlock(&rw); pthread_rwlock_rdlock(&rw); pthread_rwlock_unlock(&rw); pthread_rwlock_unlock(&rw); printf(\"ok\"); return 0; }"), vec!["ok"]); } // Reader locks can be nested
#[test] fn rwlock_tryrdlock_success() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; int r = pthread_rwlock_tryrdlock(&rw); pthread_rwlock_unlock(&rw); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rwlock_trywrlock_success() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; int r = pthread_rwlock_trywrlock(&rw); pthread_rwlock_unlock(&rw); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rwlock_trywrlock_fail() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; pthread_rwlock_rdlock(&rw); int r = pthread_rwlock_trywrlock(&rw); pthread_rwlock_unlock(&rw); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn rwlock_tryrdlock_fail() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; pthread_rwlock_wrlock(&rw); int r = pthread_rwlock_tryrdlock(&rw); pthread_rwlock_unlock(&rw); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); }
#[test] fn rwlockattr_init_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlockattr_t a; int r1 = pthread_rwlockattr_init(&a); int r2 = pthread_rwlockattr_destroy(&a); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn rwlockattr_setpshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlockattr_t a; pthread_rwlockattr_init(&a); int r = pthread_rwlockattr_setpshared(&a, PTHREAD_PROCESS_SHARED); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rwlockattr_getpshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlockattr_t a; pthread_rwlockattr_init(&a); pthread_rwlockattr_setpshared(&a, PTHREAD_PROCESS_SHARED); int s; pthread_rwlockattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_SHARED); return 0; }"), vec!["1"]); }
#[test] fn rwlock_timedrdlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <time.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; struct timespec ts; clock_gettime(CLOCK_REALTIME, &ts); ts.tv_sec += 1; int r = pthread_rwlock_timedrdlock(&rw, &ts); pthread_rwlock_unlock(&rw); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rwlock_timedwrlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <time.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; struct timespec ts; clock_gettime(CLOCK_REALTIME, &ts); ts.tv_sec += 1; int r = pthread_rwlock_timedwrlock(&rw, &ts); pthread_rwlock_unlock(&rw); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn rwlock_timedwrlock_timeout() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <time.h>\nint main() { pthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER; pthread_rwlock_rdlock(&rw); struct timespec ts; clock_gettime(CLOCK_REALTIME, &ts); ts.tv_nsec += 50000000; if(ts.tv_nsec >= 1000000000) { ts.tv_sec++; ts.tv_nsec -= 1000000000; } int r = pthread_rwlock_timedwrlock(&rw, &ts); printf(\"%d\", r != 0); pthread_rwlock_unlock(&rw); return 0; }"), vec!["1"]); }
#[test] fn rwlock_threads_readers() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <unistd.h>\npthread_rwlock_t rw = PTHREAD_RWLOCK_INITIALIZER;\nvoid* f(void* a) { pthread_rwlock_rdlock(&rw); sleep(1); pthread_rwlock_unlock(&rw); return NULL; }\nint main() { pthread_t t1, t2; pthread_create(&t1, NULL, f, NULL); pthread_create(&t2, NULL, f, NULL); pthread_join(t1, NULL); pthread_join(t2, NULL); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn rwlockattr_default_pshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_rwlockattr_t a; pthread_rwlockattr_init(&a); int s; pthread_rwlockattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_PRIVATE); return 0; }"), vec!["1"]); }
#[test] fn rwlock_destroy_locked() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to destroy locked rwlock, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn rwlock_unlock_unlocked() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to unlock unlocked rwlock, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn rwlock_wrlock_deadlock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* Double wrlock causes deadlock, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
