use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn barrier_init_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrier_t b; int r1 = pthread_barrier_init(&b, NULL, 2); int r2 = pthread_barrier_destroy(&b); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn barrier_wait_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <unistd.h>\npthread_barrier_t b;\nint v = 0;\nvoid* f(void* a) { v = 1; pthread_barrier_wait(&b); return NULL; }\nint main() { pthread_barrier_init(&b, NULL, 2); pthread_t t; pthread_create(&t, NULL, f, NULL); pthread_barrier_wait(&b); printf(\"%d\", v); pthread_join(t, NULL); return 0; }"), vec!["1"]); }
#[test] fn barrier_wait_serial_thread() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrier_t b; pthread_barrier_init(&b, NULL, 1); int r = pthread_barrier_wait(&b); printf(\"%d\", r == PTHREAD_BARRIER_SERIAL_THREAD); return 0; }"), vec!["1"]); }
#[test] fn barrierattr_init_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrierattr_t a; int r1 = pthread_barrierattr_init(&a); int r2 = pthread_barrierattr_destroy(&a); printf(\"%d %d\", r1 == 0, r2 == 0); return 0; }"), vec!["1 1"]); }
#[test] fn barrierattr_setpshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrierattr_t a; pthread_barrierattr_init(&a); int r = pthread_barrierattr_setpshared(&a, PTHREAD_PROCESS_SHARED); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn barrierattr_getpshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrierattr_t a; pthread_barrierattr_init(&a); pthread_barrierattr_setpshared(&a, PTHREAD_PROCESS_SHARED); int s; pthread_barrierattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_SHARED); return 0; }"), vec!["1"]); }
#[test] fn barrier_multiple_threads() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <unistd.h>\npthread_barrier_t b;\nint count = 0;\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\nvoid* f(void* a) { pthread_barrier_wait(&b); pthread_mutex_lock(&m); count++; pthread_mutex_unlock(&m); return NULL; }\nint main() { pthread_barrier_init(&b, NULL, 3); pthread_t t1, t2; pthread_create(&t1, NULL, f, NULL); pthread_create(&t2, NULL, f, NULL); pthread_barrier_wait(&b); pthread_join(t1, NULL); pthread_join(t2, NULL); printf(\"%d\", count); return 0; }"), vec!["2"]); }
#[test] fn barrier_reusable() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrier_t b; pthread_barrier_init(&b, NULL, 1); pthread_barrier_wait(&b); pthread_barrier_wait(&b); pthread_barrier_wait(&b); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn barrier_init_zero_count() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrier_t b; int r = pthread_barrier_init(&b, NULL, 0); printf(\"%d\", r != 0); return 0; }"), vec!["1"]); } // Count must be > 0
#[test] fn barrier_destroy_with_waiters() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to destroy barrier while threads are waiting, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn barrierattr_default_pshared() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrierattr_t a; pthread_barrierattr_init(&a); int s; pthread_barrierattr_getpshared(&a, &s); printf(\"%d\", s == PTHREAD_PROCESS_PRIVATE); return 0; }"), vec!["1"]); }
#[test] fn barrier_attr_null() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { pthread_barrier_t b; int r = pthread_barrier_init(&b, NULL, 1); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn barrier_wait_returns_serial_once() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\npthread_barrier_t b;\nvoid* f(void* a) { return (void*)(long)pthread_barrier_wait(&b); }\nint main() { pthread_barrier_init(&b, NULL, 2); pthread_t t; pthread_create(&t, NULL, f, NULL); int r1 = pthread_barrier_wait(&b); void *res; pthread_join(t, &res); int r2 = (long)res; printf(\"%d\", (r1 == PTHREAD_BARRIER_SERIAL_THREAD && r2 != PTHREAD_BARRIER_SERIAL_THREAD) || (r2 == PTHREAD_BARRIER_SERIAL_THREAD && r1 != PTHREAD_BARRIER_SERIAL_THREAD)); return 0; }"), vec!["1"]); }
#[test] fn barrier_size_check() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { printf(\"%d\", sizeof(pthread_barrier_t) > 0); return 0; }"), vec!["1"]); }
#[test] fn barrierattr_size_check() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { printf(\"%d\", sizeof(pthread_barrierattr_t) > 0); return 0; }"), vec!["1"]); }
#[test] fn barrier_two_phases() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\n#include <unistd.h>\npthread_barrier_t b;\nint p = 0;\nvoid* f(void* a) { pthread_barrier_wait(&b); p++; pthread_barrier_wait(&b); return NULL; }\nint main() { pthread_barrier_init(&b, NULL, 2); pthread_t t; pthread_create(&t, NULL, f, NULL); pthread_barrier_wait(&b); pthread_barrier_wait(&b); pthread_join(t, NULL); printf(\"%d\", p); return 0; }"), vec!["1"]); }
#[test] fn barrier_init_invalid_attr() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to pass invalid attr, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn barrier_uninitialized_wait() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to wait on uninitialized barrier, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn barrier_init_twice() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to init twice, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn barrier_use_after_destroy() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <pthread.h>\nint main() { /* UB to use after destroy, compile check only */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
