use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn socket_create_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); printf(\"%d\", fd >= 0); if(fd>=0) close(fd); return 0; }"), vec!["1"]); }
#[test] fn bind_tcp_loopback() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = 0; /* ephemeral */ int r = bind(fd, (struct sockaddr*)&addr, sizeof(addr)); printf(\"%d\", r == 0); if(fd>=0) close(fd); return 0; }"), vec!["1"]); }
#[test] fn listen_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = 0; bind(fd, (struct sockaddr*)&addr, sizeof(addr)); int r = listen(fd, 5); printf(\"%d\", r == 0); close(fd); return 0; }"), vec!["1"]); }
#[test] fn getsockname_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = 0; bind(fd, (struct sockaddr*)&addr, sizeof(addr)); struct sockaddr_in a2={0}; socklen_t len = sizeof(a2); getsockname(fd, (struct sockaddr*)&a2, &len); printf(\"%d\", ntohs(a2.sin_port) > 0); close(fd); return 0; }"), vec!["1"]); }
#[test] fn connect_accept_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\n#include <pthread.h>\nint port = 0;\nvoid* f(void* a) { int s = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = htons(port); while(connect(s, (struct sockaddr*)&addr, sizeof(addr)) != 0) usleep(10000); send(s, \"hi\", 2, 0); close(s); return NULL; }\nint main() { int l = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); a.sin_port = 0; bind(l, (struct sockaddr*)&a, sizeof(a)); socklen_t len=sizeof(a); getsockname(l, (struct sockaddr*)&a, &len); port = ntohs(a.sin_port); listen(l, 5); pthread_t t; pthread_create(&t, NULL, f, NULL); int c = accept(l, NULL, NULL); char b[5]={0}; recv(c, b, 2, 0); printf(\"%s\", b); close(c); close(l); pthread_join(t, NULL); return 0; }"), vec!["hi"]); }
#[test] fn setsockopt_reuseaddr() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int opt = 1; int r = setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)); printf(\"%d\", r == 0); close(fd); return 0; }"), vec!["1"]); }
#[test] fn getsockopt_reuseaddr() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int opt = 1; setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)); int o2 = 0; socklen_t len = sizeof(o2); getsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &o2, &len); printf(\"%d\", o2 != 0); close(fd); return 0; }"), vec!["1"]); }
#[test] fn socket_close() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int r = close(fd); printf(\"%d\", r == 0); return 0; }"), vec!["1"]); }
#[test] fn getpeername_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\n#include <pthread.h>\nint port = 0;\nvoid* f(void* a) { int s = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = htons(port); while(connect(s, (struct sockaddr*)&addr, sizeof(addr)) != 0) usleep(10000); close(s); return NULL; }\nint main() { int l = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); bind(l, (struct sockaddr*)&a, sizeof(a)); socklen_t len=sizeof(a); getsockname(l, (struct sockaddr*)&a, &len); port = ntohs(a.sin_port); listen(l, 5); pthread_t t; pthread_create(&t, NULL, f, NULL); int c = accept(l, NULL, NULL); struct sockaddr_in p={0}; len=sizeof(p); getpeername(c, (struct sockaddr*)&p, &len); printf(\"%d\", p.sin_family == AF_INET); close(c); close(l); pthread_join(t, NULL); return 0; }"), vec!["1"]); }
#[test] fn shutdown_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\n#include <pthread.h>\nint port = 0;\nvoid* f(void* a) { int s = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = htons(port); while(connect(s, (struct sockaddr*)&addr, sizeof(addr)) != 0) usleep(10000); char b[5]; recv(s, b, 5, 0); close(s); return NULL; }\nint main() { int l = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); bind(l, (struct sockaddr*)&a, sizeof(a)); socklen_t len=sizeof(a); getsockname(l, (struct sockaddr*)&a, &len); port = ntohs(a.sin_port); listen(l, 5); pthread_t t; pthread_create(&t, NULL, f, NULL); int c = accept(l, NULL, NULL); int r = shutdown(c, SHUT_WR); printf(\"%d\", r == 0); close(c); close(l); pthread_join(t, NULL); return 0; }"), vec!["1"]); }
#[test] fn setsockopt_keepalive() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int opt = 1; int r = setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &opt, sizeof(opt)); printf(\"%d\", r == 0); close(fd); return 0; }"), vec!["1"]); }
#[test] fn send_recv_flags() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\n#include <pthread.h>\nint port = 0;\nvoid* f(void* a) { int s = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = htons(port); while(connect(s, (struct sockaddr*)&addr, sizeof(addr)) != 0) usleep(10000); send(s, \"AB\", 2, MSG_OOB); close(s); return NULL; }\nint main() { int l = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); bind(l, (struct sockaddr*)&a, sizeof(a)); socklen_t len=sizeof(a); getsockname(l, (struct sockaddr*)&a, &len); port = ntohs(a.sin_port); listen(l, 5); pthread_t t; pthread_create(&t, NULL, f, NULL); int c = accept(l, NULL, NULL); char b[5]={0}; int r = recv(c, b, 2, MSG_OOB); /* May fail or succeed depending on OS handling of OOB, check compile and basic run */ printf(\"ok\"); close(c); close(l); pthread_join(t, NULL); return 0; }"), vec!["ok"]); }
#[test] fn socket_ipv6_tcp() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET6, SOCK_STREAM, 0); /* some hosts may not have ipv6, we just print if >=0 or <0 */ printf(\"%d\", fd != -99); if(fd>=0) close(fd); return 0; }"), vec!["1"]); }
#[test] fn recv_peek() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\n#include <pthread.h>\nint port = 0;\nvoid* f(void* a) { int s = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in addr={0}; addr.sin_family = AF_INET; addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK); addr.sin_port = htons(port); while(connect(s, (struct sockaddr*)&addr, sizeof(addr)) != 0) usleep(10000); send(s, \"XYZ\", 3, 0); close(s); return NULL; }\nint main() { int l = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); bind(l, (struct sockaddr*)&a, sizeof(a)); socklen_t len=sizeof(a); getsockname(l, (struct sockaddr*)&a, &len); port = ntohs(a.sin_port); listen(l, 5); pthread_t t; pthread_create(&t, NULL, f, NULL); int c = accept(l, NULL, NULL); char b1[5]={0}, b2[5]={0}; recv(c, b1, 3, MSG_PEEK); recv(c, b2, 3, 0); printf(\"%s %s\", b1, b2); close(c); close(l); pthread_join(t, NULL); return 0; }"), vec!["XYZ XYZ"]); }
#[test] fn accept_nonblocking() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int l = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); bind(l, (struct sockaddr*)&a, sizeof(a)); listen(l, 5); fcntl(l, F_SETFL, O_NONBLOCK); int c = accept(l, NULL, NULL); printf(\"%d\", c == -1); close(l); return 0; }"), vec!["1"]); }
#[test] fn getsockopt_error() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int err = 0; socklen_t len = sizeof(err); int r = getsockopt(fd, SOL_SOCKET, SO_ERROR, &err, &len); printf(\"%d %d\", r == 0, err == 0); close(fd); return 0; }"), vec!["1 1"]); }
#[test] fn setsockopt_rcvbuf() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int opt = 8192; int r = setsockopt(fd, SOL_SOCKET, SO_RCVBUF, &opt, sizeof(opt)); printf(\"%d\", r == 0); close(fd); return 0; }"), vec!["1"]); }
#[test] fn connect_refused() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\nint main() { int s = socket(AF_INET, SOCK_STREAM, 0); struct sockaddr_in a={0}; a.sin_family = AF_INET; a.sin_addr.s_addr = htonl(INADDR_LOOPBACK); a.sin_port = htons(1); /* Likely closed */ int r = connect(s, (struct sockaddr*)&a, sizeof(a)); printf(\"%d\", r == -1); close(s); return 0; }"), vec!["1"]); }
#[test] fn listen_without_bind() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\n#include <unistd.h>\nint main() { int fd = socket(AF_INET, SOCK_STREAM, 0); int r = listen(fd, 5); printf(\"%d\", r == 0); close(fd); return 0; }"), vec!["1"]); } // OS automatically binds to an ephemeral port
#[test] fn socket_invalid_family() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/socket.h>\nint main() { int fd = socket(9999, SOCK_STREAM, 0); printf(\"%d\", fd == -1); return 0; }"), vec!["1"]); }
