use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn syslog_basic() { assert_eq!(run_c("#include <syslog.h>\nint main() { syslog(LOG_INFO, \"Test message from test_c_posix_syslog_openlog\"); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn openlog_basic() { assert_eq!(run_c("#include <syslog.h>\nint main() { openlog(\"mytest\", LOG_PID | LOG_CONS, LOG_USER); syslog(LOG_INFO, \"Another message\"); closelog(); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn setlogmask_basic() { assert_eq!(run_c("#include <syslog.h>\nint main() { int old = setlogmask(LOG_MASK(LOG_ERR)); syslog(LOG_INFO, \"Should be masked\"); syslog(LOG_ERR, \"Should be logged\"); setlogmask(old); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn syslog_priorities() { assert_eq!(run_c("#include <syslog.h>\nint main() { syslog(LOG_EMERG, \"emerg\"); syslog(LOG_ALERT, \"alert\"); syslog(LOG_CRIT, \"crit\"); syslog(LOG_ERR, \"err\"); syslog(LOG_WARNING, \"warning\"); syslog(LOG_NOTICE, \"notice\"); syslog(LOG_INFO, \"info\"); syslog(LOG_DEBUG, \"debug\"); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn syslog_facilities() { assert_eq!(run_c("#include <syslog.h>\nint main() { syslog(LOG_USER | LOG_INFO, \"user info\"); syslog(LOG_LOCAL0 | LOG_DEBUG, \"local0 debug\"); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn closelog_basic() { assert_eq!(run_c("#include <syslog.h>\nint main() { openlog(\"test\", 0, LOG_USER); closelog(); closelog(); /* double close is usually safe */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn vsyslog_basic() { assert_eq!(run_c("#include <syslog.h>\n#include <stdarg.h>\nvoid log_it(int prio, const char *fmt, ...) { va_list args; va_start(args, fmt); vsyslog(prio, fmt, args); va_end(args); }\nint main() { log_it(LOG_INFO, \"vsyslog %d\", 42); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn setlogmask_upto() { assert_eq!(run_c("#include <syslog.h>\nint main() { int old = setlogmask(LOG_UPTO(LOG_WARNING)); syslog(LOG_INFO, \"masked\"); syslog(LOG_CRIT, \"logged\"); setlogmask(old); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn openlog_options() { assert_eq!(run_c("#include <syslog.h>\nint main() { openlog(\"opt_test\", LOG_PID | LOG_CONS | LOG_NDELAY | LOG_ODELAY | LOG_NOWAIT, LOG_USER); closelog(); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn syslog_percent_m() { assert_eq!(run_c("#include <syslog.h>\n#include <errno.h>\nint main() { errno = ENOENT; syslog(LOG_INFO, \"Error: %m\"); /* %m is replaced by strerror(errno) */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn setlogmask_return() { assert_eq!(run_c("#include <syslog.h>\nint main() { int m1 = setlogmask(LOG_MASK(LOG_ERR)); int m2 = setlogmask(m1); printf(\"%d\", m1 == m2); return 0; }"), vec!["1"]); } // Returns previous mask
#[test] fn syslog_null_format() { assert_eq!(run_c("#include <syslog.h>\nint main() { /* Most implementations crash if format is NULL, check we compile cleanly */ printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn openlog_null_ident() { assert_eq!(run_c("#include <syslog.h>\nint main() { openlog(NULL, LOG_PID, LOG_USER); syslog(LOG_INFO, \"null ident\"); closelog(); printf(\"ok\"); return 0; }"), vec!["ok"]); } // Usually defaults to program name
#[test] fn syslog_large_message() { assert_eq!(run_c("#include <syslog.h>\n#include <string.h>\nint main() { char msg[2000]; memset(msg, 'x', 1999); msg[1999] = 0; syslog(LOG_INFO, \"%s\", msg); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn setlogmask_zero() { assert_eq!(run_c("#include <syslog.h>\nint main() { int m1 = setlogmask(0); int m2 = setlogmask(0); printf(\"%d\", m1 == m2); return 0; }"), vec!["1"]); } // setlogmask(0) returns current mask without changing it
#[test] fn openlog_multiple_calls() { assert_eq!(run_c("#include <syslog.h>\nint main() { openlog(\"t1\", 0, LOG_USER); openlog(\"t2\", 0, LOG_LOCAL0); closelog(); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn syslog_without_openlog() { assert_eq!(run_c("#include <syslog.h>\nint main() { /* openlog is optional */ syslog(LOG_INFO, \"no openlog\"); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn closelog_without_openlog() { assert_eq!(run_c("#include <syslog.h>\nint main() { closelog(); printf(\"ok\"); return 0; }"), vec!["ok"]); } // Safe
#[test] fn syslog_thread_safety() { assert_eq!(run_c("#include <syslog.h>\n#include <pthread.h>\nvoid* f(void* a) { syslog(LOG_INFO, \"thread\"); return NULL; }\nint main() { pthread_t t1, t2; pthread_create(&t1, NULL, f, NULL); pthread_create(&t2, NULL, f, NULL); pthread_join(t1, NULL); pthread_join(t2, NULL); printf(\"ok\"); return 0; }"), vec!["ok"]); } // syslog is required to be thread-safe
#[test] fn syslog_macros_exist() { assert_eq!(run_c("#include <syslog.h>\nint main() { int x = LOG_AUTH | LOG_AUTHPRIV | LOG_CRON | LOG_DAEMON | LOG_FTP | LOG_KERN | LOG_LPR | LOG_MAIL | LOG_NEWS | LOG_SYSLOG | LOG_UUCP; printf(\"ok\"); return 0; }"), vec!["ok"]); } // Check all facility macros are defined
