use super::helpers::run_prints;
fn run_c(src: &str) -> Vec<String> { run_prints(&format!("#include <stdio.h>\n{}", src)) }

#[test] fn stat_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\n#include <fcntl.h>\nint main() { int fd = open(\"test_stat.txt\", O_CREAT|O_WRONLY, 0644); write(fd, \"x\", 1); close(fd); struct stat st; int r = stat(\"test_stat.txt\", &st); printf(\"%d %d\", r == 0, st.st_size == 1); unlink(\"test_stat.txt\"); return 0; }"), vec!["1 1"]); }
#[test] fn fstat_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\n#include <fcntl.h>\nint main() { int fd = open(\"test_fstat.txt\", O_CREAT|O_WRONLY, 0644); write(fd, \"xx\", 2); struct stat st; int r = fstat(fd, &st); printf(\"%d %d\", r == 0, st.st_size == 2); close(fd); unlink(\"test_fstat.txt\"); return 0; }"), vec!["1 1"]); }
#[test] fn lstat_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\n#include <fcntl.h>\nint main() { int fd = open(\"test_lstat.txt\", O_CREAT|O_WRONLY, 0644); close(fd); symlink(\"test_lstat.txt\", \"test_link\"); struct stat st; int r = lstat(\"test_link\", &st); printf(\"%d %d\", r == 0, S_ISLNK(st.st_mode)); unlink(\"test_link\"); unlink(\"test_lstat.txt\"); return 0; }"), vec!["1 1"]); }
#[test] fn stat_nonexistent() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { struct stat st; int r = stat(\"does_not_exist_stat\", &st); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn fstat_invalid_fd() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { struct stat st; int r = fstat(-1, &st); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
#[test] fn s_isreg() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\n#include <fcntl.h>\nint main() { int fd = open(\"test_isreg.txt\", O_CREAT|O_WRONLY, 0644); close(fd); struct stat st; stat(\"test_isreg.txt\", &st); printf(\"%d\", S_ISREG(st.st_mode)); unlink(\"test_isreg.txt\"); return 0; }"), vec!["1"]); }
#[test] fn s_isdir() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { struct stat st; stat(\"/\", &st); printf(\"%d\", S_ISDIR(st.st_mode)); return 0; }"), vec!["1"]); }
#[test] fn s_ischr() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { struct stat st; int r = stat(\"/dev/null\", &st); if(r==0) printf(\"%d\", S_ISCHR(st.st_mode)); else printf(\"1\"); return 0; }"), vec!["1"]); }
#[test] fn chmod_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\n#include <fcntl.h>\nint main() { int fd = open(\"test_chmod.txt\", O_CREAT|O_WRONLY, 0644); close(fd); int r = chmod(\"test_chmod.txt\", 0777); struct stat st; stat(\"test_chmod.txt\", &st); printf(\"%d %d\", r == 0, (st.st_mode & 0777) == 0777); unlink(\"test_chmod.txt\"); return 0; }"), vec!["1 1"]); }
#[test] fn fchmod_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\n#include <fcntl.h>\nint main() { int fd = open(\"test_fchmod.txt\", O_CREAT|O_WRONLY, 0644); int r = fchmod(fd, 0700); struct stat st; fstat(fd, &st); printf(\"%d %d\", r == 0, (st.st_mode & 0777) == 0700); close(fd); unlink(\"test_fchmod.txt\"); return 0; }"), vec!["1 1"]); }
#[test] fn mkdir_rmdir() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\nint main() { int r1 = mkdir(\"test_mkdir\", 0755); struct stat st; stat(\"test_mkdir\", &st); int r2 = rmdir(\"test_mkdir\"); printf(\"%d %d %d\", r1 == 0, S_ISDIR(st.st_mode), r2 == 0); return 0; }"), vec!["1 1 1"]); }
#[test] fn mkfifo_basic() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <unistd.h>\nint main() { int r = mkfifo(\"test_fifo\", 0644); struct stat st; if(r==0) stat(\"test_fifo\", &st); printf(\"%d %d\", r == 0, S_ISFIFO(st.st_mode)); if(r==0) unlink(\"test_fifo\"); return 0; }"), vec!["1 1"]); }
#[test] fn umask_basic() { assert_eq!(run_c("#include <sys/stat.h>\nint main() { mode_t old = umask(0022); mode_t old2 = umask(old); printf(\"%d\", old2 == 0022); return 0; }"), vec!["1"]); }
#[test] fn utimensat_compile() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <fcntl.h>\nint main() { /* AT_FDCWD */ int fd = open(\"test_utime.txt\", O_CREAT|O_WRONLY, 0644); close(fd); struct timespec ts[2] = {{0, UTIME_NOW}, {0, UTIME_NOW}}; int r = utimensat(AT_FDCWD, \"test_utime.txt\", ts, 0); printf(\"%d\", r == 0); unlink(\"test_utime.txt\"); return 0; }"), vec!["1"]); }
#[test] fn futimens_compile() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_futime.txt\", O_CREAT|O_WRONLY, 0644); struct timespec ts[2] = {{0, UTIME_NOW}, {0, UTIME_NOW}}; int r = futimens(fd, ts); printf(\"%d\", r == 0); close(fd); unlink(\"test_futime.txt\"); return 0; }"), vec!["1"]); }
#[test] fn stat_times() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_times.txt\", O_CREAT|O_WRONLY, 0644); close(fd); struct stat st; stat(\"test_times.txt\", &st); printf(\"%d\", st.st_atime > 0 && st.st_mtime > 0 && st.st_ctime > 0); unlink(\"test_times.txt\"); return 0; }"), vec!["1"]); }
#[test] fn stat_inode_dev() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\n#include <fcntl.h>\n#include <unistd.h>\nint main() { int fd = open(\"test_inode.txt\", O_CREAT|O_WRONLY, 0644); close(fd); struct stat st1, st2; stat(\"test_inode.txt\", &st1); stat(\"test_inode.txt\", &st2); printf(\"%d\", st1.st_ino == st2.st_ino && st1.st_dev == st2.st_dev); unlink(\"test_inode.txt\"); return 0; }"), vec!["1"]); }
#[test] fn s_isblk() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { /* just test macro compilation */ int x = S_ISBLK(0); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn s_issock() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { int x = S_ISSOCK(0); printf(\"ok\"); return 0; }"), vec!["ok"]); }
#[test] fn chmod_nonexistent() { assert_eq!(run_c("#define _POSIX_C_SOURCE 200809L\n#include <sys/stat.h>\nint main() { int r = chmod(\"doesnotexist_chmod\", 0777); printf(\"%d\", r == -1); return 0; }"), vec!["1"]); }
