[package]
name = "vybe_compiler_vb"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vybe_parser_basic = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_host = { workspace = true }

[dev-dependencies]
vybe_parser_js = { workspace = true }
vybe_compiler_js = { workspace = true }
