#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub line: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // Structural
    Newline,
    Indent,
    Dedent,

    // Literals
    Int(i64),
    Float(f64),
    Str(String),
    FStringStart,
    FStringText(String),
    FStringFormatSpec(String),
    FStringEnd,
    ByteStr(Vec<u8>),
    Identifier(String),

    // Keywords
    False,
    None,
    True,
    And,
    As,
    Assert,
    Async,
    Await,
    Break,
    Class,
    Continue,
    Def,
    Del,
    Elif,
    Else,
    Except,
    Finally,
    For,
    From,
    Global,
    If,
    Import,
    In,
    Is,
    Lambda,
    Match,
    Case,
    Nonlocal,
    Not,
    Or,
    Pass,
    Raise,
    Return,
    Try,
    While,
    With,
    Yield,

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    DoubleSlash,
    Percent,
    DoubleStar,
    At,
    Pipe,
    Amp,
    Caret,
    Tilde,
    LtLt,
    GtGt,
    Lt,
    Gt,
    LtEq,
    GtEq,
    EqEq,
    BangEq,
    Eq,
    ColonEq,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    DoubleSlashEq,
    PercentEq,
    DoubleStarEq,
    AtEq,
    PipeEq,
    AmpEq,
    CaretEq,
    LtLtEq,
    GtGtEq,

    // Delimiters
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Semicolon,
    Dot,
    DotDotDot,
    Arrow,

    // Special
    Eof,
}

impl TokenKind {
    pub fn from_keyword(s: &str) -> Option<TokenKind> {
        match s {
            "False" => Some(TokenKind::False),
            "None" => Some(TokenKind::None),
            "True" => Some(TokenKind::True),
            "and" => Some(TokenKind::And),
            "as" => Some(TokenKind::As),
            "assert" => Some(TokenKind::Assert),
            "async" => Some(TokenKind::Async),
            "await" => Some(TokenKind::Await),
            "break" => Some(TokenKind::Break),
            "class" => Some(TokenKind::Class),
            "continue" => Some(TokenKind::Continue),
            "def" => Some(TokenKind::Def),
            "del" => Some(TokenKind::Del),
            "elif" => Some(TokenKind::Elif),
            "else" => Some(TokenKind::Else),
            "except" => Some(TokenKind::Except),
            "finally" => Some(TokenKind::Finally),
            "for" => Some(TokenKind::For),
            "from" => Some(TokenKind::From),
            "global" => Some(TokenKind::Global),
            "if" => Some(TokenKind::If),
            "import" => Some(TokenKind::Import),
            "in" => Some(TokenKind::In),
            "is" => Some(TokenKind::Is),
            "lambda" => Some(TokenKind::Lambda),
            "match" => Some(TokenKind::Match),
            "case" => Some(TokenKind::Case),
            "nonlocal" => Some(TokenKind::Nonlocal),
            "not" => Some(TokenKind::Not),
            "or" => Some(TokenKind::Or),
            "pass" => Some(TokenKind::Pass),
            "raise" => Some(TokenKind::Raise),
            "return" => Some(TokenKind::Return),
            "try" => Some(TokenKind::Try),
            "while" => Some(TokenKind::While),
            "with" => Some(TokenKind::With),
            "yield" => Some(TokenKind::Yield),
            _ => None,
        }
    }
}
