[package]
name = "vybe_language_vb"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vybe_language_vb"

[dependencies]
vybe_compiler = { workspace = true }
inventory = { workspace = true }
vybe_ast = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_platform_vybe = { workspace = true, features = ["gui"] }
pest = { workspace = true }
pest_derive = { workspace = true }
chrono = "0.4"
vybe_widgets = { workspace = true }
vybe_platform_dotnet = { workspace = true }

[dev-dependencies]
vybe_compiler = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_ast = { workspace = true }
vybe_language_js = { workspace = true }
uuid = { workspace = true }

[[test]]
name = "vb"
path = "tests/vb/main.rs"
