[package]
name = "vybe_compiler_generic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vybe_bytecode = { workspace = true }
vybe_parser_generic = { workspace = true }
vybe_compiler_common = { workspace = true }
vybe_host = { workspace = true, features = ["gui"] }

[dev-dependencies]

[[bin]]
name = "vybeg"
path = "src/main.rs"
