[package]
name = "vybe_widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.12.0"
cosmic-text = "0.18.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ropey = "1.6.1"
uuid = { version = "1", features = ["v4"] }
vybe_forms = { path = "../vybe_forms" }
winit = "0.30"
arboard = "3.4"
