use super::helpers::compile_ok;

// ═══════════════════════════════════════════════════════════
// COBOL 2023: Modern file I/O operations
// Tests for file handling beyond basics in test_io_and_misc.rs.
// ═══════════════════════════════════════════════════════════

#[test]
fn file_section_fd() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT CUSTOMER-FILE ASSIGN TO "customers.dat"
        ORGANIZATION IS SEQUENTIAL
        FILE STATUS IS WS-STATUS.
DATA DIVISION.
FILE SECTION.
FD CUSTOMER-FILE
    RECORD CONTAINS 80 CHARACTERS.
01 CUSTOMER-REC.
   05 CUST-ID PIC 9(5).
   05 CUST-NAME PIC X(30).
   05 CUST-BALANCE PIC 9(10)V99.
WORKING-STORAGE SECTION.
01 WS-STATUS PIC X(2).
PROCEDURE DIVISION.
    OPEN INPUT CUSTOMER-FILE.
    CLOSE CUSTOMER-FILE.
    STOP RUN.
"#);
}

#[test]
fn file_section_sd() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT SORT-FILE ASSIGN TO "sort.tmp".
DATA DIVISION.
FILE SECTION.
SD SORT-FILE.
01 SORT-REC.
   05 SORT-KEY PIC X(10).
   05 SORT-DATA PIC X(70).
WORKING-STORAGE SECTION.
01 WS-DUMMY PIC X(1).
PROCEDURE DIVISION.
    DISPLAY "Sort file defined".
    STOP RUN.
"#);
}

#[test]
fn read_at_end() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-REC PIC X(80).
01 WS-EOF PIC 9(1) VALUE 0.
PROCEDURE DIVISION.
    READ WS-FILE INTO WS-REC
        AT END SET WS-EOF TO TRUE
        NOT AT END DISPLAY WS-REC
    END-READ.
    STOP RUN.
"#);
}

#[test]
fn write_advancing_lines() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-REC PIC X(80) VALUE "Test record".
PROCEDURE DIVISION.
    WRITE WS-REC AFTER ADVANCING 2 LINES.
    STOP RUN.
"#);
}

#[test]
fn write_advancing_page() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-REC PIC X(80) VALUE "Page header".
PROCEDURE DIVISION.
    WRITE WS-REC BEFORE ADVANCING PAGE.
    STOP RUN.
"#);
}

#[test]
fn indexed_file_organization() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT MASTER-FILE ASSIGN TO "master.dat"
        ORGANIZATION IS INDEXED
        ACCESS MODE IS DYNAMIC
        RECORD KEY IS WS-KEY
        FILE STATUS IS WS-STATUS.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-KEY PIC X(10).
01 WS-STATUS PIC X(2).
PROCEDURE DIVISION.
    DISPLAY "Indexed file defined".
    STOP RUN.
"#);
}

#[test]
fn relative_file_organization() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT REL-FILE ASSIGN TO "relative.dat"
        ORGANIZATION IS RELATIVE
        ACCESS MODE IS RANDOM.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DUMMY PIC X(1).
PROCEDURE DIVISION.
    DISPLAY "Relative file defined".
    STOP RUN.
"#);
}

#[test]
fn alternate_key() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
ENVIRONMENT DIVISION.
INPUT-OUTPUT SECTION.
FILE-CONTROL.
    SELECT CUST-FILE ASSIGN TO "cust.dat"
        ORGANIZATION IS INDEXED
        ACCESS MODE IS DYNAMIC
        RECORD KEY IS CUST-ID
        ALTERNATE RECORD KEY IS CUST-NAME WITH DUPLICATES.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 CUST-ID PIC X(5).
01 CUST-NAME PIC X(30).
PROCEDURE DIVISION.
    DISPLAY "File with alternate key".
    STOP RUN.
"#);
}

#[test]
fn start_with_key() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-KEY PIC X(10) VALUE "ABC".
PROCEDURE DIVISION.
    START WS-FILE KEY >= WS-KEY
        INVALID KEY DISPLAY "Not found"
        NOT INVALID KEY DISPLAY "Found"
    END-START.
    STOP RUN.
"#);
}

#[test]
fn rewrite_with_invalid_key() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-REC PIC X(80) VALUE "Updated".
PROCEDURE DIVISION.
    REWRITE WS-REC
        INVALID KEY DISPLAY "Failed"
        NOT INVALID KEY DISPLAY "OK"
    END-REWRITE.
    STOP RUN.
"#);
}

#[test]
fn delete_with_invalid_key() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-REC PIC X(80).
PROCEDURE DIVISION.
    DELETE WS-FILE RECORD
        INVALID KEY DISPLAY "Not found"
        NOT INVALID KEY DISPLAY "Deleted"
    END-DELETE.
    STOP RUN.
"#);
}

#[test]
fn open_multiple_modes() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DUMMY PIC X(1).
PROCEDURE DIVISION.
    OPEN INPUT WS-IN-FILE
         OUTPUT WS-OUT-FILE.
    CLOSE WS-IN-FILE WS-OUT-FILE.
    STOP RUN.
"#);
}

#[test]
fn sort_with_input_output_procedure() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-REC PIC X(80).
01 WS-KEY PIC X(10).
PROCEDURE DIVISION.
    SORT WS-SORT-FILE ON ASCENDING KEY WS-KEY
        USING WS-IN-FILE
        GIVING WS-OUT-FILE.
    STOP RUN.
"#);
}
