use super::helpers::compile_ok;

#[test]
fn parse_data_items_standalone() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. T.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 WS-X PIC X(10) VALUE \"Hello\".\nPROCEDURE DIVISION.\n    STOP RUN.");
}

#[test]
fn parse_data_items_no_trailing_newline() {
    compile_ok("IDENTIFICATION DIVISION.\nPROGRAM-ID. CALC.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 WS-MSG PIC X(20) VALUE \"From COBOL\".\nPROCEDURE DIVISION.\n    DISPLAY WS-MSG.\n    STOP RUN.");
}

#[test]
fn parse_data_items_with_env_div() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. CALC.
ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-MSG PIC X(20) VALUE "From COBOL".
PROCEDURE DIVISION.
    DISPLAY WS-MSG.
    STOP RUN.
"#);
}

#[test]
fn parse_subscript_access() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-TABLE.
   05 WS-ITEM OCCURS 10 TIMES PIC 9(3).
01 WS-IDX PIC 9(2) VALUE 1.
PROCEDURE DIVISION.
    DISPLAY WS-ITEM(WS-IDX).
    STOP RUN.
"#);
}
