use super::helpers::compile_ok;

// ═══════════════════════════════════════════════════════════
// COBOL 2023: Advanced string operations
// Tests for modern STRING, UNSTRING, INSPECT patterns beyond
// the basics covered in test_strings.rs.
// ═══════════════════════════════════════════════════════════

#[test]
fn string_with_pointer() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-RESULT PIC X(50) VALUE SPACES.
01 WS-PTR PIC 9(3) VALUE 1.
PROCEDURE DIVISION.
    STRING "Hello" DELIMITED BY SIZE
           " "     DELIMITED BY SIZE
           "World" DELIMITED BY SIZE
        INTO WS-RESULT
        WITH POINTER WS-PTR.
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn string_overflow_handler() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-RESULT PIC X(5) VALUE SPACES.
01 WS-LONG PIC X(20) VALUE "This is too long".
PROCEDURE DIVISION.
    STRING WS-LONG DELIMITED BY SIZE
        INTO WS-RESULT
        ON OVERFLOW DISPLAY "Overflow!"
        NOT ON OVERFLOW DISPLAY "OK"
    END-STRING.
    STOP RUN.
"#);
}

#[test]
fn unstring_multi_delimiter() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATA PIC X(30) VALUE "John,Doe;30".
01 WS-FIRST PIC X(10).
01 WS-LAST PIC X(10).
01 WS-AGE PIC X(5).
PROCEDURE DIVISION.
    UNSTRING WS-DATA
        DELIMITED BY "," OR ";"
        INTO WS-FIRST WS-LAST WS-AGE.
    DISPLAY WS-FIRST.
    DISPLAY WS-LAST.
    DISPLAY WS-AGE.
    STOP RUN.
"#);
}

#[test]
fn unstring_with_count() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATA PIC X(20) VALUE "ABC,DEFGH,IJ".
01 WS-PART1 PIC X(10).
01 WS-PART2 PIC X(10).
01 WS-CNT1 PIC 9(3).
01 WS-CNT2 PIC 9(3).
PROCEDURE DIVISION.
    UNSTRING WS-DATA
        DELIMITED BY ","
        INTO WS-PART1 COUNT IN WS-CNT1
             WS-PART2 COUNT IN WS-CNT2.
    DISPLAY WS-CNT1.
    DISPLAY WS-CNT2.
    STOP RUN.
"#);
}

#[test]
fn unstring_with_delimiter_in() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATA PIC X(20) VALUE "A,B;C".
01 WS-PART1 PIC X(5).
01 WS-PART2 PIC X(5).
01 WS-DELIM1 PIC X(1).
01 WS-DELIM2 PIC X(1).
PROCEDURE DIVISION.
    UNSTRING WS-DATA
        DELIMITED BY "," OR ";"
        INTO WS-PART1 DELIMITER IN WS-DELIM1
             WS-PART2 DELIMITER IN WS-DELIM2.
    DISPLAY WS-DELIM1.
    DISPLAY WS-DELIM2.
    STOP RUN.
"#);
}

#[test]
fn unstring_tallying() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-DATA PIC X(20) VALUE "A,B,C,D".
01 WS-P1 PIC X(5).
01 WS-P2 PIC X(5).
01 WS-P3 PIC X(5).
01 WS-P4 PIC X(5).
01 WS-COUNT PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    UNSTRING WS-DATA
        DELIMITED BY ","
        INTO WS-P1 WS-P2 WS-P3 WS-P4
        TALLYING IN WS-COUNT.
    DISPLAY WS-COUNT.
    STOP RUN.
"#);
}

#[test]
fn inspect_tallying_all() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "ABCAABCA".
01 WS-COUNT PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    INSPECT WS-STR TALLYING WS-COUNT FOR ALL "A".
    DISPLAY WS-COUNT.
    STOP RUN.
"#);
}

#[test]
fn inspect_tallying_leading() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "AAABBA".
01 WS-COUNT PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    INSPECT WS-STR TALLYING WS-COUNT FOR LEADING "A".
    DISPLAY WS-COUNT.
    STOP RUN.
"#);
}

#[test]
fn inspect_tallying_before_initial() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "ABCXDEF".
01 WS-COUNT PIC 9(3) VALUE 0.
PROCEDURE DIVISION.
    INSPECT WS-STR TALLYING WS-COUNT FOR ALL "A"
        BEFORE INITIAL "X".
    DISPLAY WS-COUNT.
    STOP RUN.
"#);
}

#[test]
fn inspect_replacing_first() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "AABAA".
PROCEDURE DIVISION.
    INSPECT WS-STR REPLACING FIRST "A" BY "X".
    DISPLAY WS-STR.
    STOP RUN.
"#);
}

#[test]
fn inspect_converting() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "Hello World".
PROCEDURE DIVISION.
    INSPECT WS-STR CONVERTING "abcdefghijklmnopqrstuvwxyz"
        TO "ABCDEFGHIJKLMNOPQRSTUVWXYZ".
    DISPLAY WS-STR.
    STOP RUN.
"#);
}

#[test]
fn reference_modification_variable() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "Hello World".
01 WS-POS PIC 9(3) VALUE 7.
01 WS-LEN PIC 9(3) VALUE 5.
01 WS-RESULT PIC X(10).
PROCEDURE DIVISION.
    MOVE WS-STR(WS-POS:WS-LEN) TO WS-RESULT.
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}

#[test]
fn reference_modification_no_length() {
    compile_ok(r#"
IDENTIFICATION DIVISION.
PROGRAM-ID. T.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-STR PIC X(20) VALUE "Hello World".
01 WS-RESULT PIC X(20).
PROCEDURE DIVISION.
    MOVE WS-STR(7:) TO WS-RESULT.
    DISPLAY WS-RESULT.
    STOP RUN.
"#);
}
