[package]
name = "vybe_language_php"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "vybe_language_php"

[dependencies]
vybe_compiler = { workspace = true }
inventory = { workspace = true }
vybe_ast = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_platform_vybe = { workspace = true, features = ["gui"] }
uuid = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
vybe_language_c = { workspace = true }

[dev-dependencies]
vybe_compiler = { workspace = true }
vybe_bytecode = { workspace = true }
vybe_ast = { workspace = true }
uuid = { workspace = true }

[[test]]
name = "php"
path = "tests/php/main.rs"
