use vybe_parser_generic::grammar::*;
use std::collections::HashMap;

pub fn python_grammar() -> GrammarDef {
    GrammarDef {
        language: LanguageSpec {
            name: "python".into(),
            case_sensitive: true,
            statement_terminator: Terminator::Newline,
            indentation_based: true,
            expression_language: false,
        },
        lexer: LexerSpec {
            comment_line: vec!["#".into()],
            comment_block: Vec::new(),
            string_delimiters: vec!["'".into(), "\"".into()],
            string_escape: Some("\\".into()),
            triple_string: vec!["'''".into(), "\"\"\"".into()],
            string_prefixes: vec!["f".into(), "r".into(), "b".into(), "fr".into(), "rb".into(), "F".into(), "R".into(), "B".into()],
            interpolation: Some(("{".into(), "}".into())),
            template_string: None,
            char_prefix: None,
            hex_prefix: None,
            keywords: vec![
                "def".into(), "class".into(), "if".into(), "elif".into(), "else".into(),
                "for".into(), "while".into(), "break".into(), "continue".into(), "return".into(),
                "pass".into(), "yield".into(),
                "try".into(), "except".into(), "finally".into(), "raise".into(),
                "with".into(), "as".into(),
                "import".into(), "from".into(),
                "and".into(), "or".into(), "not".into(), "in".into(), "is".into(),
                "lambda".into(), "global".into(), "nonlocal".into(), "assert".into(), "del".into(),
                "True".into(), "False".into(), "None".into(),
                "async".into(), "await".into(),
                "match".into(), "case".into(),
            ],
            operators: vec![
                "**=".into(), "//=".into(), ">>=".into(), "<<=".into(),
                "**".into(), "//".into(), ">>".into(), "<<".into(),
                "+=".into(), "-=".into(), "*=".into(), "/=".into(), "%=".into(),
                "&=".into(), "|=".into(), "^=".into(), "@=".into(),
                "==".into(), "!=".into(), "<=".into(), ">=".into(),
                "->".into(), ":=".into(),
                "+".into(), "-".into(), "*".into(), "/".into(), "%".into(),
                "&".into(), "|".into(), "^".into(), "~".into(),
                "<".into(), ">".into(), "=".into(),
                "(".into(), ")".into(), "[".into(), "]".into(), "{".into(), "}".into(),
                ".".into(), ",".into(), ";".into(), ":".into(), "@".into(),
            ],
        },
        operators: OperatorTable {
            prefix: vec!["not".into(), "-".into(), "+".into(), "~".into(), "await".into()],
            postfix: Vec::new(),
            infix: vec![
                InfixLevel { precedence: 1, ops: vec!["or".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 2, ops: vec!["and".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 3, ops: vec![
                    "==".into(), "!=".into(), "<".into(), ">".into(), "<=".into(), ">=".into(),
                    "in".into(), "is".into(),
                ], assoc: Assoc::Left },
                InfixLevel { precedence: 4, ops: vec!["|".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 5, ops: vec!["^".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 6, ops: vec!["&".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 7, ops: vec!["<<".into(), ">>".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 8, ops: vec!["+".into(), "-".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 9, ops: vec!["*".into(), "/".into(), "//".into(), "%".into(), "@".into()], assoc: Assoc::Left },
                InfixLevel { precedence: 10, ops: vec!["**".into()], assoc: Assoc::Right },
            ],
        },
        blocks: BlockSpec { open: "INDENT".into(), close: "DEDENT".into(), prefix: Some(":".into()), close_with_kind: false },
        types: TypeSpec { position: TypePosition::After, separator: Some(":".into()), return_separator: Some("->".into()) },
        statements: Vec::new(),
        declarations: Vec::new(),
        expressions: ExpressionSpec {
            member_access: Some(".".into()),
            optional_chain: None,
            index_open: Some("[".into()),
            index_close: Some("]".into()),
            call_open: Some("(".into()),
            call_close: Some(")".into()),
            deref: None,
            primary_forms: Vec::new(),
        },
        params: ParamSpec {
            open: "(".into(), close: ")".into(), separator: ",".into(),
            name_type_sep: Some(":".into()), type_position: TypePosition::After,
            default_value: Some("=".into()),
            rest_prefix: Some("*".into()),
            kwargs_prefix: Some("**".into()),
            multi_name: false, multi_name_sep: None,
            pass_by: HashMap::new(),
        },
        assignment: AssignmentSpec {
            operator: Some("=".into()),
            compound: [
                ("+=".into(),"Add".into()), ("-=".into(),"Sub".into()),
                ("*=".into(),"Mul".into()), ("/=".into(),"Div".into()),
                ("//=".into(),"IDiv".into()), ("%=".into(),"Mod".into()),
                ("**=".into(),"Pow".into()),
                ("&=".into(),"BitAnd".into()), ("|=".into(),"BitOr".into()),
                ("^=".into(),"BitXor".into()),
                ("<<=".into(),"Shl".into()), (">>=".into(),"Shr".into()),
            ].into_iter().collect(),
            walrus: Some(":=".into()),
        },
        program: ProgramSpec { header: None, uses: None, body: None },
    }
}
