# vybe-test: powershell/convertto_html_cmdlet/convertto_html_postcontent_footer_note
# The -PostContent parameter appends content after the main output table
$post = "<footer>Generated by automated testing pipeline</footer>"
$html = [pscustomobject]@{ Job = "Backup" } | ConvertTo-Html -PostContent $post -Fragment
$text = $html -join " "

if ($text -notmatch [regex]::Escape($post)) {
    Write-Host "FAIL: PostContent missing from HTML output"
    exit 1
}

Write-Host "PASS"
exit 0
